### ISSUE TITLE
Add Rolling Shutter Correction Model

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1000]
This is necessary to achieve good georeferencing results with rolling shutter cameras while images are captured in motion (most DJI equipment). Doesn't matter as much if pictures are taken while stopping the drone.

https://assets.ctfassets.net/go54bjdzbrgi/63gbWFoaLC0Uow2Yq2K4yg/c8f3077d7acee00cc2649d16859f22de/pix4d-isprs-paper-rolling-shutter-final-edited.pdf

**Comment by smathermather** [comment]
Agreed. Also, duplicate:
https://github.com/OpenDroneMap/ODM/issues/313

**Comment by pierotofy** [comment]
Oh didn't know this dated back to 2016 xD, I will close this one since it's a duplicate.

**Comment by smathermather** [comment]
:)  Indeed.

**Comment by kikislater** [comment]
It still needs a PhD to do : a lot of research and tests

**Comment by pierotofy** [comment]
I'd say it probably just needs some time and perseverance (funding would help too)... :smile:
