### ISSUE TITLE
Split-merge fails to restart from orthophoto

### ISSUE THREAD

**Issue by merkato** [OpenDroneMap/ODM#1011]
****************************************

### How did you install OpenDroneMap? (Docker, natively, ...)?

webodm + cluster+ nodeodm on docker machines (ubuntu 18.04)

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

chrome on linux

### What is the problem?

[INFO]    ==============
[INFO]    build_overviews: False
[INFO]    cameras: {}
[INFO]    crop: 3
[INFO]    debug: False
[INFO]    dem_decimation: 1
[INFO]    dem_euclidean_map: False
[INFO]    dem_gapfill_steps: 3
[INFO]    dem_resolution: 5
[INFO]    depthmap_resolution: 640
[INFO]    dsm: True
[INFO]    dtm: True
[INFO]    end_with: odm_orthophoto
[INFO]    fast_orthophoto: False
[INFO]    gcp: None
[INFO]    ignore_gsd: False
[INFO]    images: None
[INFO]    matcher_distance: 0
[INFO]    matcher_neighbors: 8
[INFO]    max_concurrency: 9
[INFO]    merge: all
[INFO]    mesh_octree_depth: 9
[INFO]    mesh_point_weight: 4
[INFO]    mesh_samples: 1.0
[INFO]    mesh_size: 300000
[INFO]    min_num_features: 10000
[INFO]    mve_confidence: 0.6
[INFO]    name: 66db0062-9943-4656-a38e-0c83038f6c59
[INFO]    opensfm_depthmap_method: PATCH_MATCH
[INFO]    opensfm_depthmap_min_consistent_views: 3
[INFO]    opensfm_depthmap_min_patch_sd: 1
[INFO]    orthophoto_bigtiff: IF_SAFER
[INFO]    orthophoto_compression: DEFLATE
[INFO]    orthophoto_cutline: False
[INFO]    orthophoto_no_tiled: False
[INFO]    orthophoto_resolution: 5
[INFO]    pc_classify: True
[INFO]    pc_csv: False
[INFO]    pc_ept: False
[INFO]    pc_filter: 2.5
[INFO]    pc_las: False
[INFO]    project_path: /var/www/data
[INFO]    rerun: None
[INFO]    rerun_all: False
[INFO]    rerun_from: ['odm_orthophoto']
[INFO]    resize_to: 2048
[INFO]    skip_3dmodel: False
[INFO]    sm_cluster: True
[INFO]    smrf_scalar: 1.25
[INFO]    smrf_slope: 0.15
[INFO]    smrf_threshold: 0.5
[INFO]    smrf_window: 18.0
[INFO]    split: 150
[INFO]    split_overlap: 100.0
[INFO]    texturing_data_term: gmi
[INFO]    texturing_keep_unseen_faces: False
[INFO]    texturing_nadir_weight: 22
[INFO]    texturing_outlier_removal_type: gauss_clamping
[INFO]    texturing_skip_global_seam_leveling: False
[INFO]    texturing_skip_hole_filling: False
[INFO]    texturing_skip_local_seam_leveling: False
[INFO]    texturing_skip_visibility_test: False
[INFO]    texturing_tone_mapping: none
[INFO]    time: False
[INFO]    use_3dmesh: True
[INFO]    use_exif: False
[INFO]    use_fixed_camera_params: False
[INFO]    use_hybrid_bundle_adjustment: False
[INFO]    use_opensfm_dense: False
[INFO]    verbose: False
[INFO]    ==============
[INFO]    Running dataset stage
[INFO]    Loading dataset from: /var/www/data/66db0062-9943-4656-a38e-0c83038f6c59/images
[INFO]    Loading images database: /var/www/data/66db0062-9943-4656-a38e-0c83038f6c59/images.json
[INFO]    Found 484 usable images
[INFO]    Coordinates file already exist: /var/www/data/66db0062-9943-4656-a38e-0c83038f6c59/odm_georeferencing/coords.txt
[INFO]    Parsing SRS header: WGS84 UTM 34N
[INFO]    Finished dataset stage
[INFO]    Running split stage
[WARNING] Found a split done file in: /var/www/data/66db0062-9943-4656-a38e-0c83038f6c59/opensfm/split_done.txt
[INFO]    Finished split stage
[INFO]    Running merge stage
[WARNING] Found merged point cloud in /var/www/data/66db0062-9943-4656-a38e-0c83038f6c59/odm_georeferencing/odm_georeferenced_model.laz
[WARNING] Found merged orthophoto in /var/www/data/66db0062-9943-4656-a38e-0c83038f6c59/odm_orthophoto/odm_orthophoto.tif
Traceback (most recent call last):
File "/code/run.py", line 56, in <module>
app.execute()
File "/code/stages/odm_app.py", line 93, in execute
self.first_stage.run()
File "/code/opendm/types.py", line 376, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 376, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 357, in run
self.process(self.args, outputs)
File "/code/stages/splitmerge.py", line 326, in process
merge_dems("dsm.tif", "DSM")
File "/code/stages/splitmerge.py", line 323, in merge_dems
log.ODM_WARNING("Found merged %s in %s" % (human_name, dsm_file))
NameError: global name 'dsm_file' is not defined

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Dataset processed correctly - needed to restart with changed texturing-nadir-weight (ortho looks something bumpy, with bubbles, etc.) 

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Params: pc-classify: true, sm-cluster: http://165.227.149.177:4000, min-num-features: 10000, rerun-from: odm_orthophoto, use-3dmesh: true, texturing-nadir-weight: 22, dtm: true, mesh-size: 300000, split: 150, split-overlap: 100, dsm: true, max-concurrency: 9

**Comment by pierotofy** [comment]
Thanks @merkato :pray: , this is now fixed in https://github.com/OpenDroneMap/ODM/commit/b8fa0f1d4e81a1ada2a9657eb86ad300e54889e5
