### ISSUE TITLE
Faster MVE makescene could be implemented

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1019]
The MVE file format is well documented and the code to manipulate it is alread open source. https://github.com/simonfuhrmann/mve/wiki/MVE-File-Format 

With some work we could make a version of `makescene` that uses symbolic links instead of copy+distortion of images, which is currently quite slow.

**Comment by pierotofy** [comment]
No longer applicable.

**Comment by smathermather** [comment]
Haha! Yup.
