### ISSUE TITLE
Incremental image processing

### ISSUE THREAD

**Issue by rligocki** [OpenDroneMap/ODM#1024]
I would like to ask if there is any way how to process images on the go. I have a computer, that captures images as a UAV fly survey. My goal is to process images one by one as they are captured so that after a flight, there is no need to post-process anything because orthomosaic or DEM is already generated. Best way to do that would be to create a task and then add images to queue. Everything using python.

Thanks 
Roman

**Comment by pierotofy** [comment]
Currently ODM does not support "live" image stitching, although it would be a really cool feature.

We'd welcome contributions to implement this.

Relevant: https://piero.dev/2018/08/toward-real-time-drone-mapping/

**Comment by annesteenbeek** [comment]
This is also something I would like to implement. 
Preferably  I would like to be able to generate a task that either monitors a folder or has some hook to take in new images. Maybe also some way to broadcast on when the map has been updated.
I'm just starting to familiarize myself with the codebase, how much work would this be to implement, and does anyone already have some tips on where to start?

If I have time to spare, I would also like to look at supporting this feature into webODM.

Preferably I would have some pipeline that does stitching, DSM, and classification.

**Comment by pierotofy** [comment]
This is still a very much welcomed feature, but probably belongs to a separate repository / application for the ODM ecosystem. The methods to do live "stitching" are quite different than the ones used by ODM.

It would be cool if somebody figured out a nice way to package https://github.com/ethz-asl/aerial_mapper which seems to do exactly this.

**Comment by smathermather** [comment]
Agreed. It is sufficiently different an approach that it would need to be a separate tool.
