### ISSUE TITLE
ODM_ORTHOPHOTO returns tiff without gps information

### ISSUE THREAD

**Issue by jplcarvalho** [OpenDroneMap/ODM#1034]
Hello,

I already finished the orthophoto mapa but the .tiff images doesn't have gps information. Therefore it is impossible to know the map location. Am I missing something? Thanks!

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
