### ISSUE TITLE
Problem with ./run.sh

### ISSUE THREAD

**Issue by zenereyes** [OpenDroneMap/ODM#1047]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!

First of all, thank you for taking the time to report an issue.

Before you continue, make sure you are in the right place. Please open an issue only to report faults and bugs. For questions and discussion please open a topic on http://community.opendronemap.org/c/opendronemap. 

Please use the format below to report bugs and faults. It will help improve the resolution process. 
****************************************

### How did you install OpenDroneMap? (Docker, natively, ...)?

natively

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 78 on Linux

### What is the problem?

INFO]    Finished opensfm stage
[INFO]    Running mve stage
[INFO]    running /home/lore/ODM-master/SuperBuild/src/elibs/mve/apps/makescene/makescene "/home/lore/ODM-master/project/odm_data_aukerman-master/opensfm/reconstruction.nvm" "/home/lore/ODM-master/project/odm_data_aukerman-master/mve"
/bin/sh: 1: /home/lore/ODM-master/SuperBuild/src/elibs/mve/apps/makescene/makescene: not found
Traceback (most recent call last):
  File "/home/lore/ODM-master/run.py", line 57, in <module>
    app.execute()
  File "/home/lore/ODM-master/stages/odm_app.py", line 92, in execute
    self.first_stage.run()
  File "/home/lore/ODM-master/opendm/types.py", line 370, in run
    self.next_stage.run(outputs)
  File "/home/lore/ODM-master/opendm/types.py", line 370, in run
    self.next_stage.run(outputs)
  File "/home/lore/ODM-master/opendm/types.py", line 370, in run
    self.next_stage.run(outputs)
  File "/home/lore/ODM-master/opendm/types.py", line 370, in run
    self.next_stage.run(outputs)
  File "/home/lore/ODM-master/opendm/types.py", line 351, in run
    self.process(self.args, outputs)
  File "/home/lore/ODM-master/stages/mve.py", line 32, in process
    system.run('%s "%s" "%s"' % (context.makescene_path, tree.opensfm_reconstruction_nvm, tree.mve), env_vars={'OMP_NUM_THREADS': args.max_concurrency})
  File "/home/lore/ODM-master/opendm/system.py", line 76, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 127

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

[Type answer here]

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

[Type answer here]

**Comment by smathermather** [comment]
This looks like a question rather than a bug. Can you please open a question on https://community.opendronemap.org? Thanks!
