### ISSUE TITLE
Add --epsg parameter

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1050]
Relevant discussion: https://community.opendronemap.org/t/proj-property-removed-from-recent-version-0-9-1/3105/2

**Comment by merkato** [comment]
Any progress in that issue will be appreciated ;) Pointcloud reprojection too ;)

**Comment by pierotofy** [comment]
Hasn't been done yet. Interested in contributing @merkato ?

**Comment by pierotofy** [comment]
This keeps getting asked as of late.

**Comment by pierotofy** [comment]
We're probably going to add this as part of WebODM export options. In the end, reprojection of assets via command line can be done easily via GDAL/PDAL.
