### ISSUE TITLE
Duplicate images trip ODM

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1055]
If duplicate images are added to a dataset by mistake, sometimes ODM runs out of memory. Perhaps we should include checks for duplicates?

**Comment by pierotofy** [comment]
Cause of problem was something else.

**Comment by smathermather** [comment]
Should we still be checking for dupes though? There are some other weird SfM effects if you feed in duplicates, if memory serves me.

**Comment by pierotofy** [comment]
I guess we could, just not sure how often this happens (or if its worth the runtime to do the checks).

**Comment by smathermather** [comment]
Fair. I just use `fdupes` when I know this is an issue.
