### ISSUE TITLE
deprecate liblas for PDAL

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/ODM#1056]
### How did you install OpenDroneMap? (Docker, natively, ...)?
Attempted natively under Alpine WSL

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Edge 44 on Windows 10

### What is the problem?
Dockerfile, configure.sh, configure_18_04.sh, and portable.Dockerfile still reference/depend upon liblas, which by the project's own documentation, recommends the usage of PDAL instead.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.
Making a clean break away from liblas would remove this deprecated dependency and allow easier portage to Alpine and other platforms.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
liblas is not compiled for Alpine, but PDAL is.

**Comment by pierotofy** [comment]
I've just built PDAL without `liblas-bin` in the #1156 branch so I think this can be closed?
