### ISSUE TITLE
Different output when I just change names of input images

### ISSUE THREAD

**Issue by fclof** [OpenDroneMap/ODM#1058]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

CentOS 7.2.1511

### What is the problem?

I was using PyODM API (with a NodeODM node ) to stitch drone images.

I found that I will get different output images if I just change the names of input images.

For example, let's say I have 10 images named as 'aaa_x.png' (aaa_0.png, aaa_1,png, ..., aaa_9.png). If I repeatedly call the PyODM API, I will always get the same output, which is as expected.

However, if I just change their names to 'bbb_x.png' (bbb_0.png, bbb_1,png, ..., bbb_9.png), I will get a different output image! The new output is similar to the old one (of course they are similar, because the input images are the same files), but they are different in detail (several different pixels in most cases, in the worst case an ouput missed a corner). 

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

The same input, the same output.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Not sure if this can be reproduced.

**Comment by pierotofy** [comment]
Hey @fclof :hand: I would expect this to happen, as changing the filenames might lead the point cloud reconstruction software to choose / optimize the cameras in a different order, leading to a different output.

I'm not sure if this can be fixed.
