### ISSUE TITLE
generating ply file

### ISSUE THREAD

**Issue by parang17** [OpenDroneMap/ODM#1059]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!

First of all, thank you for taking the time to report an issue.

Before you continue, make sure you are in the right place. Please open an issue only to report faults and bugs. For questions and discussion please open a topic on http://community.opendronemap.org/c/opendronemap. 

Please use the format below to report bugs and faults. It will help improve the resolution process. 
****************************************

### How did you install OpenDroneMap? (Docker, natively, ...)?

[Type answer here]
Docker 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[Type answer here]
ubuntu 18.04
### What is the problem?

[Type answer here]
I would like to get .ply data about point cloud

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

[Type answer here]

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

[Type answer here]
Here is my command.
sudo docker run -it --rm -v "$(pwd)/images:/code/images" -v "$(pwd)/odm_orthophoto:/code/odm_orthophoto" -v $(pwd)/odm_texturing:/code/odm_texturing -v "$(pwd)/odm_georeferencing:/code/odm_georeferencing" opendronemap/odm --mesh-size 100000

Here is tree structure
![image](https://user-images.githubusercontent.com/8020850/71519220-9511fe80-2884-11ea-9ec6-a075c3e737c8.png)

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
