### ISSUE TITLE
Unusual Output of ODM with GCP file generated from GCP Interface of WebODM

### ISSUE THREAD

**Issue by SifatMd** [OpenDroneMap/ODM#1060]
### What's your browser and operating system? 

Chrome 79 on Windows 10
### What is the problem?

I am generating GCP file using GCP interface of WebODM. This is the output: 

+proj=utm +zone=46 +ellps=WGS84 +datum=WGS84 +units=m +no_defs	
230622.50	2631108.96	50	3900.00	2800.00	DJI_0097.JPG	gcp01
230606.60	2631109.81	50	4460.00	2760.00	DJI_0097.JPG	gcp02
230645.72	2631068.52	50	2900.00	1230.00	DJI_0097.JPG	gcp03
230638.76	2631050.81	50	3050.00	540.00	DJI_0097.JPG	gcp04
230515.85	2631286.72	50	4240.00	330.00	DJI_0118.JPG	gcp05
230521.65	2631274.75	50	3670.00	470.00	DJI_0118.JPG	gcp06
230563.17	2631231.42	50	1860.00	1580.00	DJI_0118.JPG	gcp07
230541.15	2631237.82	50	2330.00	930.00	DJI_0118.JPG	gcp08
230603.56	2631116.19	50	3770.00	2980.00	DJI_0414.JPG	gcp09
230624.13	2631108.82	50	3840.00	1880.00	DJI_0414.JPG	gcp10
230640.32	2631074.61	50	4750.00	1400.00	DJI_0414.JPG	gcp11
230615.79	2631093.90	50	4520.00	2290.00	DJI_0414.JPG	gcp12
230666.07	2631280.05	50	3710.00	2070.00	DJI_0252.JPG	gcp13
230647.30	2631290.59	50	4110.00	1220.00	DJI_0252.JPG	gcp14
230638.67	2631276.35	50	3350.00	900.00	DJI_0252.JPG	gcp15
230656.09	2631242.44	50	2130.00	1790.00	DJI_0252.JPG	gcp16

I placed the gcp_list.txt file containing the above output in the images folder of ODM and ran ODM with the command "./run.sh OUTPUT" (As my images are in OUTPUT folder). But there is no orthophoto produced and the 3D mesh is really bizarre and unusual. What should I do to produce correct georeferenced 3D mesh file and orthophoto?

### What should be the expected behavior?

A georeferenced 3D mesh file should be produced. 

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

My steps are: 
1. Clone the project from https://github.com/OpenDroneMap/ODM.git 
2. Run: sudo bash configure.sh install
3. Set project_path in settings.yml file
4. Run: sudo pip install -r requirements.txt
5. Set environment variables in the bashrc file to appropriate paths
6. Run: ./run.sh OUTPUT

**Comment by pierotofy** [comment]
Is there a chance that the GCP coordinates could be wrong? How were they surveyed?

![image](https://user-images.githubusercontent.com/1951843/92953439-b9703400-f42f-11ea-974c-e27890cace3f.png)

Try to use 5 GCPs instead of 12 (remove the others). I'll close this for now, as it might be a problem with input rather than a bug.

To discuss further this, could we move the conversation over to https://community.opendronemap.org ? :pray:
