### ISSUE TITLE
Where to put the gcp_list.txt file in ODM project

### ISSUE THREAD

**Issue by SifatMd** [OpenDroneMap/ODM#1063]
I have run OpenDroneMap(ODM) on a bunch of drone images of a particular area. I have set the Ground Control Points(GCP) using Webodm gcp interface. Now, I have a gcp_list.txt file containing the images with appropriate latitude, longitude values. Now, in the OpenDroneMap Documentaion, it is stated that:

**The gcp_list.txt file must be created in the base of your project folder.**

Now, I have run ODM keeping the gcp_list.txt file in the images folder. But, I am not clear about where I should put the gcp_list.txt file exactly.

What does this actually mean?

What is the base of my project folder?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
