### ISSUE TITLE
[Feature] Add support for thermal bands

### ISSUE THREAD

**Issue by JCAAUSFRA** [OpenDroneMap/ODM#1067]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Edge

### What is the problem?

tried to process multi spec from Altum. got a "Process exited with code 1" error

**Comment by JCAAUSFRA** [comment]
Edge 44 on Windows 10

**Comment by pierotofy** [comment]
@JCAAUSFRA can you share your dataset and/or a copy of the output task? I know this issue is pretty old, but it's going to be though to solve without a dataset to test on or more info.

**Comment by JCAAUSFRA** [comment]
https://infarmau-my.sharepoint.com/:f:/g/personal/jerome_leray_infarm_io/EoMPtqKVzeVOsN8Wn1Q9XoYBGV8YzzjvalWiCJ_lAktGjQ?e=e6P9sR

**Comment by pierotofy** [comment]
I'll try to look into this one of these days.

**Comment by pierotofy** [comment]
The problem is due to the thermal band, which has a very small image size.

ODM needs better support for such images and will currently fail.

A workaround if you don't need the thermal band is to remove all the thermal band images.

**Comment by pierotofy** [comment]
Altum cameras are now supported! :clinking_glasses:
