### ISSUE TITLE
Orthophoto of multispectral

### ISSUE THREAD

**Issue by KeoChi** [OpenDroneMap/ODM#1070]
### How did you install OpenDroneMap? (Docker, natively, ...)?

natively

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

ubuntu16.04 

### What is the problem?
 I have run the newest code with [MicaSense dataset](https://community.opendronemap.org/t/micasense-red-gren-blue-near-ir-red-edge/3176). I found that I use "Image Viewer" to open the "odm_orthophoto.original.tif" and the garbled characters appeared on the right side of the image:
![odm_orthophoto original](https://user-images.githubusercontent.com/9250491/74308763-feea5700-4da3-11ea-881a-4e533cbf39d8.png)
  In addition, I use opencv to imread and imshow\imwrite the "odm_orthophoto.original.tif" that the result is same.
  Do the odm_orthophoto module have bug?

**Comment by pierotofy** [comment]
Possibly, this might need to be investigated. Perhaps one of the bands renders to a different image size than the others and might need to be padded. How does the file look in QGIS?

**Comment by KeoChi** [comment]
It look normaly in "Global Mapper". I have no QGIS.

**Comment by pierotofy** [comment]
https://www.qgis.org/en/site/

If it looks fine in both Global Mapper and QGIS, then it might be a problem with image viewer. The resulting file has 5 bands + alpha, which might be incorrectly handled by the image viewer.

**Comment by KeoChi** [comment]
@pierotofy Hello. I found that the alpha can influence the resulting file. But I don't know the reason.

**Comment by pierotofy** [comment]
Closing since this looks like a problem with the image reader, not ODM. :pray:
