### ISSUE TITLE
[Feature] Scale constraints support

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1071]
It has been suggested that the software could add scale constraints as described here https://community.opendronemap.org/t/scale-constraint/3622/4

This might need a different type of annotation file (similar to GCPs).

**Comment by Saijin-Naib** [comment]
What would be needed to describe each scale constraint?
XYZ and maybe a "constraint ID", so we know which two manual tie points are being used as a scale constraint together?

**Comment by pierotofy** [comment]
Being investigated at https://github.com/mapillary/OpenSfM/issues/737

**Comment by Saijin-Naib** [comment]
I see you're calling out specifically non-georeferenced data, but they can still be incredible helpful in ensuring accurate scaling for georeferenced data.

Would your proposal allow that as well?

**Comment by pierotofy** [comment]
Yes.

**Comment by pierotofy** [comment]
This is tricky; points from a 2D image could be triangulated to a closest 3D points in the **dense** point cloud, then the 3D points could be back-projected to the 2D cameras and manual features could be added to the feature list. Then (a modified) OpenSfM would have to be re-run using these novel features/3D point constraints.

And what if for any reason there are no points nearby?

An easier approach could be to apply an affine transform based on the closest 3D points alone, expect that I wouldn't trust it's accuracy due to camera angle (it would only be accurate when shots are perfectly nadir to the measurement surface).

There's a reason other software makes this process interactive and based on 3D measurements.

I'm going to close this as being out of scope. People can interactively scale a model using CloudCompare as a post-process operation.
