### ISSUE TITLE
[WARNING] LRE: submodel_0001 failed with: cannot convert Boolean

### ISSUE THREAD

**Issue by neelduttahere** [OpenDroneMap/ODM#1079]
**How did you install OpenDroneMap? (Docker, natively, ...)?**

Using Docker

 **What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)**

Chrome 79 on Windows 10

**What is the problem?**

I am trying process 500 images in WebODM using clusterODM (distributed processing).
This is how I have setup:

**Machine 1:** WebODM
**Machine 2:** ClusterODM
**Machine 3:** NodeODM
**Machine 4:** NodeODM
**Machine 5:** NodeODM

How it is connected:

**Machine 1** <-------**Machine 2** <--------**Machine (3-5)**

System Specifications:

**Machine 1** and **Machine 3-5**:

CPU: Ryzen 7 3600
RAM: 16gb DDR4 2133
500GB SSD and 1TB HDD

**Machine 2:**
CPU: i3
RAM: 12GB
1TB HDD

Essentially I am trying to achieve distributed split merge, where the 500 image data set is split into 100 images per set, so 5 sub models are created.

But this is the issue I am running into (according to log)

> [INFO]    Local Reconstruction submodel_0000
> [INFO]    ==================================
> [INFO]    running /usr/bin/env python2 /code/SuperBuild/src/opensfm/bin/opensfm detect_features "/var/www/data/122a67b7-b926-4c02-8681-f15ce938a3a9/submodels/submodel_0000/opensfm"
> **[WARNING] LRE: submodel_0001 failed with: [{"name":"texturing-skip-visibility-test","error":"Cannot convert 122a67b7-b926-4c02-8681-f15ce938a3a9 to boolean"}]**
> [INFO]    LRE: Re-queueing submodel_0001 (retries: 1)

As the above states, it is not able to convert the input from the checkbox "texturing-skip-visibility-test" to boolean. So I restart the process, but removing "texturing-skip-visibility-test". But then I get the same error, but for the checkbox I enabled just before "texturing-skip-visibility-test". So as I go unchecking the checkboxes in the custom settings options pane, each time I get the same type of error for all the checkboxes. However, I used the same settings on another dataset of 653 images, but in that case, the split was set to 218, and this error seemed to disappear. 

Also, according to log, it seems to have finished submodel_0000, the process stopped with an error.

> 2020-03-03 08:36:34,487 INFO: Reconstruction 0: 86 images, 94334 points
> 2020-03-03 08:36:34,487 INFO: 1 partial reconstructions in total.
> [INFO]    LRE: submodel_0000 finished successfully
> [INFO]    LRE: No remote tasks left to cleanup
> Traceback (most recent call last):
> File "/code/run.py", line 57, in <module>
> app.execute()
> File "/code/stages/odm_app.py", line 92, in execute
> self.first_stage.run()
> File "/code/opendm/types.py", line 464, in run
> self.next_stage.run(outputs)
> File "/code/opendm/types.py", line 445, in run
> self.process(self.args, outputs)
> File "/code/stages/splitmerge.py", line 99, in process
> lre.run_reconstruction()
> File "/code/opendm/remote.py", line 54, in run_reconstruction
> self.run(ReconstructionTask)
> File "/code/opendm/remote.py", line 251, in run
> raise nonloc.error
> pyodm.exceptions
> .NodeResponseError: [{"name":"texturing-skip-visibility-test","error":"Cannot convert 122a67b7-b926-4c02-8681-f15ce938a3a9 to boolean"}]
> 

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I create a new task, and these are the settings I use in webodm:

**

> mesh-octree-depth: 12, rerun-from: dataset, texturing-nadir-weight: 10, orthophoto-resolution: 2.0, dem-resolution: 5.0, force-gps: true, ignore-gsd: true, use-opensfm-dense: true, debug: true, split-overlap: 50, split: 100, pc-las: true, max-concurrency: 1, skip-3dmodel: true, texturing-data-term: area, texturing-skip-visibility-test: true

**

**Comment by pierotofy** [comment]
Thanks for the report @neelduttahere !

This should be fixed in `0.9.9` :+1: 

Please update and re-open this issue if the problem persists.
