### ISSUE TITLE
Computing GSD

### ISSUE THREAD

**Issue by rickesh** [OpenDroneMap/ODM#108]
GSD is computed by the formula. GSD = (Focal/Height)*CCDwidth. From the debugging of Opendronemap I found out Focal length computation and CCD width. But I do not see the computation of Height/depth anywhere in opendronemap. May I know if there is a way to get it? I am sure it is already being computed or half way through. Please let me know where/how I can get the depth/height information.

**Comment by dbrgn** [comment]
I'd also be interested in this issue.

**Comment by dakotabenjamin** [comment]
Hmm... Could you get the height from the altitude EXIF datum?

**Comment by smathermather** [comment]
I am unclear what the question is? Height / depth are implicit in the generation of camera positions and point cloud, so therefore at the bundler step in the traditional pipeline, and inside of OpenSfM in that toolchain. Maybe @paulinus could answer this better for OpenSfM.

**Comment by paulinus** [comment]
The GSD formula is correct. You can find the focal length in the file `reconstruction-with-image-size-XXX/opensfm/reconstruction.json`. In there, there is a list of cameras with their estimated `focal`. Note that this value is normalized and corresponds already to focal/width.

The height is not computed anywhere at the moment. We should define with respect to what reference altitude we would want to compute that.

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/computing-gsd/376
