### ISSUE TITLE
Cant read GPS metadata from GeoTIFF

### ISSUE THREAD

**Issue by davidlr99** [OpenDroneMap/ODM#1081]
### What is the problem?

I am trying to generate a georeferenced orthophoto from GeoTiff input data.

I want to use the `matcher-neighbors` and `matcher-distance` option to speed up the orthophoto generation. Unfortunately it looks like the GeoTiff tags from my input data **cant**  be read correctlyand therefore no coordinates file can be generated ( `matcher-neighbors` and `matcher-distance` wont work too):
```
[ERROR] Failed parsing GPS position for x.tif, skipping
[WARNING] Could not generate coordinates file. The orthophoto will not be georeferenced.
...
[INFO] No GPS information, using BOW matching
```

The GPS data is stored in the input files as [ModelTiepointTag](https://www.awaresystems.be/imaging/tiff/tifftags/modeltiepointtag.html) and as `GCP Projection`.

Best regards,
David

**Comment by pierotofy** [comment]
Hey @davidlr99 :hand: ODM cannot stitch GeoTIFFs. If these are normal photos, convert them to JPG using a tool such as GDAL. If these are orthophotos, you cannot use ODM to stitch them together.

I'll close this for now, unless there's a special use case here (a camera is producing GeoTIFFs?)
