### ISSUE TITLE
Multispectral - Rededge Mapping

### ISSUE THREAD

**Issue by jplcarvalho** [OpenDroneMap/ODM#1084]
Hello,

I'm currently dealing with images from a Micasense RedEdge-MX as input for the newest version of ODM.
During the testing I got a doubt about the process. Does the ODM already include some correction based on the DLS information, or are we required to pre-process the images based on the calibration panel?

If the DLS correction is being made, Is there an option to disable it? I believe the panel calibration would be more accurate.

Thank you

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
