### ISSUE TITLE
Improvement: refactor osfm.get_submodel_argv

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1088]
Parsing command line args should be done based on what parameters are set explicitly in `args`, not by manually parsing argv, which is tedious and error prone.

To track defaults: https://stackoverflow.com/questions/32056910/how-to-find-out-if-argparse-argument-has-been-actually-specified-on-command-line

**Comment by pierotofy** [comment]
Done in #1082

**Comment by smathermather** [comment]
That's a bit cleaner. Awesome.
