### ISSUE TITLE
Running project results in error "Process exited with code 1" after 4 seconds and will not complete

### ISSUE THREAD

**Issue by lukeworkh** [OpenDroneMap/ODM#1089]
I use ODM with Docker.

My browser is Firefox 74 running on Windows 10

The problem: When trying to run a project consisting of 469 images, ODM kicks out "Process exited with code 1" after 4 seconds and will not complete.

This began after a Docker update. 

After the update, Docker would not start, but gave me an error. I had to change Windows security settings to get it to run (I followed the recommendations here: https://github.com/docker/for-win/issues/3597#issuecomment-474949164). While this got Docker to work, upon starting WebODM, I was required to make a new account, and my previous projects were lost. I don't know if this has anything to do with the current issue, but I thought it may be relevant.

Docker settings are as follows:

CPUs: 10/12
Memory: 38.25/45.75  GB
Swap: 2/4 GB
Disk Image Size: 160 GB (10.2 GB used)/351.6

The settings for the project are as follows (though I have changed them once or twice to no avail).

Processing Node: node-odm-1 (auto)
Options: ignore-gsd: true, dsm: true, depthmap-resolution: 1000, dem-resolution: 2.0, orthophoto-resolution: 2.0, rerun-from: dataset

The dataset can be found at the following link:

https://drive.google.com/open?id=1bQ7KZgYxpXkFVnwCKkdYmTMHkj0uOYf-

The task output is as follows:

[INFO]    Initializing OpenDroneMap app - Fri Mar 20 13:02:08  2020
[INFO]    ==============
[INFO]    build_overviews: False
[INFO]    camera_lens: auto
[INFO]    cameras: {}
[INFO]    crop: 3
[INFO]    debug: False
[INFO]    dem_decimation: 1
[INFO]    dem_euclidean_map: False
[INFO]    dem_gapfill_steps: 3
[INFO]    dem_resolution: 2.0
[INFO]    depthmap_resolution: 1000.0
[INFO]    dsm: True
[INFO]    dtm: False
[INFO]    end_with: odm_orthophoto
[INFO]    fast_orthophoto: False
[INFO]    feature_type: sift
[INFO]    force_gps: False
[INFO]    gcp: None
[INFO]    ignore_gsd: True
[INFO]    matcher_distance: 0
[INFO]    matcher_neighbors: 8
[INFO]    max_concurrency: 10
[INFO]    merge: all
[INFO]    mesh_octree_depth: 10
[INFO]    mesh_point_weight: 4
[INFO]    mesh_samples: 1.0
[INFO]    mesh_size: 200000
[INFO]    min_num_features: 8000
[INFO]    mve_confidence: 0.6
[INFO]    name: fe699336-0ae4-4b27-a584-38e29c9aa905
[INFO]    opensfm_depthmap_method: PATCH_MATCH
[INFO]    opensfm_depthmap_min_consistent_views: 3
[INFO]    opensfm_depthmap_min_patch_sd: 1
[INFO]    orthophoto_compression: DEFLATE
[INFO]    orthophoto_cutline: False
[INFO]    orthophoto_no_tiled: False
[INFO]    orthophoto_png: False
[INFO]    orthophoto_resolution: 2.0
[INFO]    pc_classify: False
[INFO]    pc_csv: False
[INFO]    pc_ept: False
[INFO]    pc_filter: 2.5
[INFO]    pc_las: False
[INFO]    pc_rectify: False
[INFO]    pc_sample: 0
[INFO]    project_path: /var/www/data
[INFO]    rerun: None
[INFO]    rerun_all: False
[INFO]    rerun_from: ['dataset', 'split', 'merge', 'opensfm', 'mve', 'odm_filterpoints', 'odm_meshing', 'mvs_texturing', 'odm_georeferencing', 'odm_dem', 'odm_orthophoto']
[INFO]    resize_to: 2048
[INFO]    skip_3dmodel: False
[INFO]    sm_cluster: None
[INFO]    smrf_scalar: 1.25
[INFO]    smrf_slope: 0.15
[INFO]    smrf_threshold: 0.5
[INFO]    smrf_window: 18.0
[INFO]    split: 999999
[INFO]    split_overlap: 150
[INFO]    texturing_data_term: gmi
[INFO]    texturing_keep_unseen_faces: False
[INFO]    texturing_nadir_weight: 16
[INFO]    texturing_outlier_removal_type: gauss_clamping
[INFO]    texturing_skip_global_seam_leveling: False
[INFO]    texturing_skip_hole_filling: False
[INFO]    texturing_skip_local_seam_leveling: False
[INFO]    texturing_skip_visibility_test: False
[INFO]    texturing_tone_mapping: none
[INFO]    time: False
[INFO]    use_3dmesh: False
[INFO]    use_exif: False
[INFO]    use_fixed_camera_params: False
[INFO]    use_hybrid_bundle_adjustment: False
[INFO]    use_opensfm_dense: False
[INFO]    verbose: False
[INFO]    ==============
[INFO]    Running dataset stage
[INFO]    Loading dataset from: /var/www/data/fe699336-0ae4-4b27-a584-38e29c9aa905/images
[INFO]    Loading 469 images
[INFO]    Wrote images database: /var/www/data/fe699336-0ae4-4b27-a584-38e29c9aa905/images.json
[INFO]    Found 469 usable images
[INFO]    Parsing SRS header: WGS84 UTM 16N
[INFO]    Finished dataset stage
[INFO]    Running split stage
[INFO]    Normal dataset, will process all at once.
[INFO]    Finished split stage
[INFO]    Running merge stage
[INFO]    Normal dataset, nothing to merge.
[INFO]    Finished merge stage
[INFO]    Running opensfm stage
[INFO]    Altitude data detected, enabling it for GPS alignment
[INFO]    ['use_exif_size: no', 'feature_process_size: 2048', 'feature_min_frames: 8000', 'processes: 10', 'matching_gps_neighbors: 8', 'matching_gps_distance: 0', 'depthmap_method: PATCH_MATCH', 'depthmap_resolution: 1000.0', 'depthmap_min_patch_sd: 1', 'depthmap_min_consistent_views: 3', 'optimize_camera_parameters: yes', 'undistorted_image_format: tif', 'bundle_outlier_filtering_type: AUTO', 'align_orientation_prior: vertical', 'triangulation_type: ROBUST', 'bundle_common_position_constraints: no', 'feature_type: SIFT', 'use_altitude_tag: yes', 'align_method: auto', 'local_bundle_radius: 0']
[INFO]    running /usr/bin/env python2 /code/SuperBuild/src/opensfm/bin/opensfm extract_metadata "/var/www/data/fe699336-0ae4-4b27-a584-38e29c9aa905/opensfm"
2020-03-20 13:02:11,468 INFO: Extracting EXIF for DJI_0113.jpg
Traceback (most recent call last):
File "/code/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
command.run(args)
File "/code/SuperBuild/src/opensfm/opensfm/commands/extract_metadata.py", line 35, in run
d = self._extract_exif(image, data)
File "/code/SuperBuild/src/opensfm/opensfm/commands/extract_metadata.py", line 64, in _extract_exif
d = exif.extract_exif_from_file(data.open_image_file(image))
File "/code/SuperBuild/src/opensfm/opensfm/exif.py", line 98, in extract_exif_from_file
d = exif_data.extract_exif()
File "/code/SuperBuild/src/opensfm/opensfm/exif.py", line 359, in extract_exif
focal_35, focal_ratio = self.extract_focal()
File "/code/SuperBuild/src/opensfm/opensfm/exif.py", line 208, in extract_focal
self.extract_sensor_width(),
File "/code/SuperBuild/src/opensfm/opensfm/exif.py", line 222, in extract_sensor_width
units_per_pixel = 1 / pixels_per_unit
ZeroDivisionError: float division by zero
Traceback (most recent call last):
File "/code/run.py", line 57, in <module>
app.execute()
File "/code/stages/odm_app.py", line 92, in execute
self.first_stage.run()
File "/code/opendm/types.py", line 464, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 464, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 464, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 445, in run
self.process(self.args, outputs)
File "/code/stages/run_opensfm.py", line 25, in process
octx.extract_metadata(self.rerun())
File "/code/opendm/osfm.py", line 191, in extract_metadata
self.run('extract_metadata')
File "/code/opendm/osfm.py", line 22, in run
(context.opensfm_path, command, self.opensfm_project_path))
File "/code/opendm/system.py", line 76, in run
raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1

Any help regarding this would be fantastic!

**Comment by pierotofy** [comment]
Hey @lukeworkh  :hand: thanks for the report!

This is due to the Zenmuse camera erroneously having zero values in the `FocalPlaneXResolution` value of the EXIFs. ODM (OpenSfM) should probably handle this case better. This should be fixed in the next release. In the meanwhile, I can recommend to use `exiftool` to remove the `FocalPlaneXResolution` values from the images as a temporary workaround.

**Comment by pierotofy** [comment]
This should be fixed.
