### ISSUE TITLE
WebODM storage space stuck at 58.4GB

### ISSUE THREAD

**Issue by Vantage-DS** [OpenDroneMap/ODM#1100]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome

### What is the problem?

The storage space shown on the diagnostic page of WebODM seems to be stuck at 58.4GB, even when the Docker image size is higher or lower. I cannot process multiple datasets as the space fills up.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

When setting the image size via Docker, the storage space shown under WebODM's diagnostics page should reflect this same size and be stuck at 58.4GB,

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Install Docker Desktop.
Install WebODM App Version: 1.3.6 from git hub
Set Docker disk image size to X GB (400GB in my case)
Restart Docker and WebODM
Open the WebODM Diagnostic page - see that storage space is incorrect vs docker image disk image size

![2](https://user-images.githubusercontent.com/42471125/79050879-e15f2f80-7c24-11ea-96c9-33503a2d3cb6.PNG)
![1](https://user-images.githubusercontent.com/42471125/79050894-e58b4d00-7c24-11ea-95ac-b3a12d58dbab.PNG)

**Comment by pierotofy** [comment]
We'll continue the conversation on this thread https://community.opendronemap.org/t/webodm-space-shown-not-corresponding-to-docker-image-size/4076 (it's not a bug in ODM per-se, but a probem with docker on Windows).
