### ISSUE TITLE
About point cloud claasification using ODM

### ISSUE THREAD

**Issue by tub-sgg** [OpenDroneMap/ODM#1104]
Hello, when i checked the introduction of ODM,,  several functions  are available:
Classified Point Clouds
3D Textured Models
Georeferenced Orthorectified Imagery
Georeferenced Digital Elevation Models.

I want to know whether the Classifiy Point cloud tools mean ODM can be used for segmentation and classification of point cloud.And can specify more details or is there some document for this part?  @pierotofy

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
