### ISSUE TITLE
Split merge feature error with ODM 0.9.8

### ISSUE THREAD

**Issue by katarias** [OpenDroneMap/ODM#1110]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!
### How did you install OpenDroneMap? (Docker, natively, ...)?

Natively installed in Ubuntu 16.04 for Version 0.9.8

### What's your browser and operating system? 

 Firefox 76 on Ubuntu Linux 

### What is the problem?

When enable split-merge , it fails in processing submodels.It has only 23 images

/mnt/odm/run.sh --project-path /mnt/dataset --split 5 --split-overlap 1 --pc-csv --ignore-gsd --use-3dmesh --use-opensfm-dense --matcher-distance 150 --mesh-octree-depth 9 --mesh-size 100000 --matcher-neighbors 0 --min-num-features 8000 --crop 1 --end-with odm_orthophoto 1234 --dsm --dtm

[INFO]    Aligning submodels...
[INFO]    ========================
[INFO]    Processing submodel_0000
[INFO]    ========================
Traceback (most recent call last):
  File "/mnt/odm/run.py", line 57, in <module>
    app.execute()
  File "/mnt/odm/stages/odm_app.py", line 92, in execute
    self.first_stage.run()
  File "/mnt/odm/opendm/types.py", line 461, in run
    self.next_stage.run(outputs)
  File "/mnt/odm/opendm/types.py", line 442, in run
    self.process(self.args, outputs)
  File "/mnt/odm/stages/splitmerge.py", line 150, in process
    system.run(" ".join(map(quote, argv)), env_vars=os.environ.copy())
  File "/usr/lib/python2.7/pipes.py", line 269, in quote
    for c in file:
TypeError: 'float' object is not iterable

**Comment by pierotofy** [comment]
This has been fixed.
