### ISSUE TITLE
Is ODM support IR Image？

### ISSUE THREAD

**Issue by DrifterFun** [OpenDroneMap/ODM#1114]
### How did you install OpenDroneMap? (Docker, natively, ...)?
Docker on Windows10

### What's your browser and operating system? 
Windows10 & Chrome

### Is ODM support IR Image with GPS？ I have normally run ODM for a RGB image set and get good results. I wonder that  Is ODM supports IR Image like the following?
![DJI_0423_R](https://user-images.githubusercontent.com/33057384/83380955-f335a580-a411-11ea-8e91-6cce76e38adb.JPG)
![DJI_0425_R](https://user-images.githubusercontent.com/33057384/83380988-06487580-a412-11ea-8be3-f6095bb27d99.JPG)

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

I want to get odm_orthophoto image. I have run the code. However, the result may not satisfy my requires.
![image](https://user-images.githubusercontent.com/33057384/83381147-6ccd9380-a412-11ea-90b4-e6788c3f4cab.png)

**Comment by smathermather** [comment]
Can you post this query to community.opendronemap.org? That is a more appropriate place for questions.
