### ISSUE TITLE
libdc1394 error: Failed to initialize libdc1394

### ISSUE THREAD

**Issue by joseluisbossio** [OpenDroneMap/ODM#112]
Hi, we have a problem to testing caliterra example while running texturing:
- running texturing - Fri May 22 16:08:12 ART 2015

libdc1394 error: Failed to initialize libdc1394
Error in OdmTexturing:
Error in OdmTexturing:
Failed to read image:
'/home/cpacheco/odm_data/caliterra//IMG_9354.jpg'

For more detailed information, see log file.

quitting cause:
        "/home/cpacheco/OpenDroneMap/bin/odm_texturing" -bundleFile /home/cpacheco/odm_data/caliterra/reconstruction-with-image-size-2400/pmvs/bundle.rd.out -imagesPath /home/cpacheco/odm_data/caliterra/ -imagesListPath /home/cpacheco/odm_data/caliterra/reconstruction-with-image-size-2400/pmvs/list.rd.txt -inputModelPath /home/cpacheco/odm_data/caliterra/reconstruction-with-image-size-2400-results/odm_mesh-0000.ply -outputFolder /home/cpacheco/odm_data/caliterra/reconstruction-with-image-size-2400-results/odm_texturing/ -textureResolution 4096 -bundleResizedTo 2400 -textureWithSize 3600 -logFile /home/cpacheco/odm_data/caliterra/reconstruction-with-image-size-2400/odm_texturing/odm_texturing_log.txt
returned with code 256

Thanks in advance... 
JL

**Comment by joseluisbossio** [comment]
We executed the following command:  sudo ln /dev/null /dev/raw1394
relative the message error: "libdc1394 error: Failed to initialize libdc1394"

After that, the same error on OdmTexturing happened:

Error in OdmTexturing:
Failed to read image:
'/home/cpacheco/odm_data/caliterra//IMG_9354.jpg'

It's happened again with another example called 'benckmark'.

**Comment by smathermather** [comment]
Ah. Try renaming to .jpg instead of .JPG.

**Comment by smathermather** [comment]
Also, you can ignore the libdc1394 error. It should be a warning.

**Comment by joseluisbossio** [comment]
Hi, after rename the extension files to lower case, we have the following
problem:

tail nohup.out

Error in Georef:

Failed opening /home/cpacheco/odm_data/benchmark/gcp_list.txt for reading.

What about the gpc_list.txt file?

quitting cause:
  "/home/cpacheco/OpenDroneMap/bin/odm_georef" -bundleFile
/home/cpacheco/odm_data/benchmark/reconstruction-with-image-size-2400/pmvs/bundle.rd.out
-gcpFile /home/cpacheco/odm_data/benchmark/gcp_list.txt -imagesPath
/home/cpacheco/odm_data/benchmark/ -imagesListPath
/home/cpacheco/odm_data/benchmark/reconstruction-with-image-size-2400/pmvs/list.rd.txt
-bundleResizedTo 2400 -inputFile
/home/cpacheco/odm_data/benchmark/reconstruction-with-image-size-2400-results/odm_texturing/odm_textured_model.obj
-outputFile /home/cpacheco/odm_data/benchmark/reconstruction-with-image-size-2400-results/odm_texturing/odm_textured_model_geo.obj
-logFile /home/cpacheco/odm_data/benchmark/reconstruction-with-image-size-2400/odm_georeferencing/odm_georeferencing_log.txt
returned with code 256

Thanks in advance!
JL

**Comment by smathermather** [comment]
Yes, there is no georeference file included for that dataset, so that is just telling you that. Cheers! It completed!

**Comment by smathermather** [comment]
(That is an optional file that allows for georeferencing and orthophoto generation).

**Comment by joseluisbossio** [comment]
;) thank buddy!

About the gcp_list.txt, we are very interested in orthophotos. Do you have
(public domain) documentation about how to create this kind of photos and
the coordinates file?

**Comment by smathermather** [comment]
NP, @joseluisbossio. Check the wiki for documentation on gcp_list.txt. It's pretty simple, but let me know if any clarification is needed:

https://github.com/OpenDroneMap/OpenDroneMap/wiki/Running-OpenDroneMap

**Comment by jewelthief** [comment]
I am getting "libdc1394 error: Failed to initialize libdc1394" but after looking at above comment by smarthermather that its a warning, i have kept the processing job ON. but its not showing any new update for more than an hour now. Not sure if i have to kill the job and start again....please guide.

Looking at CPU usage, it seems like now its not doing anything, but there is no confirmation on the screen of job completed.

**Comment by jewelthief** [comment]
Update: I see the results folder have been created, but obj file is missing in texturing folder. How do i avoid this?

**Comment by smathermather** [comment]
Looks like this got resolved by letting it run to completion. Can you confirm @jewelthief? Reopen if you need to.

**Comment by jewelthief** [comment]
We can close this. Thanks @smathermather

**Comment by smathermather** [comment]
Cool. Thanks @jewelthief
