### ISSUE TITLE
problem connecting to server

### ISSUE THREAD

**Issue by quietNightTime** [OpenDroneMap/ODM#1121]
### How did you install OpenDroneMap? (Docker, natively, ...)?

installed via Docker

### What's your browser and operating system?

Chrome 83 on Windows 10

### What is the problem?

it appears I can't conect to the server

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

I can't run ODM because of it

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

trying to run via docker
![image](https://user-images.githubusercontent.com/16447853/84892054-3132fa80-b09d-11ea-9943-01032cd19251.png)

tried to reinstall via cmd:
![image](https://user-images.githubusercontent.com/16447853/84892204-71927880-b09d-11ea-990e-b46e384a310a.png)

even tried to connect to webODM to see about that server but doesn't work:
![image](https://user-images.githubusercontent.com/16447853/84892319-a56d9e00-b09d-11ea-9602-13fcd2ee2efc.png)

Do other people have trouble with connecting to the server?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: This seems like an installation issue, and not a bug. Thank you! :+1:
