### ISSUE TITLE
Split-merge submodel cutline generation fails

### ISSUE THREAD

**Issue by LinFor** [OpenDroneMap/ODM#1124]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 83 on Windows 10
Docker host (with odm) is Ubuntu 20.04 LTS

### What is the problem?

Error during split-merge processing

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Successful processing

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I run dataset processing with splitting, some of submodels fails on cutline generation:
```
...
Starting GRASS GIS...
Creating new GRASS GIS location <tmploc>...
Executing <bash script.sh> ...
Reading band 2 of 4...
Link to raster map <ortho> created.
ERROR 1: sqlite3_exec(UPDATE gpkg_contents SET min_x = NULL, min_y = NULL, max_x = NULL, max_y = NULL WHERE lower(table_name) = lower('convexhull') AND Lower(data_type) = 'features') failed: attempt to write a readonly database
...
Finding cutlines in both directions
Traceback (most recent call last):
  File "/code/opendm/grass/addons/i.cutlinesmod.py", line 641, in <module>
    main()
  File "/code/opendm/grass/addons/i.cutlinesmod.py", line 308, in main
    hnumber_lines = int(number_lines * (ewrange / nsrange))
ZeroDivisionError: float division by zero
Erasing temporary files...
ERROR: Vector map <cutline> not found
ERROR: Vector map <result> not found
FAILURE:
Unable to open datasource `result.gpkg' with the following drivers.
...
```
Seems that all went ok before this point.

My run parameters is:
```
split-multitracks: true, dtm: true, split-overlap: 250, split: 45, dsm: true, cameras: {"dji fc2103 4056 2280 brown 0.6666 rgb":{"p2":-0.0006469491524071298,"p1":-0.0010578066385128844,"width":4056,"projection_type":"brown","height":2280,"k3":0.21421955248266547,"k2":-0.3758572172770327,"k1":0.15024134660909239,"focal_y":0.6317013175338543,"focal_x":0.6317013175338543,"c_y":0.004099519063322445,"c_x":-0.011649087355432686}}, rerun-from: opensfm
```
Full log: https://pastebin.com/4cfLKJZi

**Comment by pierotofy** [comment]
This should be fixed since we've changed the cutline algorithm. :+1: If not, please re-open the issue? :pray:
