### ISSUE TITLE
line scan UAV data process

### ISSUE THREAD

**Issue by HaoweiGis** [OpenDroneMap/ODM#1127]

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by HaoweiGis** [comment]
I am very happy to move to the forum, I look forward to a professional answer. Thank you！



在 2020-06-27 21:22:42，"Piero Toffanin" <notifications@github.com> 写道：

Could we move this conversation over to the forum at https://community.opendronemap.org? 🙏 The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! 👍
