### ISSUE TITLE
When `--pc-fileter ` specified, ODM can't work.

### ISSUE THREAD

**Issue by pqiaohaoq** [OpenDroneMap/ODM#1128]
### What is the problem?

https://github.com/OpenDroneMap/ODM/blob/c4bbee2881549b8fca5bcaf68fb86d9cae4b8bd0/opendm/point_cloud.py#L14-L16
https://github.com/OpenDroneMap/ODM/blob/c4bbee2881549b8fca5bcaf68fb86d9cae4b8bd0/opendm/point_cloud.py#L31-L35

When using options `--pc-filter 0` , it will return. ODM won't copy `point_cloud.ply`. But some of the steps that follow require it.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Is it possible to copy even when`-- pc-filter 0` is specified.

**Comment by pierotofy** [comment]
Good catch! I suspect this remained hidden for so long because not too many people disable filtering.

Would you be interested in making a pull request for this? The program should probably just copy the point cloud over in this case.
