### ISSUE TITLE
Typo in tag

### ISSUE THREAD

**Issue by magnus-eigenvision** [OpenDroneMap/ODM#1135]
### What is the problem?

The last tag on the repo is "v0.1.0.1"

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Unless I misunderstood the tagging pattern it should have been "v1.0.1", which is also what can be found in the `VERSION` file.

**Comment by pierotofy** [comment]
Yep, that was a mistake. 

It has been fixed. Thank you! :+1:
