### ISSUE TITLE
Three dimensional reconstruction of multiple routes

### ISSUE THREAD

**Issue by fredcool7** [OpenDroneMap/ODM#1146]
Great job！
I am using UAV of DJI for aerial mapping. After that, ODM is used for 3D reconstruction. However, I encountered a problem. When surveying and mapping, DJI UAV will store pictures of multiple routes in multiple different folders. The photo information of each folder starts from 001. However, when I used ODM, I found that multiple folders could not appear in the path where we stored photos. We will have to store all the photos in one folder, but in this way, the route information will be disturbed, and the 3D reconstruction model will have some errors (compared with pix4d)
I'm using the Linux code in the example. Please help me solve this problem. How to reconstruct the three-dimensional model of the ground surface composed of several route photos.
Looking for your reply.
Best Regards.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
