### ISSUE TITLE
ODM 1.0.1 Compilation failure due to eigen package download

### ISSUE THREAD

**Issue by katarias** [OpenDroneMap/ODM#1147]
### How did you install OpenDroneMap? (Docker, natively, ...)?

natively

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Ubuntu 16.04

### What is the problem?

Compilation failure 
CMake Error at /mnt/odm/odm-v1.01/SuperBuild/build/mvstexturing/elibs/ext_eigen/src/ext_eigen-stamp/download-ext_eigen.cmake:27 (message):
  error: downloading 'https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz'
  failed

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Should Compile properly

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Installing ODM 1.0.1 - https://github.com/OpenDroneMap/ODM/archive/v1.0.1.zip

-------------
[ 15%] Performing download step (download, verify and extract) for 'ext_eigen'
-- downloading...
     src='https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz'
     dst='/mnt/odm/odm-v1.01/SuperBuild/build/mvstexturing/elibs/ext_eigen/src/3.3.2.tar.gz'
     timeout='none'
[ 28%] Performing download step (git clone) for 'zstd'
[ 29%] Performing download step (git clone) for 'lastools'
[ 30%] Performing download step (git clone) for 'gflags'
Cloning into 'lastools'...
Cloning into 'zstd'...
Cloning into 'gflags'...
CMake Error at /mnt/odm/odm-v1.01/SuperBuild/build/mvstexturing/elibs/ext_eigen/src/ext_eigen-stamp/download-ext_eigen.cmake:27 (message):
  error: downloading 'https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz'
  failed

    status_code: 22
    status_string: "HTTP response code said error"
    log:   Trying 18.205.93.1...

  Connected to bitbucket.org (18.205.93.1) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  TLSv1.2 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [106 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [2895 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [148 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Client hello (1):

  [1 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS change cipher, Client hello (1):

  [1 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256

  ALPN, server accepted to use http/1.1

  Server certificate:

  	 subject: businessCategory=Private Organization; jurisdictionC=US;
  jurisdictionST=Delaware; serialNumber=3928449; C=US; ST=California; L=San
  Francisco; O=Atlassian, Inc.; OU=Bitbucket; CN=bitbucket.org

  	 start date: Mar 27 00:00:00 2020 GMT

  	 expire date: May 23 12:00:00 2022 GMT

  	 subjectAltName: bitbucket.org matched

  	 issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2
  Extended Validation Server CA

  	 SSL certificate verify ok.

  [5 bytes data]

  GET /eigen/eigen/get/3.3.2.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.47.0

  Accept: */*

  

  [5 bytes data]

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  [5 bytes data]

  TLSv1.2 (OUT), TLS alert, Client hello (1):

  [2 bytes data]

elibs/CMakeFiles/ext_eigen.dir/build.make:89: recipe for target 'elibs/ext_eigen/src/ext_eigen-stamp/ext_eigen-download' failed
make[5]: *** [elibs/ext_eigen/src/ext_eigen-stamp/ext_eigen-download] Error 1
CMakeFiles/Makefile2:128: recipe for target 'elibs/CMakeFiles/ext_eigen.dir/all' failed
make[4]: *** [elibs/CMakeFiles/ext_eigen.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
------------------------
------------------------
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Compiling build
-- No build type selected, default to Release
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

CMake Warning at modules/odm_georef/CMakeLists.txt:16 (find_package):
  Could not find a package configuration file provided by "PCL" (requested
  version 1.8) with any of the following names:

    PCLConfig.cmake
    pcl-config.cmake

  Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
  to a directory containing one of the above files.  If "PCL" provides a
  separate development package or SDK, be sure it has been installed.

CMake Error at modules/odm_georef/CMakeLists.txt:19 (find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.
-- Configuring incomplete, errors occurred!
See also "/mnt/odm/odm-v1.01/build/CMakeFiles/CMakeOutput.log".
Configuration Finished

**Comment by pierotofy** [comment]
This should be fixed! Please re-open if the issue persists. Thanks for the report and patch! :pray:

**Comment by chandrahaslanka** [comment]
@pierotofy, does this require a rebuild of https://github.com/OpenDroneMap/ODM/archive/v1.0.1.zip?

I downloaded the above package and checked External-MvsTexturing.cmake. It seems to hold reference to a different tag (not `101`)

```
  GIT_REPOSITORY    https://github.com/OpenDroneMap/mvs-texturing
  GIT_TAG           099
```

https://github.com/OpenDroneMap/ODM/blob/v1.0.1/SuperBuild/cmake/External-MvsTexturing.cmake#L12

**Comment by pierotofy** [comment]
Yes we should release a new version.

For the time being I would compile from master. It's pretty much the same as 1.0.1.
