### ISSUE TITLE
Integrate LiDAR point clouds with drone aerial photos

### ISSUE THREAD

**Issue by nyinyinyanlin** [OpenDroneMap/ODM#1149]
I'm looking for the possibility of integrating with LiDAR point clouds and drone aerial photos. Can we build mesh and 3D model out of LiDAR point clouds and drone photos to texture them? Is there a possibility for that? Or are there any workarounds?

Thank you very much for your wisdom.

**Comment by tiagodc** [comment]
I'm interested in the answer as well!

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by nyinyinyanlin** [comment]
Sure thing @pierotofy 

I am sorry that I didn't know such questions are meant to be asked in another forum. Thank you very much for pointing out.
