### ISSUE TITLE
Different folders were outputed for locally run ClusterODM and remotely run NodeODM

### ISSUE THREAD

**Issue by jchen706** [OpenDroneMap/ODM#1154]
Dataset used is Phalaborwa. The 36 images. 

I used the ClusterODM locally on Virtualbox ubuntu 16.04. NodeODM was run on another machine. I used the docker configurations. 

The command ran locally was **sudo docker run -ti --rm -v /$(pwd):/datasets/code opendronemap/odm --project-path /datasets --split 18 --split-overlap 75 --use-3dmesh --sm-cluster http://172.17.0.1:4000**

The nodeODM command ran from the other machine was just **sudo docker run -p 3000:3000 opendronemap/nodeodm.**

I want to get the same folders output from the sub Model 0 ran locally and the sub Model 1. 
Sub Model 1 is missing mve, odm_filterpoints, odm_meshing, odm_texturing ..etc. As you can see in the images below.

Sub Model 0 ran locally
;
![image](https://user-images.githubusercontent.com/32785168/91243535-3a34ed80-e718-11ea-9138-1a8c51cf8958.png)

Sub Model 1 ran remotely.
![image](https://user-images.githubusercontent.com/32785168/91245895-939f1b80-e71c-11ea-96a8-f91e30853b79.png)

This is the command prompt from the other machine that nodeODM is running: 
![image](https://user-images.githubusercontent.com/32785168/91246932-1c1ebb80-e71f-11ea-905d-396c6a2f3feb.png)

**Comment by pierotofy** [comment]
This sounds like a question? Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by smathermather** [comment]
https://community.opendronemap.org/t/seems-when-a-submodel-is-ran-remotely-the-mve-folder-and-odm-mesh-are-not-generated-compare-to-a-locally-run-split-merge/5231/2
