### ISSUE TITLE
Scope of Work - Ubuntu 20.04LTS (Core20 SNAP) and WSL Image

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/ODM#1159]
### Scope of Work
Update OpenDroneMap and associated blocking libraries to be compatible with Ubuntu 20.04LTS, and Core20 snap packaging.
In addition, from the updated libraries, generate a WSL 1/2 compatible image of the same.

Further, updates to documentation (_and build tooling?_) to support any manual changes needed to ensure library compatibility with Ubuntu 20.04LTS and Core20 snap will be generated.

### Alternative Scope
Potentially, a rebase around 18.04LTS and Core18 snap packaging as an alternate if too many blocking packages/dependencies exist that we can't push upstream.

### Timeframe
Projected to be approximately 4 weeks

### Work-Hours
Projected to be approximately 160 hours

### Contractor
[Dan Llewellyn](https://snapcraft.ninja/)  
"I am the foremost independent Snap Package expert with experience of bringing many well-known proprietary apps and open source projects to the Snap Store for Linux"

### Why does this matter
1. Updated libraries bring many fixes, performance enhancements, and potentially features as well
2. Updated Ubuntu version provides a buffer of many more years of support, as well as access to more recent Linux Kernel for better device compatibility, performance, and features/security
3. Snap packaging provides a external-dependency free and sandboxed installation and runtime on compatible Linux distros, even outside of the Ubuntu family, greatly increasing the target audience.
3a. Distros supporting snapd/Store (Arch Linux, CentOS, Debian, elementary OS, Fedora, KDE Neon, Kubuntu, Manjaro, Linux Mint, openSUSE, Red Hat Enterprise Linux, Ubuntu, Raspberry Pi, and others)
3b. Snaps are compiled, hosted, and distributed for free via the Snap store.
3c. Snaps can have multiple channels (stable, dev, etc.)
4. WSL2 allows for running Linux programs natively (using the Linux Kernel) alongside other programs under Windows 10 1903 and above (WSL1 uses binary compatibility, but does not use the Linux Kernel)
4a. WSL 1/2 images can be distributed via the Microsoft store, allowing easy installation & management by end-user
4b. WSL dynamically allocates disk, RAM, CPU, and soon GPU, easing deploy and running for end-users as they don't need to configure Docker host and statically allocate resources

**Comment by pierotofy** [comment]
Funding goal achieved! Updates coming soon.

**Comment by pierotofy** [comment]
Progress updates will be posted here: https://community.opendronemap.org/t/progress-on-snap-packaging-project-for-odm/5711

**Comment by pierotofy** [comment]
I think with https://github.com/OpenDroneMap/ODM/pull/1189 this issue can now be closed.

In the next few days we will do some testing to make sure things are working properly, but otherwise this funding proposal has been completed successfully!

Thanks to all, especially @Saijin-Naib for spearheading the proposal and @diddledan for the implementation! :pray:
