### ISSUE TITLE
Generic Question: extracting individual ortho results

### ISSUE THREAD

**Issue by baziz** [OpenDroneMap/ODM#1171]
Hey Everyone,

I'm new to ODM and wonder how you can extract, after orthophoto'ing, say 1000 images, the data pertaining to a particular image.  How was it warped?  What vertices in the original image were moved where?  Can I recover this information?

Thanks for your great work!

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
