### ISSUE TITLE
Automatically assign texturing-nadir-weight values based on rooftop presence likelihood

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1175]
It would be cool to automatically guess whether a dataset contains rooftops and automatically increase the texturing-nadir-weight setting (and decrease it if there aren't).

Not sure what would be the best approach.

- ML approach (Keras, Tensorflow, etc.)
- Simple Edge Detection / Blurring / Filtering / Segmentation
- DEM analysis and count of "jumps" in steepness
- OSM buildings footprints

Or a combination.

**Comment by pierotofy** [comment]
We've solved the problem by removing the option altogether instead: https://github.com/OpenDroneMap/ODM/pull/1201 :clinking_glasses:

**Comment by smathermather** [comment]
Lol, yes indeed.
