### ISSUE TITLE
Possible bug in split merge with larger datasets

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#1206]
I haven't managed to replicate in anything smaller than my 5-7k datasets. The various errors described starting here:
https://github.com/OpenDroneMap/ODM/pull/1172#issuecomment-723142935

This is running on docker, on VMWare, which to date has not been an issue. The largest dataset I have successfully run 2.0.0 on was 91,000 images.

I can furnish the data on request.

**Comment by pierotofy** [comment]
Would you be available to provide a test environment / machine also? It might be easier that way, since it could be dependent on that.

**Comment by pierotofy** [comment]
This *should* be fixed with https://github.com/OpenDroneMap/OpenSfM/commit/6637d3e2f2821202a46a5c57b1fb6166512e502f

If not, feel free to re-open. :pray:
