### ISSUE TITLE
stack smashing detected while creating ortophoto

### ISSUE THREAD

**Issue by SimoneNascivera** [OpenDroneMap/ODM#1214]
### How did you install OpenDroneMap? (Docker, natively, ...)?

I'm currently running OpenDroneMap in Docker, with the last image just updated

### What's your browser and operating system?

I'm currently running ODM only in textual console

### What is the problem?

After extracting the features, matching them, etc etc right after generating texture patches the script brokes and gives me this error:
```
Running global seam leveling:
	Create matrices for optimization... *** stack smashing detected ***: terminated
Aborted (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 69, in <module>
    app.execute()
  File "/code/stages/odm_app.py", line 86, in execute
    self.first_stage.run()
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 361, in run
    self.next_stage.run(outputs)
  [Previous line repeated 4 more times]
  File "/code/opendm/types.py", line 342, in run
    self.process(self.args, outputs)
  File "/code/stages/mvstex.py", line 105, in process
    system.run('{bin} {nvm_file} {model} {out_dir} '
  File "/code/opendm/system.py", line 79, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 134
```

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I really don't know it's my first time with this error it always worked. I'm currently using 200 pictures with  1920x1080  as resolution.

**Comment by smathermather** [comment]
This looks like an out of memory error, not a bug. Can we take the conversation to community.opendronemap.org? 🙏 We'll get you sorted out there.
