### ISSUE TITLE
Multi-camera texturing aborts with non-default primary band

### ISSUE THREAD

**Issue by HecCas96** [OpenDroneMap/ODM#1218]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome 87 on Linux

### What is the problem?

In a multi-camera run, texturing labeling is shared for all bands. Problem is that the labeling file is generated from the primary band run and all the other bands depend on it. Texturing for each band in stages/mvstex.py should start with the primary band. Right now if the primary band is not the first one on the iteration ODM crashes because the expected .vec is not found.

**Comment by pierotofy** [comment]
Thanks @HecCas96 :+1: 

It should be fixed with #1219
