### ISSUE TITLE
Misaligned multispectral ortho when input photos are already aligned

### ISSUE THREAD

**Issue by HecCas96** [OpenDroneMap/ODM#1220]
To increase the accuracy of the reflectance maps on multispectral tasks, I’m preprocessing the captured photos before inputting them to ODM. This is because I want to take into account shots of a calibration target, so that I can anchor the info to some ground truth aside from the calibration from the DLS (the currently supported calibration in ODM). For this process I’m already unwarping and aligning each photo and each band.

The problem is that I have no way of letting ODM know this. And sometimes ODM, trying to align the secondary bands to the primary band, will force an inaccurate warp matrix on a band and the final orthophoto will end up misaligned. (Some other times I only get a warning that no alignment matrix was found and the orthophoto ends up perfectly aligned)

Would it be possible to increase the minimum of matches here? 
https://github.com/OpenDroneMap/ODM/blob/05f9e60496e5cb3daf80374cf56fc37ce0b2b231/opendm/multispectral.py#L344

There’s already an enforced 30 max_samples limit, maybe a min_samples of 10 would work . Got unaligned bands with only 1 and 6 good matches because an inaccurate warp matrix was forced on the bands.

Or, would it be possible to add a flag to skip the computation of the alignment matrices and the alignment to the primary band from the undistort pipeline? This would also speed things up for people on a similar situation, not sure if there are any though.

Here’s a link to the console out of a misaligned orthophoto:
https://drive.google.com/file/d/1_nefuUPzcDH6v2EnKPOGFUc5zpIzfbmo/view?usp=sharing

**Comment by pierotofy** [comment]
> would it be possible to add a flag to skip the computation of the alignment matrices and the alignment to the primary band from the undistort pipeline?

This might be the better way to do it.

We'd welcome a PR to add this!
