### ISSUE TITLE
Argument '-logFile' has a bad value.

### ISSUE THREAD

**Issue by gubinhua** [OpenDroneMap/ODM#1226]
docker run -it --rm -v /c/Users/odm_test/park:/code/images -v /c/Users/odm_test/odm_orthophoto:/code/odm_orthophoto opendronemap/opendronemap

error:
[INFO]    Running ODM Georeferencing Cell - Finished
[INFO]    Running ODM DEM Cell
[INFO]    Classify: False
[INFO]    Create DSM: False
[INFO]    Create DTM: False
[INFO]    DEM input file /code/odm_georeferencing/odm_georeferenced_model.laz found: True
[WARNING] DEM will not be generated
[INFO]    Running ODM DEM Cell - Finished
[INFO]    Running ODM Orthophoto Cell
[DEBUG]   running /code/build/bin/odm_orthophoto -inputFile /code/odm_texturing_25d/odm_textured_model_geo.obj -logFile /code/odm_orthophoto/odm_orthophoto_log.txt -outputFile /code/odm_orthophoto/odm_orthophoto.png -resolution 20.0  -outputCornerFile /code/odm_orthophoto/odm_orthophoto_corners.txt
Error in OdmOrthoPhoto:

Argument '-logFile' has a bad value.
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_orthophoto.py", line 94, in process
    '-outputCornerFile {corners}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1

I don't know how to fix it

**Comment by pierotofy** [comment]
This is probably an issue with mounting directories in docker. Try the following instead:

```
docker run -ti --rm -v /c/Users/odm_test:/datasets/code opendronemap/odm --project-path /datasets
```

If it still doesn't work, let's move the conversation to https://community.opendronemap.org :pray:
