### ISSUE TITLE
Specific photo split-merge Aligning submodels Segmentation fault

### ISSUE THREAD

**Issue by t-noguchi-sensyn** [OpenDroneMap/ODM#1232]
Not all, specfic photo data sets encountered to segmentation fault.Why?

 - ODM options.
    `{"dsm": "true", "dtm": "true", "orthophoto-png": "true", "min-num-features": 18000, "dem-resolution": 2.0, "orthophoto-resolution": 2.0, "split": 100, "split-overlap": 30, "verbose": "true"}`
 - split-overlap
    30 => NG
    40 => NG
    50 => NG
    150 => NG
 - EC2
    c5a.4xlarge = 32GB Memory => NG
    c5a.8xlarge = 64GB Memory => NG

```
[INFO]    LRE: Download of submodel_0002 at [71%]
[INFO]    LRE: Download of submodel_0002 at [83%]
[INFO]    LRE: Download of submodel_0002 at [100%]
[INFO]    LRE: Downloaded and extracted assets for submodel_0002
[INFO]    LRE: submodel_0002 finished successfully
[INFO]    LRE: Cleaning up remote task (b9cdc891-e4f2-4f46-9d9c-d8d5b7801cec)... OK
[INFO]    LRE: No remote tasks left to cleanup
[INFO]    Aligning submodels...
/var/opt/ODM/run.sh: line 5:  8833 Segmentation fault      (core dumped) python3 $RUNPATH/run.py "$@"
```

odm console log.
[console_log.txt](https://github.com/OpenDroneMap/ODM/files/5969963/console_log.txt)

Core file gdb stack trace is as fllows:
```
#14 0x00000000005f7146 in PyEval_EvalFrameEx (throwflag=0, f=
    Frame 0x36760b0, for file /var/opt/ODM/SuperBuild/src/opensfm/opensfm/large/tools.py, line 111, in add_camera_constraints_soft 
```
[gdb_core.txt](https://github.com/OpenDroneMap/ODM/files/5969953/gdb_core.txt)

**Comment by pierotofy** [comment]
Should be fixed with https://github.com/OpenDroneMap/OpenSfM/commit/6637d3e2f2821202a46a5c57b1fb6166512e502f

If the issue is still present, feel free to re-open. :pray:
