### ISSUE TITLE
Create and document a more native Linux build process

### ISSUE THREAD

**Issue by Artoria2e5** [OpenDroneMap/ODM#1247]
- **How did you install OpenDroneMap? (Docker, natively, ...)?**: Haven't yet. Thinking about getting it onto a Linux distro, *real* natively.
- **What's your browser and operating system?** Ain't there yet. Just hear me out.

### What is the problem?

ODM currently has a build process that's centered on Docker and Snap where dependencies are bundled in. This is in contrast to how regular package managers work (single copy of shared libraries) and actually slow down porting to different platforms due to the illusion of only needing to support one configuration.

### What should be the expected behavior?

Someone (probably just me) should figure out how to build ODM without:

* Snap
  * Wiki page should probably point to the YAML for actual deps.
* GCC hacks (it should be managed through CFLAGS)
  * Given how compute-heavy the project is, I won't be surprised that just doing a `-march=native` build might actually speed something up.
  * Here the nahelem hack is also messing with non-x86 attempts, like getting it to work on the M1.
* `ExternalProject_Add`
  * Naively the thing *should* work by skipping SuperBuild. But now that the Python code asks for SuperBuild by name... Not good.

And put it in the Wiki. (The EPA removal will take some code modification though.)

### How can we reproduce this?

I think the README is pretty clear on the fact that there is only one true OS version and architecture for ODM building already.

**Comment by Saijin-Naib** [comment]
I'm quite interested in what you accomplish with this.

It has been a long-term dream of mine to have the entire ODM ecosystem built upon and packaged into an Alpine Linux image, without docker as an abstraction layer. Quite a bit beyond my competency, though.

**Comment by pierotofy** [comment]
I'm going to close this since it's not a bug; feel free to open a PR in our docs repository https://github.com/OpenDroneMap/docs with native build instructions! :pray:
