### ISSUE TITLE
I noticed that there would be some ambiguity.

### ISSUE THREAD

**Issue by githubhanjunjun** [OpenDroneMap/ODM#1249]
I used nodeODM to generate orthophoto images.
I noticed that there would be some ambiguity.
May I ask what may cause this problem?
Below are my parameters and screenshots.
** parameters ** :
![image](https://user-images.githubusercontent.com/27795864/112597827-a1e71e80-8e48-11eb-8933-b6cb59c58a4f.png)

** screenshots **
![image](https://user-images.githubusercontent.com/27795864/112597566-3bfa9700-8e48-11eb-8964-54271d321c30.png)

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
