### ISSUE TITLE
Feature Request:  Optionally Support XMP Metadata when EXIF is missing

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/ODM#1254]
Discussion here:  
https://community.opendronemap.org/t/troubles-with-png/7157/10?u=saijin_naib

The user is converting from DNG to PNG using Adobe Bridge/Lightroom, which is stripping all EXIF when exporting to PNG, leaving all the metadata only in the XMP tags.

I think optionally supporting XMP tags as a fall-back when EXIF doesn't exist would be a great way to ensure we don't "miss" tagged images written out by other softwares or settings that may miss EXIF.

**Comment by pierotofy** [comment]
Problem with XMP is that it's even less standard than EXIF. But why not? We'd welcome a PR.

**Comment by Saijin-Naib** [comment]
> Problem with XMP is that it's even less standard than EXIF. But why not? We'd welcome a PR.

Lovely can of worms, that.

**Comment by pierotofy** [comment]
Closing, no bandwidth for this. (PR still welcome)
