### ISSUE TITLE
Feature Request: GitHub Action to make flatpak alongside SNAP and WSL2

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/ODM#1256]
I think it could be very helpful with the ease of installation for ODM to have a flatpak built alongside our SNAP and WSL2 images.

This would help greatly for platforms that lack snapd/systemd (such as Alpine, Void, etc) but which do support flatpak easily.

It would also help capture those who have an objection to using systemd/snaps for whatever reason.

Flatpak build documentation:  
https://docs.flatpak.org/en/latest/first-build.html

Flatpak Github Action template:  
https://github.com/marketplace/actions/flatpak-builder

I've not made any headway on this yet.

**Comment by pierotofy** [comment]
I'm going to close this for now; if we find a volunteer to create **and** maintain a flatpak package that's fantastic, but otherwise this is not going to get done.
