### ISSUE TITLE
Feature Request: KMZ output

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#1267]
GeoTIFFs are super useful, but KMZ output from ODM would be more widely shareable and portable for a lot of use cases, and gets the data in the hands of non-GIS folks.

**Comment by geospatialmapmashup** [comment]
If anything OGC GPKG GeoPackage NOT KMZ. Not knowing anyone that uses that or Google Earth anymore.
GPKG is the standard.

**Comment by smathermather** [comment]
I certainly prefer GPKG, but that's a separate feature request. :slightly_smiling_face: 

If you can use GPKG, you can use GeoTIFF. If what you have and are comfortable with is Google Earth, then that's the target.

**Comment by pierotofy** [comment]
Just a matter of running `gdal_translate odm_orthophoto/odm_orthophoto.tif odm_orthophoto/odm_orthophoto.kmz` and adding a `--orthophoto-kmz` flag. To be added in https://github.com/OpenDroneMap/ODM/blob/master/opendm/orthophoto.py#L58

A PR would be most welcome.

**Comment by smathermather** [comment]
https://github.com/OpenDroneMap/ODM/pull/1268

**Comment by smathermather** [comment]
Complete (at least when merged).

**Comment by smathermather** [comment]
> If anything OGC GPKG GeoPackage NOT KMZ. Not knowing anyone that uses that or Google Earth anymore.
> GPKG is the standard.

@geospatialmapmashup -- if you want to create a separate issue and pull request for GPKG, it should be a pretty quick patch.
