### ISSUE TITLE
Multithreaded odm_texturing?

### ISSUE THREAD

**Issue by FLYBYME** [OpenDroneMap/ODM#127]
Im finding the the `running texturing` step seems to only use one core on my 6 core cpu.

would it ever become multithreaded?

**Comment by smathermather** [comment]
Not a bad idea. AFAIK, no one has specific plans, but we accept pull requests :D.

Texturing is a fraction of the total processing time in the datasets I've run. Are you hitting a bottleneck with texturing?

**Comment by FLYBYME** [comment]
I would not know where to start with it. Im just learning it now.

This it would be a good idea.

**Comment by smathermather** [comment]
It's a great idea, @FLYBYME. I'll add it to the list of feature requests.

**Comment by smathermather** [comment]
I will close this for now. If someone feels an urge to chase this or update this issue, we can re-open.
