### ISSUE TITLE
2D pixel coordinates to 3D point cloud

### ISSUE THREAD

**Issue by Oringa** [OpenDroneMap/ODM#1277]
Hello.

I built a project using ODM and have OpenSfM data available. 

I managed to map a 3D point from the point cloud to all accurate 2D pixel values in all the raw images. However, I can't find the correct transformation for the reverse mapping, i.e. mapping a 2D pixel from the original images to a 3D point in the point cloud.

From my limited experience in Metashape, there is a direct approach for this mapping, however, I'm still unable to accomplish this even indirectly. 

I have tried the following: 

```python
nube = o3d.io.read_point_cloud('./opensfm/undistorted/openmvs/scene_dense_dense_filtered.ply')
data = dataset.DataSet('./opensfm')
rec = data.load_reconstruction()[0]
shot = rec.shots[image]
pose = shot.pose
cam = shot.camera
pt2D = cam.pixel_to_normalized_coordinates(pt2D_px)
bearing = cam.pixel_bearing(pt2D)
t3D_world = pose.inverse().transform(bearing)
```

I understand I need some form of scaling with the depth of the point, but there are no details in the documentation on how to do so.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
