### ISSUE TITLE
WebODM on a old Dell 2950

### ISSUE THREAD

**Issue by jeffersonpimenta** [OpenDroneMap/ODM#1280]
Hi everyone,

I buy this old server to run some photogrametry and got this message:

> Optimizing:
> Time[s]	Energy
> Illegal instruction (core dumped)
> ===== Dumping Info for Geeks (developers need this to fix bugs) =====
> Child returned 132
> ===== Done, human-readable information to follow... =====
> 
> [ERROR]   Oh no! It looks like your CPU is not supported (is it fairly old?). You can still use ODM, but you will need to build your own docker image. See https://github.com/OpenDroneMap/ODM#build-from-source
> Traceback (most recent call last):
> File "/code/stages/odm_app.py", line 83, in execute
> self.first_stage.run()
> File "/code/opendm/types.py", line 338, in run
> self.next_stage.run(outputs)
> File "/code/opendm/types.py", line 338, in run
> self.next_stage.run(outputs)
> File "/code/opendm/types.py", line 338, in run
> self.next_stage.run(outputs)
> [Previous line repeated 4 more times]
> File "/code/opendm/types.py", line 319, in run
> self.process(self.args, outputs)
> File "/code/stages/mvstex.py", line 108, in process
> system.run('{bin} {nvm_file} {model} {out_dir} '
> File "/code/opendm/system.py", line 82, in run
> raise SubprocessException("Child returned {}".format(retcode), retcode)
> opendm.system.SubprocessException: Child returned 132

![image](https://user-images.githubusercontent.com/11169349/117089430-ec06ce00-ad2b-11eb-9fc3-d0bb49a081d8.png)

Any guides or links to learn how to build my own image? The link provinded doesn't help much.

Thanks!

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
