### ISSUE TITLE
請問OenDroneMap有中文版介面嗎?

### ISSUE THREAD

**Issue by hb901011** [OpenDroneMap/ODM#1282]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!

First of all, thank you for taking the time to report an issue.

Before you continue, make sure you are in the right place. Please open an issue only to report faults and bugs. For questions and discussion please open a topic on http://community.opendronemap.org/c/opendronemap. 

Please use the format below to report bugs and faults. It will help improve the resolution process. 
****************************************

### How did you install OpenDroneMap? (Docker, natively, ...)?

[還沒下載安裝，想了解這個軟體]

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[WEB瀏覽器的設置：
現在您知道您使用的是哪種瀏覽器，下面是Web瀏覽器設置的列表。當您嘗試使用Internet解決問題時，此信息可能會有​​所幫助。

是否啟用了JavaScript？
是-已啟用JavaScript
如何啟用JavaScript
是否啟用Cookies？
是-已啟用Cookie

額外信息
您的瀏覽器告訴我們有關您的配置的一些其他信息...

64位版本
您的推薦人
我們無法分辨你來自哪裡。您是直接輸入whatismybrowser.com，還是來自未通過引薦來源網址的網站，或者您使用的是隱藏引薦來源網址的瀏覽器擴展程序。
找到更多：
我的推薦人是什麼？
WIFI詳細信息
什麼是我的WiFi？
發現您的接入點，WiFi頻道等。
IP地址
這是您的公共IP地址。

61.216.161.157
您的IP地址可以在線識別您。
使用VPN有助於保持私密性和安全性。
本地IP地址
網絡上計算機的本地IP地址。

檢測被您的網絡瀏覽器阻止
手動檢測您的本地IP
地點
您的IP地址可以顯示您的位置。

台灣台中地球
（大約）
互聯網服務提供商
這似乎是提供您的Internet連接的公司

數據通訊事業群
（我們最好的猜測）
上網速度
您的互聯網連接速度有多快？

測試您的網速
使用此工具測試您的互聯網連接速度
電腦屏幕
屏幕的分辨率和顏色深度。

1536 x 864像素
24位
瀏覽器窗口大小
包括您的工具欄。

1536 x 824 Pixels
調整瀏覽器大小以查看此更改
不追踪設定
要求網站不要追踪您。

請勿追踪已禁用或不受支持
檢測到的插件
您的瀏覽器報告它具有這些額外的附件。

使用TOR？
您正在使用洋蔥路由器網絡嗎？

不
您的流量似乎不是來自TOR出口節點]

### What is the problem?

[圖形化介面的軟體有中文版嗎?買USB版是不是不能用雲計算機?買USB版是插入電腦就可以用嗎?買USB版可以在多台電腦使用嗎?]

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

[Type answer here]

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

[Type answer here]

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
