### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by MrByte98** [OpenDroneMap/ODM#1288]
The program could not process this datasets using the current settings, Check  that the images have enough overlap, that there are enough recognizable features and that the images are in focus. You should try to increase the --min-num-features parameter.The program will now exit

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
