### ISSUE TITLE
Update OpenSfM to latest

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1293]
There's quite a bit of improvements / bug fixes in the latest OpenSfM repo.

This requires some work because there are also breaking changes.

**Comment by YanNoun** [comment]
@pierotofy among big changes, we have rig support and this doesn't break the file format.

**Comment by pierotofy** [comment]
Thanks @YanNoun :+1: I did follow the rig support work, so quite excited to check that out!

**Comment by smathermather** [comment]
Rig support as in synthetic data?
