### ISSUE TITLE
GDAL / Error - Can’t load requested DLL

### ISSUE THREAD

**Issue by unicorneu** [OpenDroneMap/ODM#1298]
ODM Version: Native Windows Install 1.9.1 Build 18/19

Browser: Firefox

### What is the problem?

Receiving error stating that gdal related dll can't be found. See attached pdf. The directory and files shown in the log does exist. I have GDAL installed and use it with QGIS, which may be triggering the error. As long as I skip the 3d model the task will finish successfully, despite showing the error. If I don't skip the 3D model, however, the task fails.

[webODM_console_GDAL.pdf](https://github.com/OpenDroneMap/ODM/files/6627470/webODM_console_GDAL.pdf)

**Comment by Saijin-Naib** [comment]
I believe this was resolved by the user removing their system-wide install of GDAL (which unsets the environment variables that were causing trouble):  
https://community.opendronemap.org/t/gdal-error-cant-load-requested-dll/7871/14?u=saijin_naib

**Comment by pierotofy** [comment]
This should be fixed with the latest update. Feel free to re-open if the issue persists. :pray:
