### ISSUE TITLE
Worse results compared to 2.4.1 release

### ISSUE THREAD

**Issue by IvanHahan** [OpenDroneMap/ODM#1300]
The generated model using the latest release is much more distorted and less quality than on 2.4.1 (The same set of images used). 
The parameters are kept default across both experiments. They appear to be the same.

Below attached images of the result 3d models for the latest and 2.4.1 version.

![image](https://user-images.githubusercontent.com/17514015/121535180-96989d80-ca0a-11eb-9841-1dc4cf6e5eb0.png)
![image](https://user-images.githubusercontent.com/17514015/121535236-a7491380-ca0a-11eb-844c-ed99339887be.png)

**Comment by pierotofy** [comment]
You probably need to tweak the settings (increase `--pc-quality` at a first glance). Sometimes we change the default values for certain settings to meet various tradeoffs of speed vs. quality.

Doesn't look like a bug. If you still have questions, could we move this conversation over to the forum at https://community.opendronemap.org? :pray: Thank you! :+1:
