### ISSUE TITLE
Feature Request: Option to apply Image Masks After Matching

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/ODM#1303]
https://community.opendronemap.org/t/masks-how-and-where-are-they-used-in-processing/7965/5?u=saijin_naib

The user brought up a really interesting point in that the current workflow/pipeline applies the mask prior to feature matching (which in some cases _could_ be desired), but in their case is making reconstruction more difficult.

I'm not sure if a change in default behavior is warranted (default to applying masks only after matching, option to apply masks from start), or if exposing another option is better.

I think this workflow tweak has a lot of merit.

**Comment by pierotofy** [comment]
This is actually the default behavior as of the latest version, so this can be closed!
