### ISSUE TITLE
Numpy installation fails to pass sanity check

### ISSUE THREAD

**Issue by HighTechHillbilly** [OpenDroneMap/ODM#1305]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!

First of all, thank you for taking the time to report an issue.

Before you continue, make sure you are in the right place. Please open an issue only to report faults and bugs. For questions and discussion please open a topic on http://community.opendronemap.org/c/opendronemap. 

Please use the format below to report bugs and faults. It will help improve the resolution process. 
****************************************

### How did you install OpenDroneMap? (Docker, natively, ...)?

Native Windows Installer

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Yandex browser on Windows 10 Pro

### What is the problem?

We loaded photos into a new job.
Then an error "Cannot process dataset" is generated, when we attempt to run the processing task.
This should begin processing the images, but it just fails. The log output is here:

Traceback (most recent call last):
File "D:\WebODM\resources\app\apps\ODM\\run.py", line 14, in <module>
from opendm.utils import double_quote
File "D:\WebODM\resources\app\apps\ODM\opendm\utils.py", line 2, in <module>
from opendm.photo import find_largest_photo_dim
File "D:\WebODM\resources\app\apps\ODM\opendm\photo.py", line 6, in <module>
import numpy as np
File "D:\WebODM\resources\app\apps\ODM\venv\lib\site-packages\numpy\__init__.py", line 305, in <module>
_win_os_check()
File "D:\WebODM\resources\app\apps\ODM\venv\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('D:\\WebODM\\resources\\app\\apps\\ODM\\venv\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

[console.txt](https://github.com/OpenDroneMap/ODM/files/6658764/console.txt)

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

[Type answer here]

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

[Type answer here]

**Comment by pierotofy** [comment]
Install https://support.microsoft.com/en-us/topic/february-2-2021-kb4598291-os-builds-19041-789-and-19042-789-preview-6a766199-a4f1-616e-1f5c-58bdc3ca5e3b (per the error message recommendation). It's not a bug in ODM, it's a bug in Windows. :+1:
