### ISSUE TITLE
Linux offline installer

### ISSUE THREAD

**Issue by arturonegocios** [OpenDroneMap/ODM#1311]
Hello I have a problem. I have to install OpenDroneMap on a linux computer without internet access due to the remoteness of the place. Is there an installer that I can use to install it without internet like an appimage?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by arturonegocios** [comment]
oops,  sorry and thank you.
