### ISSUE TITLE
Possible Bug in native code (memory allocation)?

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/ODM#1319]
### How did you install OpenDroneMap? (Docker, natively, ...)?
Native

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
NA

### What is the problem?
Aligning submodels on Windows Native keeps failing with exit code 3221225477. Quick search seems to lead to memory allocation issue.
https://github.com/electron/electron/issues/3570#issuecomment-159330269

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.
Aligning submodels on Windows Native should perform reliably, like with docker/linux.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
Options: cog: true, debug: true, dem-resolution: 1, dsm: true, dtm: true, orthophoto-cutline: true, orthophoto-kmz: true, orthophoto-png: true, orthophoto-resolution: 1, pc-geometric: true, pc-las: true, pc-tile: true, rerun-from: dataset, split: 30, split-overlap: 100, use-3dmesh: true, verbose: true

Dataset/Parameters/Original Report:  
https://community.opendronemap.org/t/aligning-submodels-odm-native-windows/8454?u=saijin_naib

**Comment by Saijin-Naib** [comment]
On the docker/linux side, but seemingly the same behavior (and a segfault on memory access, as well):  
https://community.opendronemap.org/t/segfault-on-aligning-submodels-stage/8414?u=saijin_naib

https://community.opendronemap.org/t/processing-dataset-crashes-at-aligning-submodels-stage/8315?u=saijin_naib

**Comment by pierotofy** [comment]
This should be fixed with https://github.com/OpenDroneMap/OpenSfM/commit/6637d3e2f2821202a46a5c57b1fb6166512e502f

Thanks!
