### ISSUE TITLE
docker/odm return error message: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by DonkeyLiao** [OpenDroneMap/ODM#1324]
I have tested four group images,some group merge success,and some group returned this error msg：zero-size array to reduction operation maximum which has no identity.  Is there a problem with my source images? What can I do to fix it?

**Comment by pierotofy** [comment]
Try to update to the latest version; this is a bug that should have been fixed with https://github.com/OpenDroneMap/OpenSfM/commit/54a419b446a1fd9f48907cb70b2767cbf4f1ff38

**Comment by pierotofy** [comment]
Closing, assuming this is fixed. :pray:
