### ISSUE TITLE
Issue in Autoscaling cluster odm

### ISSUE THREAD

**Issue by Anmol0503** [OpenDroneMap/ODM#1335]
Was trying to setup the cluster odm with aws autoscale and was facing issue during processing. 
LRE: submodel_0001 (b21784d2-b99a-4189-a6f3-9daa66f5fc89) is still running
[INFO]    LRE: Downloading assets for submodel_0001
[WARNING] LRE: submodel_0001 failed with: Unexpected status code: 301
[INFO]    LRE: Cleaning up remote task (b21784d2-b99a-4189-a6f3-9daa66f5fc89)... OK
[INFO]    LRE: Re-queueing submodel_0001 (retries: 1)

I am running it using odm docker image with --sm-cluster parameter. The results are being saved in the s3 bucket but it is not getting downloaded in the machine where the processing is being done

There is not verbose for the error so haven't been able to understand the issue

@pierotofy @smathermather Can you help pointing me in the direction of what might be causing the issue

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
