### ISSUE TITLE
Strange output

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/ODM#1340]
### How did you install OpenDroneMap? (Docker, natively, ...)?

WebODM windows and nodeODM in docker in ubuntu

### What's your browser and operating system? 

Chrome windows/Linux

### What is the problem?

I have an GCP list in EPSG:5850, opening the tiff in QGis and the info say WGS84 UTM but the coordinates look like EPSG:5850. 

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Would be best if the output was in the same system as the input.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

just process something with EPSG:5850

**Comment by APOS80** [comment]
Projections are flat so if ODM gets GCP’s in a flat system it could just treat it like a local system that’s flat and put the EPSG tag from the EPSG list on the output.

**Comment by pierotofy** [comment]
The output should of ODM always be in the nearest UTM CRS (even if your GCP uses a different projection/CRS).

If you think the output is incorrect, please provide at a minimum a dataset (with the GCP), screenshots and an explanation of which parts of the output you think are incorrect (show measurements and how you calculated them with expected vs actual)?  :pray: 

I can re-open this once we get more information and can confirm that this is a bug.
