### ISSUE TITLE
How to make a orthomasic project to any direction?

### ISSUE THREAD

**Issue by JimXu1989** [OpenDroneMap/ODM#1343]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!

First of all, thank you for taking the time to report an issue.

Before you continue, make sure you are in the right place. Please open an issue only to report faults and bugs. For questions and discussion please open a topic on http://community.opendronemap.org/c/opendronemap. 

Please use the format below to report bugs and faults. It will help improve the resolution process. 
****************************************

### How did you install OpenDroneMap? (Docker, natively, ...)?

[Docker]

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[Chrome]

### What is the problem?

[
Thanks a lot for the great work and generous sharing!!
The Orthomasic is projected to the ground by default, the pics is assumed taken by a drone to make a map. 
While, if I want to make a orthomasic project to , for example, a wall, make a "map" of a verticcal object, what should I do?
]

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

[Is it possiable to make a orthomasic project to any direction?]

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
