### ISSUE TITLE
Is the mesh watertight? What is the method make mesh water tight?

### ISSUE THREAD

**Issue by JimXu1989** [OpenDroneMap/ODM#1344]
### How did you install OpenDroneMap? (Docker, natively, ...)?

[Docker]

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[Chrome]

### What is the problem?

[
Thanks for the Great work and generous sharing!!
The mesh provided by ODM seems to be watertight! That is awesome!!
Open3d even don't have this function.
May you share the method how to make the mesh water-tight with us?
Thanks a lot!!
]

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

[Could you provide how to make a mesh to water-tight mesh?]

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
