### ISSUE TITLE
How to build natively with GPU?

### ISSUE THREAD

**Issue by JimXu1989** [OpenDroneMap/ODM#1345]
### How did you install OpenDroneMap? (Docker, natively, ...)?

[natively]

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[chrome]

### What is the problem?

[How to build natively with GPU?]

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

[Thanks a lot for the shareing
Please show me the method to build ODM accelerate by Nvidia cuda supported GPU,
Thanks a lot!]

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

[I work with the ODM I natively installed, it seems no gpu usage increase when the ODM working.]

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
