### ISSUE TITLE
Feature request: Add support of Popsift or AliceVision for pipeline steps

### ISSUE THREAD

**Issue by holyCowMp3** [OpenDroneMap/ODM#1357]
During research - I noticed a lot of new SFM, MVS, algorithms that have GPU support. Can we provide an opportunity to create something like ODM-GPU with already created functionality, but also with support for new technologies?

**Comment by pierotofy** [comment]
We could! Other projects already do that (see https://github.com/OpenDroneMap/NodeMICMAC and https://github.com/uav4geo/NodeCM). Perhaps you could create a NodeAliceVision or NodeAV!

**Comment by pierotofy** [comment]
Closing since this is an idea for a separate subproject (not really specific to ODM).
