### ISSUE TITLE
[WARNING] Initial residual too low: 4.18429e-08 < 0.000001

### ISSUE THREAD

**Issue by jewelthief** [OpenDroneMap/ODM#136]
I am running latest bits of OpenDroneMap and using odm_data_caliterra as my input.

<b> - running meshing - Sun Jul 26 23:29:08 UTC 2015

<b>[WARNING] Initial residual too low: 4.18429e-08 < 0.000001

<b> running texturing - Sun Jul 26 23:30:50 UTC 2015

<b> libdc1394 error: Failed to initialize libdc1394

**Comment by smathermather** [comment]
Caliber can be a problematic dataset. This is a known dataset issue. Next week I'm going to work to prune the dataset tree down to known working datasets.
