### ISSUE TITLE
Exclusion boundaries

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1363]
Allow boundaries to define areas which should not be included (e.g. outline of a building) instead of defining the boundaries which should be included.

**Comment by Saijin-Naib** [comment]
How would that be managed if one wants to have both an inclusion and exclusion boundary?

A field in the GeoJSON or other input file with a true/false (0/1) value for exclude/include?

**Comment by pierotofy** [comment]
Not enough bandwidth, not enough requests. I'll close this for now.
