### ISSUE TITLE
Possible Bug: --matcher-type does not seem to override opensfm config.py

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/ODM#1368]
### How did you install OpenDroneMap? (Docker, natively, ...)?
Native

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
NA

### What is the problem?
Currently, the config.py for OpenSFM has a number of parameters set that are over-ridden by some parameters passed to ODM/WebODM. In the case of:  
```
# Params for general matching
lowes_ratio: 0.8              # Ratio test for matches
matcher_type: FLANN           # FLANN, BRUTEFORCE, SIFT_GPU or WORDS
symmetric_matching: yes       # Match symmetricly or one-way
```
```matcher_type``` does not seem to be reliably over-ridden by the ODM option ```--matcher-type```

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.
I would expect that any value passed to ```--matcher-type``` for ODM would successfully over-ride the ```matcher_type``` present in the OpenSFM config.py.

This is critical for proper operation of the ORB feature type, for instance (using BRUTEFORCE instead of FLANN).

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
Pass ```--matcher-type bruteforce``` to a job with the default OpenSFM config.py value of FLANN in place, and watch it use FLANN for matching.
![image](https://user-images.githubusercontent.com/19295950/141009977-28473cc3-acbc-4105-aef7-77a7d1f8fae9.png)

**Comment by pierotofy** [comment]
Not a bug, it's just the way the logic is written: https://github.com/OpenDroneMap/ODM/blob/master/opendm/osfm.py#L217

If you want to try a different matcher, you'll need to edit osfm.py.

**Comment by Saijin-Naib** [comment]
Would you accept a PR to force BRUTEFORCE for ORB/AKAZE for now?

**Comment by pierotofy** [comment]
I'm a bit hesitant to include brute force as an option (due to its speed). There are no faster matchers?

**Comment by pierotofy** [comment]
I'll add the necessary logic as part of #1362 :+1:

**Comment by Saijin-Naib** [comment]
There are better matchers, but upstream OpenSFM doesn't expose them yet. Opencv has them, though.

I think as a first step this gets it mostly working.

We need Hamming Distance matchers for ORB/AKAZE (all binary descriptors in general), and I think I read we can (ab)use FLANN/kdtree with a special formula.

Thank you for hooking up the logic for this!
