### ISSUE TITLE
Possible Bug: Not falling back to CPU-only without NVIDIA GPU

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/ODM#1373]
### How did you install OpenDroneMap? (Docker, natively, ...)?
WebODM for Windows native 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
WebODM: Windows installer, version 1.9.11 build 43,
OS: Windows 10, v 21H1, build 19043.1348
CPU: AMD Ryzen 7 3700x
GPU: AMD RX 580
RAM: 32GB

### What is the problem?
```
I’m pretty sure it has to do with the fact that I’m using an AMD GPU. I get a system error - DensifyPointCloud.exe (nvcuda.dll was not found).
I was able to finish the job on a Windows PC with a Nvidia GPU.
```
### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.
On systems without a proper CUDA accelerator, we should fallback to CPU-only, or possibly use a CUDA wrapper/translator like hughperkins/coriander so the pipeline is still accelerated.
https://github.com/hughperkins/coriander

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
https://community.opendronemap.org/t/webodm-amd-gpu-program-exited-with-strange-error-code/9622?u=saijin_naib

**Comment by pierotofy** [comment]
WebODM native build coming up in a few minutes with the fix as well.
