### ISSUE TITLE
Is it possible to build an orthophoto dinamically?

### ISSUE THREAD

**Issue by migvel** [OpenDroneMap/ODM#1377]
Hello,

I'm pretty new to this project, since I didn't find information related to my need I ask it here: 
Is it possible to process an Orthorectified image dinamically/incrementally as new images are being captured? adding new single images to the previously  Orthorectified result in an incremental way? 

Regards.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by migvel** [comment]
OK thank you.
