### ISSUE TITLE
orthophoto.png is producing fragmented output

### ISSUE THREAD

**Issue by jewelthief** [OpenDroneMap/ODM#138]
I have latest bits running on VM with sufficient cpu and memory however in my 2-3 trial run of the program on the sample odm_data shared on this repo, none of them have created orthophoto.png. What could be the potential problem and what log files to look into for the same?

**Comment by jewelthief** [comment]
By re-installing OpenDroneMap and re-running the job this time around I was able to generate orthophoto.png, however I had to run "run it with argument --odm_georeferencing-useGcp false --start-with odm_georeferencing" .

Other things I am noticing here is that images output I got from running this process on odm_data_caliterra is different than what Nathan Baldwin is getting on his youtube videos. My output is particularly much more grainy and edgy with surface areas not getting smoothened out (very obvious in the areas marked out). Trying to find what i might have been doing wrong here?

See images attached,

![odm_orthphoto](https://cloud.githubusercontent.com/assets/523770/8950466/d3bea2ce-3576-11e5-937c-b7bac939aa6b.png)

<img width="578" alt="screen shot 2015-07-28 at 10 09 54 pm" src="https://cloud.githubusercontent.com/assets/523770/8950472/df82176c-3576-11e5-9009-22cab1700a66.png">

**Comment by dakotabenjamin** [comment]
I'm wondering if this has to do with texturing changes that came from  #122 and #113. Also, ODM does not do very well in general with vegetation, so you're almost always going to find gaps in those spots.

**Comment by jewelthief** [comment]
Well issue seems to be effecting not just vegetation part but also those structures, which are rendered half broken in my output vs Dennis's output.

**Comment by wolkstein** [comment]
hi,
i have the same issue since this commit. https://github.com/OpenDroneMap/OpenDroneMap/commit/5b85628e6b71a3e4742d0ab49912ee12622dc7f6 . the texture is completely fragmented.

/g
wolke

**Comment by dakotabenjamin** [comment]
Have you tried comparing to the the texture results from before that commit? @geraldmwangi have you noticed any differences being shown here?

**Comment by wolkstein** [comment]
i compare a the output from rev:
https://github.com/OpenDroneMap/OpenDroneMap/tree/636f843fd4b314014dc6248007539c85a57515c6
"left site" of the image against rev: 
https://github.com/OpenDroneMap/OpenDroneMap/tree/ebf5e267407c49ab0aa0898f44f28225a872ee72 (currently head)
"right site" of the image.
![compare](https://cloud.githubusercontent.com/assets/1617000/9090504/d65cfa60-3b9a-11e5-97eb-2d6dc4f80058.jpg)

the right side (head  rev snapshot) looking more crisp but you also noticed a lot of artefacts.
the  left side ( older revision just two commits before this change set 5b85628 ) looks less sharpen but also less artefacts.

zoomed to  gcp 3:
![compare-gcp](https://cloud.githubusercontent.com/assets/1617000/9090880/360e5d80-3b9d-11e5-8dc1-fbb59f4a5115.jpeg)

same here. the left side is generated with the old revision and at the right site from current head revision.

the photos was made with lumix gh4 14mm focal length 16:9. the copter altitude was ~65m over ground.

as you can see, on new texturing something goes wrong. every detail is distorted.

**Comment by dakotabenjamin** [comment]
I renamed to issue to something more appropriate to the problem we are facing. 

I've been going over the code changes trying to understand exactly how the algorithm works. The newer code adds two camera selection criteria (as in #113): distance from face and angle between face normal and viewplane normal. What seems to be happening now is that neighbouring triangles are more likely to be textured by a different camera. This may be the cause of the greater distortion and number of artefacts. 

How do we fix this? I'm not an expert in this field, but I have some ideas:
1. Add the old code back in and add an option to use the new code
2. Add a new criteria that examines neighbors and prioritizes the cameras they use.
3. Texture blending

**Comment by smathermather** [comment]
Agree with @dakotabenjamin, this may be a premature change without blending / histogram matching, etc..

One option: we could revert for now, as we should see some major texturing changes come down the pike in the next couple of weeks. Alternatively, if @geraldmwangi has some ideas of how to improve on this contribution, that'd be great.

**Comment by geraldmwangi** [comment]
Hi I'm sorry I didn't see this thread. I don't have much time now since I'm writting my phd thesis. In a few months I'll get back to this issue. But I have one idea: In line 597 in OdmTexturing::triangleToImageAssignment():
For each face Iook for the camera with the lowest angle& distance to the face. One could instead look at groups of connected faces, say 4 adjacent faces, and assign the camera with the lowest mean angle and mean distance to all 4 faces.

**Comment by dakotabenjamin** [comment]
@geraldmwangi look at the new changes from the branch `mvstex` if you are still interested in improving the texturing portion.
