### ISSUE TITLE
Is it a clerical error

### ISSUE THREAD

**Issue by githubhanjunjun** [OpenDroneMap/ODM#1386]
It's line 37 of file ‘ODM/SuperBuild/CMakeList.txt ’
**Code:**
`37: mark_as_advanced(SB_SOURCE_DIR)`
**Problem:**
I think 'SB_SOURCE_DIR' should be 'SB_INSTALL_DIR'

**Comment by pierotofy** [comment]
Maybe! Is it causing problems?

**Comment by githubhanjunjun** [comment]
> Maybe! Is it causing problems?

It has no problem. It should be a writing problem

**Comment by pierotofy** [comment]
If it's not causing a problem I think we can safely close this. If you'd like to fix any typos, feel free to open a pull request directly? Thank you. 🙏
