### ISSUE TITLE
Possible Bug: "copy" is not defined.

### ISSUE THREAD

**Issue by githubhanjunjun** [OpenDroneMap/ODM#1389]
### What is the problem?
Line 303 in opendm/osfm.py file. Error message: "copy" is not defined. There are currently no errors, but certain conditions may trigger this error.

> 273: def photos_to_metadata(self, photos, rerun=False):`
           ...
           303: camera_models[key] = copy.copy(overrides["all"])
           ...

**Comment by pierotofy** [comment]
Fixed with https://github.com/OpenDroneMap/ODM/commit/646b2e4f7033c1cf1d7c26bd05c099302c32950f thanks for the report! :pray:
