### ISSUE TITLE
Better handle error code 3221226505

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1395]
https://community.opendronemap.org/t/error-durring-submodel-processing-precisely-in-fused-depthmap-step-child-returned-3221226505/9947/13

It might be an out of memory indicator on Windows?

**Comment by Saijin-Naib** [comment]
I keep seeing that this error correlates to 0xC0000409, so STATUS_STACK_BUFFER_OVERRUN.

What could be causing that?

**Comment by pierotofy** [comment]
I'm thinking it might be a `137` equivalent, so an out of memory error, but I can't tell for sure.
