### ISSUE TITLE
Possible Bug: "sys" is not defined in opendm/concurrency.py

### ISSUE THREAD

**Issue by githubhanjunjun** [OpenDroneMap/ODM#1397]
What is the problem?
Line 84 in opendm/concurrency.py file. **"sys" is not defined**
`sys.exit(1)`

**Comment by pierotofy** [comment]
Fixed as part of https://github.com/OpenDroneMap/ODM/commit/d7b986a1b146b362784db1c91f0cadc7d0010dca :pray: Thanks!
