### ISSUE TITLE
当存放图片的文件夹是中文时，程序会报错opensfm\features中的部分*.npz文件

### ISSUE THREAD

**Issue by LeeChongGe** [OpenDroneMap/ODM#1400]
### 我的服务器是window server 2019，当存放图片的文件夹是中文时，odm会因opensfm\features中的部分*.npz文件没有生成报错，重启服务器后选着非中文路径可以正常运行，请问这是什么原因？

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
