### ISSUE TITLE
ODM processing from docker container run with -u parameter

### ISSUE THREAD

**Issue by mskrzypkows** [OpenDroneMap/ODM#1413]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 96, Manjaro Linux

### What is the problem?

I cannot finish full procession of orthophoto when I run docker container with docker's user different from root (`-u 1000:1000`).
```
docker run -u 1000:1000 -ti --rm -v "${PWD}":/datasets opendronemap/odm:latest --project-path /datasets project_small
```
The problem is described in more detail in the thread:
https://community.opendronemap.org/t/odm-docker-processing-fails-while-runing-the-same-from-webodm-works/10295/5

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

The ODM processing should succeed, output files should be generated in `/datasets` directory with ownership as a user of ID 1000 and group 1000.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Run processing of any dataset in docker container using `-u` option as shown above.

**Comment by HeDo88TH** [comment]
I'm working on this :+1:
