### ISSUE TITLE
Add --no-gpu config

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1424]
Currently we need to set `ODM_NO_GPU` as an environment variable to disable GPU features.

It might be easier to have a command line option instead?

**Comment by ichsan2895** [comment]
Excuse me, New variable to disable using GPU become priority?

From what I found in ODM community, most person really want GPU installation is easier/less confusing in Docker Linux WSL in Windows.

I personally use docker and Linux, if I dont want use GPU, it just remove `--gpu` flag when run `./webodm.sh start --gpu`

Thank you, hope it useful

**Comment by Saijin-Naib** [comment]
I think this can be closed safely as you added the flag a bit ago.
