### ISSUE TITLE
Handle GPU crashes with unsupported drivers while performing feature extraction

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1425]
Certain GPU cards crash the program at the feature extraction step. We should gracefully fallback to CPU in those cases.

**Comment by pdrlsoftwareteam** [comment]
got the same issue, No install step for 'opensfm'

**Comment by vdharankar** [comment]
Similar issue my end as well.

**Comment by Saijin-Naib** [comment]
> Similar issue my end as well.

Seems to be any NVIDIA card older than the GTX 9xx series, unfortunately, despite many supporting CUDA v11.4 which we are using.
