### ISSUE TITLE
Unable to Generate DepthMaps with Resolution Level 0 with GPU Docker

### ISSUE THREAD

**Issue by vivekmistry** [OpenDroneMap/ODM#1430]
In ODM, under OpenMVS stage, we tried to generate DepthMaps with Resolution Level 0 on CPU Machines. It works well but takes too much time to generate depth maps.
As an alternate solution tried to generate DepthMaps on the GPU machine but stop abruptly w/o any error. Please suggest, why there is different behavior for CPU and GPU machines?

**Comment by pierotofy** [comment]
Conversation already started here: https://community.opendronemap.org/t/unable-to-generate-depths-for-resolution-level-0-with-gpu-docker/10865/3
