### ISSUE TITLE
Failed to build/install nativly on ubuntu 20.04

### ISSUE THREAD

**Issue by assafge** [OpenDroneMap/ODM#1443]
I've download the code and activated a dedicated python environment (3.8)
```
$ bash configure.sh install
<lots of printouts>
[ 88%] Performing install step for 'poissonrecon'
[ 89%] Completed 'poissonrecon'
[ 89%] Built target poissonrecon
make: *** [Makefile:84: all] Error 2
```

I've added `set(CMAKE_VERBOSE_MAKEFILE ON)` to `CMakeLists.txt`, but no helpful information is provided.
GNU Make 4.2.1
gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0

**Comment by pierotofy** [comment]
The REAMDE is out of date (help us update it?) our target OS is currently Ubuntu 21.04, so it might not work out-of-the-box with 20.04 anymore.
