### ISSUE TITLE
Problem with reading RTK hight

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/ODM#1456]
### How did you install OpenDroneMap? (Docker, natively, ...)?

WebODM for windows 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome

### What is the problem?

WebODM somehow thinks the images has a negative altitude when it fact it’s positive 96 meters according to image exif.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

I expect it to just read the correct latitude

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Use a DJI Phantom 4 RTK, take images and try to process.

**Comment by pierotofy** [comment]
Please share a link to the input images :pray: ?
