### ISSUE TITLE
Wrong UTM on output

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/ODM#1458]
### How did you install OpenDroneMap? (Docker, natively, ...)?

WebODM on Windows

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome

### What is the problem?

In sweden its supposed to be WGS84 UTM 34N and i got that output in earlier versions.
Now i get the result in UTM 33N which is in Norway 

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

WGS84 UTM 34N

**Comment by pierotofy** [comment]
> If possible please include a copy of your dataset uploaded on Google Drive or Dropbox

Otherwise we cannot reproduce this?

Please, always include a sample dataset when opening bug reports :pray:
