### ISSUE TITLE
ODM Tracks.csv is throuwing gibberish output

### ISSUE THREAD

**Issue by JyothiKalyan** [OpenDroneMap/ODM#1462]
i tried changing encoding of the csv file, but still no luck.

![WhatsApp Image 2022-05-19 at 12 48 50 PM](https://user-images.githubusercontent.com/96404574/169234840-2dbd2eff-dbac-41f8-b488-54b8548881db.jpeg)

**Comment by pierotofy** [comment]
Not a bug; the tracks.csv file is no longer a "csv" file. https://github.com/OpenDroneMap/ODM/pull/1455

**Comment by JyothiKalyan** [comment]
How can i  make sense of this content? please help

**Comment by gentleman-zhong** [comment]
> How can i make sense of this content? please help

@JyothiKalya Hi,I also encountered the same problem. May I ask how you finally solved it and whether you have a corresponding script? Thank you very much.
