### ISSUE TITLE
Add blending and/or histogram matching to texturing of mesh

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#15]
Current texturing approach does no blending or balancing of adjacent images to smooth the output mesh and orthophoto:

![seneca_screen](https://cloud.githubusercontent.com/assets/1174901/5545909/4a88c5fa-8b00-11e4-89e4-ca53bed883bb.jpg)

![odm_orthphoto](https://cloud.githubusercontent.com/assets/1174901/5545910/4c0250c2-8b00-11e4-89d7-074ef9ce564f.png)

It would be better if some histogram matching and blending were added, ideally with automatic extraction of seams to minimize the blurring affect of blending by using natural scene seams as breaks between adjacent photo meshing.

**Comment by smathermather** [comment]
See also #81.

**Comment by xialang2012** [comment]
How is the progress? It seems the MVS-texturing branch can blend the textured image well.
