### ISSUE TITLE
Fail to match the hybrid GPU and CPU features

### ISSUE THREAD

**Issue by CosmosHua** [OpenDroneMap/ODM#1503]
### How did you install ODM? (Docker, installer, natively, ...)?

Docker in Ubuntu.

### What is the problem?

I employ the GPU version (--gpus all opendronemap/odm:gpu) to extract the SIFT features of dataset1, and employ the CPU version (opendronemap/odm) to extract the SIFT features of dataset2.
Then, I merge the images and these two types (gpu version and cpu version) of features from the two datasets.
It fails to match the hybrid GPU and CPU features when I try to execute the ODM docker (opendronemap/odm) or execute the matching.match() function of Opensfm.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

The mixed features should be matched as the same as the unmixed features.

### How can we reproduce this? What steps did you do to trigger the problem? If this is an issue with processing a dataset, YOU MUST include a copy of your dataset uploaded on Google Drive or Dropbox (otherwise we cannot reproduce this).

You can reproduce this following the steps described above.

**Comment by pierotofy** [comment]
I would expect the two not to work, as they are different implementations. We'd welcome a PR that improves this.

**Comment by pierotofy** [comment]
Closing, feel free to open a PR with a compatible version of SIFT.
