### ISSUE TITLE
Missing option for KMZ

### ISSUE THREAD

**Issue by serbinsh** [OpenDroneMap/ODM#1504]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!

First of all, thank you for taking the time to report an issue.

Before you continue, make sure you are in the right place. Please open an issue only to report faults and bugs. For questions and discussion please open a topic on http://community.opendronemap.org/c/opendronemap. 

Please use the format below to report bugs and faults. 
****************************************

### How did you install ODM? (Docker, installer, natively, ...)?

Docker

### What is the problem?

This may be a dumb question, if so my apologies.  I am running a new version of ODM/WebODM on Docker and cant find the KMZ option ([orthophoto-kmz](https://docs.opendronemap.org/arguments/orthophoto-kmz/#orthophoto-kmz)). Has this feature been removed? Or do I need to run the stack with a specific option?

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Option to output a KMZ super overlay

### How can we reproduce this? What steps did you do to trigger the problem? If this is an issue with processing a dataset, YOU MUST include a copy of your dataset uploaded on Google Drive or Dropbox (otherwise we cannot reproduce this).

Launch WebODM 1.9.15 and view task edit options

**Comment by serbinsh** [comment]
Also this may need to be posted on the "WebODM" git instead of ODM, as I suspect if I ran from cmd it would work as a option flag...

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
