### ISSUE TITLE
No GPU with docker

### ISSUE THREAD

**Issue by Camilochiang** [OpenDroneMap/ODM#1522]
When trying gpu usage (ubuntu 18.04)

```bash
sudo docker run -ti --rm  \
 -v /media/ubuntu/Elements/20220221_Berries/Melissa/Data:/Data	 \
 --gpus all opendronemap/odm:gpu --project-path /Data 20220727 \
 --dsm \
 --dtm \
 --orthophoto-resolution 2 
```

### What is the problem?
```bash
Unable to find image 'opendronemap/odm:gpu' locally
gpu: Pulling from opendronemap/odm
```

**Comment by pierotofy** [comment]
`gpu: Pulling from opendronemap/odm` --> this is just pulling the image from docker (everything looks normal, not a bug).

If you have questions about using docker, let's move this conversation over to the forum at https://community.opendronemap.org? :pray:
