### ISSUE TITLE
Failure to merge multispectral dataset

### ISSUE THREAD

**Issue by duckblaster** [OpenDroneMap/ODM#1532]
### How did you install ODM? (Docker, installer, natively, ...)?

docker

### What is the problem?

Multispectral imagery is not merging.
[console.txt](https://github.com/OpenDroneMap/ODM/files/9580433/console.txt)

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Large multispectral imagery can be split and processed successfully.

### How can we reproduce this? What steps did you do to trigger the problem? If this is an issue with processing a dataset, YOU MUST include a copy of your dataset uploaded on Google Drive or Dropbox (otherwise we cannot reproduce this).

auto-boundary: true, fast-orthophoto: true, radiometric-calibration: camera, orthophoto-cutline: true, split: 30, split-overlap: 50
[Dataset: 2940 images 14.5GB](https://1drv.ms/u/s!AsY5aB0MpC2DgeUA7Y3yPrnOBZZPsQ?e=7WqNnY)

**Comment by pierotofy** [comment]
Should be fixed with the latest version, thanks for the report!
