### ISSUE TITLE
Black border with KMZ file on Google Earth

### ISSUE THREAD

**Issue by Kitadonf972** [OpenDroneMap/ODM#1534]
Hello,
When I import a KMZ file generated by WebODM, in Google Earth, I lose the transparency, which is replaced by a black border. Is there a way to fix this bug?
Thanks in advance.
![Capture](https://user-images.githubusercontent.com/113986597/191250781-47348e4b-35ff-4529-bba2-3bd7580e2a74.JPG)

**Comment by pierotofy** [comment]
Thanks for the report! It should be fixed with https://github.com/OpenDroneMap/ODM/commit/0249d6b6c888972aa16f5324b320784f267f2569

![image](https://user-images.githubusercontent.com/1951843/191281826-c15406cd-6cca-43f4-890e-ba8629f1ffd4.png)
