### ISSUE TITLE
RTK merge?

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/ODM#1540]
### How did you install ODM? (Docker, installer, natively, ...)?

WebODM

### What is the problem?

It would be nice if split-merge could use RTK data for merging sub models.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Better and easier merge.

### How can we reproduce this? What steps did you do to trigger the problem? If this is an issue with processing a dataset, YOU MUST include a copy of your dataset uploaded on Google Drive or Dropbox (otherwise we cannot reproduce this).

Test it

**Comment by smathermather** [comment]
Essentially all that is needed here (breadcrumbs for the willing) would be to turn off the alignment step in merge. I haven't had the time to spend on this that I hoped, but there might be some insights in the beginnings of a pull request here:
https://github.com/OpenDroneMap/ODM/pull/1270
