### ISSUE TITLE
Split-merge overlap -> image overlap

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/ODM#1541]
## How did you install ODM? (Docker, installer, natively, ...)?

Windows native

### What is the problem?

Setting split merge overlap in meters is strange and not easy to grasp.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Setting the amount of shared images along the “border” between submodels would be better.

Because meters can be very different depending on altitude and space between fotos.

setting a shared image width would work across every altitude and space between fotos taken.

so instead of setting 50 or 150 meters depending on altitude and spacing you could set the overlap to 6 images across the board.

### How can we reproduce this? What steps did you do to trigger the problem? If this is an issue with processing a dataset, YOU MUST include a copy of your dataset uploaded on Google Drive or Dropbox (otherwise we cannot reproduce this).

i tried setting it up.

**Comment by pierotofy** [comment]
Not all datasets are flown using a specified pattern. If you think about all possible ways to capture images and try to apply the proposed idea, you'll see that it's actually very difficult to implement. Nonetheless, we'd welcome a PR? :pray:
