### ISSUE TITLE
Can ODM output latitude and longitude images？

### ISSUE THREAD

**Issue by Scarlett2025** [OpenDroneMap/ODM#1554]
The default output .tif image is in geodetic coordinates, can you set the parameters or modify the source code to make the output image in latitude and longitude coordinates?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
