### ISSUE TITLE
Compress or remove orthophoto_render.tif

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1573]
This is a large file that should probably be not included in the final output and confuses people because of its large size (mistakenly hinting that it might be of higher resolution, when in fact it's just not compressed).

**Comment by Saijin-Naib** [comment]
I know we aren't huge on adding flags, but perhaps we could combine this with other legacy GeoTIFF flags under an --orthophoto-legacy or such (strip encode, etc).
