### ISSUE TITLE
gcp_list.txt does not work when JPEG file names have spaces

### ISSUE THREAD

**Issue by alanterra** [OpenDroneMap/ODM#1575]
### How did you install ODM? (Docker, installer, natively, ...)?

Docker Desktop downloaded and drag-installed, and WebODM cloned from github on 2022-12-22 onto macOS Intel running Ventura 13.0.1.

### What is the problem?

WebODM does not work when you use gcp_list.txt and when there is a space in the names of the JPEG files.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

I generate the gcp_list.txt using GCP Editor Pro.app. I was able to stitch my files (e.g., into an orthophoto) as long as I did not include GCPs. But when I included GCPs I got the error "Cannot process dataset" about 1 minute into the task.

I got the same error processing locally and on WebODM Lightning.

I was able to fix this error by renaming all my JPEGs to eliminate space characters, changing, e.g., 2022-09-26 15-24-47 DJI_0293.JPG to 2022-09-26_15-24-47_DJI_0293.JPG, and making the same change in gcp_list.txt.

I did not look at the code, but it seems likely that the code for parsing gcp_list.txt uses both spaces and tabs as column delimiters. Since GCP Editor Pro.app only outputs the file with tabs as a delimiter, I suggest that it is not a good idea to use spaces when parsing this file.

### How can we reproduce this? What steps did you do to trigger the problem? If this is an issue with processing a dataset, YOU MUST include a copy of your dataset uploaded on Google Drive or Dropbox (otherwise we cannot reproduce this).

The task settings are:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/6795475/209443804-2c1b7476-8366-4858-b6dd-baa228e65eb9.png">

The files are at https://www.dropbox.com/sh/h1xfba79hby7e3k/AAD0oDF8CEnYh4AvLs_tUS-la?dl=0

**Comment by pierotofy** [comment]
This probably needs to be fixed in GCP Editor, as spaces are not allowed in the GCP file format spec.

**Comment by pierotofy** [comment]
Moving to https://github.com/uav4geo/GCPEditorPro/issues/30
