### ISSUE TITLE
Georeference information for the orthomosaics.

### ISSUE THREAD

**Issue by IuliuNovac** [OpenDroneMap/ODM#1581]
Can you tell me if the information stored in OpenDroneMap can be used for georeferencing orthomosaics, and if so, how can I access that information?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
