### ISSUE TITLE
Feature request, increase default resolution to 1cm

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#1584]
Per this conversation:
https://community.opendronemap.org/t/output-resolution-of-orthos-in-webodm-seems-to-be-fixed-and-not-a-result-of-image-resolution/14404

I think it makes some sense to increase the default resolution, given we now calculate GSD and don't go above it unless unwisely requested to do so. 1cm seems like a good compromise these days.

**Comment by pierotofy** [comment]
The compromise is always quality vs speed (and in most cases, memory usage).

I'm not so sure bumping quality to the highest is the way to go (especially being a default).

For example, I've already seen some posts from confused users, that upon selecting "Ultra Quality" either run out of memory or never finish processing (e.g. https://community.opendronemap.org/t/processing-time-over-22-hrs-now-i-would-like-some-clarification/14223/12) 

Defaults should provide sensible values to start an investigation of a dataset. First and foremost, I think they should 1) Finish in a reasonable amount of time 2) Actually finish! Running out of memory is the worst outcome, finishing in days of processing a close second worst case scenario.

A new user trying out ODM and not being able to process a dataset on the first try is a really bad outcome. They might just give up (and label the software as "unreliable", "buggy" or "not ready").

Increasing the default resolution to 1cm (from 5) is a >20x increase in RAM requirements (and disk space), aside from processing time considerations which is also impacted.

**Comment by smathermather** [comment]
Is orthophoto the RAM bottleneck? I haven't profiled in a loooong time.

**Comment by pierotofy** [comment]
It is not currently (but it might become it?). The thing is, `orthophoto-resolution` doesn't just impact the orthophoto rendering part, it affects the size of the undistorted images, which affects texturing, which is the second bottleneck overall.

**Comment by smathermather** [comment]
> which is the second bottleneck overall.

What's number 1 currently? SfM?

**Comment by pierotofy** [comment]
Depthmap fusion (densification).

**Comment by smathermather** [comment]
Cool. It's funny how and where the memory bottlenecks are depending on dataset size. I've rarely OOM'd on depthmap fusion on larger datasets.

Building a test VM, since often the OOM cases are swift and deadly, so better to put a hard cap on usage to discern whether turning the knobs exceeds the current bottleneck. I'm making it with the last 4-8GB of memory on my host, so hopefully the virtualization is well behaved... .

**Comment by smathermather** [comment]
I'm going to close this issue and the related pull request. Having tested at 4GB RAM, our stated minimum, there is no space for parameter change. If we decide to increase this value to 8GB (which is probably a kinder minimum) then we can revisit this.

I made the mistake of not resizing before processing 75 images at 4GB and wow: that was painful.

**Comment by Saijin-Naib** [comment]
Now throw an increasingly more common quad-bayer dataset at it 😬
