### ISSUE TITLE
ODM_Setup_3.0.4.exe  - Error - Create a file in the destination directory

### ISSUE THREAD

**Issue by igeofr** [OpenDroneMap/ODM#1592]
### How did you install ODM? (Docker, installer, natively, ...)?

- ODM_Setup_3.0.4.exe
- Windows 10 Professionnel

### What is the problem?

![image](https://user-images.githubusercontent.com/7761073/215715016-61ad3493-95dc-42a3-b530-416c4ff5518a.png)

**Comment by pierotofy** [comment]
Thanks for the report! This should be fixed with https://github.com/OpenDroneMap/ODM/commit/bc87a1487ee3d56d3f3630019e0901c1c9b9b3ae (new setup file will be available in a few hours).
