### ISSUE TITLE
Pipeline for split and merge

### ISSUE THREAD

**Issue by teiminryu** [OpenDroneMap/ODM#1593]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!

First of all, thank you for taking the time to report an issue.

Before you continue, make sure you are in the right place. Please open an issue only to report faults and bugs. For questions and discussion please open a topic on http://community.opendronemap.org/c/opendronemap. 

Please use the format below to report bugs and faults. 
****************************************

### How did you install ODM? (Docker, installer, natively, ...)?

Github code and docker

### What is the problem?

Is it possible to change split and merge workflow

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

I have used the split-merge to handle dataset with large amount of images and it worked well. However, the current flow is to do SfM reconstruction for each submodel, and then subsequent processes, like MVS and meshing, are implemented. May I know the possibility to refine the workflow so that MVS and meshing are proceeded right after the SfM reconstruction in each submodel. In this way, I can examine whether the flight path recovered is acceptable or not.      

### How can we reproduce this? What steps did you do to trigger the problem? If this is an issue with processing a dataset, YOU MUST include a copy of your dataset uploaded on Google Drive or Dropbox (otherwise we cannot reproduce this).

I found out that in odm_app.py, there is a standard pipeline. May you show me some tips to modify this part so that I can test the above idea. Thank you so much in advance.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
