### ISSUE TITLE
How to apply custom keypoint detector in ODM?

### ISSUE THREAD

**Issue by Atypical-Programmer** [OpenDroneMap/ODM#1595]
In recent years, there have been many new key point detectors, some of which may be better than SIFT. I want to add new methods to ODM, but the ODM source code is complex. Is there a simple way to add custom methods? Thank you.

**Comment by Saijin-Naib** [comment]
Welcome!

Are these keypoint detectors in OpenCV, or are they separate libraries with dependencies we'll need to integrate and manage?

**Comment by Atypical-Programmer** [comment]
These methods are not only in OpenCV, but also in various conferences (e.g CVPR,ICCV,ECCV) in recent years. I have used Colmap before, and I can directly and simply import custom keypoints and descriptors for matching and adjustment. But I don't know there is a similar way in ODM. Thank you.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
