### ISSUE TITLE
The 3D Model Generated by ODM With --3d-tiles Always Navigate to Italy in Cesium

### ISSUE THREAD

**Issue by PpYyRrAa** [OpenDroneMap/ODM#1599]
Appears to work fine with the 3D Tiles of the PointCloud, but the 3D model ends up in Milano, Italy:
![1](https://user-images.githubusercontent.com/92281802/218347731-5b98e6e7-1e58-455c-a0ee-3f9e86361007.jpeg)

ppyyrraa-01
Created on:	2/10/2023, 11:06:48 PM
Processing Node:	node-odm-1 (manual)
Options:	3d-tiles: true, auto-boundary: true, dsm: true
Average GSD:	2.43 cm
Area:	79,360.96 m²
Reconstructed Points:	1,917,311
WebODM current/latest, ODM v3.0.4, previewed in Cesium ION Online

![2](https://user-images.githubusercontent.com/92281802/218347743-1434f006-9259-4008-b442-c3b02e12d143.jpeg)

ppyyrraa-02

Created on:	2/10/2023, 11:07:11 PM
Processing Node:	node-odm-1 (manual)
Options:	3d-tiles: true, auto-boundary: true, dsm: true
Average GSD:	3.54 cm
Area:	80,098.1 m²
Reconstructed Points:	1,527,007
WebODM current/latest, ODM v3.0.4, previewed in Cesium ION Online

Native Dataset：
https://1drv.ms/u/s!AhZ8njnn54ZkkC2YC4TL4F4V5y1w?e=e9Zu6j

**Comment by pierotofy** [comment]
Could you copy/paste the full task output log? 🙏 

The default location for the obj2tiles program is Milan, Italy, so for some reason it looks like the program is not being invoked with the proper geographic center.

**Comment by PpYyRrAa** [comment]
[log.zip](https://github.com/OpenDroneMap/ODM/files/10728449/log.zip)
This the log.json file output by ODM.

**Comment by PpYyRrAa** [comment]
> Could you copy/paste the full task output log? 🙏
> 
> The default location for the obj2tiles program is Milan, Italy, so for some reason it looks like the program is not being invoked with the proper geographic center.

This the log.json file output by ODM.
[log.zip](https://github.com/OpenDroneMap/ODM/files/10728484/log.zip)

**Comment by pierotofy** [comment]
Thanks for the log; this should be fixed with #1603 :pray:
