### ISSUE TITLE
pc-rectify obliterates "views" property in the point cloud

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1602]
This yields an improper survey map in the report. The "views" field is stored in the UserData dimension.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/1951843/218576294-42f182af-1d9a-4f8a-a097-381989455892.png">

**Comment by HeDo88TH** [comment]
I'm working on this :+1:

**Comment by HeDo88TH** [comment]
The `UserData` dimension does not get copied to the rectified point cloud
https://github.com/OpenDroneMap/ODM/blob/ffa7871c3341580d3b3fbb7fbb495621fdffdfa2/opendm/dem/ground_rectification/io/las_io.py#L24
