### ISSUE TITLE
how to use GPU accelerate the speed of puzzle

### ISSUE THREAD

**Issue by ZYZ18870128671** [OpenDroneMap/ODM#1604]
****************************************
What factors affect the speed of odm puzzle？i have use GPU to accelerate it，but the effect is not big different from the CPU.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by ZYZ18870128671** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
