### ISSUE TITLE
libcuda.so.1 not found in docker image 

### ISSUE THREAD

**Issue by russellk** [OpenDroneMap/ODM#1605]
### How did you install ODM? (Docker, installer, natively, ...)?

The docker image was pulled on 14 Feb 2023:
opendronemap/odm:gpu
DIGEST:sha256:38cfcc29051473491673171f6e8a065675683be78cb377de3b63fad35a63fa53

The command was executed within docker-ce on a Fedora 37 workstation with the nvidia cuda drivers install (nvidia-smi returns expected results).

docker run -it --rm \
  -v "$(pwd)/gcp_list.txt:/code/gcp_list.txt" \
  -v "$(pwd)/images:/code/images" \
  -v "$(pwd)/opensfm:/code/opensfm" \
  -v "$(pwd)/odm_orthophoto:/code/odm_orthophoto" \
  opendronemap/odm:gpu --split 400 --split-overlap 15

### What is the problem?

The following error message was returned after a few hours of processing:
[...]
[INFO]    running "/code/SuperBuild/install/bin/opensfm/bin/opensfm" export_visualsfm --points "/code/submodels/submodel_0000/opensfm"
[INFO]    Finished opensfm stage
[INFO]    Running openmvs stage
[INFO]    running "/code/SuperBuild/install/bin/opensfm/bin/opensfm" export_openmvs "/code/submodels/submodel_0000/opensfm"
[INFO]    Depthmap resolution set to: 684px
[INFO]    Running dense reconstruction. This might take a while.
[INFO]    Estimating depthmaps
[INFO]    nvidia-smi not found in PATH, using CPU
[INFO]    running "/code/SuperBuild/install/bin/OpenMVS/DensifyPointCloud" "/code/submodels/submodel_0000/opensfm/undistorted/openmvs/scene.mvs"  --resolution-level 2 --dense-config-file "/code/submodels/submodel_0000/opensfm/undistorted/openmvs/Densify.ini" --max-resolution 2736 --max-threads 56 --number-views-fuse 2 --sub-resolution-levels 2 -w "/code/submodels/submodel_0000/opensfm/undistorted/openmvs/depthmaps" -v 0 --cuda-device -2
/code/SuperBuild/install/bin/OpenMVS/DensifyPointCloud: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory

===== Dumping Info for Geeks (developers need this to fix bugs) =====
Child returned 127
Traceback (most recent call last):
  File "/code/stages/odm_app.py", line 81, in execute
    self.first_stage.run()
  File "/code/opendm/types.py", line 397, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 397, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 397, in run
    self.next_stage.run(outputs)
  [Previous line repeated 1 more time]
  File "/code/opendm/types.py", line 376, in run
    self.process(self.args, outputs)
  File "/code/stages/openmvs.py", line 120, in process
    raise e
  File "/code/stages/openmvs.py", line 106, in process
    run_densify()
  File "/code/stages/openmvs.py", line 102, in run_densify
    system.run('"%s" "%s" %s' % (context.omvs_densify_path,
  File "/code/opendm/system.py", line 110, in run
    raise SubprocessException("Child returned {}".format(retcode), retcode)
opendm.system.SubprocessException: Child returned 127

===== Done, human-readable information to follow... =====

[ERROR]   The program exited with a strange error code. Please report it at https://community.opendronemap.org

===== Dumping Info for Geeks (developers need this to fix bugs) =====
Child returned 127
Traceback (most recent call last):
  File "/code/stages/odm_app.py", line 81, in execute
    self.first_stage.run()
  File "/code/opendm/types.py", line 397, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 376, in run
    self.process(self.args, outputs)
  File "/code/stages/splitmerge.py", line 192, in process
    system.run(" ".join(map(double_quote, map(str, argv))), env_vars=os.environ.copy())
  File "/code/opendm/system.py", line 110, in run
    raise SubprocessException("Child returned {}".format(retcode), retcode)
opendm.system.SubprocessException: Child returned 127

===== Done, human-readable information to follow... =====

[ERROR]   The program exited with a strange error code. Please report it at https://community.opendronemap.org

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

The expected behavior is that /code/SuperBuild/install/bin/OpenMVS/DensifyPointCloud should find nvidia-smi and the shared library libcuda.so.1 within the docker image.

**Comment by pierotofy** [comment]
This doesn't look like a bug in ODM; you need to make sure you're running docker with the `--runtime=nvidia` option? https://github.com/NVIDIA/nvidia-docker
