### ISSUE TITLE
OSError: [Errno 30] Read-only file system: '/code'

### ISSUE THREAD

**Issue by ridahuhu** [OpenDroneMap/ODM#1611]
i have installed the ODM using snap. When i run it it gives the following error:

[WARNING] Directory code does not exist. Creating it now.
Traceback (most recent call last):
  File "/snap/opendronemap/253/odm/run.py", line 45, in <module>
    system.mkdir_p(os.path.abspath(args.project_path))
  File "/snap/opendronemap/253/odm/opendm/system.py", line 136, in mkdir_p
    os.makedirs(path)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/code'

**Comment by pierotofy** [comment]
Doesn't look like a bug. Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
