### ISSUE TITLE
Incorrect bounds values in output laz header

### ISSUE THREAD

**Issue by gnosys-scrawford** [OpenDroneMap/ODM#1616]
### How did you install ODM?

Using the opendronemap/odm docker image.  Version 3.0.4.  Running on windows with docker desktop.

### What is the problem?

odm_georeferenced_model.laz bounds contained in the header are slightly incorrect.

The header shows (as collected from `pdal info odm_georeferenced_model.laz --metadata`):
```
"maxx": 587696.34,
"maxy": 3338206.103,
"maxz": 422.146,
"minx": 587518.636,
"miny": 3338021.799,
"minz": 268.149,
"offset_x": 0,
"offset_y": 0,
"offset_z": 0,
"scale_x": 0.01,
"scale_y": 0.01,
"scale_z": 0.01,
```

The min/max of the actual points (as collected from `pdal info odm_georeferenced_model.laz`):
```
"bbox":
{
  "maxx": 587696.34,
  "maxy": 3338206.1,
  "maxz": 422.15,
  "minx": 587518.64,
  "miny": 3338021.8,
  "minz": 268.15
},
```

While the numbers are close, in this example there is a point with z=422.15 but the header says maxz=422.146, which can lead to problems (eg. Potree conversion fails)

### What should be the expected behavior?

Values in header should match the data.

### How can we reproduce this? 

In this example I used the sample data from odm_data_caliterra.
`docker run -ti --rm -v C:\datasets:/datasets opendronemap/odm --project-path /datasets odm_data_caliterra --dsm --dtm --pc-las --pc-quality high`

**Comment by pierotofy** [comment]
> there is a point with z=422.15 but the header says maxz=422.146

This might be an issue of double/float conversion (or just output formatting); if there's an issue with PDAL not writing the correct values (seems unlikely) this issue might have to be opened in the PDAL repository.

**Comment by gnosys-scrawford** [comment]
In las files, coordinate = offset + scale * integer_value.  I believe the bounds stored in the header are set based on original coordinates, but when the scale and offset are set (which thus slightly changes the coordinates of every point) the header values should be updated, but are not.  I don't know if this problem is in pdal or odm.
