### ISSUE TITLE
shiny and non-textured surfaces problems

### ISSUE THREAD

**Issue by 666Le** [OpenDroneMap/ODM#1624]
Dear developer, we compared sift and akaze  feature extraction with flann matching in  photovoltaic scene reconstruction ,but the results were not satisfactory. here are some statistical results.
![image](https://user-images.githubusercontent.com/35422795/226857707-624b41f7-9f5b-46f4-8994-cb223cb2aedd.png)
 
here is the dataset for test,      
[dataset.zip](https://github.com/OpenDroneMap/ODM/files/11038697/dataset.zip)
the run command is  "python3 run.py --feature-quality ultra  --feature-type akaze  --project-path dataset/".

**Comment by pierotofy** [comment]
https://docs.opendronemap.org/flying/
