### ISSUE TITLE
How to find a point in 2D map is generated by what picture in input data?

### ISSUE THREAD

**Issue by trand2k** [OpenDroneMap/ODM#1626]
hi author,
I'm a newbie with opendronemap, can you help me to find a point in 2D (or 3D map) is generated by what picture?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
