### ISSUE TITLE
When Docker runs, what command is used to generate the tif file of epsg:4326 (wgs84)?

### ISSUE THREAD

**Issue by liangfj** [OpenDroneMap/ODM#1633]
When Docker runs, what command is used to generate the tif file of epsg:4326 (wgs84)?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
