### ISSUE TITLE
Ne créer pas le nuage de point 

### ISSUE THREAD

**Issue by x45mp** [OpenDroneMap/ODM#1637]
Bonjour, 

J'ai installé WebODM sur une machine virtuel Ubuntu 20.04. J'aimerai utiliser WebODM pour générer des othophotos à partir d'images historiques. 
Cependant le traitement échoue constamment. Sauf une fois ou le traitement a réussi je ne sais pas pour quelle raison. 

Voici le message d'erreur inscrit dans la console "error: no valid point-cloud for the ROI estimation
Segmentation fault (core dumped)" 

Voici le paramétrés que j'ai utilisé:
 
min-num-features: 30000 : 
orthophoto-resolution: 50 : 
skip-3dmodel: true : 

Merci 
Bien cordialement

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
