### ISSUE TITLE
opensfm export_colmap not working on odm's opensfm reconstructions.

### ISSUE THREAD

**Issue by joelitreview** [OpenDroneMap/ODM#1644]
### How did you install ODM? (Docker, installer, natively, ...)?

- Cloned https://github.com/OpenDroneMap/ODM
- Ran with the following command:
```bash
docker run -ti --rm -v /home/youruser/datasets:/datasets --gpus all opendronemap/odm:gpu --project-path /datasets project
```

### What is the problem?

I need to export the opensfm reconstructions to colmap format. Opensfm provides a command to run on the generated assets to do so (https://opensfm.org/docs/using.html#reconstruction-commands). It works when I generate the reconstructions with opensfm, but it doesn't when I use odm opensfm assets.

The problem lies with the tracks.csv file. I understand that it has been binarized in (https://github.com/OpenDroneMap/OpenSfM/commit/564ff2caf1caceedb838d0325cf85ac639d21062). However, even when I changed the GIT_TAG to 283 in odm/ODM/SuperBuild/cmake/External-OpenSfM.cmake, the tracks.csv was still corrupted. I also tried to use the original opensfm repo in the cmake file  (GIT_REPOSITORY    https://https://github.com/mapillary/OpenSfM/), and still corrupted. 

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

The expected behavior is to even:
- generate a readable tracks.csv file that we can parse (even with the binary file and the struct code, I couldn't make sense of the hex data), OR
- add a feature / option to generate colmap format directly using the ODM command.

### How can we reproduce this? What steps did you do to trigger the problem? If this is an issue with processing a dataset, YOU MUST include a copy of your dataset AND task output log, uploaded on Google Drive or Dropbox (otherwise we cannot reproduce this).

Run 
```bash
docker run -ti --rm -v /home/youruser/datasets:/datasets --gpus all opendronemap/odm:gpu --project-path /datasets project
```
and take a look at the opensfm/tracks.csv file.

**Comment by pierotofy** [comment]
We'd welcome a PR to our OpenSfM fork that fixes this (while leaving our binary modifications intact). As we don't use colmap we don't really support it. :pray:
