### ISSUE TITLE
Why cannot use GPU acceleration in dockerdesktop?

### ISSUE THREAD

**Issue by githubhanjunjun** [OpenDroneMap/ODM#1666]
### How did you install ODM? (Docker, installer, natively, ...)?

Computer System: Windows 10 pro 22H2 19045.2965 
Install ODM: DockerDesktop v24.0.2 use the WSL 2 backend, so resource limits are managed by Windows. Installed opendronemap/map:gup Docker Image. 

### What is the problem?
Problem: Cannot use GPU acceleration! Use the first step to verify that the GPU is accessible. But there is no output information using the GPU when running the program in the second step
Step1: run ‘docker run --rm --gpus all nvidia/cuda:10.0-base nvidia-smi’. The output information is as follows:
![image](https://github.com/OpenDroneMap/ODM/assets/27795864/0717068e-f9ae-4ef5-a8bf-d6a4ace36545)
Step2: run ‘docker run -ti --rm -v D:/ODM_data/datasets:/datasets --gpus all opendronemap/odm:gpu --project-path /datasets project‘. The output information is as follows:
![image](https://github.com/OpenDroneMap/ODM/assets/27795864/e0de3f61-70c1-416d-bce6-373f9e6ea212)

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
