### ISSUE TITLE
The file with the obj suffix is exported as a white block without color rendering

### ISSUE THREAD

**Issue by xx1425942154** [OpenDroneMap/ODM#1700]
Dear bosses
           After I use ODM, the obj file that I produce is a block and the color on the picture is not rendered to the model. Can you tell me what is the problem or is it that we have the original state

        Please help me solve this problem. Thank you！！！

**Comment by Saijin-Naib** [comment]
The OBJ file will be accompanied by an MTL and texture atlas files. The program you're using will need them all next to each other to load the textures.

What program are you using?

Try using MeshLab.
