### ISSUE TITLE
How can I see the odm execution completion time in the command line？？？

### ISSUE THREAD

**Issue by xx1425942154** [OpenDroneMap/ODM#1706]
As mentioned in the picture below, the execution time of my odm app shows the time when I started, so I am confused.
![111](https://github.com/OpenDroneMap/ODM/assets/75938918/61ac4bac-1699-4bfc-b5f9-8c3ff6506c7d)
Thanks...

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
