### ISSUE TITLE
Document appropriate rerun-from places when changing settings

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#1718]
Per: https://community.opendronemap.org/t/changed-flag-now-where-do-i-restart-from/18126, it's difficult for even some advanced users to know what point to re-run from when trying out different settings. Per João's request, we could establish this as a table, but I lean toward instead/also documenting this in the command documentation themselves so it's always visible.

**Comment by smathermather** [comment]
https://github.com/OpenDroneMap/ODM/pull/1719

**Comment by pierotofy** [comment]
| **Option**                              | **Restart Stage**     |
| --------------------------------------- | --------------------- |
| **3d-tiles**                            | PostProcess           |
| **align**                               | Georeferencing        |
| **auto-boundary**                       | Point Filtering       |
| **auto-boundary-distance**              | Point Filtering       |
| **bg-removal**                          | Load Dataset          |
| **boundary**                            | Point Filtering       |
| **build-overviews**                     | Orthophoto            |
| **camera-lens**                         | Load Dataset          |
| **cameras**                             | Load Dataset          |
| **cog**                                 | DEM                   |
| **copy-to**                             | PostProcess           |
| **crop**                                | Georeferencing        |
| **dem-decimation**                      | DEM                   |
| **dem-euclidean-map**                   | DEM                   |
| **dem-gapfill-steps**                   | DEM                   |
| **dem-resolution**                      | DEM                   |
| **dsm**                                 | DEM                   |
| **dtm**                                 | DEM                   |
| **end-with**                            | N/A                   |
| **fast-orthophoto**                     | Point Filtering       |
| **feature-quality**                     | Structure From Motion |
| **feature-type**                        | Structure From Motion |
| **force-gps**                           | Structure From Motion |
| **gcp**                                 | Load Dataset          |
| **geo**                                 | Load Dataset          |
| **gltf**                                | Texturing             |
| **gps-accuracy**                        | Load Dataset          |
| **help**                                | N/A                   |
| **ignore-gsd**                          | Structure From Motion |
| **matcher-neighbors**                   | Structure From Motion |
| **matcher-order**                       | Structure From Motion |
| **matcher-type**                        | Structure From Motion |
| **max-concurrency**                     | N/A                   |
| **merge**                               | Merge                 |
| **mesh-octree-depth**                   | Meshing               |
| **mesh-size**                           | Meshing               |
| **min-num-features**                    | Structure From Motion |
| **no-gpu**                              | N/A                   |
| **optimize-disk-space**                 | N/A                   |
| **orthophoto-compression**              | Orthophoto            |
| **orthophoto-cutline**                  | Orthophoto            |
| **orthophoto-kmz**                      | Orthophoto            |
| **orthophoto-no-tiled**                 | Orthophoto            |
| **orthophoto-png**                      | Orthophoto            |
| **orthophoto-resolution**               | Orthophoto            |
| **pc-classify**                         | DEM                   |
| **pc-copc**                             | Georeferencing        |
| **pc-csv**                              | Georeferencing        |
| **pc-ept**                              | Georeferencing        |
| **pc-filter**                           | Multi View Stereo     |
| **pc-las**                              | Georeferencing        |
| **pc-quality**                          | Structure From Motion |
| **pc-rectify**                          | DEM                   |
| **pc-sample**                           | Point Filtering       |
| **pc-skip-geometric**                   | Multi View Stereo     |
| **primary-band**                        | Load Dataset          |
| **project-path**                        | N/A                   |
| **radiometric-calibration**             | Structure From Motion |
| **rerun**                               | N/A                   |
| **rerun-all**                           | N/A                   |
| **rerun-from**                          | N/A                   |
| **rolling-shutter**                     | Structure From Motion |
| **rolling-shutter-readout**             | Structure From Motion |
| **sfm-algorithm**                       | Structure From Motion |
| **sfm-no-partial**                      | Structure From Motion |
| **skip-3dmodel**                        | Meshing               |
| **skip-band-alignment**                 | Structure From Motion |
| **skip-orthophoto**                     | Orthophoto            |
| **skip-report**                         | Report                |
| **sky-removal**                         | Load Dataset          |
| **sm-cluster**                          | Split                 |
| **sm-no-align**                         | Split                 |
| **smrf-scalar**                         | DEM                   |
| **smrf-slope**                          | DEM                   |
| **smrf-threshold**                      | DEM                   |
| **smrf-window**                         | DEM                   |
| **split**                               | Split                 |
| **split-image-groups**                  | Split                 |
| **split-overlap**                       | Split                 |
| **texturing-keep-unseen-faces**         | Texturing             |
| **texturing-single-material**           | Texturing             |
| **texturing-skip-global-seam-leveling** | Texturing             |
| **texturing-skip-local-seam-leveling**  | Texturing             |
| **tiles**                               | DEM                   |
| **use-3dmesh**                          | Texturing             |
| **use-exif**                            | Load Dataset          |
| **use-fixed-camera-params**             | Structure From Motion |
| **use-hybrid-bundle-adjustment**        | Structure From Motion |
| **version**                             | N/A                   |
| **video-limit**                         | Load Dataset          |
| **video-resolution**                    | Load Dataset          |

**Comment by jprates** [comment]
"Merge" and "Split" are not currently available options in WebODM's "Restart" button.
Assuming we must start from the previous available option, which ones would them be for each case?

Unless of course there is a plan to add them to the available options as well...

**Comment by pierotofy** [comment]
@jprates please let's move all questions over to the forum at https://community.opendronemap.org Thank you! :+1:

**Comment by jprates** [comment]
I was merely calling your attention for the fact that your table posted above (here on github) was not 100% correct, since there are 2 stages that **can't** be restarted from, at least on WebODM 2.2.1:

|Option	            |Restart Stage|
|:-----------------:|:-----------:|
|**merge**	            |Merge        |
|**sm-cluster**	        |Split        |
|**sm-no-align**	    |Split        |
|**split**	            |Split        |
|**split-image-groups**	|Split        |
|**split-overlap**	    |Split        |

One might edit the said table referring to the previous selectable stage, or confirm there will be new options for those use cases coming soon, it's a fair comment.
I fail to see how a comment about an ongoing sprint/feature posted here should be placed on the forum.

**Comment by pierotofy** [comment]
You seem to make a lot of assumptions, which are often incorrect. As a new user, please be humble and accept that you might not know everything there's to know about the software just yet. This issue is about ODM, not WebODM. Instead of being confrontational and defending your actions, please take a step back, follow the rules of our community, follow the indications of people that have contributed on this project for longer than you have and we can all continue to improving this beautiful software.

**Comment by jprates** [comment]
I'm shocked, I'm 52 and never saw this attitude nowhere in my entire life, let alone by OpenSource software developers!
It seems to me you're the one making a lot of wrong assumptions, and insulting someone who was just trying to help improve the software.

Have a nice day.

**Comment by smathermather** [comment]
Superceded by https://github.com/OpenDroneMap/ODM/pull/1720
