### ISSUE TITLE
Possible bug in determination of coordinate system when using GCPs

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#1721]
Possible bug: when my data are fed in UTM Zone 36, but ODM calculates 40S as my coordinate system somehow:
```
[INFO]    Loading 30 images
[INFO]    Wrote images database: /var/www/data/01c274ba-6ef4-4ef9-8242-058902d88be0/images.json
[INFO]    Found 30 usable images
[INFO]    15 GCP points will be used for georeferencing
[INFO]    Generated coords file from GCP: WGS84 UTM 40S
```

GCP as follows:
```
+proj=utm +zone=36 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs
706784 411645 0 1810 2184 IMG_4389.jpeg
706784 411673.5 0 1704 2191 IMG_4389.jpeg
707121.5 411673.5 0 1662 1037 IMG_4389.jpeg
706784 411645 0 1145 1172 IMG_4393.jpeg
706784 411673.5 0 1139 977 IMG_4393.jpeg
707121.5 411673.5 0 3218 962 IMG_4393.jpeg
706784 411645 0 1211 1369 IMG_4394.jpeg
706784 411673.5 0 1196 1199 IMG_4394.jpeg
707121.5 411673.5 0 3168 1167 IMG_4394.jpeg
706784 411645 0 1274 918 IMG_4395.jpeg
706784 411673.5 0 1278 751 IMG_4395.jpeg
707121.5 411673.5 0 3140 757 IMG_4395.jpeg
706784 411645 0 1419 1201 IMG_4396.jpeg
706784 411673.5 0 1415 1020 IMG_4396.jpeg
707121.5 411673.5 0 2895 998 IMG_4396.jpeg
```

Images are GPS free, so the only cue for coordinate system should be the proj string in the GCP dataset, but somehow ODM is assigning a different UTM zone.

Image and GCP data here:
https://github.com/smathermather/ioniq5/

**Comment by pierotofy** [comment]
Is it possible the coordinates are incorrect?

![image](https://github.com/OpenDroneMap/ODM/assets/1951843/648c6aa1-2cb9-46da-ad6b-261078e9fd2f)

Edit: ah, I see this is a pseudo-dataset.

Currently the UTM zone is picked based on the location of the first GCP point, not on the GCP header (that's because not all GCPs will be in UTM, and we always pivot to a UTM system).

See `get_utm_zone_and_hemisphere_from`.

**Comment by smathermather** [comment]
This would apply even if it were a real dataset (but yeah: completely arbitrary choice here). However, the coordinates in that GCP file should place it in Kenya.

I'm a little confused though: the header is relevant to parse the meaning of the GCP values and thus the determination of appropriate UTM. We cannot discern the meaning of GCPs without parsing that header, and converting those values to lat/lon to pass to pass to a function to find UTMz zone, or am I misreading something?

Imagine a (real) scenario where images have no exif to parse, but GCPs are used where the coordinate system is typically local, not angular.

**Comment by smathermather** [comment]
So, I assume the fix is a pull request parsing the header and with proj4, rewriting the `get_utm_zone_and_hemisphere_from` to calculate appropriate UTM zone? That would generalize to non-UTM headers that undoubtedly have the same challenge.

**Comment by pierotofy** [comment]
I don't think this is bug, but rather the coordinates might just be incorrect?

`706784 411645 0 1810 2184 IMG_4389.jpeg`

![image](https://github.com/OpenDroneMap/ODM/assets/1951843/8f4329f0-d58f-4fbe-ab88-ec9da54b2c04)

Your Northing value in https://epsg.io/32736 places you in Antarctica:

![image](https://github.com/OpenDroneMap/ODM/assets/1951843/c8a1287d-f67e-45fe-bee0-e57b02e8ef8a)

https://epsg.io/map#srs=32736&x=706784&y=411645&z=1&layer=streets

**Comment by smathermather** [comment]
I'm only off by an order of magnitude or so... . Closing.. :)

**Comment by smathermather** [comment]
Just follow up, with correct coordinates (this time in a zone compatible with Korea) we get this beautiful result:
![image](https://github.com/OpenDroneMap/ODM/assets/1174901/26143107-35de-4924-ab02-9c40cb5a24e6)
