### ISSUE TITLE
[ERROR] Uh oh! Processing stopped because of strange values in the reconstruction

### ISSUE THREAD

**Issue by xx1425942154** [OpenDroneMap/ODM#1723]
What I built here is 1000 pictures, and it was no problem after several hours of construction, but suddenly reported this mistake, is there any good solution, thank you guys

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
