### ISSUE TITLE
how to show real-world coordinates in a tif flle generated by ODM?

### ISSUE THREAD

**Issue by Chuanheliu1** [OpenDroneMap/ODM#1726]
hi there, i am a rookie of ODM, got a problem here,

Once i successfully generated a map tif file(the drone data comes from DJ1 and contains longitude and latitude), and opened it by Qgis ; but i can't visualize the real-world coordinates data on the map, how to show longtiude and latitude on the map.

Thanks for the help.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
