### ISSUE TITLE
Skip missing multi-band images instead of failing

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1737]
Currently if a multispectral dataset lacks all the images for a band, the reconstruction will fail:

```
[ERROR]   Multi-camera setup detected, but band "RedEdge" (identified from "IMG.TIF") has only 54 images (instead of 53), perhaps images are missing or are corrupted. Please include all necessary files to process all bands and try again.
[INFO]    Found 213 usable images
```

We should make it so that the reconstruction continues, emit a warning, and discard the files with missing bands instead.

**Comment by smathermather** [comment]
This is a huge usability improvement for multispectral users. +1
