### ISSUE TITLE
ODM Is not processing MP4 videos when uploaded with SRT file

### ISSUE THREAD

**Issue by DanielALT0134** [OpenDroneMap/ODM#1741]
Hi,

I've been trying to process a MP4 video with the SRT file to increse the resolution, but with no success.  When I try to do it without the SRT file it works correctly.

See the log file
[console.txt](https://github.com/OpenDroneMap/ODM/files/14022485/console.txt)

If necessary, here is the [link](https://www.dropbox.com/scl/fo/zz5ct1mbtuj68ay42yw4r/h?rlkey=im0dfhry0rz3t1bdflgmbyk2m&dl=0) to download the dataset.

**Comment by pierotofy** [comment]
Thanks for the report and dataset @DanielALT0134, this should be fixed as soon as https://github.com/OpenDroneMap/ODM/pull/1742/commits/9fd3bf3eddbc856511eb931613b6157606c99f6c is merged :pray:

**Comment by pierotofy** [comment]
Seems to render in the right place and with the proper scale (roughly). ![image](https://github.com/OpenDroneMap/ODM/assets/1951843/1617d426-d184-4b80-ad0b-83cc6e8251cd)

**Comment by DanielALT0134** [comment]
Thank you Piero !
