### ISSUE TITLE
Feature request / Proposal -- increase default GPS-Accuracy to 2̶m̶  3m

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#1748]
For a couple years now, I've been of the mind that the default GPS-Accuracy under-constrains the model using GPS values, resulting in calibration issues which presents as excessive doming in the elevation data produced. Based on processing dozens of datasets on the community forum, the accuracy (or in this case, really a measure of consistency) for individual flights (rather than aggregate datasets) can be safely tuned to 0.2m / 2 decimeters.

### Doming in dataset from Monrovia, Liberia
![image](https://github.com/OpenDroneMap/ODM/assets/1174901/a06ee644-449f-4689-9064-c0d9a18360ad)

> data credit: Community mapping in Monrovia, Liberia, with Slum Dwellers International. Residents are creating drone imagery, ditigitizing buildings, and conducting enumeration surveys using OpenDataKit and the HOT Field Mapping Tasking Manger.

For aggregate (multi-flight) datasets where there can be GPS consistency differences over time, it's safer to set this value to a larger value such as 2m.

I'm currently testing the switch to 2m with roughly a dozen community datasets shared with me over the last few years:
![ezgif-6-1a59c8ad6c](https://github.com/OpenDroneMap/ODM/assets/1174901/e0ef54cb-c527-4967-8f57-2e6b820703c0)

Thoughts? Any good counter examples? I have yet to break a dataset by reducing to 2m, but I could be missing salient examples.

**Comment by smathermather** [comment]
Community conversation on this here:
https://community.opendronemap.org/t/default-gps-accuracy/19510

**Comment by pierotofy** [comment]
I think this would warrant a decent amount of datasets testing; over-constraining the BA problem this way might make the program more sensitive to GPS measurement errors, causing failures when such measurement errors are present.

I don't know how often such errors happen in practice. Changing the default could be OK if it's beneficial for most datasets (and doesn't substantially raise the failures).

**Comment by smathermather** [comment]
In the dozen sets I tried, not a single failure at 2m. Sounds like @Saijin-Naib uses 3 and has yet to see a failure.

**Comment by Saijin-Naib** [comment]
The only time I need to relax it is when using ground-level mobile phone collects with my TeraCube, but even the default 10m isnt nearly coarse enough. 30m is normally needed

**Comment by smathermather** [comment]
https://github.com/OpenDroneMap/ODM/pull/1749

**Comment by smathermather** [comment]
Edited to 3m on @Saijin-Naib and Mike_F's recommendation.
