### ISSUE TITLE
Feature request: moar tag types for DOP

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#1759]
I could be misreading, but as far as I can tell, a limited number of DOP tag estimates are used. The DJI Mavic 3EM writes in the following form:

```
Rtk Std Lon                     : 1.23673
Rtk Std Lat                     : 1.19709
Rtk Std Hgt                     : 3.91458
```

Propose we build in logic to support this and other formats for tags. Happy to update get_gps_dop to support more tag types, but figured I'd open an issue first since it's friday and my brain is mush.

**Comment by pierotofy** [comment]
https://github.com/OpenDroneMap/ODM/blob/master/opendm/photo.py#L387 ?

**Comment by smathermather** [comment]
Looking in the wrong location... . Thanks!

**Comment by smathermather** [comment]
Todo: GitHub that auto closes any issues I open on Friday afternoon.
