### ISSUE TITLE
The generated image is too small and disordered.

### ISSUE THREAD

**Issue by JV-X** [OpenDroneMap/ODM#1764]
I want to generate an orthographic projection image for my 3D scene (a person lying on a sofa), and the generated image will be used for human pose recognition and face recognition in Google's `Mediapipe` project. However, when I followed the commands in the README.md to generate the image, what I got was an image with a width of 103px and a height of 53px. for me, it's too small.Is there a way to adjust the size of the generated image to get an image with a width of about 1600px and a height of about 1000px? How can I adjust the size of the image? 

![odm_orthophoto](https://github.com/OpenDroneMap/ODM/assets/29137451/74691d10-de6e-4640-b506-6b22166eb98b)

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by JV-X** [comment]
> Could we move this conversation over to the forum at https://community.opendronemap.org? 🙏 The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! 👍

OK, thanks for your reply.
