### ISSUE TITLE
Feature Request: Adapt las export resolution according to GSD

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#1789]
Related pull request: https://github.com/OpenDroneMap/ODM/pull/1788

Propose we filter las export resolution according to some factor of estimated GSD.

I have a few questions:
* Any favorite GSD measure I should use?
* Thinking of using some factor of GSD -- possibly 1/10 average OpenSFM estimated GSD
* Anything else I should be thinking about?

Related prior issue:
https://github.com/OpenDroneMap/ODM/issues/1432

Dataset where current 0.001 value starts to be come an issue:
![image](https://github.com/user-attachments/assets/a5725e47-ecdc-4828-870b-d0d1f1b0091b)
![Screenshot from 2024-08-07 13-01-32](https://github.com/user-attachments/assets/86918030-2383-4045-a092-37bdb2a37666)

**Comment by pierotofy** [comment]
In odm_filterpoints there's a JSON file that actually has a fairly reliable estimate of the average metric distance between points. It probably works better than GSD.

I would not set it to default at a low value like the current draft PR proposes, I think it will impact compression (and possibly issues with precision on larger scale datasets?). As this looks like an edge case of sort, an improvement could be:

```
scale = 0.001 # current
if <json file exists> and <value from json in odm_filterpoints> < threshold:
    scale = <multiple of 1/10 based on value>
```

**Comment by smathermather** [comment]
> In odm_filterpoints there's a JSON file that actually has a fairly reliable estimate of the average metric distance between points. It probably works better than GSD.

Oh nice! I'll take that approach.

> I would not set it to default at a low value like the current draft PR proposes

Oh yeah. Just set that for testing purposes. I don't think we want to default beyond what we already have. Just wanted to be able to detect the change in a dataset. That will go away in the final pull.

**Comment by smathermather** [comment]
Ahh, that's better!

![ezgif-4-a6c40324b4](https://github.com/user-attachments/assets/b880dfed-6e8e-4a66-b1cd-7f9778eab979)

**Comment by smathermather** [comment]
This is complete with https://github.com/OpenDroneMap/ODM/pull/1788
