### ISSUE TITLE
Add digital surface model output

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#18]
Current outputs from ODM include point cloud, mesh, textured mesh, georeferenced textured mesh, and orthophoto. It'd be just dandy if the mesh could also be output as a digital surface model, as a simple raster.

**Comment by lupus78** [comment]
Is there any update on this? I am keen to get an elevation raster out of ODM.

**Comment by smathermather** [comment]
Sadly, no progress yet on this. But, with the python port, you'll get georeferenced point clouds from which you can create a surface model in other software.

**Comment by lupus78** [comment]
Which software can do that and how?

**Comment by smathermather** [comment]
QGIS & GRASS are two good candidates. I'd start with QGIS (https://qgis.org).

**Comment by lupus78** [comment]
Yep, with the `option-0000_georef.ply` I had to make a CSV, with the X,Y shifted by the offsets, and I could import in into QGIS with GRASS plugin `r.in.xyz` command.

I'm thinking to add this to run.py to make that CSV.

However there is also an other format LIDAR (las) outputed by run.py, but I had no success using that yet in QGIS.

**Comment by smathermather** [comment]
@lupus78, adding this CSV output would be very welcome.

**Comment by KommandorKeen** [comment]
Cloud Compare with the Cloth Simulation Filter does a great job (with tweeking) of separating the ground from above ground features, then you can use the raster generation tool to create the DSM, or DEM as required.  All part of an opensource toolchain.

**Comment by yjmenezes** [comment]
@KommandorKeen 

Ground point classification is a challenge. I will try Cloth Simulation, thx.
take a look: PKtools is licensed by GPL v3.
http://pktools.nongnu.org/html/md_apps.html#available_tools

**Comment by KommandorKeen** [comment]
Thanks

Installed pktools on ubuntu and the QGIS plugin

Cannot seem to get the raster dataset from LAS(Z) to give any values.

Have tried with both LIDAR las and Drone photogrammetry las files.

 

Otherwise the Raster tools ad functionality to QGIS which was sorely missing.

 

Thanks,

 

Simon

**Comment by yjmenezes** [comment]
@KommandorKeen 

you can run PKtools from Command line.
Check your QGIS menu Processing pktools patch. My Pktools folder is: /usr/bin

I am testing PKtools with my drone dataset.
I have a second dataset with contours compiled, by hand,  with a photogrammetric workstation.
I did not test LiDAR data, yet.  I have two LiDAR datasets ( urban and rural ) but unfortunately i have no drone Images over those datasets.

I think we have some good FOSS tools for point clout processing.
I like PDAL. ( Thx Howard Butler, Michael Gerlek );

![pktools_02](https://cloud.githubusercontent.com/assets/4775645/26640484/39e6f6e8-45fe-11e7-8b24-006f568e8ddb.png)
![pktools_01](https://cloud.githubusercontent.com/assets/4775645/26640483/39e0398e-45fe-11e7-95c4-786d256bb1b9.png)

**Comment by jmprovencher** [comment]
Is it in the OpenDroneMap Roadmap to implement DSM output in the regular workflow in the near future?

**Comment by KommandorKeen** [comment]
@jmprovencher 
Please clarify. DSM or Bare Earth DTM?
The current orthomodel is better than a 2.5D DSM, but creating a DTM from a point cloud that does not see the ground in dense bush is not possible. I use Cloud Compare for that and have to fiddle a lot with CSF and multiple filters, curvature/roughness etc. Have tried the Canupo filter but the challenge is dense low bush.  So answer is........  probably not. YOu have a point cloud and there are many places to play with that and extract away.

Big plus would be to allow mor point cloud filtering options to create a 'cleaned cloud' as a discrete output  prior to meshing, SOR filter, etc.

**Comment by dakotabenjamin** [comment]
The `--dem` and related options do a progressive morphological filter to generate a rough ground model, but you are right it doesn't work for high vegetation areas like a lidar-produced model would.
