### ISSUE TITLE
Why to use FlightYawDegree instead of GimbalYawDegree

### ISSUE THREAD

**Issue by khaled-hammoud** [OpenDroneMap/ODM#1809]
While I am looking the file `photo.py`, exactly here:
https://github.com/OpenDroneMap/ODM/blob/12e5b63b6f5423383892d325467b64ce295e3a9c/opendm/photo.py#L463

I see using of gimbal's roll and pitch BUT flight's yaw instead of gimbal's yaw, why?

Could the author explain, why to use it? in Forum no answer was found.

On the other side when looking into file `exif.py` from opensfm, exactly here:
https://github.com/mapillary/OpenSfM/blob/537275b730d7a6417fce68c3645f69c834bddca3/opensfm/exif.py#L494

then I see what I expect or claim to be, is there any explanation for that?

<img width="1082" alt="asas" src="https://github.com/user-attachments/assets/3fba008b-a4cf-4b8a-9872-6f41d3413f25">

My regards.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by khaled-hammoud** [comment]
Is that not a potential misstype to be asked here?
