### ISSUE TITLE
MI PROGRAMA OPEN NO ME DEJA INICIAR

### ISSUE THREAD

**Issue by RicardoColomerOlaya** [OpenDroneMap/ODM#1812]
NO ME PERMITE INICIAR EL PROGRAM, YO ADQUIRI UNA LICENCIA A PERPETUIDAD
ME DEJA ESTE ARCHIVO
"Booting WebODM 2.5.2 build 105..."
"Trying to connect to NodeODM localhost:29301..."
"Attempt 0 failed, retrying..."
"nodeodm: (node:1272) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode\non September 8, 2024 and reach end-of-support on September 8, 2025.\n\nPlease migrate your code to use AWS SDK for JavaScript (v3).\nFor more information, check blog post at https://a.co/cUPnyil\n"
"nodeodm: info: Authentication using SimpleToken\r\n"
"nodeodm: info: Listening on 0.0.0.0:6367 UDP for progress updates\r\n"
"nodeodm: info: Initialized 1 tasks\r\n"
"nodeodm: info: Checking for orphaned directories to be removed...\r\n"
"nodeodm: info: About to run: C:\\WebODM\\resources\\app\\apps\\ODM\\run.bat --auto-boundary --dsm --pc-ept --cog --gltf --project-path C:\\WebODM\\resources\\app\\apps\\NodeODM\\data 8b2601b0-b77a-431d-a4ae-cab0c4765858\r\n"
"nodeodm: info: Server has started on port 29301\r\n"
"Trying to connect to NodeODM localhost:29301..."
"Connected to NodeODM 2.2.3"
"(node:2016) UnhandledPromiseRejectionWarning: undefined"
"(node:2016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)"
"(node:2016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."
"redis-server: exited with code -4058"
"nodeodm: info: About to run: C:\\WebODM\\resources\\app\\apps\\NodeODM\\apps\\7z\\7z.exe a -mx=0 -y -r -bd C:\\WebODM\\resources\\app\\apps\\NodeODM\\data\\8b2601b0-b77a-431d-a4ae-cab0c4765858\\all.zip odm_orthophoto/odm_orthophoto.tif odm_georeferencing odm_texturing odm_dem/dsm.tif entwine_pointcloud images.json cameras.json task_output.txt log.json odm_report\r\n"
{}

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by RicardoColomerOlaya** [comment]
Gracias, se me resolvió, desinstalando. E instalando de nuevoMuchas gracias

Yahoo Mail: busca, organiza, toma el control de tu buzón 
 
  El lun., 18 de nov. de 2024 a la(s) 11:08 p. m., Piero ***@***.***> escribió:   


Could we move this conversation over to the forum at https://community.opendronemap.org? 🙏 The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! 👍
