### ISSUE TITLE
Can't read the GPS from exif of Dji drone photo

### ISSUE THREAD

**Issue by smallworld-network-wupeng** [OpenDroneMap/ODM#1814]
I am using the Docker version of OpenDroneMap. Recently, I discovered that reconstructing ODM images using a set of photos taken by a DJI drone always fails. After spending two days investigating this issue, I found that OpenDroneMap fails to read GPS information from the photos’ EXIF data and cannot retrieve the latitude and longitude, which causes the ODM reconstruction to fail.

I carefully checked the photos with ExifTool and found that the EXIF data does contain complete latitude and longitude information. Below is the GPS section from the EXIF data:
---- GPS ----
GPS Version ID                  : 2.3.0.0
GPS Latitude Ref                : North
GPS Latitude                    : 23 deg 14' 5.66"
GPS Longitude Ref               : East
GPS Longitude                   : 113 deg 25' 14.03"
GPS Altitude Ref                : Above Sea Level
GPS Altitude                    : 220.778 m
GPS Status                      : Measurement Active
GPS Map Datum                   : WGS-84 

This might be a bug. If possible, please fix this issue.

**Comment by Saijin-Naib** [comment]
Please provide full logs and dataset.
