### ISSUE TITLE
How to have orthorectified images saved individually in geotiff?

### ISSUE THREAD

**Issue by automataIA** [OpenDroneMap/ODM#1816]
### How did you install ODM?
Docker, installer,

### What is the problem?

I would like to know how to perform fast orthorectification of a series of drone images while saving each orthorectified image as a separate GeoTIFF, instead of creating a mosaic.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

The expected behavior is:
1. Each drone image is orthorectified individually.
2. The orthorectified images are saved as separate GeoTIFF files.
3. No needs mosaic.

If this feature is not currently available, I suggest adding an option or a flag to enable individual image orthorectification and saving.

### How can we reproduce this? What steps did you do to trigger the problem? 
this is the sample link: https://we.tl/t-av0mQVZcoR

Steps:
1. Run ODM with a series of drone images as input.
2. Look for an option to save orthorectified images individually.
3. Notice that there seems to be no straightforward way to achieve this.

If additional information or datasets are needed, please let me know.

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by automataIA** [comment]
the site don't give me the email for sign in

**Comment by pierotofy** [comment]
CC'ing @smathermather

**Comment by smathermather** [comment]
@automataIA -- can you reach out to info@opendronemap.org and we'll fix things so you can create an account. Sorry for the trouble.
