### ISSUE TITLE
install.sh doesn't finish properly

### ISSUE THREAD

**Issue by edgarriba** [OpenDroneMap/ODM#188]
Hi,

I'm trying to install the project using the installation file but it stops at texturing without errors.
Any idea? Thanks in advance !

Screen log:

> pcl 
>     - configuring pcl
>     - building and installing pcl
>   < done - mar oct 27 14:37:20 CET 2015
> 
> meshing 
>     - configuring odm_meshing
>     - building odm_meshing
>   < done - mar oct 27 14:37:40 CET 2015
> 
> texturing 
>     - configuring odm_texturing
>     - building odm_texturing

**Comment by dakotabenjamin** [comment]
Please post your odm_texturing log files found in the logs directory. Thanks!

**Comment by edgarriba** [comment]
Scanning dependencies of target odm_texturing
[ 25%] Building CXX object CMakeFiles/odm_texturing.dir/src/Logger.cpp.o
[ 50%] Building CXX object CMakeFiles/odm_texturing.dir/src/main.cpp.o
[ 75%] Building CXX object CMakeFiles/odm_texturing.dir/src/OdmTexturing.cpp.o
[100%] Building CXX object CMakeFiles/odm_texturing.dir/src/modifiedPclFunctions.cpp.o
Linking CXX executable odm_texturing
CMakeFiles/odm_texturing.dir/src/OdmTexturing.cpp.o: In function `OdmTexturing::loadCameras()':
OdmTexturing.cpp:(.text+0x3812): undefined reference to`cv::imread(cv::String const&, int)'
CMakeFiles/odm_texturing.dir/src/OdmTexturing.cpp.o: In function `OdmTexturing::createTextures()':
OdmTexturing.cpp:(.text+0x782e): undefined reference to`cv::imread(cv::String const&, int)'
OdmTexturing.cpp:(.text+0x7dd4): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
OdmTexturing.cpp:(.text+0x805b): undefined reference to`cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
make[2]: **\* [odm_texturing] Error 1
make[1]: **\* [CMakeFiles/odm_texturing.dir/all] Error 2
make: **\* [all] Error 2

**Comment by edgarriba** [comment]
I would add that have OpenCV 3.0 installed

**Comment by dakotabenjamin** [comment]
Which branch are you using? Try switching to `python-port`

**Comment by edgarriba** [comment]
main branch. Ok, trying.

**Comment by edgarriba** [comment]
@dakotabenjamin got the same the error

**Comment by dakotabenjamin** [comment]
OK, thanks. We need to get OpenCV contained so that other installations do not conflict. This has been a problem for other users as well.

**Comment by dakotabenjamin** [comment]
@edgarriba I think #192 may fix your problem. Please test and report back.

**Comment by edgarriba** [comment]
@dakotabenjamin 

```
- script finished - Fri Oct 30 11:07:13 UTC 2015
```

thanks!

**Comment by dakotabenjamin** [comment]
Yay!
