### ISSUE TITLE
How to create a LOD from the large scale point cloud

### ISSUE THREAD

**Issue by SimFaris** [OpenDroneMap/ODM#191]
Now, I have got a large area point cloud from many aerial imagies. ODM can texture the terrain model with the point cloud, but the model is large and the frame is so slow. So My question is how to create the LOD of terrain model from the so large terrain point cloud.Thank you.

**Comment by smathermather** [comment]
Ah, good question, @SimFaris. @hobu -- what do you recommend for LOD stuff these days. (BTW, got your e-mail. I'm excited to look at this this weekend.)

**Comment by ghost** [comment]
A system I know about is the pop buffer for x3dom:http://x3dom.org/pop/
Looks very promising but 
I didnt try it so far. Would be great to see other opinions here.

**Comment by smathermather** [comment]
Nice that it handles textured meshes too.

**Comment by SimFaris** [comment]
thank you. I just known that outofcore module of PCL can generate the multi-resolution and out-of-core point cloud based on octree. Maybe I could get the poisson mesh and texture the models on the basis of the every multi-resolution point cloud. But the question will occur because of the skirt. Maybe some can give some more advise.

**Comment by smathermather** [comment]
Hi @SimFaris -- any luck with LOD?

**Comment by SimFaris** [comment]
I just divided the point cloud with quadtree, and then texture the models with the multi-redolution point cloud. But I did not constrain the points between the neighboring partiotions with the poisson mesh, so the neighboring partiotions are not corresponded.
