### ISSUE TITLE
OpenDroneMap-gui

### ISSUE THREAD

**Issue by edgarriba** [OpenDroneMap/ODM#199]
Hi folks,

I would like to know if there's any plan to create a graphical user interface for odm? Since the current standard software options such as Pix4D are quite expensive, it would be a nice opportunity to push this project to a high level interface for research groups or professionals that cannot afford private software amenities.

**Comment by smathermather** [comment]
Closing this with the development of https://github.com/OpenDroneMap/WebODM .
