### ISSUE TITLE
Parallel does not build

### ISSUE THREAD

**Issue by miquelmassot** [OpenDroneMap/ODM#2]
I was following the instructions, and the build stopped at "building parallel". 

```
$ cat logs/parallel_2_build.log 
make  all-recursive
make[1]: Entering directory `/home/miquel/opt/OpenDroneMap/src/parallel'
Making all in src
make[2]: Entering directory `/home/miquel/opt/OpenDroneMap/src/parallel/src'
pod2man --release='20100922' --center='parallel' \
        --section=1 ./parallel > ./parallel.1
pod2man --release='20100922' --center='parallel' \
        --section=1 ./sem.pod > ./sem.1
pod2man --release='20100922' --center='parallel' \
        --section=1 ./sql > ./sql.1
pod2html ./parallel > ./parallel.html
pod2html ./sem.pod > ./sem.html
pod2html ./sql > ./sql.html
rm -f ./pod2htm*
rm -f ./pod2htm*
./parallel around line 334: Expected text after =item, not a number
./parallel around line 340: Expected text after =item, not a number
rm -f ./pod2htm*
./parallel around line 1510: Expected text after =item, not a number
./parallel around line 1514: Expected text after =item, not a number
POD document had syntax errors at /usr/bin/pod2man line 71.
make[2]: *** [parallel.1] Error 255
make[2]: Leaving directory `/home/miquel/opt/OpenDroneMap/src/parallel/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/miquel/opt/OpenDroneMap/src/parallel'
make: *** [all] Error 2
```

As suggested in the fix for a [similar problem](http://comments.gmane.org/gmane.network.inn/9841), the solution is to put "Z<>" in the "=item" argument string.

**Comment by miquelmassot** [comment]
I changed the parallel version (which is from 2010!) for a newer one (20141022) and now it's working.

**Comment by smathermather** [comment]
Cool. Can you create a pull request?

**Comment by smathermather** [comment]
@miquelmassot -- What OS / version were you building on?

**Comment by miquelmassot** [comment]
Ubuntu 14.04 64bit

El dilluns, 24 novembre de 2014, Stephen Mather notifications@github.com
va escriure:

> @miquelmassot https://github.com/miquelmassot -- What OS / version were
> you building on?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDroneMap/OpenDroneMap/issues/2#issuecomment-64271944
> .

## 

Miquel Massot

miquel.massot@gmail.com    https://github.com/miquelmassot

**Comment by smathermather** [comment]
Awesome. I will test and add to docs.
