### ISSUE TITLE
Replace existing Perl control script

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#20]
Replace existing Perl control script with something in Python, or should license allow, controls written in C for full binary compile.

**Comment by wildintellect** [comment]
As noted on the email list Python possibly Flask seems like a good way to go. Should be able to run from command line or via optional interface (local web browser?)

**Comment by smathermather** [comment]
I do like the idea of having a light framework. What was Bborie's suggestion at FOSS4GNA regarding framework access to the parts of the toolchain as well as the overall control?

**Comment by dbrgn** [comment]
Please don't tie it to Flask and a Browser. If it's a binary / script with a nice command line interface (or even an API), it can be called from a Flask server though.

If I'd start with a Python version of the script that provides a base structure as well as argument parsing, would that be welcome? I'd probably use [docopt](https://pypi.python.org/pypi/docopt) for argument parsing. We could vendor it in, or install from apt (available in trusty but not precise).

**Comment by dakotabenjamin** [comment]
I would hold off on writing a script just yet because some folks from Spotscale should have one ready in the next few weeks. The Flask app I'm working on will only be a front-end interface and won't contain any ODM code.

**Comment by dakotabenjamin** [comment]
see python-port branch for python port of run.pl.
