### ISSUE TITLE
CMakeLists.txt for installation

### ISSUE THREAD

**Issue by edgarriba** [OpenDroneMap/ODM#201]
Hi folks,

has anyone considered to port the installation.sh to a CMake? Until now I haven't succeed with installation and run a simple demo from odm_data due to library linking errors. Maybe by doing a standard installation using CMakeLists and submodules could help in addition to easily debug what's going on during the whole process.

**Comment by smathermather** [comment]
Definitely interested in make / cmake install for it, especially any work that gets us closer to tying into package management as well.

**Comment by edgarriba** [comment]
@smathermather I started a SuperBuild cmake project. 
@dakotabenjamin @paulinus You might be interested in that.
You can check here:
 https://github.com/edgarriba/OpenDroneMap/tree/fd338c40c39c0120e5a4c0d0134fbd339f1ef26e/SuperBuild

**Comment by paulinus** [comment]
looking good!
