### ISSUE TITLE
Allow for partitioning of mesh algorithm with different approaches for built structures vs. vegetation vs. ground

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#21]

**Comment by KommandorKeen** [comment]
Use Cloud Compare and the Cloth Simulation Filter

**Comment by dakotabenjamin** [comment]
https://github.com/CloudCompare/CloudCompare/blob/master/plugins/qCSF/qCSF_instructions.pdf for reference.

**Comment by KommandorKeen** [comment]
Also been working with CC and SAGA to do cloud cluster analysis using normalised RGB ratio's, surface curvature, roughness indices (at mutliple scales) as inputs to the cluster analysis.

**Comment by pierotofy** [comment]
Can this be closed (or more details be added to the original intent of the feature)?

**Comment by pierotofy** [comment]
Closing for now but feel free to re-open with more info!
