### ISSUE TITLE
OpenCV 2.4.11 

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#210]
Currently, opencv is installed via package manager, which means in Trusty the version is 2.4.8 but in precise the version is 2.3.1-7

Version 2.4.11 is needed to support future texturing improvements (i.e blending), so I think we should add opencv as an internal module in the code, rather than an external dependency.

**Comment by xialang2012** [comment]
Yes, blending is really important for ODM to obtain smoother images.
