### ISSUE TITLE
How to upload an updated ccd_defs.json?

### ISSUE THREAD

**Issue by asierrl** [OpenDroneMap/ODM#226]
I updated my ccd_defs.json file and I would like to upload it; my ridiculously small contribution. I was following the instructions in the README.md file, which should be 1) check if it compiles and 2) do a pull request.
I don't even fully understand what "check it it compiles" mean, but I entered ccd_defs_check.py in a terminal and I got a "command not found" message.
What am I doing wrong?
Thanks!!
Asier

**Comment by dakotabenjamin** [comment]
try `python ccd_defs_check.py`

**Comment by asierrl** [comment]
Thanks. It works!! Although, only from the OpenDroneMap folder.

**Comment by dakotabenjamin** [comment]
That's right. I look forward to the pull request :+1:

**Comment by asierrl** [comment]
I tried...but I am afraid I didn't understand all the process. I'm knew to GitHub and some of the concepts are not clear to me...I have to come back on the issue again, and see if I can understand it all in a second read...
Thanks for your support.

**Comment by dakotabenjamin** [comment]
No worries! Here's some help that I found when I was learning git: 

https://rogerdudler.github.io/git-guide/
http://git-scm.com/book/en/v2/Getting-Started-Git-Basics
https://try.github.io/levels/1/challenges/1

**Comment by asierrl** [comment]
Thanks!! Those were really useful...after a couple of hours of reading I've been able to complete muy pull request.

**Comment by dakotabenjamin** [comment]
Nice! :+1:
