### ISSUE TITLE
Allow for integration of photogrammetric break lines for sharp natural and man-made features

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#23]
Allow for integration of photogrammetric break lines for sharp natural and man-made features

**Comment by pierotofy** [comment]
How would this be implemented?

**Comment by smathermather** [comment]
Wow, this is an old issue... . My general impression is given the dense nature of photogrammetric point clouds, breaklines aren't necessary. They are being used much less now in LiDAR datasets for the same reason.
https://desktop.arcgis.com/en/arcmap/latest/extensions/3d-analyst/breaklines-in-surface-modeling.htm

Probably, this can be closed unless someone shows up with a good solution.

**Comment by pierotofy** [comment]
I'll close this for the time being :pray:
