### ISSUE TITLE
Code 32512

### ISSUE THREAD

**Issue by Rafaelaniemann** [OpenDroneMap/ODM#234]
Hi people,

I'm trying to run ./run.py command to add the images, however it gives me the following error:

running import_bundler
running PYTHONPATH=/home/jeco/OpenDroneMap/lib/python2.7/dist-packages "/home/jeco/OpenDroneMap/src/OpenSfM/bin/import_bundler" opensfm --list list.txt
sh: 1: /home/jeco/OpenDroneMap/src/OpenSfM/bin/import_bundler: not found
b

quitting cause: 
    PYTHONPATH=/home/jeco/OpenDroneMap/lib/python2.7/dist-packages "/home/jeco/OpenDroneMap/src/OpenSfM/bin/import_bundler" opensfm --list list.txt
returned with code 32512.

what can I do? I'm getting lost, rs

Thanks

**Comment by xialang2012** [comment]
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH
