### ISSUE TITLE
ccd_defs is soon to be depreciated

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#237]
Since we have more or less removed support for matcher/bundler (it still exists in the code, but OpenSfM is faster and better and therefore runs as the default), ccd_defs.json has been replaced with OpenSfM's own [sensor data file](https://github.com/mapillary/OpenSfM/blob/master/opensfm/data/sensor_data.json).

I will not be merging any ccd_defs.json update PRs anymore.

**Comment by renzoepolo** [comment]
Micasense RedEdge Size CCD?

**Comment by dakotabenjamin** [comment]
I don't know how a multispectral camera would work with ODM. I think you'll have to get in contact with Micasense to get more information on their sensors.

**Comment by smathermather** [comment]
RedEdge has 5 bands, correct? ODM assumes 3 bands at this time, but we're open to contributions which extend that to multispectral.

**Comment by renzoepolo** [comment]
Yes, RedEdge has 5 band.
I going to work with one band each time.

**Comment by dakotabenjamin** [comment]
That being said, I don't think OpenSfM actually 'fails' when there's no ccd width information.
