### ISSUE TITLE
returned with code 35584

### ISSUE THREAD

**Issue by bobit200** [OpenDroneMap/ODM#243]
Hi,
Any had any issues with this error code.  Trying to produce an orphophoto but keep getting this message on completion.  My mesh is created fine and I am using a Gcp file for my reference points.
![11](https://cloud.githubusercontent.com/assets/17023034/12898895/da02729a-cea6-11e5-98c5-3c406955c5c2.JPG)
![12](https://cloud.githubusercontent.com/assets/17023034/12898927/028328b8-cea7-11e5-8413-5c5a9e4eeed6.JPG)

**Comment by bobit200** [comment]
Anyone got any ideas?

**Comment by dakotabenjamin** [comment]
What do you get from `reconstruction-with-image-size-2400/odm_georeferencing/odm_georeferencing_log.txt`?

**Comment by bobit200** [comment]
hi,
that file is empty - 0 bytes.  It does exist.

Tried running it again but with different UTM reference points and increased the number to ten. Three of the points in the original gcp file were the same UTM point but on different images. odm now produced an orthophoto with the new gcp file.

Thanks.

**Comment by dakotabenjamin** [comment]
Perfect. Is the problem solved?

**Comment by bobit200** [comment]
Yes.  Issue closed.
