### ISSUE TITLE
Is it available to run ODM on Windows

### ISSUE THREAD

**Issue by xialang2012** [OpenDroneMap/ODM#247]
Just curious... I have checked the libraries which used by ODM, it seems most of the libraries have the Windows version, except the gsl.

**Comment by dakotabenjamin** [comment]
I've never tried to build it on windows, as is I don't think it will work. But if what you say is true, maybe it could be installed manually with [gsl for windows](http://gnuwin32.sourceforge.net/packages/gsl.htm)

**Comment by xialang2012** [comment]
Okay, If I have enough time, I will try it.

**Comment by xialang2012** [comment]
I have already successful built ODM on Windows with VS 2013.

**Comment by dakotabenjamin** [comment]
I will have to try this! What did you do to make it work?

**Comment by smathermather** [comment]
Whoa! Awesome.

**Comment by xialang2012** [comment]
@dakotabenjamin The  compatibility of the ODM is very well, I have never revised any codes on it. Just built Opencv 3.0, PCL 1.7.2 (it is wise to use all in to installer), PROJ 4.8 on Windows with VS 2013, then built the modules of the ODM respectively. The include and library paths, the libraries used are as below:

> <IncludePath>C:\Program Files\PCL 1.7.2\include\pcl-1.7;C:\Program Files\PCL 1.7.2\3rdParty\Eigen\eigen3;C:\Program Files\PCL 1.7.2\3rdParty\Boost\include\boost-1_55;C:\Program Files\PCL 1.7.2\3rdParty\FLANN\include;C:\Program Files\PCL 1.7.2\3rdParty\QHull\include;C:\Program Files\PCL 1.7.2\3rdParty\VTK\include\vtk-5.10;D:\opencv3\build\include;E:\gdal\proj-4.8.0\src;
> 
> <LibraryPath>C:\Program Files\PCL 1.7.2\lib;C:\Program Files\PCL 1.7.2\3rdParty\Boost\lib;C:\Program Files\PCL 1.7.2\3rdParty\VTK\lib\vtk-5.10;E:\opencv3\lib\Release;E:\gdal\proj-4.8.0\src;
> 
> <AdditionalDependencies>pcl_common_release.lib;pcl_io_release.lib;pcl_surface_release.lib;pcl_kdtree_release.lib;vtkCommon.lib;opencv_core300.lib;opencv_imgproc300.lib;opencv_imgcodecs300.lib;opencv_highgui300.lib;proj_i.lib;

**Comment by ahmadusman** [comment]
xialang can you share work, I have tried but its getting error

**Comment by GeospatialDaryl** [comment]
Hi-

I've put a fair amount of effort into making the ODM structure platform
independent.

Other than OpenSfM, most of the components compile pretty readily on VS2013
- with some tweaking.  Thinking long-term, there are some basic conventions
  in python programming that can ensure cross-comparabilit (e.g. use os.sep,
  etc).

Daryl

On Fri, Mar 4, 2016 at 7:59 AM, ahmadusman notifications@github.com wrote:

> xialang can you share work, I have tried but its getting error
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDroneMap/OpenDroneMap/issues/247#issuecomment-192333607
> .

## 

---

Daryl Van Dyke
GIS Analyst
Klamath Strategic Habitat Conservation Team
US Fish & Wildlife Service - AFWO, R8
(707) 825-5153
https://github.com/GeospatialDaryl

**Comment by dakotabenjamin** [comment]
@ahmadusman can you post your errors? I'd like to get around to this at some point in the near future.

**Comment by ahmadusman** [comment]
I have manually installed all the dependencies but its still asking for more every time I build it

**Comment by ahmadusman** [comment]
Missing Dependencies

**Comment by xialang2012** [comment]
@GeospatialDaryl, yes, the problem is the openSFM, but we can used visualSFM or openMVG to replace it. (visualSFM is not an open-source project...)

**Comment by dakotabenjamin** [comment]
Given the modular nature of the project, if in the future we want to get Windows support fully and OpenSfM isn't supported by then, we could probably sidle openMVG in as a replacement for windows builds. I think OpenSfM is the best option in general so it shouldn't be replaced.
