### ISSUE TITLE
Does OpenDroneMap work on Mac OS X? 

### ISSUE THREAD

**Issue by nitinPandya** [OpenDroneMap/ODM#248]
Hi,

I've been trying for a while to install ODM on a Mac machine using home-brew and tweaking install script - without success.

Is there a better way to compile OpenDroneMap on Mac?

Thanks in advance,
~Nitin Pandya

**Comment by dakotabenjamin** [comment]
Not that I know of. As is the case with #247 it may take some hack'n'slashing to get it to work. Currently there is no official support for OSX. 

What exactly is failing?

**Comment by dakotabenjamin** [comment]
OK so with boot2docker, you may be able to get it to work. I have not tested this though.

**Comment by dakotabenjamin** [comment]
With full docker integration you can run with OSX
