### ISSUE TITLE
[edgarriba-cmake] csfm (again)

### ISSUE THREAD

**Issue by Fi156** [OpenDroneMap/ODM#252]
Disclaimer:
I have this problem on the **Mint** machine only, but I found some issues where it also occurred on Ubuntu:

https://github.com/OpenDroneMap/OpenDroneMap/issues/189
https://github.com/OpenDroneMap/OpenDroneMap/issues/217

```
/usr/bin/ld: /usr/local/lib/libceres.a(covariance.cc.o): relocation R_X86_64_32 against `__gxx_personality_v0' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libceres.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[5]: *** [/media/simon/dataSSD250gb/OpenDroneMap/SuperBuild/src/opensfm/opensfm/csfm.so] Error 1
make[4]: *** [CMakeFiles/csfm.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [opensfm/stamp/opensfm-build] Error 2
make[1]: *** [CMakeFiles/opensfm.dir/all] Error 2
make: *** [all] Error 2
Script finished
```

The log from `*/SuperBuild/src/opensfm/cmake_build/CMakeFiles` can be found here:
http://pastebin.com/3S9feAmm

I also tried to build opensfm manually with: `python setup.py build`, but OpenCV was not found correctly.

**Comment by dakotabenjamin** [comment]
Usually the error is a failure to install OpenSfM, which is solved by installing it manually. I would check this out on Mint but [given recent problems](http://arstechnica.com/security/2016/02/linux-mint-hit-by-malware-infection-on-its-website-and-forum-after-hack-attack/) I am hesitant to do so.
