### ISSUE TITLE
OSX: install.sh - /proc - no such file

### ISSUE THREAD

**Issue by energo80** [OpenDroneMap/ODM#283]
Installing on OSX failuire.
- script started - Wed Mar 30 14:55:24 CEST 2016
  grep: /proc/cpuinfo: No such file or directory

I can make some progress on OSX - if needed....

**Comment by dakotabenjamin** [comment]
Yeah we currently don't support OSX. I would recommend using a vagrant box to run it in Ubuntu.

**Comment by dakotabenjamin** [comment]
@energo80 you should checkout the Docker repo, so you can run ODM on Mac OSX using a Docker container: https://hub.docker.com/r/opendronemap/opendronemap/
