### ISSUE TITLE
ccd_defs for DJI Phantom 2 Vision+

### ISSUE THREAD

**Issue by dkovar** [OpenDroneMap/ODM#29]
Greetings,

The definition for this camera appears to be:

"DJI PHANTOM VISION FC200" => 6.17,

-David

**Comment by smathermather** [comment]
Cool, can you do a pull request?

**Comment by dkovar** [comment]
Greetings,

Unfortunately, I blew away the VM with the instance. It may be next week before I get everything rebuilt.

-David

**Comment by smathermather** [comment]
No worries. I'll add.

**Comment by smathermather** [comment]
Apparently I did this and didn't close the issue. Definition is now in the defs file:

https://github.com/OpenDroneMap/OpenDroneMap/commit/75c67c7b4f06beecfb3baf951ab30ebf5bdaaa49#diff-7f13dab363df1ca3ed0607c3d4a6a7bd
