### ISSUE TITLE
odm_data_rv_nir data running failed at pmvs2

### ISSUE THREAD

**Issue by jangbi882** [OpenDroneMap/ODM#311]
I downloaded odm_data_rv_nir-7c86404650f1ad2cddd1b48995b950d776be48a9.zip.
And run it using opendronemap/opendronemap:dev Docker.
But it is stopped on running /code/SuperBuild/install/bin/pmvs2 /images/pmvs/recon0/ option-0000.

I ran it two times because first try stopped with no clear message.

I attach log file and result files list.
[odm_data_rv_nir_result_files.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/271705/odm_data_rv_nir_result_files.txt)
[odm_data_rv_nir_log.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/271706/odm_data_rv_nir_log.txt)

**Comment by dakotabenjamin** [comment]
It looks like you ran out of memory. This seems to be a recurring problem with larger datasets: #296 #290 

This is a software that should be able to handle large numbers of images, that's its job. What are your machine's specs?

**Comment by jangbi882** [comment]
8GB.
I will retry after supply more ram to my VM.

Thank you.

Regards
BJ Jang.
2016. 5. 31. 오후 10:20에 "Dakota Benjamin" notifications@github.com님이 작성:

It looks like you ran out of memory. This seems to be a recurring problem
with larger datasets: #296
https://github.com/OpenDroneMap/OpenDroneMap/issues/296 #290
https://github.com/OpenDroneMap/OpenDroneMap/issues/290

This is a software that should be able to handle large numbers of images,
that's its job. What are your machine's specs?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/OpenDroneMap/OpenDroneMap/issues/311#issuecomment-222685735,
or mute the thread
https://github.com/notifications/unsubscribe/AB5gse8ChQ9_GlSVR7omW_7qzuQxXvduks5qHDWagaJpZM4Ih2hN
.

**Comment by smathermather** [comment]
Did you have luck, @jangbi882?

**Comment by jangbi882** [comment]
Yes. this work was finished good with 24GB RAM VM.
Thank you so much.

2016-06-10 11:49 GMT+09:00 Stephen Mather notifications@github.com:

> Did you have luck, @jangbi882 https://github.com/jangbi882?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/OpenDroneMap/OpenDroneMap/issues/311#issuecomment-225081417,
> or mute the thread
> https://github.com/notifications/unsubscribe/AB5gsdhJQ5I1wzSgTZl9Lcem05otuhO8ks5qKNC8gaJpZM4Ih2hN
> .

## 

Open Source GIS Technical Manager / e-Cartographer
장병진 팀장 | BJ Jang

_가이아쓰리디__(_주)
서울시 금천구 가산동 60-19 SJ테크노빌 702호
tel: 02-3397-3475 | fax: 02-3397-3278
_e-mail: jangbi882@gmail.com jangbi882@gmail.com | mobile: 010-3390-7056_

**Comment by smathermather** [comment]
:+1:
