### ISSUE TITLE
GCPs + EXIF?

### ISSUE THREAD

**Issue by rion-saeon** [OpenDroneMap/ODM#312]
Not so much an issue but rather a question.

If I pass `--odm_georeferencing-useGcp` (.txt list of GCPs), would the images' GPS-tagged data be considered at all in orthophoto generation?

I am asking because, of a concern about a current dataset's GCPs being placed too far apart and not contained in all images.

**Comment by smathermather** [comment]
I believe (without double checking) that GCPs are an override. We'll be moving to a more integrated model soon which takes into account a weighted set of inputs including any geo info + matching info which should serve to do a better job overall of georeferencing, but for now it's kinda simplistic.

**Comment by smathermather** [comment]
Watch this OpenSfM branch: https://github.com/mapillary/OpenSfM/tree/gcp

**Comment by pierotofy** [comment]
It used to be that we used only 3 GCPs, but OpenSfM now allows us to use all of them during computation. I'll close this for now. :pray:
