### ISSUE TITLE
Rolling shutter correction

### ISSUE THREAD

**Issue by kikislater** [OpenDroneMap/ODM#313]
It should be good to implement rolling shutter under ODM.

Link to have idea about process : 
 https://pix4d.com/rolling-shutter-correction/
http://www.eurocow2016.org/files/Vautherin-EuroCOW.pdf  
https://pix4d.com/wp-content/uploads/2016/05/pix4d-isprs-paper-rolling-shutter-final-edited.pdf

**Comment by dakotabenjamin** [comment]
This is an interesting problem space. As I understand it, we could use a rolling shutter model (the equation in the last link) to adjust the images using the drone's velocity? That could be pulled from flight logs or simply by estimate. 

I don't completely understand the math behind it, but would this translation (?) would happen during the orthophoto creation step?

**Comment by smathermather** [comment]
It seems like the translation affects everything from matching onward. If my intuition is correct, one could treat each scan as a separate image.

**Comment by KommandorKeen** [comment]
Any progress on this?
Happy to help.
Simon

**Comment by kikislater** [comment]
smathermather have a good suggestion : separate each frame of a rolling shutter in relation to shutter speed. It could be done with imagemagick. 
What is difficult is to know sensor readout with sport camera like gopro or others ...

Example : with repage here =
http://www.fmwconcepts.com/imagemagick/tidbits/image.php#crop1
Crop Vertically
convert monet.jpg -crop 100%x50% +repage monet_vertical_%d.jpg
![monet](https://cloud.githubusercontent.com/assets/13238064/26624039/b839ce38-4600-11e7-8611-43e33633384a.jpg)  ![rightarrow](https://cloud.githubusercontent.com/assets/13238064/26624049/c0717fa6-4600-11e7-8893-01ea3bce8f82.gif) ![monet_vertical_0](https://cloud.githubusercontent.com/assets/13238064/26624072/d2f1bec0-4600-11e7-9e12-6008e60d7024.jpg) ![monet_vertical_1](https://cloud.githubusercontent.com/assets/13238064/26624084/dbeba2d4-4600-11e7-8a18-e23039670b06.jpg)

**Comment by smathermather** [comment]
It seems there's an opportunity to measure the rolling shutter effect. Is there any project, similar to lensfun for addressing the nature of rolling shutter for different cameras?

**Comment by kikislater** [comment]
updated post above with method in imagemagick. 

IMO, very slow readout with rolling shutter like gopro @30ms sensor readout without stabilisation is problematic for photogrammetry.
Since CMOS sensor are rolling shutter without exception at this time. Like Sony A6000, Nikon D810, Canon 6D have a sensor readout of around 4ms or 1/250s, it seems not be an issue. 
Small CMOS sensor have better readout like 1" on g9x or rx100 (may be the same sensor and of course same as parrot soda or dji phantom4 pro) or Canon S100, Sony WX220 around 0.5ms or 1/2000s

**Comment by yjmenezes** [comment]
if it acts as systematic effect, i think, for multirotor,  it could be modeled by Imagemagick skew as a preprocessing stage, using a mean values of  flight speed and  height. 
It should be done or not, depending of flight plan and camera type as pointed by @kikislater.

http://www.fmwconcepts.com/imagemagick/skew/index.php

**Comment by KommandorKeen** [comment]
My trawl of info:
https://pix4d.com/rolling-shutter-correction/
Lots of other sites focus on this as a source.

Looks like the DJI Phantom 4 has a 30 - 33 ms rolling shutter, so at 5m/s this takes  15cm along my line of flight, but at 10m/s this is 30cm

If I am flying at 100m with a 3000x4000 camera (94degFOV) my GSD is 5.3cm 

Assuming that the time for the image taken is at the start of the image taking process and drone is flying oriented predominantly along track lines.

A quick fix may be to compress the vertical dimension of the image by my alongtrack speed / GSD and to offset the image by half the rolling shutter delay * along track speed

will play with the above and get back to you

Simon

**Comment by smathermather** [comment]
This is really interesting, @KommandorKeen. Do let us know what you discover.

**Comment by CarlosGrohmann** [comment]
This could be interesting: https://github.com/shimrcv/SfSM

**Comment by rion-saeon** [comment]
@smathermather , @dakotabenjamin , @KommandorKeen any progress on this matter?

We might look into Parrot Sequoia+ sensor and it employs a rolling shutter. Before making this expensive purchase, we would like this issue #313 to be addressed before deciding to purchase Pix4D or remain with ODM.

I will be at a conference this week where the matter of which software to use with which expensive UAV hardware, will be discussed.

**Comment by kikislater** [comment]
Rolling shutter on sequoia(+) is only on RGB sensor. RGB sensor on sequoia doesn't make any value added output ...
Rolling shutter doesn't matter if you have mechanical shutter which is not the case of sequoia

**Comment by smathermather** [comment]
> @smathermather , @dakotabenjamin , @KommandorKeen any progress on this matter?
> 
> We might look into Parrot Sequoia+ sensor and it employs a rolling shutter. Before making this expensive purchase, we would like this issue #313 to be addressed before deciding to purchase Pix4D or remain with ODM.
> 
> I will be at a conference this week where the matter of which software to use with which expensive UAV hardware, will be discussed.

For what you spend on Pix4D, you might be able to create some momentum behind adding this feature to ODM. :)

**Comment by smathermather** [comment]
And by "this feature" I mean this one: https://github.com/OpenDroneMap/OpenDroneMap/issues/500#issuecomment-423524570

**Comment by rion-saeon** [comment]
> > @smathermather , @dakotabenjamin , @KommandorKeen any progress on this matter?
> > We might look into Parrot Sequoia+ sensor and it employs a rolling shutter. Before making this expensive purchase, we would like this issue #313 to be addressed before deciding to purchase Pix4D or remain with ODM.
> > I will be at a conference this week where the matter of which software to use with which expensive UAV hardware, will be discussed.
> 
> For what you spend on Pix4D, you might be able to create some momentum behind adding this feature to ODM. :)

Very true RE cost of Pix4D but, I don't have the skills currently to add this to ODM! Seems I might have some self-teaching skills coming up but would appreciate any help in order to improve ODM. Just difficult imagine that someone else using these types of sensors haven't added it yet.

**Comment by smathermather** [comment]
> > > @smathermather , @dakotabenjamin , @KommandorKeen any progress on this matter?
> > > We might look into Parrot Sequoia+ sensor and it employs a rolling shutter. Before making this expensive purchase, we would like this issue #313 to be addressed before deciding to purchase Pix4D or remain with ODM.
> > > I will be at a conference this week where the matter of which software to use with which expensive UAV hardware, will be discussed.
> > 
> > 
> > For what you spend on Pix4D, you might be able to create some momentum behind adding this feature to ODM. :)
> 
> Very true RE cost of Pix4D but, I don't have the skills currently to add this to ODM! Seems I might have some self-teaching skills coming up but would appreciate any help in order to improve ODM. Just difficult imagine that someone else using these types of sensors haven't added it yet.

We take all sorts of contributions, including monetary ones, is what I am saying. I understand the skill-set limitation. Take a look at the code contributions. Mine are now overwhelmed by folks much better at this than I am.

This need is something that would also be beneficial to my organization and maybe some others. Reach out at svm[[[[[@]]]]]clevelandmetroparks.com and we can have a discussion about how we might finance it.

**Comment by Saijin-Naib** [comment]
From my prior usage of Pix4D with a 3DR Solo with GoPro Hero4 Black for agricultural field mapping (few thousand+ acres mapped), the usage of the rolling shutter compensation was really important. It made some really early flights (with sub-optimal overlap/sidelap) stitch properly, and for properly designed flights, greatly improved the quality of the point cloud and thereby the products (DSM, ortho, mesh) quite visibly. Accuracy measurements during the Pix4D accuracy report improved markedly, as well.

I'm a HUGE proponent of having this capability (likely on by default), if possible.

**Comment by kikislater** [comment]
Some recents documents on this subject : 
http://openaccess.thecvf.com/content_cvpr_2018/papers/Lao_A_Robust_Method_CVPR_2018_paper.pdf

https://arxiv.org/pdf/1903.03943.pdf

It seems to be available in MicMac ...

**Comment by pierotofy** [comment]
ODM 2.8.6 now includes rolling shutter correction using the method presented in `A two-step approach for the correction of rolling shutter distortion in UAV photogrammetry`: https://www.sciencedirect.com/science/article/abs/pii/S0924271619302849 

If your camera is in our database, simply pass `--rolling-shutter` to enable rolling shutter correction.

You also need to supply the camera readout time via `--rolling-shutter-readout` (ms) if it's not in our database. A default of `30` will be used otherwise, which is purely a guess.

:clinking_glasses:
