### ISSUE TITLE
Cant run python script

### ISSUE THREAD

**Issue by LeithHawkins** [OpenDroneMap/ODM#320]
Hi,

I am having a hard time getting the new version up and running.  I have installed but when 
i got to run the app using the python file .  

this is going to be a PEBCAK error for sure. Just trying to run Dennis Baldwins Dataset to start in the new version.

`~/OpenDroneMap$ python run.py [--project-path] /odm-data-caliterra/images`
![error](https://cloud.githubusercontent.com/assets/10125109/16261794/5150fe02-38b0-11e6-9e85-16b593712201.png)

sorry for the noob question.

thanks

Leith

**Comment by Fi156** [comment]
Just try: 
`python run.py --min-num-features 10000 --project-path /odm-data-caliterra/images`

Your path will not work most likely. Be sure to use an absolute or relative path.
The given path above assumes, that the "odm-data-caliterra" is located in your root directory.
I would exspect sometthing like "/home/"YourUserName"/odm-data-caliterra/..."

**Comment by LeithHawkins** [comment]
![screen shot 2016-06-22 at 7 31 59 pm](https://cloud.githubusercontent.com/assets/10125109/16261869/a5b8b778-38b0-11e6-94c3-ce1ea22884ce.png)

thanks yeah I have looked at that as well screen shot of latest results

**Comment by LeithHawkins** [comment]
![screen shot 2016-06-22 at 7 39 30 pm](https://cloud.githubusercontent.com/assets/10125109/16261979/178aaa6e-38b1-11e6-9c18-a1629f36a2b5.png)

I ran ls -d -1 $PWD/_._  to confirm the path

**Comment by Fi156** [comment]
Just to be sure:
Do you have this structure:

|--/home/ubuntu/odm-data-caliterra/
    |-- images/
        |-- img-1234.jpg
        |-- ...

Taken from:
https://github.com/OpenDroneMap/OpenDroneMap#running-opendronemap

**Comment by LeithHawkins** [comment]
yep 

> /home/ubuntu/odm_data_caliterra/images/IMG_9354.jpg

**Comment by dakotabenjamin** [comment]
Just reference the project base i.e `/home/ubuntu/odm_data_caliterra`

although a relative path should work just fine.

**Comment by LeithHawkins** [comment]
HI,  I hav tried running from both.

Still getting the error message: `you must put your pictures in an <images> directory`

**Comment by LeithHawkins** [comment]
hmm well thats interesting I restarted my Linux Box today and tried re running and I got an Error message  that was similar to this #251  it was related to the Ecto import. I re ran the install using -

`git clone https://github.com/OpenDroneMap/OpenDroneMap.git .
export PYTHONPATH=$PYTHONPATH:`pwd`/SuperBuild/install/lib/python2.7/dist-packages:`pwd`/SuperBuild/src/opensfm
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/SuperBuild/install/lib
bash configure.sh
mkdir build && cd build && cmake .. && make && cd ..`

and now I am back to where I started with the error message about images.  I have imported another dataset from github just to make sure it wasn't that .

`ubuntu@ip-172-31-44-152:~/OpenDroneMap$ python run.py --min-num-features 10000 --project-path home/ubuntu/odm_data_seneca
[INFO]    Initializing OpenDroneMap app - Thu Jun 23 09:00:35  2016
[INFO]    Running ODM Load Dataset Cell
[ERROR]   You must put your pictures into an <images> directory
[INFO]    OpenDroneMap app finished - Thu Jun 23 09:00:35  2016`

**Comment by rion-saeon** [comment]
Hi,

I'm having issues with that ecto import only. With both the ODM.zip download and install directly from GitHub the first sets of images would be analysed perfectly but, when I rerun the exact script even after exiting the terminal ecto shows me a lib.ecto? error. @dakotabenjamin has the e-mail from me stating those issues. I’m currently still playing around with the release 0.1 to try and make it work.

What seemed to solve my above problem was rerunning `bash ./configure.sh` after restarting Ubuntu but, frequently internet time-outs occurred with za.ubuntu.archive access.

**Comment by Fi156** [comment]
Exactly, you have to add those two paths to your bashrc at the moment.
See issue #251, or dakotabenjamins comment directly: 
https://github.com/OpenDroneMap/OpenDroneMap/issues/251#issuecomment-187691443
(Of course, you need to alter the paths according to your ODM installation path...)

**Comment by Fi156** [comment]
@LeithHawkins 

> ubuntu@ip-172-31-44-152:~/OpenDroneMap$ python run.py --min-num-features 10000 --project-path home/ubuntu/odm_data_seneca

From my point of view, the trailing slash does make a difference:
`python run.py --min-num-features 10000 --project-path /home/ubuntu/odm_data_seneca`

But you showed correct versions already, so I dont think it will make a difference...

**Comment by rionlerm** [comment]
What am I doing wrong here?
I extracted the release ~v0_1.zip to the Ubuntu 14.04 Desktop and ran the following through the Terminal with resultant error:
![screenshot from 2016-06-23 11 58 52](https://cloud.githubusercontent.com/assets/13643064/16299313/e60fe506-3939-11e6-99bf-66e7e3ebb0f7.png)

**Comment by dakotabenjamin** [comment]
@rionlerm yeah the environment variables you set are only stored in the current bash session, unless you hard-code them into your .bashrc file. 

Be careful not to put the `pwd` part in the bash file- but actually type in the real absolute path. 

---

@LeithHawkins can you post a screenshot of your project (images) folder contents (via `ls -al /home/ubuntu/odm_data_seneca`)?

**Comment by dakotabenjamin** [comment]
If you are pulling from the odm_data repo, then you should run a `git pull`. I just updated all those repos to incorporate the new project structure changes.

**Comment by dakotabenjamin** [comment]
Hey @LeithHawkins are you still running into problems?

**Comment by LeithHawkins** [comment]
Sorry for the delay @dakotabenjamin,  work is getting in the way of a good time. 

  I am still having trouble with the python paths paths :sob:  however I dont think its an issue as such more a user error. 

I think what ill do is close this and open a discussion on the mailing list if that is preferable to opening up the issues in Github.

**Comment by dakotabenjamin** [comment]
@LeithHawkins alright, you can also chat more directly here: https://gitter.im/OpenDroneMap/generalhelp

Although, I'm usually only on there during Eastern Standard Time work hours (9-5EST M-F)
