### ISSUE TITLE
Issue With Colour Blending

### ISSUE THREAD

**Issue by arosendorff** [OpenDroneMap/ODM#322]
Hi,

I've recently installed OpenDroneMap and am trying to use it to generate orthophotos. However, the final output image appears to be stitched together properly, but the colour is very patchy, changing in sections. Is there a way to disable this if it is intended? I cannot seem to find a way to enable a mosaic mode for generating the orthophotos, which is what I assume I need to prevent the colour blending.

Here's an example of the issue I'm having, the colour of the original images is all perfectly uniform.
![image](https://cloud.githubusercontent.com/assets/1186123/16342799/33d1172e-3a34-11e6-9047-31ccb81c9190.jpeg)

Thanks!

**Comment by dakotabenjamin** [comment]
Yes this is currently how the orthophoto is generated. Don't lose hope, though. We've got updates in the pipeline that improve texturing, implementing better blending. It's not ready for production yet, but the `mvs-texturing-addition` branch has what you need. See the image below for differences:

![](https://files.gitter.im/OpenDroneMap/OpenDroneMap/urQp/mvs_diffs1.png)

**Comment by arosendorff** [comment]
Okay thank you, that does look better, I'll give it a try!
