### ISSUE TITLE
configure.sh issue

### ISSUE THREAD

**Issue by Fire5Earth** [OpenDroneMap/ODM#327]
Hello I am stuck on step 11. After "bash configure.sh" i get these errors at the end. 
![bash configure sh](https://cloud.githubusercontent.com/assets/20093824/16434921/75613848-3d47-11e6-9252-02544a7453f4.png)

**Comment by dakotabenjamin** [comment]
It's hard to say what is failing from that screenshot because it is a multi-threaded compilation.

However, this is a recurring issue: https://github.com/OpenDroneMap/odm_vagrant/issues/15

**Comment by Fire5Earth** [comment]
Yes, it seems we have the same issue.

**Comment by Fire5Earth** [comment]
This is just a guess but some files may have not install correctly because some variables were undeclared. Such as meanStore

**Comment by Fire5Earth** [comment]
Question: Do we make the python path before or after the bash configure.sh? And are you Abel to produce the same results? I'm using Ubuntu 14.04.

**Comment by dakotabenjamin** [comment]
You must set the environment variables (PYTHONPATH and LD_LIBRARY_PATH) before running the python script run.py.

**Comment by dakotabenjamin** [comment]
I've been unable to replicate this issue on a fresh vagrant machine. (SInce you are referring to step 11, I am assuming you are following the directions for setting up a vagrant machine)

 I need the whole log of your install in order to properly understand the problem you are facing.

**Comment by Fire5Earth** [comment]
Are you talking about the steps I used to install or the logs of the vagrant machine? If it is the logs I am not sure how to get them. Can you tell me how? And, Thank you.

**Comment by Fire5Earth** [comment]
![virtualbox_github_default_1467142023936_29841_30_06_2016_09_05_50](https://cloud.githubusercontent.com/assets/20093824/16495372/fda327f6-3ea1-11e6-8254-25271b736eb2.png)

**Comment by dakotabenjamin** [comment]
2 ways: 
1. If you're in git shell or git bash, you can simply highlight and copy the text into a document on your host machine. 
2. you can run the configure.sh script to write to a file:

```
bash configure.sh 2>&1 | tee config.log
```

And then post the log to pastebin or something like that.

**Comment by Fire5Earth** [comment]
Okay

**Comment by Fire5Earth** [comment]
I created the log file but how do i post it or access it from windows?

**Comment by dakotabenjamin** [comment]
You can `cp config.log /vagrant_data/` and then you should be able to access it from that vodm_data folder you made before.

**Comment by dakotabenjamin** [comment]
Then you can upload it to http://pastebin.com/ or https://gist.github.com/

**Comment by Fire5Earth** [comment]
The file did not show up there. Are there other commands?

**Comment by dakotabenjamin** [comment]
what's the output of `ls -al /vagrant_data/` ?

**Comment by Fire5Earth** [comment]
It says that it cannot be access and that there is No such file or directory.

**Comment by dakotabenjamin** [comment]
Hmm... did you follow the steps here https://github.com/OpenDroneMap/odm_vagrant ?

The Vagrantfile should connect `/vagrant_data/` to `vodm_data` without any issue.

**Comment by Fire5Earth** [comment]
I will retry the steps again.

**Comment by heenalee** [comment]
I am stuck on Step #11 as well. I've tried a few times to install OpenDroneMap. My system is a multi-threaded compilati
![opendronemap install](https://cloud.githubusercontent.com/assets/10171036/20906115/348fdff2-bb0c-11e6-8d2c-a626198eb876.JPG)
on. What can I do? Please help!

**Comment by dakotabenjamin** [comment]
@heenalee I don't see any error in your screen grab. Can you find the error in the configure.sh output and post that?

**Comment by heenalee** [comment]
How can I do that? I am a newbie...

**Comment by heenalee** [comment]
I restarted to run "bash configure.sh" and got stuck again. Please see attached. Is this what you are looking for?
[Stuck on Bash Configure.sh.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/634083/Stuck.on.Bash.Configure.sh.txt)

**Comment by pierotofy** [comment]
@heenalee delete the build/ and SuperBuild/build directories. Then restart the configure.sh script.

To capture all output, run:

`bash configure.sh 2>&1 | tee -a log.txt`

Attach the log.txt file if you can't build.

**Comment by heenalee** [comment]
Thank you pierotofy for adding the comment!

I've found the reason it got stuck. The VM ran out of the memory. I've changed the memory setting in VirtualBox Manager, but it overwrites when I run Vagrant Up. So I've changed the memory setting in Vagrantfile directly. 
Now, it ran through Configure.sh but got errors. Please take a look attached file. 
[Configure.sh Error.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/635270/Configure.sh.Error.txt)

**Comment by pierotofy** [comment]
Well, it looks like you might still have some memory issues...

```
virtual memory exhausted: Cannot allocate memory
/usr/bin/cmake: error while loading shared libraries: libc.so.6: cannot map zero
-fill pages: Cannot allocate memory
```

How much RAM did you allocated to the VM?

**Comment by heenalee** [comment]
4096 out of 8192. I watched my computer memory went up to 70% and cpu usage went up to 100%.  
Do I need to modify the cpu as well? vb.cpus = 9 in Vagrantfile.

**Comment by pierotofy** [comment]
Try allocating more memory, or enable a swap file before starting the compilation process.

**Comment by dakotabenjamin** [comment]
This issue is outdated and will be closed. Please open a new thread in http://community.opendronemap.org and reference this issue if you would like to continue the conversation.
