### ISSUE TITLE
python: can't open file '../OpenDroneMap/run.sh': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Bavar2142** [OpenDroneMap/ODM#328]
home/gis/Pictures# ../OpenDroneMap/run.py
bash: ../OpenDroneMap/run.py: Permission denied

Anyone got ideas as to how i'd get around the above issue?

**Comment by Bavar2142** [comment]
After restarting it is now saying permission denied

/home/gis/Pictures# ../OpenDroneMap/run.py
bash: ../OpenDroneMap/run.py: Permission denied

**Comment by Fi156** [comment]
try:
home/gis/Pictures# `python ../OpenDroneMap/run.py`

**Comment by Bavar2142** [comment]
~/Pictures$ python ../OpenDroneMap/run.py
Traceback (most recent call last):
  File "../OpenDroneMap/run.py", line 8, in <module>
    import ecto
  File "/home/gis/OpenDroneMap/SuperBuild/install/lib/python2.7/dist-packages/ecto/**init**.py", line 30, in <module>
    from ecto.ecto_main import _cell_base, _cell_cpp, __getitem_list__, **getitem_slice**, **getitem_str**, **getitem_tuple**, lookup
ImportError: libecto.so.0.6: cannot open shared object file: No such file or directory

is what i get. Does that help?

**Comment by Bavar2142** [comment]
I have the images themselves within a folder called images in the Pictures folder.

**Comment by Bavar2142** [comment]
This is what I get when I try to run it in the images folder:

/Pictures/images$ python ../OpenDroneMap/run.sh
python: can't open file '../OpenDroneMap/run.sh': [Errno 2] No such file or directory

**Comment by Bavar2142** [comment]
I am currently running a clean install of Ubuntu 16.04 if that helps.

**Comment by dakotabenjamin** [comment]
If I understand correctly, your ODM install is here: `/home/gis/OpenDroneMap`

If that is the case, then it would be easier to `cd /home/gis/OpenDroneMap` then 

```
./run.sh --project-path /home/gis/Pictures`
```

**Comment by Bavar2142** [comment]
Bingo. Thanks for all the help and patience.

**Comment by dakotabenjamin** [comment]
@Bavar2142 it looks like the problem was that you have to call run.sh from within the ODM directory, that's all.
