### ISSUE TITLE
Bad result when changing default resize-to parameter

### ISSUE THREAD

**Issue by rmallermartins** [OpenDroneMap/ODM#329]
I'm having an issue with v0.1 when using bigger resize-to parameter then the default value. 

Result with the default value:
![ortho2400](https://cloud.githubusercontent.com/assets/2859673/16467420/977955a6-3e1d-11e6-9e12-c61105b1a01d.png)

Result with resize-to equals 3000:
![ortho3000](https://cloud.githubusercontent.com/assets/2859673/16467449/c360bbe6-3e1d-11e6-8777-8d0c26702116.png)

Both are taking +- 30min to process

**Comment by dakotabenjamin** [comment]
OpenSfM tries to create a single reconstruction, but sometimes needs to make multiple, and pmvs will only take the largest reconstruction. See this issue for more technical explanation: https://github.com/OpenDroneMap/OpenDroneMap/issues/186

**Comment by smathermather** [comment]
I don't know if this is the issue, or it's a matter of tweaking the OpenSfM/PMVS parameters to increase the match number. Any thoughts @paulinus?

**Comment by dakotabenjamin** [comment]
Try increasing `--min-num-features` to increase image matches.

**Comment by dakotabenjamin** [comment]
This issue is outdated and will be closed. Please open a new thread in http://community.opendronemap.org and reference this issue if you would like to continue the conversation.
