### ISSUE TITLE
Error 32512 During ODM Mesh file writing

### ISSUE THREAD

**Issue by Bavar2142** [OpenDroneMap/ODM#330]
[ERROR]   quitting cause: 
    /home/gis/OpenDroneMap/build/bin/odm_meshing -inputFile /home/gis/Pictures/pmvs/recon0/models/option-0000.ply -outputFile /home/gis/Pictures/odm_meshing/odm_mesh.ply -logFile /home/gis/Pictures/odm_meshing/odm_meshing_log.txt -maxVertexCount 100000 -octreeDepth 9 -samplesPerNode 1.0 -solverDivide 9
returned with code 32512.

Above error occurred during mesh generation of Ubuntu 16.04. I5 quad core, 4 gigs of ram and ssd.

**Comment by dakotabenjamin** [comment]
What's in this: /home/gis/Pictures/odm_meshing/odm_meshing_log.txt

**Comment by Bavar2142** [comment]
Ill run it again and get back to you

**Comment by Bavar2142** [comment]
Its also saying could not find ccdwidth file.

**Comment by jpmaniac** [comment]
I'm having the exact same issue on the dev branch... have you found out what caused it or a work around? Also, my "log file" for odm_meshing... my entire odm_meshing folder is empty
