### ISSUE TITLE
[BUG] odm_georeferencing when some photos have lat-long set to 0

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#331]
While possibly an uncommon problem that one or two photos have corrupted or failed to set their geotags properly, this has occurred at least once to me, and was recently brought up by another user in the email list. Sometimes when a camera first turns on, if it has internal GPS capabilities (the Canon PowerShot S100 for example does this) then the first few photos may not have correct GPS coordinates. 

In any case, the result of this problem is that the georeferencing step will create distorted objects which will in turn lead to improperly scaled orthophotos. 

I found that deleting those problem photos fixed the problem. It would be better for the software to throw a warning and attempt to fix the problem either by estimating the camera coordinates by the reconstruction or not using those photos.

**Comment by smathermather** [comment]
@paulinus -- we should be sure to address these problem cases correctly in the updated georeferencing approach.
