### ISSUE TITLE
Bash Configure taking too much time. Can some one provide sandbox for VirtualBOX.

### ISSUE THREAD

**Issue by Sharathmk99** [OpenDroneMap/ODM#345]
Hi All,

I'm trying to install ODM using vagrant.
bash configure.sh is taking too much time around 1 day, my computer will be not work.
Laptop configuration is: 8GB Ram, 4Core machine.

Please some one help me to get sanbox image for VirtualBox, where all the things have been installed and ready to use.

Thanks
Sharath

**Comment by dakotabenjamin** [comment]
Have you tried Docker? It may work better for you.

**Comment by Sharathmk99** [comment]
Yes I tried Docker, but I'm getting different error. So please help me to
get sandbox..

**Comment by dakotabenjamin** [comment]
This issue is outdated and will be closed. Please open a new thread in http://community.opendronemap.org and reference this issue if you would like to continue the conversation.
