### ISSUE TITLE
when attempting to run open drone map: Permission Denied

### ISSUE THREAD

**Issue by Bavar2142** [OpenDroneMap/ODM#365]
When I attempt to run open drone map in a new install it says permission is denied even when I have sudo access.

**Comment by Bavar2142** [comment]
Does anyone have any ideas?

**Comment by v4ven27** [comment]
Can you provide more information about your ODM installation?

**Comment by Bavar2142** [comment]
Its on 16.04 i believe running via a vm. Does that help?

**Comment by dakotabenjamin** [comment]
Does your user have sudo privileges?

**Comment by Bavar2142** [comment]
Ill give that a go and let you know if it works or not

**Comment by Bavar2142** [comment]
Sadly I get the same error.

**Comment by dakotabenjamin** [comment]
Can you post screenshots?

**Comment by Bavar2142** [comment]
here we are
![screenshot from 2016-09-15 09-36-15](https://cloud.githubusercontent.com/assets/20199894/18533665/02400e4c-7b28-11e6-819f-408b2ffe3742.png)

**Comment by v4ven27** [comment]
Have you tried running this command ? :
`chmod +x run.py`

**Comment by Bavar2142** [comment]
Ill try that now.

**Comment by Bavar2142** [comment]
chmod cannot access 'run.py': no such file or directory.

**Comment by v4ven27** [comment]
You should run the above command in the OpenDroneMap directory, the one containing run.py.

**Comment by Bavar2142** [comment]
Ok ive done that. What do i do next?

**Comment by Bavar2142** [comment]
This is the result I get when trying to run after that command.

![screenshot from 2016-09-15 10-15-53](https://cloud.githubusercontent.com/assets/20199894/18534352/721301c0-7b2d-11e6-8635-4cf81cee5e3c.png)

**Comment by dakotabenjamin** [comment]
Make sure you are following the instructions in the README. If you run into errors, document exactly what part of the instructions you were on, what command you ran, and what errors appeared, with screenshots if possible. I'm working on improving the documentation and would like to know where the instructions are confusing, lacking, or misleading.

**Comment by Bavar2142** [comment]
So far my procedure has just been the renanme command then ../OpenDroneMap/run.py. Will attempt readme.

**Comment by Bavar2142** [comment]
python run.py --project-path /path/to/project

using the wiki I found this command.

I take it the command should be  "python run.py --Pictures/images"?

**Comment by smathermather** [comment]
Hi @Bavar2142, more like:
`python run.py --project-path ~/Pictures/images`

**Comment by Bavar2142** [comment]
![screenshot from 2016-09-19 08-57-27](https://cloud.githubusercontent.com/assets/20199894/18619717/2946d79c-7e47-11e6-9bab-28266c22a736.png)

Like this? @smathermather

**Comment by Bavar2142** [comment]
Ignore that second command.

**Comment by Bavar2142** [comment]
If we cant solve this issue ill revert back to 15.10 or .04 as I dont think i have had issues with either of those two versions.

**Comment by dakotabenjamin** [comment]
I don't think this is an issue with your operating system. Actually @smathermather may have given you a misleading command call. What does the file tree look like starting at `~/Pictures`?

**Comment by Bavar2142** [comment]
Do you mean above or below? Below its just the images folder itself. Above its just home/gis/Pictures/images

**Comment by Bavar2142** [comment]
Thanks for the help everyone. Ill revert back to 15.04 for now.

**Comment by dakotabenjamin** [comment]
It looks like you don't have a project folder setup. You will want to create a project folder as follows: Let's say you flew a site in Brooklyn, NY. I would recommend setting up a directory structure like this: `~Pictures/ODMProjects/Brooklyn/` then place the images in an a subdirectory of ./Brooklyn. It will look like this:

```
~
|-- Pictures
    |-- ODMProjects
        |-- Brooklyn
            |-- images
                |-- IMG_0001.JPG
        |-- Waterbury
        |-- . . . 
```

Then you will call ODM as such:

```
python run.py --project-path ~/Pictures/ODMProjects/Brooklyn
```

**Comment by Bavar2142** [comment]
Upon attempting that line of code this was the result.
odm@odm-VirtualBox:~$ python run.py --project-path ~/Pictures/ODMProjects/Example/images
python: can't open file 'run.py': [Errno 2] No such file or directory

**Comment by Bavar2142** [comment]
I take it I run that straight into the terminal without cd'ing anywhere?

**Comment by dakotabenjamin** [comment]
Make sure you are referencing run.py where it is.

**Comment by Bavar2142** [comment]
The run.py is in the ODM folder. Does that change the code I typed in above?

**Comment by dakotabenjamin** [comment]
Yes, if you type `python run.py` it looks in the current directory (in your case above, `~` or `/home/odm/`). You either need to `cd` into the ODM folder or specifically reference run.py (~/ODM/run.py) or else python won't know where to look.

**Comment by Bavar2142** [comment]
Hey @dakotabenjamin thanks for the help so far. This is what I get when I run python run.py from the ODM folder.

odm@odm-VirtualBox:~/OpenDroneMap$ python run.py
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    import ecto
  File "/home/odm/OpenDroneMap/SuperBuild/install/lib/python2.7/dist-packages/ecto/**init**.py", line 30, in <module>
    from ecto.ecto_main import _cell_base, _cell_cpp, __getitem_list__, **getitem_slice**, **getitem_str**, **getitem_tuple**, lookup
ImportError: libecto.so.0.6: cannot open shared object file: No such file or directory

**Comment by dakotabenjamin** [comment]
Check that you set your environment variables correctly: https://github.com/OpenDroneMap/OpenDroneMap#steps-to-get-opendronemap-running

**Comment by dakotabenjamin** [comment]
Or trade `python run.py` with `./run.sh` which sets them for you.

**Comment by Bavar2142** [comment]
![screenshot from 2016-10-04 08-42-27](https://cloud.githubusercontent.com/assets/20199894/19055187/8194cb52-8a0e-11e6-9139-ba8ed1a70ed0.png)

is what I get.

**Comment by dakotabenjamin** [comment]
What i mean is do this:
odm@odm-VirtualBox:~$ ./run.sh --project-path ~/Pictures/ODMProjects/Example/images

**Comment by Bavar2142** [comment]
I run that line of code both outside the odm directory "no such file" and within "you must place your files in an image directory". Any idea as to what im doing wrong?

**Comment by dakotabenjamin** [comment]
Where are the images again?

**Comment by Bavar2142** [comment]
in an images folder within the pictures folder.

**Comment by dakotabenjamin** [comment]
from within the odm directory: `./run.sh --project-path ~/Pictures/`

I think this is helping me realize that the way we ask users to set up their mapping projects is confusing and should be changed for a better user experience.

**Comment by Bavar2142** [comment]
I'd have to agree with you there. From an end users perspective something like node ODM or Web ODM is preferred as its basically "click and drag the pictures click go and wait" and the fewer stages something has the fewer chances users have to make a mistake. Im rather excited to be able to get my hands on web ODM once it starts kicking.

Perhaps I should clarify the location of the images directory. It is within the pictures folder of the home directory.

**Comment by dakotabenjamin** [comment]
You should make your folders look like https://github.com/OpenDroneMap/OpenDroneMap/issues/365#issuecomment-249680835
