### ISSUE TITLE
Handling of photo exposure differences in orthophoto

### ISSUE THREAD

**Issue by rion-saeon** [OpenDroneMap/ODM#366]
Hi all,

is/are there parameters to set that will blend photo exposure differences better in ODM orthophoto creation (see image below)?

It is important to eliminate such anomalies as it conflicts with accurate habitat/land cover classification in a GIS.

![capture](https://cloud.githubusercontent.com/assets/13643064/18003408/9ec3fbb6-6b8d-11e6-850e-58e1d280b6de.JPG)

**Comment by dakotabenjamin** [comment]
MVSTexturing has been introduced to the dev branch.  

It handles seam leveling, photo consistency, and color correction. Check it out and see if that works for you.

**Comment by rion-saeon** [comment]
@dakotabenjamin , I suppose the `bash configure.sh` will update the dev branch from the ODM directory to see the effects of the updated branch?

**Comment by rion-saeon** [comment]
I did the above and followed dev branch install instructions but, seams and colour correction didn't seem to improve?:

DJI P3A
80% overlap
60% sidelap
50 mAGL

![screenshot from 2016-09-13 16 49 21](https://cloud.githubusercontent.com/assets/13643064/18478647/4a393572-79d2-11e6-8f01-6f61bcdb606e.png)

**Comment by dakotabenjamin** [comment]
Odd. Can you give some more details about your upgrade process?

**Comment by rion-saeon** [comment]
I added the 3 export lines to the ~/.bashrc and then performed bash
configure .sh from ODM folder. Should I reclone the ODM GitHub repository?

Regards,
_Rion Lerm (jnr.)_
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON http://www.saeon.ac.za/saeon-background

**Comment by dakotabenjamin** [comment]
Did you run `git checkout dev` first?

**Comment by rionlerm** [comment]
No I didn't. Sorry but, before *bash configure.sh*?

Regards,
*Rion Lerm (jnr.)*
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON <http://www.saeon.ac.za/saeon-background>

**Comment by rionlerm** [comment]
[image: Inline images 1]

Regards,
*Rion Lerm (jnr.)*
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON <http://www.saeon.ac.za/saeon-background>

**Comment by dakotabenjamin** [comment]
Yes, so:

```
git checkout dev
bash configure.sh
```

You don't need to edit the .bashrc file again though.

**Comment by rionlerm** [comment]
Did you see my screenshot?

Regards,
*Rion Lerm (jnr.)*
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON <http://www.saeon.ac.za/saeon-background>

**Comment by dakotabenjamin** [comment]
No, you have to post it on GitHub directly. It won't work over email for some reason.

**Comment by rion-saeon** [comment]
![screenshot from 2016-09-14 16 28 40](https://cloud.githubusercontent.com/assets/13643064/18516212/5516af12-7a98-11e6-805f-29b86fdd0b64.png)

**Comment by dakotabenjamin** [comment]
Is that directory a git repository?

**Comment by rion-saeon** [comment]
The ODM folder where ODM was installed to and used to run from.

Regards,
_Rion Lerm (jnr.)_
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON http://www.saeon.ac.za/saeon-background

**Comment by dakotabenjamin** [comment]
If it's not a git repo then I assume you downloaded a zip file to install ODM. You can either 
(a) clone the repo and then run `git checkout dev` to checkout the dev branch, or
(b) download the dev zip: https://github.com/OpenDroneMap/OpenDroneMap/archive/dev.zip

**Comment by rion-saeon** [comment]
Maybe I should reinstall everything?

Regards,
_Rion Lerm (jnr.)_
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON http://www.saeon.ac.za/saeon-background

**Comment by rion-saeon** [comment]
Thanks!

Regards,
_Rion Lerm (jnr.)_
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON http://www.saeon.ac.za/saeon-background

**Comment by Bavar2142** [comment]
@dakotabenjamin 
How would I go about updating to the dev branch? I have been having that same issue with some of our latest mosaics. Ive used that checkout dev line of code after having cd to the directory and it spat out

"branch was set up to track remote branch dev from origin. Switched to a new branch 'dev'."

**Comment by dakotabenjamin** [comment]
I would recommend reading up on how git works. It's a really useful tool but can take some time to understand. Basically once you switch to the dev branch (which you did sucessfully) you need to reinstall using the instructions from the dev branch's [README](https://github.com/OpenDroneMap/OpenDroneMap/blob/dev/README.md). Then you can run normally.

**Comment by rion-saeon** [comment]
Cool,

busy with that. Thanks.

Regards,
_Rion Lerm (jnr.)_
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON http://www.saeon.ac.za/saeon-background

**Comment by rion-saeon** [comment]
Huge improvement in dev branch. Well done to all:

**Comment by rion-saeon** [comment]
Well done to all with dev branch thus far. The result looks much better!

![screenshot from 2016-09-20 14 27 53](https://cloud.githubusercontent.com/assets/13643064/18670113/8d18995c-7f3e-11e6-8ecb-c0b8d1c2c9ec.png)

**Comment by dakotabenjamin** [comment]
That does look good!
