### ISSUE TITLE
provisos known ccd definition of  Panasonic DMC-GH4 is gone

### ISSUE THREAD

**Issue by wolkstein** [OpenDroneMap/ODM#368]
where are all the definitions of known camera ccd parameters. i just update odm and now the gh4 ccd definition which was provisos configured in ccd_defs.json (Line 235 of ccd_defs.json: "Panasonic DMC-GH4": 17.3,) will ignored.

**Comment by dakotabenjamin** [comment]
ccd_defs has bee nremoved in favor of opensfm's more complete sensors dataset.

Found [here](https://github.com/mapillary/OpenSfM/blob/master/opensfm/data/sensor_data.json) and in your local build SuperBuild/opensfm/opensfm/data/sensor_data.json
