### ISSUE TITLE
Georeferenced mesh coordinate frame

### ISSUE THREAD

**Issue by v4ven27** [OpenDroneMap/ODM#370]
Hello ODMers, 

I've used GPS (lat, lon, alt) information in the EXIF metadata of images to produce geo-referenced meshes.
[Here's](https://github.com/OpenDroneMap/OpenDroneMap/files/457811/odm_textured_model_geo.obj.zip) a zip file containing the OBJ file of the georeferenced model.

I'd appreciate help answering the following question: What frame of reference do the vertices of the georeferenced mesh belong to? 

Thanks!

**Comment by v4ven27** [comment]
Figured it out: They are represented in local ENU coordinate frame with the origin coordinates (in UTM) specified in `odm_georeferencing/odm_georeferencing_model_geo.txt`

**Comment by smathermather** [comment]
:+1:
