### ISSUE TITLE
packages Docker image?

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#375]
Just noticed that the Dockerfile for the `dev` branch contains:

```
#Pull in previously built packages image with lots of libraries.
FROM packages
```

Where is packages defined?

**Comment by dakotabenjamin** [comment]
Here: https://github.com/OpenDroneMap/OpenDroneMap/blob/dev/packages.Dockerfile

**Comment by pierotofy** [comment]
I see, thanks!
