### ISSUE TITLE
Boolean command line parameters defined as strings?

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#377]
I was wondering if there was any particular reason for declaring boolean parameters as strings:

https://github.com/OpenDroneMap/OpenDroneMap/blob/dev/opendm/config.py

For example:

```
parser.add_argument('--mvs_texturing-skipGeometricVisibilityTest',
                        metavar='<string>',
                        default="false",
                        help=('Skip geometric visibility test. Default:  %(default)s'))
```

Shouldn't this be:

```
parser.add_argument('--mvs_texturing-skipGeometricVisibilityTest',
                        action='store_true',
                        default=False,
                        help='Skip geometric visibility test. Default:  %(default)s'))
```

?

It makes it more difficult for an external parser to detect the command line options. I could work on it and create a PR, just wanted to know if there was a reason for using strings vs booleans before proceeding.

Thanks!

**Comment by dakotabenjamin** [comment]
Thanks!
