### ISSUE TITLE
DSM artefacts

### ISSUE THREAD

**Issue by rion-saeon** [OpenDroneMap/ODM#380]
Hi,

I don't know whether it's QGIS but, when creating a DSM with las2dem (LAStools: https://rapidlasso.com/lastools/) and using ODM's ply.las products the following artefacts can be seen. This issues has been noticed before but, doesn't show on all generated DSMs:

![capture](https://cloud.githubusercontent.com/assets/13643064/18671186/6709637c-7f43-11e6-9d10-66f2ca9ca993.JPG)

Any ideas?

(PS apart from the artefacts the result is impressive)

**Comment by dakotabenjamin** [comment]
I've not used las2dem, can you explain the artefacts to me? Are they the little blue lines?

**Comment by rion-saeon** [comment]
Correct, small blue lines. I've been using LAStools constantly. The only
thing that changed was ODM.

Regards,
_Rion Lerm (jnr.)_
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON http://www.saeon.ac.za/saeon-background

**Comment by dakotabenjamin** [comment]
I tried this: `las2dem -i odm_georeferenced_model.ply.las -o dem1.tif`

and got: 
![las2dem-ex](https://cloud.githubusercontent.com/assets/1847818/18672042/714607e8-7f14-11e6-8f5f-e00f6b7a5062.png)

**Comment by rion-saeon** [comment]
Thanks,

something quickly off topic...it seems your step size remained at 1.0. Changing to 0.01 produces a much
finer DSM.

Any way, I don't find the artefact problem with all DSMs but, will try your
command line paras'.

Regards,
_Rion Lerm (jnr.)_
(+27) 76 913 8381 (Cell)
(+27) 13 735 3536 (Office)
Ndlovu Node
Phalaborwa Gate, Kruger National Park
South African Environmental Observation Network (SAEON)

Click here to learn about SAEON http://www.saeon.ac.za/saeon-background

**Comment by smathermather** [comment]
@rionlerm -- are you using a licensed lastools? If not, it will introduce regular artifacts like this.

**Comment by rion-saeon** [comment]
Hello @smathermather ,

I don't use a licensed version but, these artefacts are NOT regular. Most of the DSMs I generate with LAStools show none.

**Comment by smathermather** [comment]
I don't think it does it every time... . You might try doing it in https://PDAL.io and see if you get the same artifacts.

**Comment by dakotabenjamin** [comment]
This issue is outdated and will be closed. Please open a new thread in http://community.opendronemap.org and reference this issue if you would like to continue the conversation.
