### ISSUE TITLE
Set of images produces "collage" like distorted orthophoto

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#384]
Input images: https://masseranolabs.com/images.zip (taken at 50 meters AGL, 80% overlap). Trees in the area likely lead to poor features detection.
Camera: DJI Phantom 3 (ccd: 6.16)

Processed using dev branch, default options.

Resulting orthophoto: 

![orthophoto_1](https://files.gitter.im/OpenDroneMap/OpenDroneMap/xKMB/odm_orthophoto.png)

Changing option "--matcher-distance" to 50 yields:

![orthophoto_2](https://files.gitter.im/OpenDroneMap/OpenDroneMap/Oi2c/odm_orthophoto.png)

GPS EXIF data looks correct:

![exit_data](https://files.gitter.im/OpenDroneMap/OpenDroneMap/B7Bp/blob)

@paulinus

**Comment by dakotabenjamin** [comment]
This looks like an issue with OpenSfM. Look at the sparse cloud here: ![croppercapture 4](https://cloud.githubusercontent.com/assets/1847818/18847881/eecb9220-83f9-11e6-8078-06ab41d873bb.Gif)

**Comment by dakotabenjamin** [comment]
For the sake of transparency, it was suggested on the [gitter](https://gitter.im/OpenDroneMap/OpenDroneMap) that this may be a camera calibration issue. 

I've produced a kludge-y calibration tool [here](https://github.com/dakotabenjamin/CameraCalibration) that produces calibrated photos based on distortion parameters from checkerboard reference photos.

**Comment by pierotofy** [comment]
I'll try to run the tool and retry processing. I'll report results here. Thanks @dakotabenjamin

**Comment by pierotofy** [comment]
I ran the CameraDistortion tool using the calibration images for DJI Phantom 3, and I got this:

![odm_orthophoto](https://cloud.githubusercontent.com/assets/1951843/18969560/a17671f2-865b-11e6-8198-7de057c39290.png)

Point cloud (shows part of one of the houses, which makes sense, since there are more features there).

![model](https://cloud.githubusercontent.com/assets/1951843/18969694/29492fca-865c-11e6-9807-e7ce33f39210.gif)

**Comment by dakotabenjamin** [comment]
That's disappointing. It looks like there are a few problems going on here
1. You have a partial reconstruction. This _may_ be solved by increasing the number of features extracted or, oddly enough, decreasing the resize value. 
2. Since the point colors in the point cloud are fine I'm wondering if it's a texturing bug. 

Quick question, what time of day were these photos taken? It almost looks like there are lots of shadows in the point colors of the point cloud.

**Comment by pierotofy** [comment]
On 1. original images were 4000x3000 but I set a resize parameter of 1000.

Images were taken around 5:25pm, so just before twilight. Not ideal light conditions I realize. I would expect some distortion, but the output is really messed up.

**Comment by dakotabenjamin** [comment]
I'm at a loss at this point. I'm hoping @paulinus can provide any insight, although if its a texturing problem, @smathermather we should ping spotscale.

**Comment by pierotofy** [comment]
Result of processing with DroneDeploy: http://drdp.ly/2XlFAs

Some distortion near trees, but main features are reconstructed.

**Comment by smathermather** [comment]
Resize parameter of 1000 is pretty low, and if you didn't change your matching parameters, this could result in a smaller point cloud. @pierotofy: have you run this with undistorted images and with defaults?

**Comment by pierotofy** [comment]
@smathermather just tried with all defaults parameters and undistorted images.

![odm_orthophoto](https://cloud.githubusercontent.com/assets/1951843/19005938/3a93a31c-872b-11e6-8a89-f278e29c1be9.png)

**Comment by smathermather** [comment]
@pierotofy -- what does your textured mesh look like?

**Comment by pierotofy** [comment]
Here it is (default parameters):

![image](https://cloud.githubusercontent.com/assets/1951843/19222009/e77a2702-8e1c-11e6-9105-1ef3b1d0c002.png)

Doesn't look too good.

**Comment by smathermather** [comment]
Hard to tell for sure-- does the textured mesh look fine but the orthophoto is problematic?

**Comment by pierotofy** [comment]
Well, the orthophoto is definitely problematic, the textured mesh is not complete, it displays only a very small area (like, 4 tiles instead of  the 200+ from the dataset) and elevation is also not properly represented (look at the warp in the image above).

Images are linked at the top of this discussion for anyone that wants to reproduce this problem.

**Comment by dakotabenjamin** [comment]
Hey @xialang2012 I ran your images. Can you tell me what parameters you used?

**Comment by dakotabenjamin** [comment]
@pierotofy have you tried a resize of 1200 or 1500? It looks like on #392 it's being linked back to a too-small resizing.

**Comment by pierotofy** [comment]
I've tried using 2400 (the default), but I still get malformed output.

I wish I had more time to dig into the code myself to troubleshoot it, but I'm busy with WebODM.

**Comment by xialang2012** [comment]
@pierotofy ,I have test the dataset that you provide with the default parameter, and the result is reasonable

![qq 20161021121716](https://cloud.githubusercontent.com/assets/14291651/19586535/51aa6028-9788-11e6-82d6-2fadc643ecb1.jpg)

With --rezise--to 1000
![qq 20161021155512](https://cloud.githubusercontent.com/assets/14291651/19590883/cc52c9fa-97a6-11e6-9c8d-4da2851ca969.jpg)

**Comment by pierotofy** [comment]
O_o

Is it be possible that a computer with low RAM is the cause? I ran my dataset with a VM that had only 3 GB of RAM.

**Comment by xialang2012** [comment]
Youd better to update to the lastly version of the dev branch and try it again.
I think it is none of the business about the RAM size.

For my experience the weird ortho image would be product when number of the input images is small, such as less than 8 and with the resize to 1000(about). Besides, I found only when we used the mvs-texting to texture the mesh, it will occurred.

**Comment by pierotofy** [comment]
Ok I can confirm that using the latest code in the dev branch seems to work. I got this results (resized the images to 1800, default parameters).

![odm_orthophoto large](https://cloud.githubusercontent.com/assets/1951843/19616111/25c96750-97d9-11e6-98d4-3bb147fc74cb.png)

![image](https://cloud.githubusercontent.com/assets/1951843/19616131/8343ea04-97d9-11e6-9a6a-15cb28ca7aa2.png)

This can probably be closed! Thanks everyone for the help.

**Comment by JLMarcelino** [comment]
Hi! Sorry for bothering here, but I have the exact same problem (2024!). Can  you explain how can I update to the lastly version of the dev branch?

**Comment by smathermather** [comment]
This was a walk through memory lane to see this issue. Hi @pierotofy -- did you ever figure out how to improve your results from OpenDroneMap? :smile: 

@JLMarcelino -- please come over to community.opendronemap.org where we provide support and troubleshooting. We try to keep the repositories focused on bug reports and improvements, but we'll get you sorted over on the community forum.
