### ISSUE TITLE
Odd orthophoto but good point cloud

### ISSUE THREAD

**Issue by asierrl** [OpenDroneMap/ODM#398]
I'm experiencing a problem similar to that of #392, although the origin doesn't seem the same, as I have no gps info in the exif and rather I run ODM with a GCP file.
When running with default parameters I run out of memory, and hence I tried again with resize-image=1200. My orthophoto looks like this:
![ortofoto_nueva_camino](https://cloud.githubusercontent.com/assets/8058052/19400758/f5a121a2-9257-11e6-86ac-bcccd7530a5b.png)

But, my point cloud looks nice:
![vistanubepuntos2016-10-14_ 21_33_00](https://cloud.githubusercontent.com/assets/8058052/19400770/097e14f0-9258-11e6-904a-7054bab17228.png)

Odd enough...I run this same set of images with resize=1200 one year ago (different computer, I was trying to check now that everything installed correctly) and got good results:

![ortofoto_anterior_camino](https://cloud.githubusercontent.com/assets/8058052/19400807/31a6e6b4-9258-11e6-942b-d7699491686f.png)

Both orthos have been copied from QGIS, with the same view extent. So, appart from the interative mosaic-like patter, there is also a size or georeferencing  problem.
I used exactly the same files as one year before (including the gcp file).
By the way...I also read #384, but it doesn't seem the same problem to me, as in that case the point cloud was not either good.
Any hint?
Thanks a lot!!
Asier

**Comment by dakotabenjamin** [comment]
@asierrl recently I pushed some changes in #386 which changed which images to pull from when georeferencing. Do you think this could be the cause?

**Comment by asierrl** [comment]
Hi, Benjamin....Honestly...I don't have a clue if that might be the
problem. Sorry, I'm too ignorant on these issues. But I am glad to try to
guess.
I installed ODM last week, so that if you did that change 18 days ago, the
change should be already within my ODM version. But I saw you did this
change in OpenDroneMap:dev. I read several times that ODM can be run from
different branches...and dev is one of them. Perhaps I could try that, but
I don't know how to do it. Currently I go into the OpenDroneMap folder and
run the "python run.py..." command. How could I do to run it on dev?
Thanks!!
Asier

2016-10-17 14:43 GMT+02:00 Dakota Benjamin notifications@github.com:

**Comment by dakotabenjamin** [comment]
```
git checkout dev
bash configure.sh
python run.py ...
```

should do

**Comment by dakotabenjamin** [comment]
That being said, I am now unconvinced of my original theory.

**Comment by asierrl** [comment]
Mmm...yeah, I guess it was a memory issue. In fact, I did as you suggested, running it in dev branch and run out of memory. I already did a resize-to 1200. I don't know if I can go lower, but I probably will give it a try and let you know.
Thanks for your support and help (and for the software :-) )
Best regards,
Asier

**Comment by asierrl** [comment]
Ah...and I forgot... I always get a warning that ccd width was not found for my camera. Do you think that could be the reason for the odd orthophoto? I would say no, but for no good reason.
I made a pull request to include it in sensor_data.json. It was included and it worked (same data I'm trying now). I have checked and in fact the camera model is included, but it says Panasonic Lumix DMC-GH4. Instead exif info refers to it as panasonic dmc-gh4. Should I include it as a new camera in sensor_data.json? should I forced a ccwidth within the command? or is it a way for ODM to recognize it as the same camera?
Best regards, 
Asier

**Comment by xialang2012** [comment]
The Orthophoto module has some problems to co-work with mvs-texturing.

**Comment by asierrl** [comment]
So, any idea on how to avoid this effect? or about its relationship with
the amount of memory?

2016-10-24 11:26 GMT+02:00 xialang2012 notifications@github.com:

**Comment by dakotabenjamin** [comment]
How much memory do you have?

**Comment by asierrl** [comment]
I got last year's good result on my desktop, with i7, 32Gb RAM and a 3Gb
graphic card.
Now I am running it on my laptop, with a Intel B940 processor, 8 Gb RAM and
an integrated Intel HD graphic card (1696 Mb graphic memory available, 64
Mb dedicated to video, 1632 Mb shared with the system).

**Comment by asierrl** [comment]
8 Gb RAM

**Comment by dakotabenjamin** [comment]
This issue is outdated and will be closed. Please open a new thread in http://community.opendronemap.org and reference this issue if you would like to continue the conversation.
