### ISSUE TITLE
DJI Phantom 4 Images

### ISSUE THREAD

**Issue by hugowikstrom** [OpenDroneMap/ODM#402]
Hello

I really like ODM, but I have problems to process the images from my DJI Phantom 4. It seems to be missing some information in the images .. Is there any way to prepare the images so that they work in ODM?

Anyone have an idea?

**Comment by pierotofy** [comment]
What information seems to be missing? Could you copy the output of ODM?

**Comment by hugowikstrom** [comment]
hugo@Asus-K72Dr:~/odm/OpenDroneMap$ ./run.sh --project-path ../vartan/
[INFO]    Initializing OpenDroneMap app - Sat Oct 22 08:38:17  2016
[INFO]    Running ODM Load Dataset Cell
[DEBUG]   Loading dataset from: /home/hugo/odm/vartan/images
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0594.JPG | camera: dji fc330 | dimensions: 4000 x 3000 | focal: 3.61 | ccd: None
Premature end of JPEG file
Traceback (most recent call last):
  File "/home/hugo/odm/OpenDroneMap/run.py", line 38, in <module>
    plasm.execute(niter=1)
  File "/home/hugo/odm/OpenDroneMap/scripts/dataset.py", line 57, in process
    self.params.force_ccd)
  File "/home/hugo/odm/OpenDroneMap/opendm/types.py", line 32, in **init**
    self.parse_pyexiv2_values(self.path_file, force_focal, force_ccd)
  File "/home/hugo/odm/OpenDroneMap/opendm/types.py", line 77, in parse_pyexiv2_values
    self.width = img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by hugowikstrom** [comment]
I also test with option --force-ccd but it did not work.

**Comment by pierotofy** [comment]
I think the problem is `Premature end of JPEG file`, it has nothing to do with ccd. It looks like DJI_0594.JPG might be corrupted? Could you attach the file here?

**Comment by hugowikstrom** [comment]
![dji_0594](https://cloud.githubusercontent.com/assets/22952325/19620241/42431d4a-9879-11e6-8b59-846debcc0419.JPG)

**Comment by pierotofy** [comment]
Image looks fine; it might have to do with the way you built opendronemap. Did you build from the `dev` branch?

**Comment by pierotofy** [comment]
Processing for that image works fine here: http://nodeodm.masseranolabs.com/ (it runs the latest `dev` code).

**Comment by hugowikstrom** [comment]
You seem to be on track that the image is incorrect. I run a different set of images now and it seems to work better. I will return.

I compiled the entire ODM last weekend .. How do I install the dev version

**Comment by pierotofy** [comment]
```
git clone https://github.com/OpenDroneMap/OpenDroneMap.git
git checkout dev
```

Then follow the readme: https://github.com/OpenDroneMap/OpenDroneMap/tree/dev

**Comment by dakotabenjamin** [comment]
This issue is outdated and will be closed. Please open a new thread in http://community.opendronemap.org and reference this issue if you would like to continue the conversation.
