### ISSUE TITLE
reversed image

### ISSUE THREAD

**Issue by rcverheggen** [OpenDroneMap/ODM#403]
I ran a project through ODM and got an interesting result - the image was reversed.  I am not sure how accurate the georeferencing is, but i do know that ESRI's Drone2Map dropped it in the right place.  
Below is a side-by-side of a bing maps image (left) and the ODM image (right).
![river](https://cloud.githubusercontent.com/assets/22818559/19568237/63850078-96b6-11e6-8e9c-e2ffae73d6ec.png)

any thoughts or ideas on how to fix this?

I ran another image set through it yesterday, and it worked perfectly.
Thanks in advance

**Comment by sethfitz** [comment]
Are there other files in the source `images/` directory? (E.g. non-JPEGs)

**Comment by rcverheggen** [comment]
There are no other files in the images folder.

**Comment by xialang2012** [comment]
We need to reverse it? I also face the same problem about it.

**Comment by rcverheggen** [comment]
Any thoughts on this?  I can make the image folder available somewhere if you think that would help diagnose the issue.

**Comment by dakotabenjamin** [comment]
How do you have your photos georeferenced? If there's no gps data then the software won't know which way is up

**Comment by rcverheggen** [comment]
Well, I took the photos straight off the memory card from a phantom 3.  I have run other sets of photos from the same UAV in the same way through ODM and they come within a few feet (and not reversed).  The unit had GPS connectivity through both runs I have tried in ODM.

Also - I just looked at the coords.txt file and it indicates WGS84 UTM 16N

**Comment by piousgreek** [comment]
Sorry to dig up an older thread or commandeer it, but i am running into this issue as well.  The image is flipped.  I am using images that are geotagged in mission planner and i believe them to have accurate location data.  The coords.txt file which ODM generated indicates WGS84 UTM 11N which is accurate for my location in Fresno, California.

EDIT: the process i used to geotag the images did not yield accurate results.  as a result, my ODM results were problematic.  The geotags were corrected and everything is now working properly for me.

**Comment by dakotabenjamin** [comment]
This issue is outdated and will be closed. Please open a new thread in http://community.opendronemap.org and reference this issue if you would like to continue the conversation.
