### ISSUE TITLE
⌃C only takes effect after stages complete

### ISSUE THREAD

**Issue by sethfitz** [OpenDroneMap/ODM#405]
When hitting ⌃C to cancel a running job, it continues running until the active stage completes (rather than quitting immediately). I suspect that this is due to the use of `os.system()` in [`opendm.system.run`](https://github.com/OpenDroneMap/OpenDroneMap/blob/dev/opendm/system.py#L22) rather than the `subprocess` (or similar), which has improved handling of subprocesses.

**Comment by sethfitz** [comment]
(I'm also volunteering to fix this once I have time, so feel free to assign to me.)

**Comment by pierotofy** [comment]
+1 for this
