### ISSUE TITLE
Input photo coordinates are written as UTM

### ISSUE THREAD

**Issue by sethfitz** [OpenDroneMap/ODM#406]
In [`odm_georeferencing.py`](https://github.com/OpenDroneMap/OpenDroneMap/blob/dev/scripts/odm_georeferencing.py#L120-L121), input files have their coordinates rewritten as UTM within the EXIF data.

[IMO] input files shouldn't be touched during processing, particularly as the pipeline can only handle input files with Lng/Lat coordinates.

This is the root cause of #397, as I was re-processing imagery that had already been run through.

**Comment by sethfitz** [comment]
(Also volunteering to fix this one, though it's an easy removal, so if someone else gets to it first, that's cool ;-)

**Comment by dakotabenjamin** [comment]
iirc the input photos are the resized photos but i'll have to double-check

**Comment by dakotabenjamin** [comment]
This issue is outdated and will be closed. Please open a new thread in http://community.opendronemap.org and reference this issue if you would like to continue the conversation.
