### ISSUE TITLE
Remove white around the orthophoto

### ISSUE THREAD

**Issue by GCorbel** [OpenDroneMap/ODM#408]
Hi,

When I generate an Orthophoto, there is always an ugly border like you can see here : 
![capture du 2016-10-24 16 08 17](https://cloud.githubusercontent.com/assets/1296201/19662056/1b2dad6a-9a04-11e6-8481-d480b629d528.png) . Is it possible to generate a cleaner image ?

Thanks !

**Comment by elRubas** [comment]
in my experience, all the codes I had used give you in the result the border and if you don't needed you can removed manually in programs like meshlab

**Comment by Bavar2142** [comment]
@elRubas Is there a chance you could tell us how?

**Comment by GCorbel** [comment]
Thanks for anwser @elRubas I cannot use meshlab because I'm trying to automate a process. Any other idea ?

**Comment by elRubas** [comment]
@Bavar2142  here is a youtube tutorial video how you can do, Its more easy and fast see than explain

https://www.youtube.com/watch?v=m2nmeJj5Ij4

and the orthophoto

https://www.youtube.com/watch?v=yUcL2or24OI

@GCorbel  I really don't have idea how to give you automaticly a clean resut but if I see how to do it I will give you the info

**Comment by dakotabenjamin** [comment]
The white background should be transparent. Can you try opening the png in something like GIMP to see if it's not the software you are using?

**Comment by GCorbel** [comment]
I have the same result with GIMP.

2016-10-26 9:10 GMT-04:00 Dakota Benjamin notifications@github.com:

**Comment by GCorbel** [comment]
It works with the `convert` command of image magick. Here is an example `convert source.png -fuzz 1% -transparent white target.png`.
