### ISSUE TITLE
Help!, Where are located the routine and the result features matched?

### ISSUE THREAD

**Issue by elRubas** [OpenDroneMap/ODM#409]
Hi, I'm looking for where is the routine and the result of the matching feature. Because I want to create a sub routine who select random features matches of all the final features matched, before go to the next SfM step who computes the 3D sparse structure 

someone Knows where I can find this?

**Comment by dakotabenjamin** [comment]
Matching is performed in [OpenSfM](https://github.com/mapillary/OpenSfM). The matching code is found [here](https://github.com/mapillary/OpenSfM/blob/master/opensfm/matching.py).
