### ISSUE TITLE
 Package 'libvtk5-dev' has no installation candidate on bash configure

### ISSUE THREAD

**Issue by Bavar2142** [OpenDroneMap/ODM#410]
E: Package 'libvtk5-dev' has no installation candidate
ERROR: Error when Installing Dependencies Requisites

Hello all,
had to reinstall ubuntu on the vm so i had to redo the odm install for 16.10. I ran into the above error and tried to find it via synaptic package manager with no luck.
Does anyone have an idea?

**Comment by dakotabenjamin** [comment]
https://launchpad.net/ubuntu/yakkety/+source/vtk

It looks like no release yet. @smathermather

**Comment by Bavar2142** [comment]
Ah, that would explain it. I tried with libvtk6 with no luck either.

**Comment by smathermather** [comment]
Is this a blocking issue for 16.04 as well?

**Comment by sethfitz** [comment]
No. I've been running on 16.04 with no problems.

**Comment by dakotabenjamin** [comment]
No, it is only for 16.10. Should go away soon.

[http://sig.cmparks.net/cmp-ms-90x122.png]Dakota Benjamin
Geospatial Developer
clevelandmetroparks.comhttp://www.clemetparks.com/

http://www.clemetparks.com/

**Comment by Bavar2142** [comment]
@dakotabenjamin did you have an idea of when thatd be?

**Comment by dakotabenjamin** [comment]
No, we don't have any control over these dependencies. I'm assuming it won't be too long because this looks like a well-maintained package.

**Comment by dakotabenjamin** [comment]
https://answers.launchpad.net/ubuntu/+source/vtk/+question/403584

The package has been replaced. Reopening so that we can get this fixed

**Comment by Bavar2142** [comment]
Good to know its being looked at.

**Comment by jpmaniac** [comment]
Any luck on this? I'm on 16.10 and am unable to configure ODM still on the latest Release Candidate

**Comment by dakotabenjamin** [comment]
This problem is more complicated than I thought. We have some older code that vtk6 appears to break

**Comment by dakotabenjamin** [comment]
I don't know how much legacy code still exists in some of our modules, but it looks like updating from vtk5 to vtk6 breaks all of them. PMVS and odm_meshing most notably. I do not have the c++ skills to get dirty with the code to port it over, but I will put this on our priorities list. 

The best solution for now is to use [Docker to containerize ODM](https://github.com/OpenDroneMap/OpenDroneMap#build-and-run-using-docker).

**Comment by smathermather** [comment]
Should we get rid of PMVS? I realize that only solves half the problem, but at least it's a start.

Created an issue for PMVS: https://github.com/OpenDroneMap/OpenDroneMap/issues/442

**Comment by dakotabenjamin** [comment]
#659 is related.

**Comment by dakotabenjamin** [comment]
This issue is outdated and will be closed. Please open a new thread in http://community.opendronemap.org and reference this issue if you would like to continue the conversation.
