### ISSUE TITLE
how can i compile orthophoto module independently

### ISSUE THREAD

**Issue by assbben** [OpenDroneMap/ODM#415]
here are my command in dir modules/odm_orthophoto
mkdir build
cd build
cmake ..
make 
but it has some errors
`error: no matching function for call to ‘std::vector<std::vector<Eigen::Matrix<float, 2, 1>, Eigen::aligned_allocator<Eigen::Matrix<float, 2, 1> > > >::push_back(std::vector<Eigen::Matrix<float, 2, 1> >&)’`
`error: no matching function for call to ‘std::vector<std::vector<Eigen::Matrix<float, 2, 1>, Eigen::aligned_allocator<Eigen::Matrix<float, 2, 1> > > >::push_back(std::vector<Eigen::Matrix<float, 2, 1> >&)’`

therefore i used make -i to compile it
although it said `[100%] Built target odm_orthophoto` i cant found it

or there has another way to compile it

thanks

**Comment by bryanibit** [comment]
To be honest, I want to compile orthophoto module independly too.Recently I found that orthophoto is as a cell of ecto like other module. Specificlly, I still not understand the code of ODM. I think you could start to see the script/orthophoto.py and try to understand the orthophoto module.

**Comment by juvinski** [comment]
To solve this issue I had to use the Eigen 3.2.10, with this version, PCL 1.8.0 and VTK 7.1.1 - compiling and installing manually(downloading and compiling).
Btw, I' m using Ubuntu 17.04.

**Comment by dakotabenjamin** [comment]
I know this is old, but you can find the orthophoto module in `build/bin`
