### ISSUE TITLE
 bebop 2 fisheye images

### ISSUE THREAD

**Issue by frasanz** [OpenDroneMap/ODM#463]
I'm trying to use opendronamap with this bebop 2 imageset (180º eyefish images)

https://support.pix4d.com/hc/en-us/articles/209620783-Example-Datasets-Available-for-Download-Parrot-Bebop-2-House#gsc.tab=0

Using by default run.py without extra parameters, I have the typicall white walls, but also a very ugly model

https://skfb.ly/ZJWv

![image](https://cloud.githubusercontent.com/assets/456573/22402954/52589a4c-e609-11e6-91a3-e12858617698.png)

Not sure if it's a problem with the eyefish images or only I need to insert some extra parameters.

**Comment by frasanz** [comment]
Sorry...also, not sure what to insert into force-ccd

**Comment by dakotabenjamin** [comment]
These will be difficult if not impossible to reconstruct currently because of the fisheye and the images have horizon/sky in them. I don't know what it would take to get this to work like pix4d.

**Comment by frasanz** [comment]
Ok, thanks for your answer.

**Comment by hblanken** [comment]
Could we add this into an improvement suggestion/seeking help - onto the release roadmap? There are quite a few fisheye cameras which would be a good addition for ODM. Parrot fisheye + GPS exif images would make a great input addition for ODM.

**Comment by KommandorKeen** [comment]
My understanding of Bebop is the stabilisation is digital and therefore the distortion is dynamic not static.
But if you are capturing the whole image then use openCV to undistort the images (chessboard procedure) and then crop the image to more like a 90 degree view.  THEN guess suitable CCD and focal length values and input these into ODM using --forc-focal and --force-ccd.

**Comment by gmaclennan** [comment]
It would be great if ODM could support images from the Parrot Bebop 2, it is a great value drone that can collect good orthophotos with the Pix4D capture app.

**Comment by pierotofy** [comment]
Fish-eye cameras have been fully supported for a while now. Just use the `--camera-lens fisheye` option! :)
