### ISSUE TITLE
Northing and Easting values in CSV file don't appear correct

### ISSUE THREAD

**Issue by piousgreek** [OpenDroneMap/ODM#469]
I may be misinterpreting this file, but the CSV file generated does not appear to contain complete point data.  I believe that in the northing and easting columns that it only contains the values for the seconds (not the minutes or degrees). 

![image](https://cloud.githubusercontent.com/assets/25551690/22721281/8782bc4a-ed64-11e6-92e8-32bd9e967b5c.png)

The complet CSV is here:
https://www.dropbox.com/s/eu0xhzvejl24i03/odm_georeferenced_model.csv?dl=0

The geotagged source images can be found here:
https://www.dropbox.com/s/f1vvqos4l6cfxny/ShepherdDeWolf.zip?dl=0

The command I ran was:
python run.py --orthophoto-resolution 160.0 --force-focal 3.97 --pmvs-csize 1 --mesh-size 400000 --mesh-octree-depth 12 --project-path /Desktop/quickwork/geotagged

**Comment by smathermather** [comment]
That looks like UTM, not geographic (lat, lon).

**Comment by LucasMM86** [comment]
Yes, this file has UTM coordinates, not lat/lon. See https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system
In the file coords.txt you can find the zone (for example 19S).

**Comment by piousgreek** [comment]
Thank you all, i greatly appreciate the guidance and assistance.  Really cool work, steep learning curve at first.
