### ISSUE TITLE
Global configuration file

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#473]
There should be a configuration file (YAML) in the ODM directory that has the following:
- default project directory (where all the projects are stored)
- default parameters
- max processors to use
- output types (ply vs las)
- etc.

This would help users who have workflows, among other things.

**Comment by piousgreek** [comment]
yes, I was wondering where the default parameters are stored actually.  alternatively, one could place a config file within the project specific folder or in the images sub directory that would have project specific configuration parameters that would be loaded automatically when ODM is run and override the defaults.  

Or perhaps even have the ability to have multiple configurations stored as separate "profiles" with a specific configurations that can be selected as a command line parameter.

**Comment by dakotabenjamin** [comment]
Good idea. I'll keep that in mind.

**Comment by dakotabenjamin** [comment]
Merged as of #510
