### ISSUE TITLE
Do we need to resize images? 

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#478]
Opensfm does its own resizing IIRC and everything else can and should use the maximum resolution images. Project folders would be smaller if we skipped this.

**Comment by smathermather** [comment]
Sounds like we can drop resizing... .

**Comment by pierotofy** [comment]
If dropping resize does not increase significantly memory usage, then yes.

**Comment by dakotabenjamin** [comment]
I'll run some tests.

**Comment by smathermather** [comment]
I suppose this would depend on https://github.com/OpenDroneMap/OpenDroneMap/issues/442 (and removal altogether of PMVS).
