### ISSUE TITLE
question regarding the impact of including overlapped photos from different altitudes

### ISSUE THREAD

**Issue by piousgreek** [OpenDroneMap/ODM#479]
Perhaps this is not the proper venue for these questions, but:

1. How would the accuracy and maximum resolution of the generated orthophotos be affected if ODM were to be applied to a data set that contained images of the same survey flown at two different altitudes (example at 125' and at 400').

2. Can ODM handle mixed data sets of oblique and nadir photos? Do oblique photos need to be tagged or identified in some way with the angle?

3. if a ground control point file is specified, is the gps exif data in the photos ignored?

**Comment by dakotabenjamin** [comment]
1. I've not tried it personally but I suppose it would work. @smathermather may know better. 
2. This is ideal for more complex reconstructions- vegetation, buildings, and such. Just make sure you don't have photos with horizon on them. 
3. yes.

**Comment by smathermather** [comment]
Great questions all. Mixed altitudes is anticipated to produce better results than single altitude flights, although we haven't specifically tested this.

**Comment by pulquero** [comment]
I have had mixed results with mixed data sets and altitudes in the past. I kind of hoped that a high-level photo would help patch together a set of low-level photos, but it didn't seem to work like that. Just seemed to get more confused. This was all pre-the-new-opensfm-stuff, I have much higher hopes with opensfm, but haven't had time to push my big mixed data set through yet.

**Comment by smathermather** [comment]
@pulquero -- it's definitely a whole new project with the addition of OpenSfM. If you are willing / able to share test datasets, we'll be happy to help test.

**Comment by dakotabenjamin** [comment]
Closing, please reopen if more questions come up :smile:
