### ISSUE TITLE
Tone Mapping parameter missing for mvs_texturing

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#492]
While digging through mvs_texturing's code, I noticed that we currently don't have a way to enable the tone mapping feature, here:

https://github.com/nmoehrle/mvs-texturing/blob/master/apps/texrecon/arguments.cpp#L69

Which I think is directly related to the "bland" colors you sometimes observe as output on the orthophotos: 
![image](https://cloud.githubusercontent.com/assets/1951843/23182260/ec3d54ce-f845-11e6-9d95-fab8c06dc9b9.png)

Notice the white areas near trees.

This seems directly related to the tone mapping feature, which is disabled by default: https://github.com/nmoehrle/mvs-texturing/issues/24

**Comment by dakotabenjamin** [comment]
I will see if exposing this parameter will help.

**Comment by dakotabenjamin** [comment]
https://github.com/dakotabenjamin/OpenDroneMap/tree/tone-mapping-param 

Note that this doesn't include an update to MVS-Texturing. You will have to pull #471 changes in or update manually. 

I don't have a dataset on hand to find any tangible differences between 'gamma' and 'none' so I'm hoping you can test that. Also, I was unsure whether to use the mvs-tex args (gamma and none) or just a boolean flag, but can easily switch if you think one is preferable over the other.

**Comment by pierotofy** [comment]
Thank you @dakotabenjamin! I will do some testing and report my results.

**Comment by pierotofy** [comment]
Mm, no significant improvements over the faded trees. This is what I got out with the latest mvs texturing and tone mapping set to gamma:

![image](https://cloud.githubusercontent.com/assets/1951843/23334215/68ccc1c6-fb68-11e6-9f91-2280cf014e4b.png)

I think the tone mapping option should be included, but perhaps have it set by default to none. Leaving it as a string is fine by me.

**Comment by pierotofy** [comment]
Settings tone mapping to `none` with the latest mvs texturing resulted in much nicer results:

![image](https://cloud.githubusercontent.com/assets/1951843/23334798/698ea8ca-fb74-11e6-8cb9-be2568f2881d.png)

So while just upgrading to the latest mvs texturing code will fix the problem, it might be beneficial for some users to expose the tone mapping option. But better to leave the default to `none`.

**Comment by pierotofy** [comment]
I'll close this since it has been taken care of as part of #499
