### ISSUE TITLE
Using full available resources

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#493]
In the mid/long term, we need to look at where we are threading effectively and not:

<img width="620" alt="resource_use" src="https://cloud.githubusercontent.com/assets/1174901/23222083/d07e52c4-f8f4-11e6-942b-602b31237e6e.PNG">

**Comment by smathermather** [comment]
That middle period where we are below 100% is a real cost (especially if the cost per cores is inelastic).

**Comment by Jakst3r** [comment]
+1

**Comment by smathermather** [comment]
Lots of improvements to ODM since this issue, including ways to optimize memory use, split-merge, and others. I will close this for now.
