### ISSUE TITLE
Error 4: does not exist in the file system, and is not recognised as a supported dataset name.

### ISSUE THREAD

**Issue by msampayog** [OpenDroneMap/ODM#496]
Hi, I have been running WebODM with docker and Virtual box, but just when the process is to end, the aplication shows the following message, 

[DEBUG]   running /code/build/bin/odm_orthophoto -inputFile /var/www/data/12c98789-2ef6-4875-8a5e-668df5606b93/odm_texturing/odm_textured_model.obj -logFile /var/www/data/12c98789-2ef6-4875-8a5e-668df5606b93/odm_orthophoto/odm_orthophoto_log.txt -outputFile /var/www/data/12c98789-2ef6-4875-8a5e-668df5606b93/odm_orthophoto/odm_orthophoto.png -resolution 20.0  -outputCornerFile /var/www/data/12c98789-2ef6-4875-8a5e-668df5606b93/odm_orthophoto/odm_orthophoto_corners.txt

ERROR 4: `data/12c98789-2ef6-4875-8a5e-668df5606b93/odm_orthophoto/odm_orthophoto.tif' does not exist in the file system, and is not recognised as a supported dataset name.

Usage: gdal2tiles.py [options] input_file(s) [output]

gdal2tiles.py: error: It is not possible to open the input file 'data/12c98789-2ef6-4875-8a5e-668df5606b93/odm_orthophoto/odm_orthophoto.tif'.

I dont know what is the problem.

Previously I assigned to my virtual machine 12 GB in RAM

Thanks a lot.

**Comment by dakotabenjamin** [comment]
This is a WebODM issue, I would open one over [there](https://github.com/OpenDroneMap/WebODM/issues/new). 

But, I think I can offer a little help. Do your photos have GPS tags in the EXIF? That would cause the process to fail at that point.
