### ISSUE TITLE
Summary how ODM work

### ISSUE THREAD

**Issue by Davidlapalma** [OpenDroneMap/ODM#511]
Hi, my question is, How work ODM, I'm saying what functions use the program, what is the principal code and what call to the functions do and the principal code.

**Comment by dakotabenjamin** [comment]
This is quite a big question, which currently I don't have the personal resources to answer. I can lead you to some links and things that you can use to get started though, and maybe try to answer specific questions you may have. Start here: https://github.com/OpenDroneMap/OpenDroneMap/wiki/Process-Breakdown I will continue to update this over the next few weeks as I work on documentation.

**Comment by dakotabenjamin** [comment]
Closing this for now, see #516 for more info.
