### ISSUE TITLE
Add KML to outputs for Google Earth

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#519]
See https://github.com/OpenDroneMap/WebODM/issues/126

**Comment by atoone** [comment]
This would be a genuinely useful feature

**Comment by grizzlyau** [comment]
This would be a great feature for ODM.

**Comment by mattkerle** [comment]
This would be awesome!

**Comment by smathermather** [comment]
I will close for now. Will re-open if there is interest and energy.
