### ISSUE TITLE
Webpage - wrong link

### ISSUE THREAD

**Issue by bgrotan** [OpenDroneMap/ODM#520]
http://opendronemap.org/ has a link to OpenAerialMap, but the URL refers to OpenTopography.
Correct url for OpenAerialMap should be http://openaerialmap.org/ instead of http://www.opentopography.org/

**Comment by smathermather** [comment]
Yes. Do you mind opening a pull request?

**Comment by bgrotan** [comment]
What´s the project url (git) for that webpage?

**Comment by smathermather** [comment]
It's the gh-pages branch of this repo.

**Comment by bgrotan** [comment]
fork && commit && pull-request done.

**Comment by smathermather** [comment]
Merged. Thanks!
