### ISSUE TITLE
2.5D Mesh Generation

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#521]
So I've been meaning to do some work on improving the orthophoto results (I've started a conversation here time ago: https://github.com/OpenDroneMap/OpenDroneMap/pull/444)

Achieving a 2.5D mesh can be done using a constrained delaunay triangulation and it's detailed here https://github.com/CloudCompare/CloudCompare/blob/579ee91594e16beba5863e2e4d15cf0729eb68a8/libs/qCC_db/ccMesh.cpp and here https://github.com/CloudCompare/CloudCompare/blob/579ee91594e16beba5863e2e4d15cf0729eb68a8/CC/src/Delaunay2dMesh.cpp

![image](https://cloud.githubusercontent.com/assets/1951843/24326123/ccea4e00-117d-11e7-83b8-68f9a19a9e5f.png)

CloudCompare offers this feature built-in and has a command line mode http://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode, however I don't think I'd want to include all of its dependencies (including QT!) just for the sake of generating a 2.5D mesh.

I could isolate just the code that takes care of the 2.5D mesh generation (and add some filtering of my own to reduce the spikes), but it will be necessary to add http://www.cgal.org/ as a dependency. PCL does not have any support for delaunay triangulations.

@dakotabenjamin what are your thoughts?

**Comment by pierotofy** [comment]
Also cc @smathermather

**Comment by smathermather** [comment]
Can we also isolate just the bits of CGAL we need, or is that a fools errand?

**Comment by pierotofy** [comment]
CGAL is complicated to just use as-is, I wouldn't venture as far as isolating a single component. What are the downsides of including CGAL, besides increased compilation time and docker image size?

**Comment by smathermather** [comment]
Just that. We can include it and then put it on a list of dependencies to remove later. I'm happy to take that approach: we're at an add features stage for the project, so I'd say proceed!

**Comment by pierotofy** [comment]
Feel free to assign me the task.

**Comment by dakotabenjamin** [comment]
Can we migrate all the current PCL functions over to CGAL? I don't have any experience with it. Removing PCL could speed up complication times significantly.

**Comment by pierotofy** [comment]
Probably. The good news is that there's a prebuilt package for including CGAL in Ubuntu. `apt-get install libcgal-dev`.

**Comment by dakotabenjamin** [comment]
That is pretty good news. PCL is heavy.

I would suggest for now just getting the 2.5D work in and we can sit down and sort through the possibilities of a full migration at a later date.

**Comment by pierotofy** [comment]
Boom! 

![image](https://cloud.githubusercontent.com/assets/1951843/24464145/fc70fcb8-1476-11e7-8f24-9923f290827c.png)

Still need to do some smoothing / filtering.

**Comment by pierotofy** [comment]
![image](https://cloud.githubusercontent.com/assets/1951843/24464654/7ca11bba-1478-11e7-831e-dd2ba79a565e.png)

**Comment by smathermather** [comment]
Awesome!

**Comment by pierotofy** [comment]
Starting to look a lot better:

![image](https://cloud.githubusercontent.com/assets/1951843/24618124/0bc2b148-1864-11e7-94b4-38f09c592ec2.png)

**Comment by pierotofy** [comment]
Still need to do further smoothing, but I think we're going to get free cropping along with this enhancement!

![image](https://cloud.githubusercontent.com/assets/1951843/24729900/728d417e-1a2e-11e7-96a7-5ac2f4192832.png)

This is due to the delaunay triangulation and outlier removal which makes some nice sharp edges around the resulting orthophoto (vs poisson).

**Comment by kikislater** [comment]
It seems nice, how to test it ?

**Comment by pierotofy** [comment]
Checkout this commit https://github.com/pierotofy/OpenDroneMap/commit/503671487020fa4ff6dad77bdf984bb5592f5313

And run with the `--use-25dmesh` argument. It's still a work in progress though, expect improvements in the next few days.

**Comment by pierotofy** [comment]
You will also need to compile the odm_25dmeshing module and copy the resulting binary in the bin folder. If you are not comfortable with cmake, make, etc. I would wait until I configure the configure.sh script properly.

**Comment by dakotabenjamin** [comment]
How is the cropping? Any areas that are over-cropped when compared to a ortho generated via 3d mesh?

**Comment by pierotofy** [comment]
It depends on the outlier removal parameter. The more outliers are removed, the more conservative the crop is.

**Comment by kikislater** [comment]
Ok, I'm familiar with make and cmake but use it with docker under archlinux. I will wait to test.
Control of outlier is planned ?

**Comment by pierotofy** [comment]
Yes, I'm adding a outlier removal parameter that can be tuned as well as a max vertex count parameter that defines the precision of the output mesh.

**Comment by pierotofy** [comment]
Old:

![image](https://cloud.githubusercontent.com/assets/1951843/24811382/daa1eda8-1b93-11e7-806c-d3f519f89741.png)

2.5D:

![image](https://cloud.githubusercontent.com/assets/1951843/24811356/c325b51a-1b93-11e7-8c96-e7bfeb7a6a16.png)

**Comment by pierotofy** [comment]
Old:

![image](https://cloud.githubusercontent.com/assets/1951843/24811426/076f4d3a-1b94-11e7-842e-059fa0dab8ad.png)

2.5D:

![image](https://cloud.githubusercontent.com/assets/1951843/24811436/12cc5a56-1b94-11e7-9f86-a284651fe1d4.png)

**Comment by kikislater** [comment]
Look nice!
Any idea why struture between 2 trees is wavy with delaunay ?

**Comment by pierotofy** [comment]
I'm not entirely sure; I'm not very familiar with the mvs texturing package, which is the component that overlays the texture over the surface model.

**Comment by pierotofy** [comment]
Probably because of noise: 
![image](https://cloud.githubusercontent.com/assets/1951843/24812204/248574be-1b97-11e7-8875-503e8c5be943.png)

**Comment by kikislater** [comment]
Looks like more a shiny surface with different shine on each picture.

**Comment by pierotofy** [comment]
No that's because illumination is turned on.

![image](https://cloud.githubusercontent.com/assets/1951843/24812521/677803c6-1b98-11e7-81e4-de5d28479651.png)

**Comment by pierotofy** [comment]
Re-ran it with half the number of vertices (less noise, but less definition on edges):

![image](https://cloud.githubusercontent.com/assets/1951843/24812591/b54233ba-1b98-11e7-9e60-dce92e71576f.png)

![image](https://cloud.githubusercontent.com/assets/1951843/24812636/d98ac03e-1b98-11e7-99fc-bb36c7031a5f.png)

**Comment by pierotofy** [comment]
@kikislater you should be able to test the 2.5D mesh feature by checking out the changes in #542 and running `. configure.sh`.
