### ISSUE TITLE
PDAL pipeline distorts point cloud in certain datasets

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#522]
Input dataset: https://www.dropbox.com/sh/d28k2p7silx5ows/AAD0jglE7C70DuNFT0zu-xEda?dl=0

Problem happens with either OpenSfM or PMVS.

The resulting `odm_georeferenced_model.ply` point cloud is generated correctly (see below):

![image](https://cloud.githubusercontent.com/assets/1951843/24334439/3ef1e304-1238-11e7-9b5b-55ae8b15ed96.png)

The `odm_georeferenced_model.ply.las` file generated with `/code/SuperBuild/build/pdal/bin/pdal pipeline -i /var/www/data/53683562-45b6-495e-86d6-f00a22208e68/odm_georeferencing/pipeline.xml --readers.ply.filename=/var/www/data/53683562-45b6-495e-86d6-f00a22208e68/odm_georeferencing/odm_georeferenced_model.ply --writers.las.filename=/var/www/data/53683562-45b6-495e-86d6-f00a22208e68/odm_georeferencing/odm_georeferenced_model.ply.las` however is "striped". See below:

Potree display:

![image](https://cloud.githubusercontent.com/assets/1951843/24334467/9ffab84c-1238-11e7-9a92-c0d564d59b60.png)

CloudCompare display:

![image](https://cloud.githubusercontent.com/assets/1951843/24334469/a5558bfa-1238-11e7-99d8-0b652fe2d4db.png)

PLY file: https://ufile.io/08728
LAS file: https://ufile.io/d3d511

**Comment by pierotofy** [comment]
`pipeline.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Pipeline version="1.0">
   <Writer type="writers.las">
      <Option name="filename">transformed.las</Option>
      <Option name="a_srs">EPSG:32756</Option>
      <Filter type="filters.transformation">
         <Option name="matrix">1  0  0  340695        0  1  0  6259514        0  0  1  0        0  0  0  1</Option>
         <Reader type="readers.ply">
            <Option name="filename">untransformed.ply</Option>
         </Reader>
      </Filter>
   </Writer>
</Pipeline>
```

**Comment by smathermather** [comment]
Wacky. Does it do the same with a JSON file instead of XML?

**Comment by pierotofy** [comment]
Here's another dataset that has the same problem:

https://drive.google.com/open?id=0B4Tf0aIvxRLJTnpKOWlsU3ZaN2c

![image](https://cloud.githubusercontent.com/assets/1951843/24839888/8c14542a-1d30-11e7-80ce-ade0f01ea363.png)

**Comment by smathermather** [comment]
Have we tried processing this with a json file instead of the XML? My guess is this is an XML regression that hasn't been caught in PDAL because we are the only ones left using XML in PDAL... . Sorry I haven't had a change to look into this myself.

**Comment by dakotabenjamin** [comment]
https://github.com/dakotabenjamin/OpenDroneMap/blob/pdal-dem/opendm/types.py I've changed to JSON in this branch. Can someone test?

**Comment by pierotofy** [comment]
Just tested, I think we should switch to JSON regardless, but it doesn't fix the problem.

I think the problem is due to the limitations of floating point precision.

The matrix in the first dataset for example reads:

```"1 0 0 340695 0 1 0 6259514 0 0 1 0 0 0 0 1```

Plugging in some coordinates from input files and multiplying them by the matrix yields several points with more than 7 digits of precision.

**Comment by dakotabenjamin** [comment]
https://github.com/dakotabenjamin/OpenDroneMap/tree/pdal-dem I just pushed an update that forwards the scale. It looks good to me.

**Comment by pierotofy** [comment]
I confirm that adding "forward": "scale" to the pipeline fixes the problem.

![image](https://cloud.githubusercontent.com/assets/1951843/24866644/bf0599e0-1dd8-11e7-98d9-ac91b4e956f2.png)

**Comment by hblanken** [comment]
Works for me! :1st_place_medal:

**Comment by dakotabenjamin** [comment]
Great. Look forward to a PR in the next week or so.

**Comment by hblanken** [comment]
Has this now been been integrated into PR #549. Will test both this weekend.

**Comment by dakotabenjamin** [comment]
Yes it also fixed that by forwarding the scale through the pipeline: https://github.com/OpenDroneMap/OpenDroneMap/pull/549/files#diff-02fe4f960c0e32f739192d0fdfa38756R185

**Comment by dakotabenjamin** [comment]
@hblanken did you get good results?

**Comment by hblanken** [comment]
Sorry to only reply now - I pulled your new ODM master and unfortunately have not been able to create a las without stripes. I am now running ODM natively and produce output via plas.io
![image](https://cloud.githubusercontent.com/assets/1486914/25373821/7165363e-29de-11e7-8926-045425262c52.png)

**Comment by pierotofy** [comment]
After pulling ODM master, did you remove all previous results from the dataset folder (all the directories expect the images/ directory)?

**Comment by hblanken** [comment]
@pierotofy Yes, clean dataset folder. I tried today with a dataset with a gcp_list.txt and have similar results. Both in Meshlab and and in plas.io and webODM i get stripes.
![image](https://cloud.githubusercontent.com/assets/1486914/25428845/65d355c6-2aba-11e7-9f47-272476d72a8c.png)

**Comment by dakotabenjamin** [comment]
Have the changes been reflected in WebODM yet @pierotofy ?

**Comment by pierotofy** [comment]
It has not; the docker image hasn't been upgraded in a while (the build process was stuck, I need to code up some sort of notification system for when this happens in the future).

I'm rebuilding it now, it should be ready in a few hours.

Keep an eye on the "Last pushed" field here https://hub.docker.com/r/opendronemap/opendronemap/ and here https://hub.docker.com/r/opendronemap/node-opendronemap/

Then `./webodm.sh update` should do it.

**Comment by pierotofy** [comment]
Ok, the new images have been built. @hblanken could you confirm that things now work after an update?

**Comment by hblanken** [comment]
Hi @pierotofy - Thanks for trying to get to the bottom of this. I pulled the latest docker webodm and node and now the potree visual looks better, with quite large bubbles as default (which I know can be adjusted in the potree options), but the stripes are gone. See below. When I pull all the odm assets from docker and view the .las file in plas.io - it still has the stripes. Question: This means, if I run ODM natively (which I tend to do), without WedODM, the stripes will remain in the .las files? (Note for you - the screenshot in your webODM readme also shows the stripes in the sheffield park potree view. Maybe worth updating to the latest commit)
![image](https://cloud.githubusercontent.com/assets/1486914/25473007/010202d4-2b71-11e7-831f-47201012493b.png)

**Comment by pierotofy** [comment]
Thanks for pointing out the screenshot in the readme. If you run ODM without WebODM, the stripes should be gone as well. This is a patch we've added in ODM core.

**Comment by pierotofy** [comment]
Actually, I'm going to backtrack a moment and I think that this is still a problem. The reason the potree point cloud looks fine is because there have been some filename changes (`odm_georeferenced_model.ply.las` is no longer created, but `odm_georeferenced_model.las` is), which triggered node-odm's failsafe to generate a las file from the original `merged.ply` point cloud (which is not georeferenced).

Long story short, this is still a problem, and adding "forward": "scale" does not solve the issue. After reading more, the forward directive only applies when reading from a las/laz source, not ply. So in essence adding "forward" : "scale" doesn't do anything.

The problem is still the matrix transformation:

```
{
  "pipeline": [
    "untransformed.ply",
    {
      "matrix": "1 0 0 576705 0 1 0 5188170 0 0 1 0 0 0 0 1",
      "type": "filters.transformation"
    },
    {
      "a_srs": "EPSG:32615",
      "filename": "transformed.las"
    }
  ]
}
```

We lose precision after the transformation is applied. We need to calculate appropriate scale and offset parameters (see https://www.pdal.io/stages/writers.las.html `scale_x`, `scale_y`, `offset_x`, `offset_y`).

I found this discussion interesting for the purpose: https://gis.stackexchange.com/questions/132632/reprojecting-lidar-data-with-liblas/132635

**Comment by pierotofy** [comment]
![image](https://cloud.githubusercontent.com/assets/1951843/25507885/9cd01d12-2b7c-11e7-9c54-0e219dae4f05.png)

**Comment by pierotofy** [comment]
@hblanken could you confirm that there's the following line in the last output log for the dataset you processed?

```
odm_georeferenced_model.ply.las is missing, will attempt to generate it from
```

@dakotabenjamin perhaps instead of a matrix transformation, we just need to specify `offset_x` and `offset_y`?

https://github.com/OpenDroneMap/OpenDroneMap/blob/master/opendm/types.py#L170

**Comment by hblanken** [comment]
@pierotofy - I believe you mean the geo_referencing logs? I attach both files in the directory:[odm_georeferencing_log.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/965846/odm_georeferencing_log.txt)
[odm_georeferencing_utm_log.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/965847/odm_georeferencing_utm_log.txt)

**Comment by pierotofy** [comment]
Sorry, no I mean this output log from the WebODM interface: 

![image](https://cloud.githubusercontent.com/assets/1951843/25555468/0c9477f4-2cb5-11e7-91a0-6a4695cd7812.png)

**Comment by hblanken** [comment]
Sure - this is what I get, see below: I don't see  "odm_georeferenced_model.ply.las is missing"
>>spacing calculated from diagonal: 0.594157
READING:  data/4bc923fd-cbd3-4d72-8331-76411fa99970/odm_georeferencing/odm_georeferenced_model.ply.las
INDEXING: 1,000,000 points processed; 1,000,000 points written; 1.107 seconds passed
closing writer

conversion finished
1,425,761 points were processed and 1,425,761 points ( 100% ) were written to the output. 
duration: 2.383s
Compressing all.zip

**Comment by dakotabenjamin** [comment]
@pierotofy is this an issue with core ODM or node-ODM?

**Comment by pierotofy** [comment]
ODM. I just processed this with the latest master.

Las file (noticed the stripes):

![image](https://cloud.githubusercontent.com/assets/1951843/25581296/09962b3c-2e55-11e7-9c28-f1e9127d580b.png)

Ply file (correct point distrubition):

![image](https://cloud.githubusercontent.com/assets/1951843/25581325/27c8506c-2e55-11e7-96ea-e719e30faf03.png)

What is the reason for using the matrix transform in the PDAL pipeline?

**Comment by dakotabenjamin** [comment]
@smathermather would be able to answer that.

**Comment by pierotofy** [comment]
So I digged through the code, the idea of the matrix transform is to add a offset to the coordinates (x + utm east offset = geo referenced x coordinate, same for y, z is already in meters above the geoid).

Setting an offset_x and offset_y property in the las writer options should have worked, but the problem did not go away. 

The reason this is not working is because of the PLY reader!

If you look at the header of our input PLY files:

```
property float x
property float y
property float z
```

X,Y,Z coordinates are defined as floats. So PDAL (correctly) creates Point objects that have a float data type: https://github.com/PDAL/PDAL/blob/dd97a033c5d487000e200304a7619e9978de6ae2/filters/TransformationFilter.cpp#L100

```c
    point.setField(Dimension::Id::X,
        x * m_matrix[0] + y * m_matrix[1] + z * m_matrix[2] + m_matrix[3]);
```

setField will apply the proper offset, but precision is lost in the process because points are treated as floats, not doubles.

![image](https://cloud.githubusercontent.com/assets/1951843/25775624/8a2bb8e0-3277-11e7-83dc-61685267fdfa.png)

Changing the PLY header to:
```
property double x
property double y
property double z
```

Yields proper results.

![image](https://cloud.githubusercontent.com/assets/1951843/25775627/a874c562-3277-11e7-9cbe-9436beb724c1.png)

**Comment by hblanken** [comment]
This error was bugging me for the last weeks with processing several striped Las files. Big breakthrough finding @pierotofy @dakotabenjamin  ! So if I understand you correctly the .las is created based on the PLY and if the proper header is passed on for las processing the Las will show up correctly as well? Is this sth I can implement in the code somehow?

**Comment by pierotofy** [comment]
If the PLY header specifies its dimensions data type as double instead of float, the las file is generated properly. I'm still trying to figure out the best way to fix this, as I'm not sure I'd want to modify the PLY headers for the sake of executing the conversion.

**Comment by smathermather** [comment]
If PLY is written by OpenSfM, maybe a pull request against that project to correctly specify type in the header is required.

**Comment by pierotofy** [comment]
This might get fixed in PDAL: https://github.com/PDAL/PDAL/issues/1584

**Comment by pierotofy** [comment]
It should be fixed in the latest PDAL master: https://github.com/PDAL/PDAL/commit/aea5bb0cacc64b91d626eff491fbdbb5668c06d7

I'll make a PR that uses the latest PDAL version.

**Comment by smathermather** [comment]
W00t
