### ISSUE TITLE
usage: run.py [options] <project name>  run.py: error: too few arguments

### ISSUE THREAD

**Issue by jackxieweiwu** [OpenDroneMap/ODM#529]
jack@jack:~/OpenDroneMap$ sudo ./run.sh --project-path /home/jack/OpenDroneMap/img/test/
usage: run.py [options] <project name>
run.py: error: too few arguments

**Comment by pierotofy** [comment]
Hello!

We have added a few improvements to the command line, the new syntax is now:

`sudo ./run.sh --project-path /home/jack/OpenDroneMap/img test`

See: `./run.sh --help`

**Comment by dakotabenjamin** [comment]
@pierotofy has the correct solution. Please reopen if it doesn't work for you.
