### ISSUE TITLE
No module named ecto

### ISSUE THREAD

**Issue by mgctech-gk** [OpenDroneMap/ODM#530]
Hi, 
When I run "bash ./run.sh --project-path /home/ubuntu/projects/robertson test" or " python run.py -i /home/ubuntu/projects/robertson test" I keep getting this error:
"
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    import ecto
ImportError: No module named ecto
"
I saw on some old posts that you might have to rerun the ./configure file again, which I have done.
Any help would be great. 
Thanks

Edit:
I cloned directly from GitHub and did not use the download from "https://github.com/OpenDroneMap/OpenDroneMap/releases", this seems to have worked now.

**Comment by danbjoseph** [comment]
hrm, i downloaded https://github.com/OpenDroneMap/OpenDroneMap/releases/download/v0.3.1/OpenDroneMap_v0_3_1.tar.gz and then got  
```
Traceback (most recent call last):
  File "/root/OpenDroneMap_v0_3_1/run.py", line 8, in <module>
    import ecto
ImportError: No module named ecto
```
after `./run.sh`
