### ISSUE TITLE
files with more times of processing 

### ISSUE THREAD

**Issue by Davidlapalma** [OpenDroneMap/ODM#533]
Hello, I will try to reduce the time of processing of the ODM by parallelism on GPU Nvidia and I would like what is the part or the file that spend more time of processing.

**Comment by dakotabenjamin** [comment]
We welcome contributions towards improving computation time.

**Comment by pierotofy** [comment]
@Davidlapalma :hand: if this still of interest, we'd still welcome contributions. Feel free to open a PR anytime.
