### ISSUE TITLE
Full Package audit

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#534]
We've been updating the modules continuously but haven't been keeping up too well with the dependencies list. A full package audit will help reduce the size of the ODM, including the docker image. See #461

**Comment by KommandorKeen** [comment]
What's involved in the audit and do you need volunteers?

**Comment by dakotabenjamin** [comment]
It involves going through each dependency in configure.sh and the Dockerfile and finding out where it is or was used in ODM. If that package or w/e is irrelevant, then remove it. It's a fairly straight-forward task but requires some in-depth knowledge of the whole process, or a willingness to be thorough. If you're up to the task, by all means we need all the help we can get.
