### ISSUE TITLE
 ODM install ERROR (Docker): "c++: internal compiler error: Killed (program cc1plus)"

### ISSUE THREAD

**Issue by ProjectNeurogenesis** [OpenDroneMap/ODM#539]
Ran Docker and followed all command inputs outlined in https://github.com/OpenDroneMap/OpenDroneMap#build-and-run-using-docker. 
Everything was built successfully except during this last part in which the ff were displayed (am I the only one encountering these kinds of errors in recent odm installations? T_T)
![5_programkilled](https://cloud.githubusercontent.com/assets/26026229/24753832/7a38d4fa-1b06-11e7-8b2b-346f94c6fca2.JPG)

Attached below is a .txt file of the LOG from the installation. The above mentioned error can be found at Line: 6054

Thank you.#

**Comment by dakotabenjamin** [comment]
I don't think the txt file attached. 

I've never seen that error before... But whenever I see a "Killed" error I think that it is a memory issue. Have you allocated enough memory to Docker? @pierotofy maybe we should add those instructions to the readme...

**Comment by pierotofy** [comment]
Yes, the build failed because the machine ran out of memory. Make sure your docker machine has enough memory allocated.

And yes we should add a note in the readme.

**Comment by stiward** [comment]
I have the same problem, how can I solve it?
How can I allocate more virtual memory to Docker

Tnks you

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/odm-install-error-docker-c-internal-compiler-error-killed-program-cc1plus/398
