### ISSUE TITLE
--mesh-size is unrecognized on run.py

### ISSUE THREAD

**Issue by tteke** [OpenDroneMap/ODM#547]
In the documentation on run-time parameters, there is a parameter called mesh-size, however, i can't use it on the run.py. I get  

run.py: error: unrecognized arguments: --mesh-size 1000000

**Comment by dakotabenjamin** [comment]
What version of opendronemap are you running?

**Comment by tteke** [comment]
0.2.1

**Comment by dakotabenjamin** [comment]
Sorry, I updated the wiki too soon! The old meshing parameter is `--odm_meshing-maxVertexCount 1000000`. If you need a reference, you can run `run.py --help`

**Comment by dakotabenjamin** [comment]
This should be resolved. Please reopen if you still have issues.
