### ISSUE TITLE
Question: Re rolling log in Web ODM

### ISSUE THREAD

**Issue by clarkerz** [OpenDroneMap/ODM#550]
Hi,

is it possible to change the GMT time  so that the rolling log in the web browser shows the local time (in my case BST)?

Thanks

Andy

**Comment by dakotabenjamin** [comment]
That's a good question for @pierotofy

**Comment by pierotofy** [comment]
I assume that you mean this log:

![image](https://cloud.githubusercontent.com/assets/1951843/25361035/faff6876-2919-11e7-974d-b565513ef967.png)

In that case, at the moment we have no way to set a GMT time. The log is simply the output taken from ODM. This is probably something that needs to be implemented in node-odm.

@clarkerz could you open an issue here https://github.com/OpenDroneMap/node-OpenDroneMap as a enhancement request?

**Comment by dakotabenjamin** [comment]
Closing as it applied to https://github.com/OpenDroneMap/node-OpenDroneMap

**Comment by clarkerz** [comment]
Apologies as I have been away for a few days. Have just raised in node-OpenDroneMap as request.

Thanks

Andy
