### ISSUE TITLE
v0.2 install struggle

### ISSUE THREAD

**Issue by rion-saeon** [OpenDroneMap/ODM#552]
Hi all,
I recently realised that v0.2 (beta) is out however, I am struggling with accessing `settings.yaml` to edit my `/project/path`.

I followed the Instructions as per new description on ODM but, cannot access the above file in order to copy and change path to projects folder.

**Comment by dakotabenjamin** [comment]
settings.yaml is not in 0.2. It is in `master` and the 0.3 release that is coming out this week.
