### ISSUE TITLE
Alphanumeric characters

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#553]
```run.py: error: argument <project name>: . is not a valid name. Must use alphanumeric characters.```

This strikes me as an anti-pattern -- if I understand what's happening correctly, it will make internationalization a real headache. Instead of checking for alphanumeric characters, can we check if it's a valid and accessible directory?

**Comment by dakotabenjamin** [comment]
The project name should not be a directory. If you try to make the project name `.` that would mess with the directory structure.

**Comment by smathermather** [comment]
Ah, fair, but a dot can be specifically tested for.
