### ISSUE TITLE
Associate textured mesh polygon with source image?

### ISSUE THREAD

**Issue by fredlllll** [OpenDroneMap/ODM#554]
Hi there,

im currently trying to find a way to associate polygons of the textured mesh with its source image.
I though i could do that by parsing the data in reconstruction.meshed.json or reconstruction.json, but the faces of the jsons are in no way correlated to the ones in the obj it seems. does anyone have an idea? or some references that could help me?

**Comment by dakotabenjamin** [comment]
See #557
