### ISSUE TITLE
Add OpenDroneMap into OSGeoLive

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#555]
This is a suggestion that came up in the WebODM repository, but I think it applies to the entire ODM stack.

https://wiki.osgeo.org/wiki/Live_GIS_Add_Project#What_gets_into_OSGeoLive.3F

**Comment by dakotabenjamin** [comment]
Yeah it is something we should try to get in before the workshop in August.

**Comment by dakotabenjamin** [comment]
@smathermather Yeah it is something we should try to get in before the workshop in August.

**Comment by kikislater** [comment]
Nice, very happy to see ODM incubated in Osgeo.

**Comment by dakotabenjamin** [comment]
We are not being incubated in Osgeo, but we've discussed it before.
