### ISSUE TITLE
References for ODM

### ISSUE THREAD

**Issue by CarlosGrohmann** [OpenDroneMap/ODM#559]
It would be really nice to have a page with the preferred references for citing ODM in scientific articles. A page in the wiki could also be used to list all papers that use ODM.

**Comment by dakotabenjamin** [comment]
Does anyone know how to cite ODM in scientific papers? That is something I would put right in the README.

**Comment by LucasMM86** [comment]
Hello Benjamin,
I found something here: http://blog.apastyle.org/apastyle/2015/01/how-to-cite-software-in-apa-style.html

It would be like this:
Reference:
Open Drone Map [Computer software]. (2017) Retrieved from https://github.com/OpenDroneMap/OpenDroneMap

Cite: 
"We used Version 0.2 of Open Drone Map (2017) to complete our work."

But maybe there are better ways to do that, i am not an expert! regards

**Comment by CarlosGrohmann** [comment]
Yes, that would be the way to cite the software itself. 

I was thinking on something in the lines of this GRASS page:
https://grasswiki.osgeo.org/wiki/GRASS_Citation_Repository


Are there any scientific papers about ODM?

**Comment by dakotabenjamin** [comment]
None published that I am aware of.

**Comment by dakotabenjamin** [comment]
This should be linked over at #516

**Comment by CarlosGrohmann** [comment]
A good starting point would be a list of references for the parts that make ODM (OpenSfM, libraries, etc). It would be very useful for a paper describing ODM.

**Comment by CarlosGrohmann** [comment]
Using Google Scholar, I found some papers using ODM.

I'll make a list, but this one seem to be of special interest:

Comparing and characterizing three-dimensional point clouds derived by structure from motion photogrammetry
by Schwind, Michael, M.Sc., TEXAS A&M UNIVERSITY - CORPUS CHRISTI, 2016, 129 pages; 10247379
http://hdl.handle.net/1969.6/1137

**Comment by rion-saeon** [comment]
Citing of a well-known statistical software package:

To cite R in publications, use

  title        = {R: A Language and Environment for Statistical
                  Computing},
  author       = {{R Core Team}},
  organization = {R Foundation for Statistical Computing},
  address      = {Vienna, Austria},
  year         = YEAR,
  url          = {https://www.R-project.org}

**Comment by pierotofy** [comment]
@smathermather what would be the best way to do this? (Add a reference in the README/Docs?)

**Comment by CarlosGrohmann** [comment]
Some projects have a section in their website (like Citing XX), but a section in the README works well.

**Comment by smathermather** [comment]
We could add to the README and maybe a page at opendronemap.org.
