### ISSUE TITLE
Resizing images to original size gives wrong warning

### ISSUE THREAD

**Issue by CarlosGrohmann** [OpenDroneMap/ODM#563]
This is more of a report, nothing critical, but when using --resize-to 4000  with 3000x4000 Phantom 4 images, ODM gives this warning message:

```
[DEBUG]   Resized DJI_0275.JPG | dimensions: (3000, 4000, 3)
[WARNING] Resize Parameter is greater than the largest side of the image
```

Since the resize parameter is actually the same as the largest side of the image, the message can be a bit confusing.

**Comment by dakotabenjamin** [comment]
see #567
