### ISSUE TITLE
Spatial distribution of points in CSV and LAS

### ISSUE THREAD

**Issue by CarlosGrohmann** [OpenDroneMap/ODM#566]
Using CloudCompare, I noticed that the spatial distribution of points in the CSV and LAS files are quite different. 

In CSV, points are randomly scattered in the area, while in LAS, they follow narrow strips (see below), and the points are vertically distributed in these strips.

<img width="1155" alt="CSV (white) and LAS (coloured)" src="https://cloud.githubusercontent.com/assets/1870265/25707127/f1a47aea-30b8-11e7-8912-c20a0fc5c3eb.png">

**Comment by dakotabenjamin** [comment]
This is a known bug. I'm trying to find the issue where we've documented this.

**Comment by pierotofy** [comment]
Yup, it's documented here: #522

**Comment by CarlosGrohmann** [comment]
Ok, since this is a duplicate, I'll close it.
Thanks
