### ISSUE TITLE
PC freeze running v0.3 on image set

### ISSUE THREAD

**Issue by rion-saeon** [OpenDroneMap/ODM#569]
Hi all,
Ubuntu 14.04
PC with 12 Gig RAM
300 photos
v.0.3

Runs with previous versions on same photo set delivered results.
Currently script freezes together with PC at `...cleaning depthmap on image...`

Suggestions?

**Comment by pierotofy** [comment]
Hi @rionlerm, we've had quite a few people reporting issues with the depthmap calculation process stalling. The best workaround at the moment is to use the `--use-pmvs` flag during processing.

**Comment by pierotofy** [comment]
Also if you could provide us a copy of the dataset to reproduce the issue it would help us narrow down the root cause of this.

**Comment by dakotabenjamin** [comment]
Maybe we should just default nproc-1 for opensfm-processes

**Comment by pierotofy** [comment]
Could be a good temporary workaround. Better slow than freezing.
