### ISSUE TITLE
Update OpenSfM to latest changes

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#570]
There are some important georeferencing additions and other improvements that should be incorporated into ODM.

**Comment by merkato** [comment]
OpenSfM is available as an pre-built package (PPA). It should make building OpenDroneMap faster ;) 
https://github.com/mapillary/OpenSfM/issues/172

**Comment by dakotabenjamin** [comment]
Oh sweet. We are holding off on this until they finish the work on large-scale datasets but will integrate that for sure.

**Comment by dakotabenjamin** [comment]
This has been partially addressed in #644 but I'm not going to close it until the split-merge features have been completed.
