### ISSUE TITLE
Improve default values for DEM

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#578]
I thought I'd report my findings here. :)

Whenever I process a dataset, I seem to need to tweak the `--dem-sample-radius`, `--dem-resolution` and `--dem-radius`. The default values produce spotted results.

Input: https://github.com/pierotofy/drone_dataset_sheffield_park_1 (default options plus `--dem`)

Output:

![image](https://cloud.githubusercontent.com/assets/1951843/26039414/b72fbf40-38e8-11e7-9b13-a889983edde6.png)

With `--dem-radius 2`:

![image](https://cloud.githubusercontent.com/assets/1951843/26039467/1f9b2b8c-38e9-11e7-9fce-719decd5e9a4.png)

(Resolution is quite low)

With `--dem-radius 2 --dem-resolution 0.2`:

![image](https://cloud.githubusercontent.com/assets/1951843/26039512/aa3e4008-38e9-11e7-8909-608a20ff1fb8.png)

(Resolution is good, almost the same as the orthophoto, but interpolated values are "bubbly" looking, see the image below)

![image](https://cloud.githubusercontent.com/assets/1951843/26039522/c7027aba-38e9-11e7-83fc-ae7e68ea0473.png)

With `--dem-sample-radius 0.25 --dem-resolution 0.2 --dem-radius 0.5`:

![image](https://cloud.githubusercontent.com/assets/1951843/26062185/1a250c26-3958-11e7-85f1-b3692ec90117.png)

Still some holes, but resolution is good and no "bubbly" values. It also took 16 minutes to process the PDAL pipeline, if speed is a concern, perhaps adding the "approximate" option to pmf could speed things up: https://www.pdal.io/stages/filters.pmf.html

With `--dem-sample-radius 0.25 --dem-resolution 0.2 --dem-radius 1`:

![image](https://cloud.githubusercontent.com/assets/1951843/26058794/6cd69e40-394d-11e7-95fa-f9e1c79bc85c.png)

Mostly OK, still some holes, took 17 minutes. I suspect increasing the max_window_size in pmf would interpolate the nodata cells, but would also add significant overhead.

In general I think the current defaults are undersampling and the resolution might be too low. There should also be more hole filling perhaps? Just suggestions. 👍 love the new DEM functionality.

**Comment by smathermather** [comment]
I really think we just need better interpolators in PDAL. Great interpolation isn't needed for lidar, but is critical for photogrammetrically derived point clouds.

**Comment by pierotofy** [comment]
Relevant: https://github.com/OpenDroneMap/node-OpenDroneMap/issues/15

**Comment by dakotabenjamin** [comment]
This is irrelevant now, correct? Please reopen if I'm wrong.
