### ISSUE TITLE
Feedback on Bundler

### ISSUE THREAD

**Issue by soler2000** [OpenDroneMap/ODM#58]
Would it be possible to enable some feedback on bundler,  When it runs there is nothing to indicate it is running or halted.

Checking CPU Utilisation shows only 2-3% use on the current dataset I am running on a EC2 instance c4.8xlarge and it has not shown an indication of life in the last 2 hrs!

**Comment by smathermather** [comment]
Wow. How big of a dataset?

Labeling this as feature enhancement.

**Comment by smathermather** [comment]
Closing as duplicate. Should be addressed as part of #207.
