### ISSUE TITLE
[Enhancement] Add StatisticalOutlierRemoval to odm_meshing module

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#583]
Many datasets end up having small artifacts lying around both the textured mesh and orthophoto. Many of these small artifacts could be prevented by removing outliers prior to mesh building.

See for example:

![image](https://cloud.githubusercontent.com/assets/1951843/26223878/10b8e9ee-3bee-11e7-9749-259ee2afddfb.png)

We've already have a `--mesh-remove-outliers` for the 2.5D mesh, we could probably use it for the 3D mesh as well.

**Comment by dakotabenjamin** [comment]
The question is whether there's a functional equivalent, or have to be added to the module manually. Any C++ devs want to take up the challenge?

**Comment by pierotofy** [comment]
I could probably add it to the meshing module: http://docs.pointclouds.org/trunk/classpcl_1_1_statistical_outlier_removal.html

**Comment by mribbons** [comment]
👍  this is a great suggestion.

I'm not a c++'er unfortunately, but I could assist with testing and debug once some code is written.

**Comment by osmanmesutozcan** [comment]
I can help with this, if there is no one working on it.

**Comment by pierotofy** [comment]
I haven't started working on this, so go ahead, it would be awesome to have this feature!

**Comment by hy9be** [comment]
It would be great to have this!

**Comment by smathermather** [comment]
Done since 2018.
