### ISSUE TITLE
Comparison: ODM vs. DroneDeploy

### ISSUE THREAD

**Issue by AnthonyCoughlin** [OpenDroneMap/ODM#598]
Hey @pierotofy 

Wanted to give you guys some prospective on ODM vs. DroneDeploy.  First off, I updated WebODM this morning.  I captured these images this afternoon (10Jun17).  Its a small field house at a sports complex.  I processed the images through WebODM using the default settings and also processed them through DroneDeploy.  See the attached screenshots.  Also below, I've uploaded the images to Google Drive and provided a link if you'd like to inspect. 

Hope this helps further ODM's progress!
Anthony

![nep_fieldhouse_dd2](https://user-images.githubusercontent.com/25381671/27007005-dfbbcc8e-4e09-11e7-80c2-134b6987f070.JPG)
DroneDeploy1

![nep_fieldhouse_odm](https://user-images.githubusercontent.com/25381671/27007006-dfbd081a-4e09-11e7-8e73-fcd1eeab0882.JPG)
WebODM1

![nep_fieldhouse_odm2](https://user-images.githubusercontent.com/25381671/27007007-dfbd63e6-4e09-11e7-884b-4e404d9d30ca.JPG)
WebODM2

![nep_fieldhouse_dd](https://user-images.githubusercontent.com/25381671/27007008-dfbe7dee-4e09-11e7-91f1-90efe3182c63.JPG)
DroneDeploy2

https://drive.google.com/open?id=0B4Tf0aIvxRLJai1VM1VSUWV6Rm8

**Comment by Fi156** [comment]
Photoscan:
No manual tie points were set. 

![photoscan1](https://user-images.githubusercontent.com/2189169/27010020-c3e996b6-4e9b-11e7-90f1-a9f25dcccaec.png)
![photoscan2](https://user-images.githubusercontent.com/2189169/27010021-c3eafe70-4e9b-11e7-9270-290238b778f2.png)


I really really dislike the drone deploy result: They are completely omitting roof overhang!
ODM however will produce much better results with parameter tweaking I guess.

**Comment by AnthonyCoughlin** [comment]
Man, the Photoscan results look great.  What do you mean by "no manual tie-in points were set" (ground control points?) and how do I correct it!!??  I'm still learning the inner workings of ODM!

**Comment by flyandi** [comment]
So what parameter tweaking do you have to do to achieve similar results? I am still trying to figure out the best angles to capture proper image data to generate high resolution 3d models from objects.

**Comment by AnthonyCoughlin** [comment]
@Fi156, I would like to know more about "better parameter tweaking" as well.  I use force focal length for sure.  I am still having difficulty understanding and obtaining the correct CCD width for my on board camera.  If somebody could please advise.   For GPS I just utilize the EXIF data.  I also adjust the octree level depending on the level of detail.

Thanks in advance!

**Comment by flyandi** [comment]
Whats your camera?

**Comment by AnthonyCoughlin** [comment]
I fly Autel Robotics.  The EXIF data has the camera listed as XB004.  Some of my research has shown that the X-STAR uses the Sony Exmor-R sensor.  Correct me if I am wrong, but this sensor uses CMOS technology and not CCD and I'm not 100% if this effects the results of ODM.  However, on the Wikipedia page under the Exmor-R sensors section, there is a 12MP version so I use the dimension listed there (7.81mm)...

https://en.wikipedia.org/wiki/Exmor

https://www.bhphotovideo.com/c/product/1243948-REG/autel_robotics_xsprmor_x_star_premium_quadcopter_with.html

Thanks for the help.

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/comparison-odm-vs-dronedeploy/377
