### ISSUE TITLE
example how to use the parameters are needed

### ISSUE THREAD

**Issue by soler2000** [OpenDroneMap/ODM#60]
If for example I want to run two parameters should the parameters be used in the following format
./run.pl —odm_meshing-maxVertexCount=150000 —odm_meshing-octreeDepth=11 

or

./run.pl —odm_meshing-maxVertexCount 150000 —odm_meshing-octreeDepth 11 

what is the correct syntax for this?

**Comment by smathermather** [comment]
The correct syntax is a space between the parameter and its value:
`./run.pl --odm_meshing-maxVertexCount 150000 --odm_meshing-octreeDepth 11`

**Comment by soler2000** [comment]
added this to the wiki,  it needs some more info on each one of the parameters and what is the effect it has

**Comment by dbaldwin** [comment]
@soler2000 @smathermather I'd like to assist with wiki documentation. Can you let me know how I go about this? I tried making a small edit, but it doesn't look like it took. Unless you have to approve it first.

**Comment by soler2000** [comment]
You should just be able to save new edits to it.  I don't think there is any approval needed.

—

**Comment by smathermather** [comment]
Indeed. Please edit away, @dbaldwin

**Comment by okiave** [comment]
Regarding the todo of adding descriptons to parameters.
The documentation page for PMVS (v2) has a few of the parameters. 
http://www.di.ens.fr/pmvs/documentation.html

**Comment by smathermather** [comment]
That's very helpful.
