### ISSUE TITLE
Matching only the consecutive images in OpenSfM

### ISSUE THREAD

**Issue by AgarwalSaurav** [OpenDroneMap/ODM#602]
OpenSfM has an option matching_order_neighbors: n to match consecutive images only when the geoposition data is not available. See [this](https://github.com/mapillary/OpenSfM/issues/82). This is particularly helpful when frames are extracted from a video and it is known that the consecutive images are to be matched.

Is there a way we can activate this option while running OpenDroneMap? I believe the feature was introduced in OpenSfM on Jan 26. See [this](https://github.com/mapillary/OpenSfM/pull/133). I am not sure if ODM uses the latest OpenSfM.

**Comment by dakotabenjamin** [comment]
We haven't updated OpenSfM to the newest changes yet, we are currently working with Mapillary on some updates and will have the newest changes added with that update.

**Comment by AgarwalSaurav** [comment]
Ok thanks. Looking forward to it!

**Comment by pierotofy** [comment]
Related, I think this would also solve https://github.com/OpenDroneMap/WebODM/issues/213

**Comment by smathermather** [comment]
This is integrated.
