### ISSUE TITLE
Problems installing 

### ISSUE THREAD

**Issue by Gregoriomartjim** [OpenDroneMap/ODM#603]
Hello i am trying to install OpenDroneMap in a laptop with ubuntu 16.04
however i get this two errors while installing

[CMakeFiles/cgal.dir/all] Error 2
[cgal/stamp/cgal-download] Error 1
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALExports.cmake:83 (message):
  The imported target "CGAL::CGAL_Qt5" references the file
     "/usr/lib/x86_64-linux-gnu/libCGAL_Qt5.so.11.0.1"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALExports.cmake"
  but not all the files it references.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake:12 (include)
  modules/odm_25dmeshing/CMakeLists.txt:10 (find_package)
-- Configuring incomplete, errors occurred!
See also "/home/rafaga/Escritorio/Gregorio/OpenDrone/build/CMakeFiles/CMakeOutput.log".
See also "/home/rafaga/Escritorio/Gregorio/OpenDrone/build/CMakeFiles/CMakeError.log".
Configuration Finished

I been trying installing this libraries independently but it doesnt work 

could you help me out please

cheers

Gregorio Martinez

**Comment by yjmenezes** [comment]
@Gregoriomartjim 

Qt5 is not used by ODM.
I compile today ODM 0.3.1
try:
1- upgrade your installed Ubuntu16.04, than  run  apt-get autoremove
2- remove OpenDroneMap directory
rm  -r  ~/OpenDroneMap
3- as $ user,  git clone ODV v0.3.1
4-  as $ user, run ./configure.sh  install

ODM 0.3.1 ./configure.sh install is running softly for me under Ubuntu . /etc/os-release 16.04.2  LTS

**Comment by Gregoriomartjim** [comment]
I just reinstall ubuntu 16.04 and now it runs smoothly

Thanks
