### ISSUE TITLE
errors running opendronemap

### ISSUE THREAD

**Issue by Gregoriomartjim** [OpenDroneMap/ODM#604]
I just install OpenDroneMap, but when i try to do the ./run.sh i got this error 

File "~/OpenDrone/run.py", line 8, in <module>
    import ecto
  File "~/OpenDrone/SuperBuild/install/lib/python2.7/dist-packages/ecto/__init__.py", line 30, in <module>
    from ecto.ecto_main import _cell_base, _cell_cpp, __getitem_list__, __getitem_slice__, __getitem_str__, __getitem_tuple__, lookup
ImportError: /home/rafaga/Escritorio/Gregorio/OpenDrone/SuperBuild/install/lib/libecto.so.0.6: undefined symbol: _ZN5boost7archive23basic_binary_iprimitiveINS0_15binary_iarchiveEcSt11char_traitsIcEE4loadERSs

could some one please help me out 

Regards

**Comment by Gregoriomartjim** [comment]
I just reinstall ubuntu 16.04 and now it runs smoothly

**Comment by dakotabenjamin** [comment]
Sounds good!
