### ISSUE TITLE
Texturing: failed to read image (JPG vs jpg)

### ISSUE THREAD

**Issue by petrasovaa** [OpenDroneMap/ODM#61]
My image files have upper case extension .JPG and texturing failed because of that:

```
- running texturing - 
Error in OdmTexturing:
Error in OdmTexturing:
Failed to read image:
'/vagrant_data/uav/uav_small//DSC00016.jpg'
```

Changing file extension to .jpg helped, but it would be nice support JPG as well.

**Comment by smathermather** [comment]
Thanks @petrasovaa.  Agreed. This is a duplicate issue though, so I'm going to close it:

https://github.com/OpenDroneMap/OpenDroneMap/issues/33

If you want to try tackling it, it shouldn't be a difficult patch.
