### ISSUE TITLE
Install errors: not found GDAL

### ISSUE THREAD

**Issue by bryanibit** [OpenDroneMap/ODM#610]
FindGDAL.cmake:
 gdal-config not found. Please set it manually: GDAL_CONFIG=GDAL_CONFIG-NOTFOUND
-- Could NOT find GDAL (missing:  GDAL_LIBRARY GDAL_INCLUDE_DIR) (Required is at least version "1.9.0")
CMake Error at cmake/gdal.cmake:12 (message):
  GDAL support is required
Call Stack (most recent call first):
  CMakeLists.txt:108 (include)

-- Configuring incomplete, errors occurred!

The above is the error info. Do I need to download and install GDAL manually? Is there anyone to help me? Thank you!

**Comment by dakotabenjamin** [comment]
gdal should install in the configure script. If running `./configure.sh reinstall` doesn't work, you can manually install with `sudo apt-get install libgdal-dev`

**Comment by bryanibit** [comment]
I tried it manually and the error is solved.
