### ISSUE TITLE
Importing OpenSfM dense reconstruction using Docker

### ISSUE THREAD

**Issue by dgriffiths3** [OpenDroneMap/ODM#616]
Hi there,

Is is possible to process the OpenSfM point cloud independently, then import the results into ODM to geo-reference and create orthophoto? I am on MacOS and running ODM using docker.

If this would be quite inconvenient/not possible, is there a way to manually add the radial distortion coefficients like can with the `camera_models_overrides.json` file in OpenSfM.

Any help would be very appreciated,
Dave

**Comment by dakotabenjamin** [comment]
I'm hoping we can get the opensfm updates synched up with ODM in the next few weeks. but I think you could try to run odm up to opensfm (try the `--end-with resize` param), run opensfm, copy the results into an opensfm dir in your odm project, then run odm again (it will not overwrite if it is able to find the proper outputs). Theoretically it would work. 

This brings up an interesting point regarding importing/exporting. Something to ponder.

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/importing-opensfm-dense-reconstruction-using-docker/373
