### ISSUE TITLE
Could not find a package configuration file provided by "Eigen3"

### ISSUE THREAD

**Issue by NikhilMadaan** [OpenDroneMap/ODM#620]
While installing the latest release of ODM i'm getting the following error, i have checked solution for this issue in answers given to related issues but it was of no benefit ,

> 

CMake Warning at modules/odm_25dmeshing/CMakeLists.txt:14 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Error at modules/odm_25dmeshing/CMakeLists.txt:21 (message):
  This program requires the Eigen3 library, and will not be compiled.

-- Configuring incomplete, errors occurred!

> 
@dakotabenjamin

**Comment by naivefun** [comment]
@NikhilMadaan  I see the same error, can you please share how you solved this issue? Thanks.
