### ISSUE TITLE
No files in the pmvs folder even after the process was completed succuessfully.

### ISSUE THREAD

**Issue by NikhilMadaan** [OpenDroneMap/ODM#622]
ODM finished the process without any errors or so but nothing was present in the pmvs folder, if i'm not wrong this folder should contain the point cloud,
 
Command used:
`time python run.py -i --use-pmvs /home/user/Nikhil/images first`
and nothing was found in the pmvs folder but if i run 
`run.py  --use-pmvs  first` then point cloud is generated but i want it to be done in a single command 
Please help 

![odm_runtime_newdata](https://user-images.githubusercontent.com/22570326/27896241-5715d7a8-6236-11e7-9011-02c79a5392ca.png)

**Comment by yjmenezes** [comment]
@NikhilMadaan 
-i must be followed by image directory
run.py --help

try:
time python run.py -i  /home/user/Nikhil/images    --use-pmvs 
or
./run.sh  --project-path /home/user      Nikhil   --use-pmvs    --time

**Comment by dakotabenjamin** [comment]
Hi @NikhilMadaan did @yjmenezes suggestions work? Please reopen if not.
