### ISSUE TITLE
aligning two point clouds using georeference

### ISSUE THREAD

**Issue by Gregoriomartjim** [OpenDroneMap/ODM#623]
Hello 

I have some photos with georeference. i used opendronemap to get the point cloud but i cant get the point clouds aligned, (i used the altitude, latitude and longitude) however i cant manage to align them. 

Is there a way to do this or am i doing something wrong?
Is there a way to set the origin in opendronemap?

this is a picture of the 2 point cluods
![both00](https://user-images.githubusercontent.com/29259166/27927366-212bca2e-6251-11e7-8ae4-95f4605faf0c.png)

Regards

**Comment by dakotabenjamin** [comment]
A naive alignment will not likely work in this case. ODM currently does not have this functionality. So are these two point clouds encompassing the same area? I'm not sure exactly what I'm looking at

**Comment by Gregoriomartjim** [comment]
yes they are the same area, but different pictures. They look to have the same plane orientation, but one is above the other.

**Comment by dakotabenjamin** [comment]
OK, I think this is outside the scope of ODM, so I will close this issue.

**Comment by yjmenezes** [comment]
@dakotabenjamin , i apologise, let me reopen this issue.

@Gregoriomartjim 

it is interesting, to compare same area at different time. ( temporal analysis )
Could you, please, share your command line options and your  "logs" , and  gcp_list.txt, if available ?

**Comment by Gregoriomartjim** [comment]
well i got the GPS coordinates from a different sensor, then using exiftool i add the coordinates to the pictures, finally i used this in ODM. how could i upload the pictures ?

**Comment by yjmenezes** [comment]
@Gregoriomartjim 

you can create a new repo and upload your images.
Git has a 25MB limit for upload.
compress your images using several blocks if necessary.

**Comment by Gregoriomartjim** [comment]
https://github.com/Gregoriomartjim/gps-pictures ok i put the images here, i use the first 5 for one map and the next 5 for the second map, thanks for the answers

**Comment by yjmenezes** [comment]
@Gregoriomartjim 

It seems you do not have a good dataset.
please check:
1- exif coordinates, two images at same location
2- image size  856x480
3- camera focal mm ??? sensor width mm ???
[odm_gregorio.zip](https://github.com/OpenDroneMap/OpenDroneMap/files/1142326/odm_gregorio.zip)
4- few images,  two overlapping strips would be better.
5- GSD or flight height ?

what parameters are you using at command line ?

a ground gcp_list.txt points could  help

**Comment by Gregoriomartjim** [comment]
Hello i download a set of pictures with all the required data   [https://github.com/Gregoriomartjim/gpsimages-full-/upload/master](url), however i still have the same problem, i used the first ten in one folder and the next ten in the other, then ODM and finally i open them with meshlab, they both are in the same plane but they are stacked up, i would like to find a way to stitch the point clouds in the corresponding part in the map.  

Here is how the point clouds look , the parking lot is stacking up in the house part
![aanddstackup01](https://user-images.githubusercontent.com/29259166/28222486-50e6c4fc-688d-11e7-8d54-36429a4f5263.png)

this is the map , check out the parking lot and house.
![gcp_list_gcpposition](https://user-images.githubusercontent.com/29259166/28222496-58766ff6-688d-11e7-9369-6ecc32d1cb5b.jpg)

**Comment by yjmenezes** [comment]
@Gregoriomartjim 

I have a good dataset with painted targets gcps.  Two sets, same location, same gcps.
i am asking data set owner for permission to share  with ODM list or thru my git repo.

**Comment by Gregoriomartjim** [comment]
Thanks for your help

**Comment by dakotabenjamin** [comment]
So I think I know what is going on here. Our version of OpenSfM doesn't use altitude tags by default (OpenSfM is typically used for ground level photos from mobile phone cameras which have bad altitude values) but this could be enabled when we update OpenSfM. I'm hoping to get that working this week. If you're willing to test let me know.

**Comment by Gregoriomartjim** [comment]
yes i am totally willing to help you guys. i am working in a project where i will have to use many of the tools you have developed, so i am really interested in learn how to use OpenSfM and ODM

**Comment by yjmenezes** [comment]
@Gregoriomartjim 

if you like, i have this small and good dataset. two sets, same location and gcps.
  | set02a.tar.bz2 | 2017-07-16 18:10 | 94M |  
  | set02b.tar.bz2 | 2017-07-16 18:10 | 89M |  
  | set02gcp.tar.bz2 | 2017-07-16 18:35 | 5.9M |  

i will let it available for you here:
http://cartognu.org/hakan/

please notify me if you download it.

**Comment by Gregoriomartjim** [comment]
Thanks @yjmenezes i will try to do it and post the results 

regards

**Comment by Gregoriomartjim** [comment]
the maps are in the same plane however now we can notice a rotation , even with all the coordinates , i understand i could merge them in different manners but i would like to generate the point clouds already with the same orientations. 
![snapshot00](https://user-images.githubusercontent.com/29259166/28378703-b4d985de-6c76-11e7-8845-d085da92f48f.png)

**Comment by yjmenezes** [comment]
@Gregoriomartjim 

please, could you describe your steps ?
georeferencing is the ODM last stage ( final pipiline stage ),  models are in local coordinate system.
take a look odm_georeferencing_log.txt

**Comment by Gregoriomartjim** [comment]
I im just running ODM and then plotting the point clouds together from the folder opensfm "merged.ply". The odm_georeferencing_log.txt file is working fine, it uses the gps coordinates from the gcp list, however the pointclouds and the meshes are rotated and the dont match.

I open the .ply files from the odm_georeferencing folder and using meshlab i place them together this is what i found

the maps are better aligned but still they are shifted 

![snapshot02](https://user-images.githubusercontent.com/29259166/28428177-1e07f294-6d3e-11e7-9125-89c6c9c5561c.png)
 

Regards

**Comment by smathermather** [comment]
@Gregoriomartjim -- we are working on a branch specifically to split and rejoin datasets while using matching to ensure alignment:
https://github.com/paulinus/OpenDroneMap/tree/feature-split-dataset/scripts/metadataset

There's not a lot of documentation for this yet, but if you want to give it a try, it may help with what you're trying to do.

**Comment by Gregoriomartjim** [comment]
@smathermather  thanks for the info but i would like to have them already in position from the begging, so i wont need to use other scritp. However thanks i will check it 


Regards

**Comment by yjmenezes** [comment]
@Gregoriomartjim 

Are my dataset set02 useful for you ?
I have the set01, same location, overlapping the set02 at east side.
I think the idea can be usefull to break very large dataset into overlapping blocks.

**Comment by Gregoriomartjim** [comment]
i just got the set02a and b , if you post your set01 i will try to put them together , i also will try to split one of the sets and try to overlap both of them.


cheers

**Comment by yjmenezes** [comment]
@Gregoriomartjim 

Please, take odm_set01*  images + gcps from my server.
http://cartognu.org/hakan/

cheers

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/aligning-two-point-clouds-using-georeference/370
