### ISSUE TITLE
Single core used in Docker

### ISSUE THREAD

**Issue by eyeNsky** [OpenDroneMap/ODM#626]
Haven't checked out the project out in a while, looking good!

I ran the Docker workflow and it is only using one core on the host.

Settings:
Linux Docker 17.05.0-ce
docker system info -> CPUs: 8
docker run --cpuset-cpus has no impact.
--opensfm-processes has no impact.
gdal_translate -co NUM_THREADS=ALL_CPUS step also shows a single thread.

**Comment by pierotofy** [comment]
Hi, welcome back 😄 

Setting `--opensfm-processes` should use multiple cores.

How are you checking for the core usage?

**Comment by eyeNsky** [comment]
System Monitor on the host.

**Comment by pierotofy** [comment]
Mm, this is what I'm currently getting using opensfm-processes 2 for example:

![image](https://user-images.githubusercontent.com/1951843/28227174-ce6e843c-68a6-11e7-8878-f2f4e76a29b7.png)

```
Docker version 17.05.0-ce, build 89658bed64
```

```
Kernel Version: 4.11.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 23.42GiB
```

How does the CPU usage look like when you run:

```
docker run --rm -it --cpuset-cpus="0-3" jess/stress --cpu 4
```

?

**Comment by eyeNsky** [comment]
That lights up 4 cores.

**Comment by pierotofy** [comment]
Could you share the exact command you are using to run opendronemap?

**Comment by eyeNsky** [comment]
Ahh, I was using --cpuset-cpus incorrectly (and unnecessarily!).

I had  --cpuset-cpus="3", but the "0-3" syntax works. However, it is not needed.  Setting --opensfm-processes has the desired effect.

Thanks and mark it "Closed: User error" !!

**Comment by pierotofy** [comment]
Glad you figured it out! 😄

**Comment by mrgloom** [comment]
Also worked for me, here is full command:

`docker run --cpus 8 -it --rm -v  <images_path>:/code/images -v <odm_orthophoto_path>:/code/odm_orthophoto -v <odm_georeferencing_path>:/code/odm_georeferencing opendronemap/opendronemap --opensfm-processes 8`

But I'm not sure if `opensfm-processes` will parallelize all steps of pipeline, is it true?

**Comment by dakotabenjamin** [comment]
the rest of the pipeline is parallelized automatically where parallel processes exist. IIRC that's only in the ortho generation step

**Comment by pierotofy** [comment]
2.5D mesh generation also uses all available cores. Not sure about the rest.
