### ISSUE TITLE
Corrupt JPEG data: premature end of data segment

### ISSUE THREAD

**Issue by mfarook** [OpenDroneMap/ODM#629]
I have around 138 JPEG images and tried processing via OpenDroneMap but immediatley after the process had started up, it is resulting in an error attached below in snapshot

![jpegdatacorrupt](https://user-images.githubusercontent.com/8999372/28314033-ac8a0fb6-6bd6-11e7-9a7c-325820ac5b83.png)

Please help me what is the issue.

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/corrupt-jpeg-data-premature-end-of-data-segment/403
