### ISSUE TITLE
CMVS / PMVS Build fails when out of RAM

### ISSUE THREAD

**Issue by BangorSkis** [OpenDroneMap/ODM#63]
See #62 

Tried building ODM on Amazon's t2.micro instance (1 CPU, 1GB of ram), and the build fails.

Worth noting that by default the Amazon AMI image isn't configured to use a swap file, so that 1GB was a hard limit in my case.

**Comment by smathermather** [comment]
Looks like the related #62 is closed. Closing this as well. Let me know if it needs reopened.
