### ISSUE TITLE
Show the latest README information on opendronemap.org

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#631]
It looks like the web page at http://opendronemap.org is showing a README from a while ago; it would be beneficial to show users the latest version. cc @smathermather

**Comment by pierotofy** [comment]
FYI, to keep it up to date go to Settings:

![image](https://user-images.githubusercontent.com/1951843/28494464-8babb842-6efd-11e7-8f50-212a7f67eb5e.png)

Then change the branch to "master" instead of "gh-pages".

![image](https://user-images.githubusercontent.com/1951843/28494469-a2b78e9e-6efd-11e7-8ac4-3def1d8f124e.png)

**Comment by dakotabenjamin** [comment]
That doesn't actually work, because of the way we were building the website.

**Comment by pierotofy** [comment]
After switching to master branch, the URL at https://opendronemap.github.io/OpenDroneMap/ was correctly showing the latest README information. For the domain name to reflect the changes, the "Custom domain" field needed to be set to "opendronemap.org", otherwise github does not know how to associate the two and you'll get a 404. Hope this makes sense.

**Comment by dakotabenjamin** [comment]
Thanks, fixed.
