### ISSUE TITLE
How to combine textures?

### ISSUE THREAD

**Issue by flyandi** [OpenDroneMap/ODM#636]
I have successfully processed a lot of different stitching projects however I fail to understand how to combine all the texture files in one big happy file. 

Does ODM has a command line switch that I may missed? Or is this usually done through intensive post processing, and if so, how?

Any guidance is highly appreciated.

**Comment by dakotabenjamin** [comment]
It is not something ODM is capable of yet. We are working to some scaling improvements by the end of the year which will be able to split large datasets and then merge them, which will include textured models as well. But for now I think manual post-processing is necessary. A quick google didn't find much but this video seems to describe what you want at around the 15 min mark: https://vimeo.com/14783202

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/how-to-combine-textures/368
