### ISSUE TITLE
Improve 2.5D mesh and orthophoto

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#640]
Feel free to assign this to me, this is just a placeholder for notes and a reminder that this needs to be done at some point 😄 

The goal is to further improve the quality of orthophotos. The biggest problem that has been reported multiple times by users is that of trees appearing too much like blobs. A suggested approach would be as follow:

- Remove noise from point cloud
- Classify ground/non-ground points using PDAL's smrf filter (https://www.pdal.io/stages/filters.smrf.html, which should perhaps also be the preferred choice when calculating DSMs in lidar2dems instead of the classical pmf filter, which takes a long time to compute)
- Take the non-ground points (vegetation and buildings) and eliminate the points that surpass a certain "roughness" threshold (similar to what lasclassify does https://rapidlasso.com/lastools/lasclassify/). An algorithm for such computation has been implemented in CloudCompare http://www.cloudcompare.org/doc/wiki/index.php?title=Roughness so pulling out the code for that shouldn't be difficult. Those points are likely trees, so we remove them.
- Merge back buildings and ground points.
- Smoothing and 2.5D delaunay triangulation, which we already have in place. We can probably remove some of the stuff in the 2.5D mesh generation code at this point.

**Comment by pierotofy** [comment]
I don't think PDAL has a "roughness" filter, but perhaps somebody can point out a way to do what lasclassify does in PDAL without having to extract CloudCompare's algo?

**Comment by pierotofy** [comment]
Related #598

**Comment by PeterSprague** [comment]
That would be great.  I posted recently on odm gitter about this issue when processing a series of forest health survey images.

**Comment by dakotabenjamin** [comment]
What kind of reporting (quality, etc.) can we glean from these changes, or the mesh in general? How can we determine quantitatively improvements to the mesh?

**Comment by pierotofy** [comment]
The change would be aimed at producing better orthophotos, not at producing better meshes (I don't think we should remove vegetation for an accurate mesh). Quantitatively it should be easy to run multiple datasets with or without the 2.5D mesh option (after enhancements are added) and compare results visually to the older poisson mesh results, or compare the input images to the resulting orthophoto for artifacts and/or distortion/blobs.

**Comment by pierotofy** [comment]
Here's a tentative filter (still need to add noise filtering, maybe decimation, or just let the CGAL code handle that):

```

{
  "pipeline": [
    {
      "type":"readers.ply",
      "filename":"merged.ply"
    },
    {
      "type": "filters.smrf",
      "slope": 0.15
    },
    {
      "type": "filters.approximatecoplanar",
      "knn": 10
    },
    {
      "type": "filters.predicate",
      "script": "filter_ground_plus_coplanar.py",
      "function": "filter"
    },
    {
      "type":"writers.ply",
      "filename":"final.ply"
    }
  ]
}
```
```python
import numpy as np

def filter(ins,outs):
  cls = ins['Classification']
  cpl = ins['Coplanar']

  # Keep all ground points
  keep = np.equal(cls, 2)

  # To those, add the ones that are coplanar
  keep = keep + (np.equal(cpl, 1))

  outs['Mask'] = keep
  return True
```

**Comment by pierotofy** [comment]
Some preliminary screens:

Old:
![image](https://user-images.githubusercontent.com/1951843/31506515-9ec3ddf0-af45-11e7-88d2-80161510a92c.png)

New:
![image](https://user-images.githubusercontent.com/1951843/31506537-ac06bd34-af45-11e7-9255-01bb5ca78d8d.png)

Ground + Buildings filter:

![image](https://user-images.githubusercontent.com/1951843/31506601-dc1e7bec-af45-11e7-8dc6-1b7e47db9750.png)

**Comment by pierotofy** [comment]
After smoothing:

![image](https://user-images.githubusercontent.com/1951843/31579151-e5dced08-b0fd-11e7-9a77-2d4bc0a9fc7c.png)

**Comment by smathermather** [comment]
w00t

**Comment by pierotofy** [comment]
Review of point cloud segmentation and classification algorithms: https://www.int-arch-photogramm-remote-sens-spatial-inf-sci.net/XLII-2-W3/339/2017/isprs-archives-XLII-2-W3-339-2017.pdf

**Comment by pierotofy** [comment]
Original:

![image](https://user-images.githubusercontent.com/1951843/31854519-ac1e6932-b668-11e7-838e-5f6502b2c3f2.png)

Ground vs segmented non-ground:

![image](https://user-images.githubusercontent.com/1951843/31854521-b64baa46-b668-11e7-8cae-29ffc65fc521.png)

Ground plus planar surfaces segments:

![image](https://user-images.githubusercontent.com/1951843/31854523-c5523d02-b668-11e7-9e8a-06c1bf4686ae.png)

Original:

![image](https://user-images.githubusercontent.com/1951843/31854536-f63ec318-b668-11e7-9f42-25b8c388fc5d.png)

Ground vs segmented non-ground:

![image](https://user-images.githubusercontent.com/1951843/31854540-0483e64c-b669-11e7-9f76-1590d48f6e38.png)


Ground plus planar surfaces segments:

![image](https://user-images.githubusercontent.com/1951843/31854542-0e00b510-b669-11e7-86dc-dd86f0b17cfc.png)

Original:

![image](https://user-images.githubusercontent.com/1951843/31854709-b213e788-b66b-11e7-8413-0fe2f21a5b3e.png)

Ground vs segmented non-ground:

![image](https://user-images.githubusercontent.com/1951843/31854710-ba16b55a-b66b-11e7-9758-00171d4b02c8.png)

Ground plus planar surfaces segments:

![image](https://user-images.githubusercontent.com/1951843/31854712-c24b709e-b66b-11e7-933b-5502a1ed815f.png)

Another cool before/after screen:

![image](https://user-images.githubusercontent.com/1951843/31854731-1bb088e0-b66c-11e7-8907-c37e51c74f87.png)

![image](https://user-images.githubusercontent.com/1951843/31854733-21454db8-b66c-11e7-8209-d4091a0dc7d9.png)

**Comment by dakotabenjamin** [comment]
Are the last image pairs only removing vegetation? very cool

**Comment by pierotofy** [comment]
Yes!

**Comment by dakotabenjamin** [comment]
How far do you think until we can pull this in?

**Comment by pierotofy** [comment]
Probably 1 or 2 more weeks, depending on free time. I'm removing the 2.5D Delaunay triangulation to go back to a poisson reconstruction (without trees) since from my tests, mvs_texturing seems to find better faces when using poisson (all other things being equal). This calls for a simplification of the code base, removal of the odm_25dmeshing module and addition of the new changes to odm_meshing.

**Comment by pierotofy** [comment]
Current mesh:

![image](https://user-images.githubusercontent.com/1951843/31965024-feb91eb8-b8d3-11e7-9373-d57040c22f81.png)

New:

![image](https://user-images.githubusercontent.com/1951843/31965031-05c7b4bc-b8d4-11e7-86fc-6a7d30910e1f.png)

Current mesh:

![image](https://user-images.githubusercontent.com/1951843/31965168-780f9c42-b8d4-11e7-8c7b-5d09791375dd.png)

New:

![image](https://user-images.githubusercontent.com/1951843/31965179-7ee5436e-b8d4-11e7-9d2f-66fc6e91b0a3.png)

Current mesh:

![image](https://user-images.githubusercontent.com/1951843/31965417-5adc6ab4-b8d5-11e7-969e-2ff3e7a86c6c.png)

New:

![image](https://user-images.githubusercontent.com/1951843/31965394-45a210b8-b8d5-11e7-874c-aacfe6c09e9e.png)

**Comment by pierotofy** [comment]
On a slightly different note, @dakotabenjamin is there a reason why we've been using the dense point cloud from OpenSfM instead of the sparse one for orthophoto generation? I'm getting some good results by using the sparse output and 2.5D meshing (which doesn't have much vegetation).

![image](https://user-images.githubusercontent.com/1951843/32085710-b99e3a6c-ba9e-11e7-85fe-0712f4b97b50.png)

The bonus would be that people that just want an orthophoto (agriculture) don't need to do a dense reconstruction.

**Comment by dakotabenjamin** [comment]
No reason, let's try it!

**Comment by dakotabenjamin** [comment]
@pierotofy if you don't already have some code written for that, I could work on sparse -> ortho today.

**Comment by pierotofy** [comment]
Started working on a branch today; I've been mostly focused on slimming the 2.5D mesh module at this point. See https://github.com/pierotofy/OpenDroneMap/tree/sparse

**Comment by pierotofy** [comment]
Changes to `scripts/odm_meshing.py` in that branch need to be reverted, but we'll probably still need to run spmf from PDAL to segment ground vs non ground. Finding that excessive smoothing leads to poor building textures.

**Comment by pierotofy** [comment]
Could use some help in setting up the pipeline with ecto!

**Comment by dakotabenjamin** [comment]
Yeah that's what I was thinking

**Comment by dakotabenjamin** [comment]
How are you getting the sparse output in usable format?

**Comment by pierotofy** [comment]
First make sure min-num-frames is set to something higher than 4000. I'm getting good results with 12000 or 20000. Otherwise there are too few points to reconstruct anything decent.

`bin/opensfm_run_all <dataset>`
`bin/opensfm undistort <dataset>`
`bin/opensfm export_ply <dataset>`

Note that the resulting PLY has camera points.

For texturing we also need the nvm file:

`bin/opensfm export_visualsfm <dataset>`

**Comment by dakotabenjamin** [comment]
I'm going to avoid changing any of the ecto pipe because (1) I plan to remove it in the near future and (2) opensfm.py has both sparse and dense reconstruction so very little actually changes in the pipeline. It can be done with flags similar to --use-pmvs. 

Drawbacks is that it makes opensfm.py more unreadable than it already is. 

See: https://github.com/dakotabenjamin/OpenDroneMap/tree/sparse

**Comment by dakotabenjamin** [comment]
This should solve the camera positions: https://github.com/mapillary/OpenSfM/pull/229

**Comment by dakotabenjamin** [comment]
So what do we do if the sparse point cloud has no normal values? Have you already worked that out with the upside_down code?

**Comment by pierotofy** [comment]
The upside_down method is not relevant anymore; if the points are flipped, we'll need another way to check. I haven't delved into that yet.

**Comment by pierotofy** [comment]
I wonder if the pipeline should be rearranged in case the --sparse option is used; when a user just wants to generate an orthophoto (and doesn't care about having a 3D model, or a dense point cloud), the meshing, texturing and georeferencing steps should happen before the dense reconstruction.

In fact, since we always have a sparse reconstruction, the orthophoto should probably be always generated with the sparse reconstruction. Then we should give users the option to continue processing the dense point cloud and associated 3D model.

images --> sparse recon --> meshing (from sparse) --> texturing --> georeferencing --> orthophoto | optional from here, processing could stop if specified by user | --> dense recon --> meshing (from dense) --> texturing --> georeferencing -->  orthophoto from dense (optional)

Thoughts?

**Comment by smathermather** [comment]
I think this approach makes sense, particularly if the sparse mesh/orthophoto is good enough for most purposes. The dense construction is still a bit aspirational, requires additional optimization (which is a couple months away), better meshing (which doesn't have a timeline, etc..

**Comment by dakotabenjamin** [comment]
It's a good idea. Implementation should be fairly simple.

I've pushed some of the pipeline work up until meshing on my fork, I'll see what I can do to get the above ideas

**Comment by dakotabenjamin** [comment]
Quick question, do you envision 2.5d meshing to be run for both sparse and dense pipelines, and if not, which?

**Comment by pierotofy** [comment]
2.5D for sparse, poisson for dense. Poisson smooths the data too much for a sparse dataset (all buildings will come out severely warped). I'm currently working to improve the 2.5D meshing module to better suit a sparse dataset.

**Comment by dakotabenjamin** [comment]
Great. I'm thinking of running the pipeline similar to how you did 2.5dmeshing (because F&%$ ecto):
```
        runs = [{
            'infile': tree.opensfm_sparse_model,
            'outfile': tree.odm_mesh,
            '25dmesh': tree.odm_25dmesh
        }]
        
        if args.dense:
            if args.use_pmvs:
                runs += [{
                    'infile': tree.pmvs_model,
                    'outfile': tree.odm_mesh_dense,
                }]
            else:
                runs += [{
                    'infile': tree.opensfm_model,
                    'outfile': tree.odm_mesh_dense,
                }]
            
```

So I'll wait on your changes and then change that up through the steps.

**Comment by dakotabenjamin** [comment]
One possible solution to estimating point normals: create a plane from the nearest n points and compute the normal from that.

**Comment by pierotofy** [comment]
I don't think we'll need normals, but if we do there are a multitude of methods to estimate them. See http://pointclouds.org/documentation/tutorials/normal_estimation.php

**Comment by pierotofy** [comment]
Another approach which does not require code is to use https://www.pdal.io/stages/filters.normal.html

**Comment by dakotabenjamin** [comment]
Closing this
