### ISSUE TITLE
How are those odm_textured_model_material images generated?

### ISSUE THREAD

**Issue by hs5530hs** [OpenDroneMap/ODM#646]
I studied the code in the odm_texturing part, I found the picture output result should be **texture_*.png**  and the patches in the picture are arranged in rectangle, but I found the real picture output result in ubuntu are **odm_textured_model_material*****_map_kd.png** and the patches arrangement are irregular. I checked the  code in others part but still can't find the reasons, can anybody explain it to me? Thanks!

**Comment by dakotabenjamin** [comment]
we pull this code in: https://github.com/nmoehrle/mvs-texturing have you looked at that?

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/how-are-those-odm-textured-model-material-images-generated/379
