### ISSUE TITLE
SLAM reconstruction problem with latest release: build/bin/odm_slam: not found

### ISSUE THREAD

**Issue by DelphiR** [OpenDroneMap/ODM#649]
I downloaded the latest release and build it in 14 and 16 Ubuntu.
In both cases after all builds with SLAM support and attempt to run the reconstruction I get the same error: build/bin/odm_slam: not found

**Comment by dakotabenjamin** [comment]
I haven't looked into the SLAM module in a while, I'm sorry it isn't working for you. I've labeled it as a bug, we will look into it

**Comment by DelphiR** [comment]
Thank you. Wait for a news. It is very interesting feature of OpenDroneMap. I can support you bug fix. I can test. Please could be possbile to make a path to exisitng release (3.1) ?

**Comment by Ntweat** [comment]
I have solved this problem
Build you do cmake in build directory edit the CMakeCache.txt, fine ODM_BUILD_SLAM:BOOL to ON
and then type make
will compile

**Comment by smathermather** [comment]
Video processing has been removed.
