### ISSUE TITLE
Not an issue, just information

### ISSUE THREAD

**Issue by KommandorKeen** [OpenDroneMap/ODM#651]
https://lv.eosda.com/
is the best tool I have found for that intermediate resolution satellite images. With a big plus, display of the various indices, NDVI, etc and the option to download. Sentinel 3 or Landsat 8 are pretty good resolution. Not Worldview 2 resolution (google Earth) but more recent.

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/not-an-issue-just-information/364
