### ISSUE TITLE
Point cloud generation noisy

### ISSUE THREAD

**Issue by KommandorKeen** [OpenDroneMap/ODM#653]
![odm_colmap](https://user-images.githubusercontent.com/16811869/29400990-b8a5dd30-8372-11e7-89a2-6e9127c17e58.png)

ODM on left colmap on the right.

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/point-cloud-generation-noisy/366

**Comment by smathermather** [comment]
Discussion to date has been around improving the point cloud algorithm, filtering the points, and filtering on resultant products.

Noise reduction is needed, though it's not entirely clear where. I'm bringing this issue back as I explore this over the next few weeks. Pulling this from the [community post by Adam Steer](http://community.opendronemap.org/t/point-cloud-generation-noisy/366/2).

![image](https://user-images.githubusercontent.com/1174901/48875242-bbce4d80-edc5-11e8-9cfe-a00149149641.png)

Noise reduction on the DSM generated from these data has limited value without noise reduction further back in the toolchain:
![image](https://user-images.githubusercontent.com/1174901/48875297-1bc4f400-edc6-11e8-9ea3-e749a43a67bf.png)
![image](https://user-images.githubusercontent.com/1174901/48875299-2089a800-edc6-11e8-9bf9-e2de36b24b1a.png)

**Comment by smathermather** [comment]
Utilities for noise reduction in points and rasters: https://personalpages.manchester.ac.uk/staff/neil.mitchell/mdenoise/ (via @pierotofy).

**Comment by smathermather** [comment]
Next week, looking to test the following:
* Test changes to SMVS gamma
* Test use of OpenMVE for point cloud
* Test use of COLMAP for point cloud
* Test mdenoise on point clouds individually before merging if possible.
* Test mdenoise on point clouds once merged

**Comment by kikislater** [comment]
Good ! In case you didn't notice, mdenoise is also working in grass (it's a python script). I use it to clean drone dem. Some references : 
http://carlosgrohmann.com/denoise-srtm-grass/
http://www.portailsig.org/content/denoise-un-nouvel-algorithmeprogramme-pour-eliminer-le-bruit-des-mnt
https://grass.osgeo.org/grass74/manuals/addons/r.denoise.html

**Comment by pierotofy** [comment]
Closing, we've made lots of improvements to point clouds and DEMs since this was first opened. :+1: 

I'm willing to bet we currently outperform / or at least match COLMAP.

**Comment by smathermather** [comment]
Agreed: this issue has been thoroughly buried. :smile:
