### ISSUE TITLE
Large scale reconstruction

### ISSUE THREAD

**Issue by mrgloom** [OpenDroneMap/ODM#655]
1. Is it possible to do large scale reconstruction using some sort of distributed setup?
2. How can I rough estimate RAM requrement based on number of images? Is it possible to do some sort of incremental reconstruction in cases when full dataset doesn't fit in RAM?

**Comment by mrgloom** [comment]
Seems related
https://github.com/OpenDroneMap/OpenDroneMap/issues/497

**Comment by dakotabenjamin** [comment]
It's in the pipeline, hopefully in the next few months.
