### ISSUE TITLE
What is the status of Classified Point Clouds 

### ISSUE THREAD

**Issue by AsimAziz** [OpenDroneMap/ODM#656]
Hi, 

Sir I am successfully Classify Las Files as Ground Vs Non Ground But i want classification with further classes like **buildings,Power Lines, vegetation, vehicles, and water**.As required unit case is , I have to classify this in given point cloud.

Can You Please Inform Status of Classified Point Cloud   And  Please Also Explain Either Classification Means elements **Classification  [buildings,Power Lines, vegetation, vehicles, and water]** OR  JUST
**Ground Vs NON GROUND Classification**.

**Comment by dakotabenjamin** [comment]
Currently we only classify ground vs non-ground. I would greatly welcome contributions to this end and can answer questions as to where in the code the classification process is.

**Comment by pierotofy** [comment]
Classification happens in the lidar2dems code (via PDAL). Only ground vs non-ground. I don't think there are robust methods to classify automatically other types of objects. It's an area of active research.

**Comment by KommandorKeen** [comment]
The karttapullautin code  is the best 'general' classification code I have come across. But most of the time I will use Canupo in Cloud Compare as this allows me to define the point classes easily. 
ANOTHER alternative is to grid the data at a suitable resolution and calculate/collect:
Average Height,Height SD, Height spread, number of points, Red, Green, Blue, (sum of RGB), normalised R,G and B, for each cell and then run a clustering algorithm.

**Comment by smathermather** [comment]
@KommandorKeen -- does karttapullautin do classification of use an existing classified cloud?

I've been facinated by Canupo too -- it seems promising for shape-based classification. I know folks have also done some advanced classifications in PDAL using the variety of filters there.

**Comment by pierotofy** [comment]
Keep an eye on CGAL also... their latest beta features:

```
Classification (new package)
This package offers an algorithm that classifies a data set into a user-defined set of labels (such as ground, vegetation, buildings, etc.). A flexible API is provided so that users can classify any type of data, compute their own local features on the input data set, and define their own labels.
```

https://www.cgal.org/2018/02/27/cgal412-beta1/

No docs yet, so maybe will wait for a stable release before looking into it.

**Comment by smathermather** [comment]
Woah!

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/what-is-the-status-of-classified-point-clouds/363

**Comment by Sajjadmanal** [comment]
@AsimAziz Hi, just curious to know if you were able to classify buildings,Power Lines, vegetation, vehicles, and water too?
