### ISSUE TITLE
TopoAxis telemetry (*.tel) flight log usage

### ISSUE THREAD

**Issue by mrgloom** [OpenDroneMap/ODM#657]
Is it possible to use *.tel flight log with OpenDroneMap or it should be converted to some internal representation?

In Photoscan manual it's called `TopoAxis telemetry (*.tel)` :
Camera flight log section
http://www.agisoft.com/pdf/photoscan-pro_1_3_en.pdf

**Comment by dakotabenjamin** [comment]
Right now we don't use any flight logs or telemetry to augment the ODM process. It would be a great contribution though!

**Comment by mrgloom** [comment]
But seems ODM support georeferencing, so in what format it should be?

**Comment by dakotabenjamin** [comment]
We support GPS in camera exif data and GCP format: https://github.com/OpenDroneMap/OpenDroneMap/wiki/Running-OpenDroneMap#running-odm-with-ground-control
