### ISSUE TITLE
Multiple example datasets fail

### ISSUE THREAD

**Issue by galvanized** [OpenDroneMap/ODM#667]
I am using a freshly-installed instance of ODM on Docker, and I have been trying to get some of the [example datasets](https://github.com/OpenDroneMap/odm_data) to work. So far, I have tried four, and all of them have failed. 
As per the readme, I am running each with
 `docker run -it --rm -v $(pwd)/images:/code/images -v $(pwd)/odm_orthophoto:/code/odm_orthophoto -v $(pwd)/odm_texturing:/code/odm_texturing opendronemap/opendronemap`
while inside the correct directory.

The [aukerman](https://github.com/OpenDroneMap/odm_data_aukerman) dataset (the one suggested by the readme) gets all the way to georeferencing before failing with `ValueError: invalid literal for int() with base 10: '17N'`.
[Caliterra](https://github.com/OpenDroneMap/odm_data_caliterra) also fails on georeferencing: `ValueError: invalid literal for int() with base 10: '14N'`.
It looks like this particular problem is already documented in #450, though that user mentioned they ran the test data successfully.

During incremental reconstruction, the [benches](https://github.com/OpenDroneMap/odm_data_benchmark) dataset fails with `numpy.linalg.linalg.LinAlgError: SVD did not converge`.

Immediately after beginning incremental reconstruction, the [boruszyn](https://github.com/merkato/odm_boruszyn_kap) dataset fails with `IOError: [Errno 2] No such file or directory: '/code/opensfm/reconstruction.json'`. (Issue #607?)

I have included the output from both stdout and stderr:
[aukerman-log.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1275633/aukerman-command-log.txt)
[benches-log.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1275634/benches-log.txt)
[boruszyn-log.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1275635/boruszyn-log.txt)
[caliterra-log.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1275636/caliterra-log.txt)

I using Docker version 17.07.0-ce on Arch Linux (amd64).

Any help getting up and running is appreciated!

**Comment by dakotabenjamin** [comment]
Fixed in #665
