### ISSUE TITLE
Using Web Interface

### ISSUE THREAD

**Issue by viks2015** [OpenDroneMap/ODM#669]
I have installed opendronemap on linux directly and it is working with commandline
now how can I add web access to it.

Also I just want to combine all the drone geo-referenced images into open geotiff  image to be used with google earth and don't want a 3d model, so will the proess will be faster and what commands do I use for it.

Thansks

**Comment by dakotabenjamin** [comment]
I answered in gitter, but for posterity, check out the instructions in [OpenDroneMap/WebODM](https://github.com/OpenDroneMap/WebODM). It's technically a different software than the core ODM build. 

Currently we build the ortho-mosaic from the 3D model so you have to do the whole process. We've discussed how to do a simple stitch but the are currently no plans to implement unless a community member champions it.
