### ISSUE TITLE
Missing opensfm on the current master branch

### ISSUE THREAD

**Issue by hy9be** [OpenDroneMap/ODM#670]
I clone the current repo and try to build the master branch via the approach mentioned [here](https://github.com/OpenDroneMap/OpenDroneMap/wiki/Installation). But the ``SuperBuild/src/opensfm`` folder is empty after the installation, thus ODM cannot run.

Anyone see the same issue? Thanks!

**Comment by dakotabenjamin** [comment]
Can you run `git pull` and then `configure.sh reinstall`?

**Comment by hy9be** [comment]
Yes, I tried that but still see the empty folder. So it is okay for you guys right?

**Comment by dakotabenjamin** [comment]
I sometimes run into this. How big is your processor?

**Comment by hy9be** [comment]
I am using a 8 cpu machine. It is the aws large CPU optimized instance.

**Comment by rion-saeon** [comment]
@dakotabenjamin same issue with me. Could it be related to this: [Issue#671](https://github.com/OpenDroneMap/OpenDroneMap/issues/671)

and subsequent Docker Run on example dataset from ODM site;
`docker run -it --rm -v /home/rion/Desktop/odm_projects/odm_data_aukerman-master/images:/code/images -v /home/rion/Desktop/odm_projects/odm_data_aukerman-master/odm_orthophoto:/code/odm_orthophoto -v /home/rion/Desktop/odm_projects/odm_data_aukerman-master/odm_georeferencing:/code/odm_georeferencing opendronemap/opendronemap`
![screenshot from 2017-09-15 13 23 16](https://user-images.githubusercontent.com/13643064/30480359-a6dd1434-9a19-11e7-915a-00b535570068.png)

Also tried what you mentioned above:
![screenshot from 2017-09-15 13 35 00](https://user-images.githubusercontent.com/13643064/30480586-bcb354a2-9a1a-11e7-8c3e-64e7420000ee.png)


PC specs: 
![screenshot from 2017-09-15 13 29 50](https://user-images.githubusercontent.com/13643064/30480448-0870e400-9a1a-11e7-8c47-349893daf9f0.png)

**Comment by hy9be** [comment]
@rionlerm I am not sure if ours are the same issue. Does your configure.sh start with ``#!/bin/bash``? Or maybe you can try ``bash configure.sh reinstall``.

**Comment by rion-saeon** [comment]
Hi @hy9be, my configure.sh is run via the latter code you mentioned. Your install approach I used in the past to install ODM a while back. Since then follow new approach by just reinstalling.
