### ISSUE TITLE
Reinstall error

### ISSUE THREAD

**Issue by rion-saeon** [OpenDroneMap/ODM#671]
![screenshot from 2017-09-15 11 26 53](https://user-images.githubusercontent.com/13643064/30476181-7ab5915c-9a09-11e7-90e3-7883704fb656.png)

@dakotabenjamin I can e-mail the CMakeOutput.log?

**Comment by rion-saeon** [comment]
Problem persists when passing `bash configure.sh reinstall` in Ubuntu 16.04
![screenshot from 2017-09-18 13-39-24](https://user-images.githubusercontent.com/13643064/30540324-f6b36800-9c76-11e7-832b-6245a2a7f7cc.png)

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/reinstall-error/404
