### ISSUE TITLE
run ODM with Docker in Windows

### ISSUE THREAD

**Issue by danng007** [OpenDroneMap/ODM#673]
Hi,

I'm a new user for this. After all install, I got an error: Not enough supported images in /code/images. Anyone can help please?

I created a folder called 'images' in current working directory, and downloaded some images from https://github.com/OpenDroneMap/odm_data. 

my docker running command is : docker run -it --rm -v $(pwd)/images:/code/images -v $(pwd)/odm_orthophoto:/code/odm_orthophoto -v $(pwd)/odm_georeferencing:/code/odm_georeferencing opendronemap/opendronemap. Then the error will appear.

Thanks for anyone's help.
Best,
Wantao

**Comment by danng007** [comment]
The full print after enter the command is:
[INFO]    Initializing OpenDroneMap app - Thu Sep 21 16:05:50  2017
[INFO]    Running ODM Load Dataset Cell
[DEBUG]   Loading dataset from: /code/images
[DEBUG]   /code/images
[ERROR]   Not enough supported images in /code/images
[INFO]    OpenDroneMap app finished - Thu Sep 21 16:05:50  2017

**Comment by PeterSprague** [comment]
I don't work in Windows, but first thing I would check is your permissions.

I noticed you had asked for help on gitter.  My take on this issue is that it is not a ODM code issue, but specific to the user environment.  That is what the Gitter help page is for.
