### ISSUE TITLE
odm_extract_utm does not parse altitude correctly

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#674]
Thanks @fredlllll for helping diagnose this bug

In https://github.com/OpenDroneMap/OpenDroneMap/blob/master/modules/odm_extract_utm/src/UtmExtractor.cpp#L310 odm_utm_extract is looking for the jhead output with "GPS Altitude :" but this is not always how image exif is saved. See: 
![image](https://user-images.githubusercontent.com/1847818/30714478-ea549b26-9ee0-11e7-93ae-166423623877.png)
vs:
![image](https://user-images.githubusercontent.com/1847818/30714949-ba1a16b4-9ee2-11e7-923b-dcf234eb7f75.png)

This is both an issue with odm_utm_extract AND jhead. We should find a new library for reading image exif into C++ and update the module. Options include ImageMagick's identify script, exiftool (which is slow and depends on perl), libexif, or [Exiv2](http://www.exiv2.org).

**Comment by dakotabenjamin** [comment]
exiv2 dependencies are all free software:
```
Feature                     Package   Configure options
--------------------------  --------  ----------------------------
PNG image support           zlib      --without-zlib
                                      --with-zlib=DIR
Native language support     gettext   --disable-nls
Characterset conversions    libiconv  --without-libiconv-prefix
                                      --with-libiconv-prefix[=DIR]
XMP support                 expat     --disable-xmp
                                      --with-expat=DIR

zlib         http://zlib.net/
gettext  *)  http://www.gnu.org/software/gettext/
libiconv *)  http://www.gnu.org/software/libiconv/
expat        http://expat.sourceforge.net/
```

**Comment by fredlllll** [comment]
dependencies for imagemagick here https://github.com/ImageMagick/ImageMagick/blob/master/Install-unix.txt under the "Delegate Configuration"

**Comment by dakotabenjamin** [comment]
a native c++ library is probably more ideal anyways. see: http://exiv2.org/examples.html#example1

**Comment by fredlllll** [comment]
looks much cleaner than the current parsing using a temporary file and the sketchy string processing

**Comment by KommandorKeen** [comment]
Just pulled your fix, compiled it, and am running it now. 
In the opensfm directory the data in the individual exif data files matches the RTK data I inserted into the header using EXIFtool :-).  Just processing the images now, but this is a great step forward as the aircraft is a Phantom4 with an Emlid Reach kinematic GPS post-processed.

I can confirm this fix  works well. Now if I can find that modification to the opensfm config that puts a higher weighting (by modifying the pdop) on the GPS position I will be real happy.

**Comment by dakotabenjamin** [comment]
Merged in master
