### ISSUE TITLE
Missing Checkerboard link

### ISSUE THREAD

**Issue by Ntweat** [OpenDroneMap/ODM#678]
Hi 
I built opendrone with ORB SLAM, but the checkerboad link is not working.
Where else can I find it?

**Comment by pierotofy** [comment]
Does this work? http://docs.opencv.org/2.4/_downloads/pattern.png

Could you also point out where the broken link is exactly?

**Comment by Ntweat** [comment]
@pierotofy  Thanks 

Links are broken on https://github.com/OpenDroneMap/OpenDroneMap/wiki/Reconstruction-from-Video 

All the dropbox links are broken

**Comment by pierotofy** [comment]
Mm, @smathermather  are you dropbox user `2801164`? 😄

**Comment by smathermather** [comment]
Noap. But I bet @paulinus is.

**Comment by Ntweat** [comment]
@pierotofy @smathermather  can you give me the config.yaml and the castle video files? 
I tried running opendrone sfm on my video it is not able to track the camera or features.

**Comment by dakotabenjamin** [comment]
@Ntweat sorry for the late reply- I've fixed some of the links but I don't have access to the video files. I hope that helps a little.

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/missing-checkerboard-link/380
