### ISSUE TITLE
How can i get control over point cloud ? 

### ISSUE THREAD

**Issue by gogikomal** [OpenDroneMap/ODM#680]
Hey, 
I have installed OpenDroneMap in Linux 16.04, once the the data set is run and extracted the result is viewed in Meshlab, I'm facing problems in point cloud results as the gaps are not filled resulting in texturing image not being that smooth 
The Parameters i changed are
--resize: 4000
--use-pmvs: true 
--pmvs-level: 0
--pmvs-csize: 1  
How can i fill the gaps in point cloud and smooth the texturing ?

**Comment by dakotabenjamin** [comment]
Using the default depth mapping should produce more points overall -> fewer holes.

**Comment by gogikomal** [comment]
I got better results by using --use-25dmesh : true, most of the gaps were filled
