### ISSUE TITLE
How to use only orthophoto module of ODM with openmvs+openmvg pipeline?

### ISSUE THREAD

**Issue by ManishSahu53** [OpenDroneMap/ODM#681]
I am using openMVG+openMVS project to produce dense point cloud. I want to use ODM orthophoto module to generate orthomosaic of my dataset. Can anyone suggest me how to do it? Thanks

**Comment by ManishSahu53** [comment]
I used the python script orthophoto.py of ODM itself to generate orthomosaic.

**Comment by KeoChi** [comment]
Hello! I also want to use openMVG+openMVS instead of the OpenSFM+smvs. Can you share your detailed practice? I found that the coordinates of openMVG are different from the coordinates of OpenSfM.
