### ISSUE TITLE
Generating texture patches Killed 

### ISSUE THREAD

**Issue by YingyingXie16** [OpenDroneMap/ODM#682]
I'm running opendronemap through docker on windows10.

![image](https://user-images.githubusercontent.com/21263377/31293219-76da0422-aaa4-11e7-9141-997b5f79dfa6.png)

I tried a few times, but always got empty folders of odm_orthophoto and odm_georeferencing, and a folder of odm_texturing with three files: odm_textured_model_data_costs, odm_textured_model.conf, and odm_textured_model_labeling.vec.

The processing showed:
![image](https://user-images.githubusercontent.com/21263377/31293347-e73cad8c-aaa4-11e7-96eb-0c4a5b1b2662.png)

I'm not sure what's wrong. Please help. Thanks.

**Comment by dakotabenjamin** [comment]
Can you share the odm_meshing/odm_mesh.ply?

**Comment by YingyingXie16** [comment]
Yeah, but could you help me find the odm_meshing/odm_mesh.ply? I'm not sure where to find it...thanks.

**Comment by bingzhang** [comment]
Hello,

I have the same issue on running on the sample dataset ``Download a sample dataset from here (about 550MB)''

I use docker ce17 on mac.

`docker run -it --rm -v /localpath/odm_data_aukerman-master/images/:/code/images opendronemap/opendronemap`

```
	0000	Increase of energy - stopping optimization
	Took: 54.74s
Generating texture patches:
	Running... Killed
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/mvstex.py", line 124, in process
    '{keepUnseenFaces}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 137
```

**Comment by YingyingXie16** [comment]
@dakotabenjamin I rerun the process and output the odm-mesh.ply file today. I also opened this file in MeshLab. It seems that it's ok as it does show the right landscape captured in my test photos, just some trees around a parking lot with cars and a few buildings. I still do not know what's wrong with the killed texturing process. 

Please check the odm_meshing/odm_mesh.ply in the attached zip file. Thanks.

[odm_meshing.zip](https://github.com/OpenDroneMap/OpenDroneMap/files/1377154/odm_meshing.zip)

**Comment by dakotabenjamin** [comment]
Can you try running without the --mesh-size option? It may be decimating too much.

**Comment by bingzhang** [comment]
@dakotabenjamin , please see my post, I did not use --mesh-size option, but still get the same error.

**Comment by YingyingXie16** [comment]
@dakotabenjamin OK, I ran it without the --mesh-size option, and it proceeded a bit but still got Blending texture patches killed...Please help.

> Generating texture patches:
>         Running... done. (Took 33.747s)
>         4521 texture patches.
> Running global seam leveling:
>         Create matrices for optimization...  done.
>         Lhs dimensionality: 105378 x 105378
>         Calculating adjustments:
>                 Color channel 0: CG took 112 iterations. Residual is 9.78849e-05
>                 Color channel 2: CG took 113 iterations. Residual is 9.8304e-05
>                 Color channel 1: CG took 114 iterations. Residual is 9.91845e-05
>                 Took 0.801 seconds
>         Adjusting texture patches 100%... done. (Took 100.08s)
> Running local seam leveling:
>         Blending texture patches 21%...Killed
> Traceback (most recent call last):
>   File "/code/run.py", line 47, in <module>
>     plasm.execute(niter=1)
>   File "/code/scripts/mvstex.py", line 124, in process
>     '{keepUnseenFaces}'.format(**kwargs))
>   File "/code/opendm/system.py", line 34, in run
>     raise Exception("Child returned {}".format(retcode))
> Exception: Child returned 137

**Comment by dakotabenjamin** [comment]
OK both of you please tell me how much memory is allocated to docker, and then increase if it's only like 4GB

**Comment by bingzhang** [comment]
Thanks, @dakotabenjamin! 
By increasing the memory, it works perfectly. Maybe a further question, the memory will be related to the size of datasets? What is your suggestion of the minimum memory.

**Comment by dakotabenjamin** [comment]
Yeah more images => more memory overhead. I suggest 8 for bare minimum
