### ISSUE TITLE
global debug logging level

### ISSUE THREAD

**Issue by bingzhang** [OpenDroneMap/ODM#685]
Hello:

It seems opendronemap enables the global debug logging level, can you set logging level just to the modules of opendronemap?

Regards.

**Comment by dakotabenjamin** [comment]
The logging level is set here: https://github.com/OpenDroneMap/OpenDroneMap/blob/master/opendm/log.py#L17

so we could set up a parameter like `--logging info|debug` or something like that and default it to info. Or we could change the already existing `--verbose` param to enable the debug logging.
