### ISSUE TITLE
What vertical datum is my data in?

### ISSUE THREAD

**Issue by ghost** [OpenDroneMap/ODM#688]
I have processed drone imagery using OpenDroneMap captured with a DJIP3P using the latest firmware.
The data were processed without any GCP data.  The drone is suppose to record elevation values in height above the home point.  The imagery was captured with the drone at 40m.  My resulting LAS points plot values between -2 and -13.  The elevation at this location is ~10feet(NAVD88).  What are the elevation values relative to?

**Comment by PeterSprague** [comment]
This question may get faster response in ODM Gitter help or the new discourse discussion when on-line.  Please copy question to Gitter for help from a great group of users and developers.

To possibly answer your question, I believe all GPS use WGS-84 as their datum.  My logs show absolute height in meters above sea level when inserted in EXIF of images.

**Comment by ghost** [comment]
Sorry for choosing the wrong venue but maybe it is an issue.  The EXIF headers of the images show an elevation 114ft but the LAS files output from ODM have z values of -2.114 to -13.199.  I am not sure if the output from ODM shows Z in meters but I am assuming so since the X and Y data are in UTM10N.  I have confimed with DJI that the DJIP3P with the latest firmware is capturing Z values in height above the home point using the altimemeter and not the GPS elevation. The same images processed in DroneDeploy return values between 1.5 and 6.6 which would be constant with the expected values of height above the home origin.

**Comment by PeterSprague** [comment]
No worries, was just a suggestion because often the Gitter help yields quicker response.  Might actually be an issue.  

If using altimeter, not GPS, then my response is not relevant.  Have revised my response.

**Comment by dakotabenjamin** [comment]
Unless I'm mistaken, I believe we've resolved this issue.

**Comment by ghost** [comment]
Yes. Resolved. The odd readings come from DroneDeploy which is basically making up elevation data. OpenDroneMap is returning the correct elevation values based on EXIF.
Open source wins again.
Thanks. Do I need to take any further action?


Sent from my Verizon Wireless 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Dakota Benjamin <notifications@github.com> </div><div>Date:10/20/2017  4:26 PM  (GMT-08:00) </div><div>To: OpenDroneMap/OpenDroneMap <OpenDroneMap@noreply.github.com> </div><div>Cc: Gerry Gabrisch <gerry@gabrisch.us>,Author <author@noreply.github.com> </div><div>Subject: Re: [OpenDroneMap/OpenDroneMap] What vertical datum is my data in?
  (#688) </div><div>
</div>Unless I'm mistaken, I believe we've resolved this issue.
