### ISSUE TITLE
what is the option to limit the maximum memory usage of odm?

### ISSUE THREAD

**Issue by bingzhang** [OpenDroneMap/ODM#701]
I witness the memory usage peak would be very high, for one dataset, the peak is 20GB.
Is there a way to limit the maximum memory usage of odm without breaking anything?

Regards.

**Comment by dakotabenjamin** [comment]
There are some options that affect memory usage for specific parts of the process, but no global limiter. Do you know where the memory is peaking? 

For example, you can reduce memory usage during opensfm by lowering the number of parallel processes. It defaults to using all, so you could try half or just 1 or 2. 
```
--opensfm-processes n
```

**Comment by kikislater** [comment]
With cgroup it's possible to limit memory usage but odm will crash I think
