### ISSUE TITLE
Unable to install opendrone map under ubuntu 16.0.5

### ISSUE THREAD

**Issue by peteraftsamy** [OpenDroneMap/ODM#704]
Hi,
am trying to install the opendronemap under ubuntu 16.0.5  however each time am ending up with 
----------------
ImportError: No module named csfm
Traceback (most recent call last):
  File "/home/peter/OpenDroneMap-0.3.1/run.py", line 46, in <module>
    plasm.execute(niter=1)
  File "/home/peter/OpenDroneMap-0.3.1/scripts/opensfm.py", line 85, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/home/peter/OpenDroneMap-0.3.1/opendm/system.py", line 28, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
peter@ajay-pc:~/OpenDroneMap-0.3.1$ 

Could u pl. advise

**Comment by dakotabenjamin** [comment]
Hi,

Occasionally when installing some modules will fail to install due to some race conditions. Try running the installer again to see if opensfm installs properly. Let me know if that doesn't work.

**Comment by peteraftsamy** [comment]
tried more than 3 times....but unable to proceed....

**Comment by dakotabenjamin** [comment]
OK, can you clarify what operating system you are using? Ubuntu 16.0.5 is not a version that exists. 

Can you also find any errors in the configure output? That will help too.

**Comment by dakotabenjamin** [comment]
Due to inactivity I will close this issue, please reopen if the problem is persisting.
