### ISSUE TITLE
options to generate higher resolution of orthograph

### ISSUE THREAD

**Issue by bingzhang** [OpenDroneMap/ODM#705]
Hello:

I have a dataset with 200+ image and total size is 1.5 GB. By default 40 pixels per meter, the output orthograph is around 200 MB. I tried to increase to 70 pixels per meter, the output orthograph size does not increase however a little bit less than the default 40 setting. By using another tool, the output result size is around 1 GB. Is there a way to increase the output size of orthograph, please?

Regards.

**Comment by dakotabenjamin** [comment]
It depends on the resolution of your images. If you try to increase the resolution higher than the resolution of your images, then you won't get anything higher. It's possible the other tool is not efficiently handling the orthomosaic. It is also possible that the other tool is processing a larger area. ODM tends to be more conservative around the geographic edges of a dataset, and therefore will construct a smaller orthophoto, despite having the same resolution.
