### ISSUE TITLE
Crash in system.py

### ISSUE THREAD

**Issue by lorenzo93** [OpenDroneMap/ODM#706]
I ran the Docker container provided by you and at some point it crashes as showed by the screenshot.
Is there any fix?

![screenshot_171](https://user-images.githubusercontent.com/12275050/32500442-bb22b508-c3d5-11e7-89a9-9c11eed47b00.png)

**Comment by dakotabenjamin** [comment]
I think you have to increase the memory of the docker instance

**Comment by lorenzo93** [comment]
I gave docker 20GB of RAM, is it not enough?

**Comment by dakotabenjamin** [comment]
No that should be enough. Can you give me more information? I see you're running docker in Windows. What was your run command?

**Comment by lorenzo93** [comment]
The one provided in your guide, modified with my paths:

docker run -it --rm -v D:\images:/code/images -v D:\odm_orthophoto:/code/odm_orthophoto -v D:\odm_texturing:/code/odm_texturing opendronemap/opendronemap

The model it is very big, 370 pictures 3000x4000 each

**Comment by pierotofy** [comment]
@dakotabenjamin I wonder if the addition of TBB https://github.com/nmoehrle/mvs-texturing/commit/313f20379bcca7db90bbcae636224ffb94252161 has caused memory usage to go up. I've seen quite a bit of reports like this in the last few weeks.

edit: never mind, those changes have not been added to ODM. 

The generating textures patches step is very memory intensive however.

**Comment by pierotofy** [comment]
I think we're seeing this happening more often because the images are pulled in their original definition (they are not resized, since we have removed the resize module).

The input images come from opensfm's `undistort` directory, and the files used to be resized.

**Comment by pierotofy** [comment]
There's a linear correlation between image size and memory usage in the texrecon program.

A 170 image dataset at 4000px (largest side) used about 9GB of memory while running. The same dataset scaled to 2000px used about 5GB. We could consider re-adding the resize module to reduce memory usage.

Edit: or modify texrecon to support scaled images. But then we would be doing two resizes (one in opensfm, one in texrecon).
