### ISSUE TITLE
orthophoto distortion

### ISSUE THREAD

**Issue by bingzhang** [OpenDroneMap/ODM#709]
I use the default 20 pixel per meter and sometimes I found there is distortion in orthophoto. May I know there is option to remove distortion, please?

The line should be straight and continuous in the below image.
<img width="63" alt="screen shot 2017-11-13 at 10 56 10 am" src="https://user-images.githubusercontent.com/5349154/32738043-58b2e7e0-c861-11e7-9e38-68cd620afa80.png">

**Comment by KommandorKeen** [comment]
@dakotabenjamin has code for undistorting images prior to use in ODM and ODM allows for undistortion to be turned off.  Does rely on you having a good camera calibration first though.

**Comment by bingzhang** [comment]
@dakotabenjamin, May I have the code to try the undistorting images?

**Comment by dakotabenjamin** [comment]
https://github.com/dakotabenjamin/cameracalibration

Also, you may run into distortion like that if your mesh is small. You can increase that using `--mesh-size`. Default is 100k. Increasing `--mesh-octree-depth` to 10 or 11 may also help.
