### ISSUE TITLE
Offsets for GCPs - how are they calculated and why

### ISSUE THREAD

**Issue by CarlosGrohmann** [OpenDroneMap/ODM#713]
Checking the log for a dataset processed with ODM using GCPs, I noticed this (only 4 first lines of GCPS shown):

```
Reading following GCPs from file:
x_: 316675 y_: 7.40503e+06 z_: 939.968 pixelX_: 638 pixelY_: 2970 image: DJI_0026.jpg
x_: 316689 y_: 7.40508e+06 z_: 918.39 pixelX_: 726 pixelY_: 172 image: DJI_0026.jpg
x_: 316689 y_: 7.40508e+06 z_: 918.39 pixelX_: 472 pixelY_: 578 image: DJI_0027.jpg
x_: 316689 y_: 7.40508e+06 z_: 918.39 pixelX_: 208 pixelY_: 1131 image: DJI_0028.jpg

The calculated easting offset for the georeferenced system: 316587
The calculated northing offset for the georeferenced system: 7.40506e+06

Recalculated GCPs with offset:
x_: 88.449 y_: -23.201 z_: 939.968
x_: 102.126 y_: 27.739 z_: 918.39
x_: 102.126 y_: 27.739 z_: 918.39
x_: 102.126 y_: 27.739 z_: 918.39
```

This is similar to the optional 'shift' of coordinates in Photoscan. From what I could find, this is done to increase the numerical stability of the computations.

Thinking in a proper description of methods (for a near-future scientific paper), I wonder if someone could provide a simple explanation about the 'numerical stability', or point me to a reference.

thanks

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/offsets-for-gcps-how-are-they-calculated-and-why/360
