### ISSUE TITLE
DEM generation option is ambiguous

### ISSUE THREAD

**Issue by June-Skeeter** [OpenDroneMap/ODM#715]
I'm trying to create a DEM, but when I run the following command:

`ubuntu@ip-172-31-7-75:~/OpenDroneMap$ ./run.sh -i /home/ubuntu/Temp_Data 821_Down_and_Oblique_HighRes_wDEM --opensfm-processes 8 --min-num-features 10000 --dem --use-25dmesh`

I get this traceback
```
usage: run.py [options] <project name>
run.py: error: ambiguous option: --dem could match --dem-gapfill-steps, --dem-resolution, --dem-maxsd, --dem-approximate, --dem-terrain-type, --dem-maxangle, --dem-initial-distance, --dem-decimation
```

**Comment by dakotabenjamin** [comment]
You will want to use either `--dtm` or `--dsm` instead.

**Comment by dakotabenjamin** [comment]
Closing this, please reopen if you still have issues.
