### ISSUE TITLE
Process with knn-matching and odm_georeferencing even when there is malformed geotags

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#728]
It shouldn't disable knn-matching or fail at georeferencing when there's one or two images that didn't get tagged right. 

Other options: 
- throw out the images (could break reconstruction)
- make the missing images only match all other images (not as fast as knn but faster than pairwise)
- ??? other ???

**Comment by pierotofy** [comment]
I'd say throw out the images and emit a warning.

**Comment by pierotofy** [comment]
I think this can be closed, as it refers to code we no longer use. :+1:
