### ISSUE TITLE
Extracting registered images pair

### ISSUE THREAD

**Issue by arielbenitah** [OpenDroneMap/ODM#733]
Not an issue: just a question: is there a way to extract registered images pair with their corresponding matching features?
thanks for your help...

**Comment by pierotofy** [comment]
Mm, out of the box, I don't think so. You might have to modify opensfm's code to get that information out.

What is the use case here? Just curious 😄

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/extracting-registered-images-pair/362
