### ISSUE TITLE
Remove sudo statements from configure.sh

### ISSUE THREAD

**Issue by tomasholderness** [OpenDroneMap/ODM#738]
Currently, configure.sh prefixes individual commands with `sudo` which breaks in environments where `sudo` is not installed and user is already `root`.

I would propose removing `sudo` prefixes from the script and updating documentation to advise users to do `sudo configure.sh install` in environments where it is required.

An example of the configure.sh script without `sudo` statements can be seen [here](https://github.com/OpenDroneMap/OpenDroneMap/commit/53cf8f62fd4d2e6dea1b49d1364fb959e04a8b1f).

**Comment by dakotabenjamin** [comment]
This is a good idea. 

I've always felt weird using `sudo` and on top of that installing dependencies like we do might anger some potential users.
