### ISSUE TITLE
"No module named osgeo" while trying to run opendronemap docker image

### ISSUE THREAD

**Issue by cleberzavadniak** [OpenDroneMap/ODM#747]
- Docker is "brand new";
- `docker pull opendronemap/opendronemap`
- `docker run -v /mnt/tmp/photos/01C4AGZ67NZSXP143HRTPS68F9/photos:/code/images -v /mnt/tmp/odm/ticket-01C4AHAC1T2NF9P4XMER2ZV4DV/project/odm_texturing:/code/odm_texturing -v /mnt/tmp/odm/ticket-01C4AHAC1T2NF9P4XMER2ZV4DV/project/odm_meshing:/code/odm_meshing opendronemap/opendronemap -e mvs_texturing`

```
Traceback (most recent call last):
  File "/code/run.py", line 11, in <module>
    from scripts.odm_app import ODMApp
  File "/code/scripts/odm_app.py", line 16, in <module>
    from odm_georeferencing import ODMGeoreferencingCell
  File "/code/scripts/odm_georeferencing.py", line 10, in <module>
    from opendm.cropper import Cropper
  File "/code/opendm/cropper.py", line 4, in <module>
    from osgeo import ogr
ImportError: No module named osgeo
```

This error is new, and I think it may be connected to the new Docker image, that was pushed "17h ago".

I have no idea what to do.
Can I use the old image? Is it available at Docker hub?
Thanks.

**Comment by cleberzavadniak** [comment]
Well, it seems to work with `docker pull opendronemap/opendronemap:wb`.
What does the `wb` tag means?

**Comment by dakotabenjamin** [comment]
This is a known bug and should be fixed soon! Thanks for reporting. 

see: https://github.com/OpenDroneMap/OpenDroneMap/commit/0fdea3d145a3818c5ae729538155ab9b716e5826#commitcomment-27023033

**Comment by pierotofy** [comment]
This will be fixed within 24 hours (when the new docker images are pushed to docker hub).

Just issue a `docker pull opendronemap/opendronemap`.
