### ISSUE TITLE
ODM Texturing fails for images with all caps extension

### ISSUE THREAD

**Issue by nirabpudasaini** [OpenDroneMap/ODM#75]
The Texturing step is failing because it is trying to read the image "DJI02051.jpg" in OdmTexturing::loadCameras() but i have "DJI02051.JPG" as my source image. 

The code fails to read my file because of the case of the extension which is the default that i get from the Camera of DJI drone. The file is read after changing the "JPG" to "jpg".

**Comment by smathermather** [comment]
Hi @nirabpudasaini,

This is a known issue: https://github.com/OpenDroneMap/OpenDroneMap/issues/33 (see also https://github.com/OpenDroneMap/OpenDroneMap/issues/61 ) although apparently it was closed. I re-opened. Would definitely welcome a patch!

Best
