### ISSUE TITLE
enabling fast-orthophoto causes 25dmeshing seg fault

### ISSUE THREAD

**Issue by PeterSprague** [OpenDroneMap/ODM#754]
Successfully runs and produces ortho w/o fast-orthophoto enabled.  Opensfm_processes set to 12 on an AMD64 32 core 64Gb workstation.

With fast-orthophoto enabled:
2018-01-31 20:43:33,473 DEBUG: Undistorting image 2017_0909_114819_028.JPG
2018-01-31 20:43:33,505 DEBUG: Undistorting image 2017_0909_115521_230.JPG
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_ply --no-cameras /var/www/data/60dc1e42-05d0-4b17-af63-e03077f64b56/opensfm
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/export_bundler /var/www/data/60dc1e42-05d0-4b17-af63-e03077f64b56/opensfm
[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running ODM Meshing Cell
[DEBUG]   Writing ODM 2.5D Mesh file in: /var/www/data/60dc1e42-05d0-4b17-af63-e03077f64b56/odm_meshing/odm_25dmesh.ply
[DEBUG]   running /code/build/bin/odm_25dmeshing -inputFile /var/www/data/60dc1e42-05d0-4b17-af63-e03077f64b56/opensfm/reconstruction.ply -outputFile /var/www/data/60dc1e42-05d0-4b17-af63-e03077f64b56/odm_meshing/odm_25dmesh.ply -logFile /var/www/data/60dc1e42-05d0-4b17-af63-e03077f64b56/odm_meshing/odm_25dmeshing_log.txt -maxVertexCount 30000 -neighbors 24 -resolution 0 -verbose
Loading point cloud... loaded 167044 points
Remove outliers... 8878 points removed
Squash point cloud to plane... Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_meshing.py", line 105, in process
    '-resolution {resolution} {verbose}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 139

**Comment by pierotofy** [comment]
Could you share your `/var/www/data/60dc1e42-05d0-4b17-af63-e03077f64b56/opensfm/reconstruction.ply`? This might be a bug.

Thank you!

**Comment by PeterSprague** [comment]
Here is the file.  I am using VTK v8.1.0 built from source, not v7.1.1 as originally specified in cmake
[reconstruction.ply.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1683385/reconstruction.ply.txt)

**Comment by pierotofy** [comment]
That might be the root cause of the issue. I ran this on a VTK7 build and the task ran successfully. 

```
./odm_25dmeshing -inputFile ./reconstruction.ply -outputFile test_output.ply -verbose
Loading point cloud... loaded 167044 points
Remove outliers... 8878 points removed
Squash point cloud to plane... OK
Automatically set resolution to 3.962223
Plane extentX: 280.582718, extentY: 403.588531
DSM size is 1112x1600 (8.000000 MB) 
Point interpolation using shepard's kernel... OK
Transfering interpolation results to DSM... OK
Median filter...OK
Triangulate... OK
Transform... OK
Saving mesh to file... OK
```

[test_output.ply.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1683402/test_output.ply.txt)

**Comment by PeterSprague** [comment]
Check the errors here: https://github.com/mapillary/OpenSfM/issues/277
Almost exactly the same.  Would your core2 solution work here?

**Comment by PeterSprague** [comment]
Reverted to VTK v7.1.1 built from source, includes vtk6-dev pkg  opensf_processes @16

[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running ODM Meshing Cell
[DEBUG]   Writing ODM 2.5D Mesh file in: /var/www/data/34d695f9-4899-45d7-bb8a-21d369d8623f/odm_meshing/odm_25dmesh.ply
[DEBUG]   running /code/build/bin/odm_25dmeshing -inputFile /var/www/data/34d695f9-4899-45d7-bb8a-21d369d8623f/opensfm/reconstruction.ply -outputFile /var/www/data/34d695f9-4899-45d7-bb8a-21d369d8623f/odm_meshing/odm_25dmesh.ply -logFile /var/www/data/34d695f9-4899-45d7-bb8a-21d369d8623f/odm_meshing/odm_25dmeshing_log.txt -maxVertexCount 30000 -neighbors 24 -resolution 0 -verbose
Loading point cloud... loaded 167208 points
Remove outliers... 8499 points removed
Squash point cloud to plane... Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_meshing.py", line 105, in process
    '-resolution {resolution} {verbose}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 139

**Comment by pierotofy** [comment]
I really don't know what the cause would be. Can you recover the `core` dump file and attach it here? Perhaps we'll know more once we take a look at it.

**Comment by PeterSprague** [comment]
Reverted  back to VTK v8.1.0, run on amd64 32 core w/ 64Gb 
Built opengv --> core2 flag

w/o fast_ortho @16 opensfm_processes--> 157 block-1-east test images
produced nice looking ortho @01:49

w/ fast_orthophoto opensfm_processes @16 
running all night, no results, just sitting at ceres solver, load @~8, python thread showing in top
rerun --> error @01:17

2018-02-01 16:36:43,224 DEBUG: Undistorting image 2017_0909_114819_028.JPG
2018-02-01 16:36:43,266 DEBUG: Undistorting image 2017_0909_115521_230.JPG
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_ply --no-cameras /var/www/data/9a54d9c4-c4b2-4c6f-8349-7d3a4a99e705/opensfm
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/export_bundler /var/www/data/9a54d9c4-c4b2-4c6f-8349-7d3a4a99e705/opensfm
[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running ODM Meshing Cell
[DEBUG]   Writing ODM 2.5D Mesh file in: /var/www/data/9a54d9c4-c4b2-4c6f-8349-7d3a4a99e705/odm_meshing/odm_25dmesh.ply
[DEBUG]   running /code/build/bin/odm_25dmeshing -inputFile /var/www/data/9a54d9c4-c4b2-4c6f-8349-7d3a4a99e705/opensfm/reconstruction.ply -outputFile /var/www/data/9a54d9c4-c4b2-4c6f-8349-7d3a4a99e705/odm_meshing/odm_25dmesh.ply -logFile /var/www/data/9a54d9c4-c4b2-4c6f-8349-7d3a4a99e705/odm_meshing/odm_25dmeshing_log.txt -maxVertexCount 30000 -neighbors 24 -resolution 0 -verbose
Loading point cloud... loaded 167191 points
Remove outliers... 7851 points removed
Squash point cloud to plane... Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_meshing.py", line 105, in process
    '-resolution {resolution} {verbose}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 139

**Comment by PeterSprague** [comment]
"Can you recover the core dump file and attach it here? Perhaps we'll know more once we take a look at it."
Where? 
$ whereis core
core: /usr/share/man/man5/core.5.gz

Rebuilding w/o core2 flag, since didn't seem to help the issue

**Comment by PeterSprague** [comment]
amd64 32 core 64Gb
opensfm_processes @32
opengv built from source w/o core2 flag
no fast_ortho checked
VTK v8.1.0

Success, good ortho

rerun w/ fast_ortho checked @32 ortho_processes
2018-02-02 05:14:31,471 DEBUG: Undistorting image 2017_0909_115521_230.JPG
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_ply --no-cameras /var/www/data/e2faa46b-2cf0-4517-8259-b4d127373831/opensfm
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/export_bundler /var/www/data/e2faa46b-2cf0-4517-8259-b4d127373831/opensfm
[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running ODM Meshing Cell
[DEBUG]   Writing ODM 2.5D Mesh file in: /var/www/data/e2faa46b-2cf0-4517-8259-b4d127373831/odm_meshing/odm_25dmesh.ply
[DEBUG]   running /code/build/bin/odm_25dmeshing -inputFile /var/www/data/e2faa46b-2cf0-4517-8259-b4d127373831/opensfm/reconstruction.ply -outputFile /var/www/data/e2faa46b-2cf0-4517-8259-b4d127373831/odm_meshing/odm_25dmesh.ply -logFile /var/www/data/e2faa46b-2cf0-4517-8259-b4d127373831/odm_meshing/odm_25dmeshing_log.txt -maxVertexCount 30000 -neighbors 24 -resolution 0 -verbose
Loading point cloud... loaded 166609 points
Remove outliers... 6182 points removed
Squash point cloud to plane... Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_meshing.py", line 105, in process
    '-resolution {resolution} {verbose}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 139

rerunning at 12 opensfm_processes

**Comment by PeterSprague** [comment]
nada

2018-02-02 06:40:34,007 DEBUG: Undistorting image 2017_0909_115521_230.JPG
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_ply --no-cameras /var/www/data/7c7d5211-9e70-4f3b-a7ae-53ce9d0a4ef9/opensfm
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/export_bundler /var/www/data/7c7d5211-9e70-4f3b-a7ae-53ce9d0a4ef9/opensfm
[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running ODM Meshing Cell
[DEBUG]   Writing ODM 2.5D Mesh file in: /var/www/data/7c7d5211-9e70-4f3b-a7ae-53ce9d0a4ef9/odm_meshing/odm_25dmesh.ply
[DEBUG]   running /code/build/bin/odm_25dmeshing -inputFile /var/www/data/7c7d5211-9e70-4f3b-a7ae-53ce9d0a4ef9/opensfm/reconstruction.ply -outputFile /var/www/data/7c7d5211-9e70-4f3b-a7ae-53ce9d0a4ef9/odm_meshing/odm_25dmesh.ply -logFile /var/www/data/7c7d5211-9e70-4f3b-a7ae-53ce9d0a4ef9/odm_meshing/odm_25dmeshing_log.txt -maxVertexCount 30000 -neighbors 24 -resolution 0 -verbose
Loading point cloud... loaded 166854 points
Remove outliers... 7339 points removed
Squash point cloud to plane... Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_meshing.py", line 105, in process
    '-resolution {resolution} {verbose}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 139

**Comment by PeterSprague** [comment]
Atom J3455 4 core 16gb RAM
using fast-ortho
may222018
reran with complete rebuild of all images & source on Atom
used newest source -> VTK v8.1.1
successful all build including ortho
fast-ortho checked in Node-OpenDroneMap --> same error
-----------------------------------
/src/OpenSfM/bin/opensfm export_geocoords /var/www/data/1fa5a2e2-8389-4be3-9bfe-ac6e926fdee2/opensfm --transformation --proj '+units=m +no_defs=True +datum=WGS84 +proj=utm +zone=10 '
[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running ODM Meshing Cell
[DEBUG]   Writing ODM 2.5D Mesh file in: /var/www/data/1fa5a2e2-8389-4be3-9bfe-ac6e926fdee2/odm_meshing/odm_25dmesh.ply
[DEBUG]   running /code/build/bin/odm_25dmeshing -inputFile /var/www/data/1fa5a2e2-8389-4be3-9bfe-ac6e926fdee2/opensfm/reconstruction.ply -outputFile /var/www/data/1fa5a2e2-8389-4be3-9bfe-ac6e926fdee2/odm_meshing/odm_25dmesh.ply -logFile /var/www/data/1fa5a2e2-8389-4be3-9bfe-ac6e926fdee2/odm_meshing/odm_25dmeshing_log.txt -maxVertexCount 30000 -neighbors 24 -resolution 0 -verbose
Loading point cloud... loaded 112632 points
Remove outliers... 8261 points removed
Squash point cloud to plane... Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_meshing.py", line 106, in process
    '-resolution {resolution} {verbose}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 139

**Comment by PeterSprague** [comment]
With newest ODM master w/ VTK 8.1.1, successful 25DMesh and fast-orthophoto runs.  Resulting images have very distorted texturing.  Hard to even recognize a tree in an open conifer forest survey.  Tried with both default and my forestry settings which bumps the min_num to 15000, mesh size to 30000, octree depth to 5, ....

**Comment by pierotofy** [comment]
`0` means automatically compute a suitable resolution. You can see the exact formula in odm_25dmeshing.cpp. It's quite possible that that is the cause of the seg fault, although it's probably caused by VTK.

You'll be happy to know that we are planning to update the 2.5D meshing program and remove the VTK 7+ dependency. We are keeping the VTK version that is available on apt, but will remove the one we are currently compiling from sources! Keep an eye on https://github.com/OpenDroneMap/OpenDroneMap/projects/2

**Comment by PeterSprague** [comment]
I'm using VTK 8.1.1.  Debian Stretch is at VTK6 6.3.0
Thought VTK 8.1 had enhanced GPU and parallel processing capabilities.  Wouldn't you want that in ODM?
