### ISSUE TITLE
Broken link for config.yaml in Wiki

### ISSUE THREAD

**Issue by stephenmelsom** [OpenDroneMap/ODM#758]
The [dropbox link](https://dl.dropboxusercontent.com/u/2801164/odm/config.yaml) in [this part of the Wiki](https://github.com/OpenDroneMap/OpenDroneMap/wiki/Reconstruction-from-Video) appears to be failing.  Any help?  Just looking to find an example file so I can use ODM with SLAM.  Thanks!

**Comment by dakotabenjamin** [comment]
It should be fixed now, thanks!
