### ISSUE TITLE
ExifTools tags and processing

### ISSUE THREAD

**Issue by spifftek70** [OpenDroneMap/ODM#759]
Can you create a list of Exif GPS tags that are required for ODM to properly run and/or enhance the process?   I've search and search, but I can't seem to find a list of hard tags the ODM looks for in an image.

**Comment by dakotabenjamin** [comment]
This is a great idea. Here's where in the code ODM extracts exif info: https://github.com/OpenDroneMap/OpenDroneMap/blob/master/opendm/types.py#L68

I will also add this to the documentation.

**Comment by spifftek70** [comment]
Thanks for the quick reply!

**Comment by spifftek70** [comment]
Hmm..  Have you thought about incorporating `GPSImgDirection` (heading) into the processing?  Might be able to speed things up.

**Comment by yjmenezes** [comment]
@spifftek70 

I wrote a bash script to search OpenDroneMap sources tree.
usage:  
find_source_code.sh  ~/OpenDroneMap  py    exiv2 
find_source_code.sh  ~/OpenDroneMap  cpp   exiv2 

output: 

-------- OpenDroneMap/opendm/types.py
import pyexiv2
        self.parse_pyexiv2_values(self.path_file, force_focal, force_ccd)
    def parse_pyexiv2_values(self, _path_file, _force_focal, _force_ccd):
        metadata = pyexiv2.ImageMetadata(_path_file)
            # try/catch tag value due to weird bug in pyexiv2 
            except (pyexiv2.ExifValueError, ValueError) as e:

-------- OpenDroneMap/SuperBuild/src/opensfm/opensfm/geotag_from_gpx.py
import pyexiv2
from pyexiv2.utils import make_fraction
Requires pyexiv2, see install instructions at http://tilloy.net/dev/pyexiv2/
(or use your favorite installer, e.g. 'brew install pyexiv2').
    metadata = pyexiv2.ImageMetadata(filename)
    metadata = pyexiv2.ImageMetadata(filename)

-------- OpenDroneMap/modules/odm_extract_utm/src/UtmExtractor.cpp
#include <exiv2/exiv2.hpp>

I am facing exif tags problems with my church_dataset.

**Comment by dakotabenjamin** [comment]
Sorry for the late reply @spifftek70 That sounds like a great addition, and we always welcome community contributions.

**Comment by skorasaurus** [comment]
I had spent a couple hours debugging a setup only to figure out missing EXIF tags were part of my problem; I'm glad to make a PR for this but I'm unsure where to put in docs.opendronemap.org (

cc https://github.com/OpenDroneMap/ODM/issues/910

**Comment by pierotofy** [comment]
@skorasaurus a bit late :smile: but you can just add it as a new section ("Exif Tags" or something similar) if you're still interested in making a PR. https://github.com/OpenDroneMap/docs

**Comment by professorfabioandrade** [comment]
Do you guys know how I can see a list of EXIF tags used by ODM? 

I tried the types.py file but couldn't find any reference to the GPS tags for example .

It would be great to know the tags that are used to enhance the results as I insert the EXIF data myself in the pictures. That's because I am using a simulation environment with Airsim and Unreal Engine 4 to capture the images.

**Comment by smathermather** [comment]
Ha! Pretty interesting use case. Can you come over to community.opendronemap.org for questions?

**Comment by pierotofy** [comment]
(Parsing code is now in https://github.com/OpenDroneMap/ODM/blob/master/opendm/photo.py#L94). Yes, questions should go on the forum :pray:
