### ISSUE TITLE
GCPs detection and ortho-correction

### ISSUE THREAD

**Issue by spifftek70** [OpenDroneMap/ODM#760]
First, I can't say enough on the application.  It's great.

I'm looking to create highly accurate ortho-stitched GeoTiffs (centimeter) using drone images over large fields.  The drone has GPS, but as we all know, they aren't the most accurate of process on small drones.  

We have standardized surveyed GCPs in these fields.  I know that Photoscan has the ability to detect and recognize certain patterns of GCPs and use the corresponding surveyed coordinates to produce highly accurate GeoTiffs.  

Does ODM have this capability or are there plans for such a function?

**Comment by pierotofy** [comment]
ODM has supports for GCPs, see https://github.com/OpenDroneMap/OpenDroneMap/wiki/Running-OpenDroneMap#running-odm-with-ground-control but doesn't have automatic pattern recognition built-in yet. There's a project that has started tackling this issue: https://github.com/wolkstein/OpenDroneMap-GCP_LIST.TXT-generator

**Comment by smathermather** [comment]
This is something that interests me a lot -- it just needs funding or a champion.

**Comment by danbjoseph** [comment]
I had experimented with [wolkstein/OpenDroneMap-GCP_LIST.TXT-generator](https://github.com/wolkstein/OpenDroneMap-GCP_LIST.TXT-generator) but couldn't get it to do a good enough job picking out all the GCPs and it had an even harder time accurately distinguishing the patterns apart.

<img width="250" alt="" src="https://user-images.githubusercontent.com/4806884/36073716-045a709e-0f03-11e8-981d-9fbe315f8103.jpg">
<img width="500" alt="screen shot 2017-08-15 at 5 12 45 pm" src="https://user-images.githubusercontent.com/4806884/36073688-9ce548bc-0f02-11e8-95cc-49e4f50dedd7.png">

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/gcps-detection-and-ortho-correction/359
