### ISSUE TITLE
How I can view orthophoto: odm_orthophoto/odm_orthophoto.tif?

### ISSUE THREAD

**Issue by hbzhang** [OpenDroneMap/ODM#766]
I am new here, how I can visualize odm_orthophoto.tif file? Thanks!

**Comment by danbjoseph** [comment]
QGIS is an excellent free and open source GIS software that can visualize *.tif files (as well as tons of other cool stuff).
https://qgis.org/en/site/

Here's an (old) tutorial that covers some related material:
http://www.qgistutorials.com/en/docs/raster_mosaicing_and_clipping.html

**Comment by hbzhang** [comment]
Perfect, thank you! I will take a look!

**Comment by smathermather** [comment]
@hbzhang -- you might consider adding pyramids to the image when you load in QGIS for faster access to the tif, which is particularly important for larger images.
