### ISSUE TITLE
Error in open cloud points

### ISSUE THREAD

**Issue by leonardojoao** [OpenDroneMap/ODM#767]
I am having problem to open the cloud points file, gives the following error:

While opening: .../odm_meshing/odm_mesh.ply'
Error encountered while loading file: .../odm_meshing/odm_mesh.ply"
Error details: Unespected eof

Anyone know the reason for the 3d file when opening becomes all black? Looks like the texture is missing.

The orthosauric is generating correctly.

**Comment by yjmenezes** [comment]
@Leonardojoao01 

What SW are you using to open *ply ?
Meshlab, CloudCompare ?

**Comment by leonardojoao** [comment]
Meshlab

**Comment by yjmenezes** [comment]
@Leonardojoao01 

Meshlab works for  me with outputs from ODM 0.3.1 running under Ubuntu1604.
Try reprocess yours dataset.

**Comment by leonardojoao** [comment]
I installed the CloudCompare solved the problem.

Can you tell me what parameter I need to change to change the density of the point cloud? and resolution map 3d ?

**Comment by yjmenezes** [comment]
@Leonardojoao01 

Sorry, i am not testing point cloud at moment. I have to test it too.
try follow this issue: #769
runtime options: https://github.com/OpenDroneMap/OpenDroneMap/wiki/Run-Time-Parameters

**Comment by smathermather** [comment]
@Leonardojoao01 -- there are new parameters in the pipeline for increasing the point cloud density and other parts and pieces that are currently buried in opensfm config files. I can't find the pull request, but @pierotofy was working on this.

related: https://github.com/OpenDroneMap/OpenDroneMap/issues/750 https://github.com/OpenDroneMap/OpenDroneMap/issues/769
