### ISSUE TITLE
Expose some opensfm depthmaps config parameters

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#769]
I can take care of this sometimes in the next few weeks (or if somebody else beats me to it).

I propose to expose some of opensfm's depthmaps parameters since I think the defaults sometimes can lead to less than optimal results. In particular, to increase the quality of our meshes and orthophotos, we could really benefit from getting more points in the dense reconstruction. Here are some of my tests with certain parameters:

`depthmap_min_consistent_views`:

![depthmap_min_consistent_views](https://user-images.githubusercontent.com/1951843/36604214-16aceb6e-188b-11e8-8edf-ff413ca2afd6.gif)

Default: 3 ( ~262k points )
Changed: 2 ( ~515k points )
Notes: more noise

`depthmap_resolution`:

![depthmap_resolution](https://user-images.githubusercontent.com/1951843/36604939-2e6f8714-188d-11e8-86c0-73ef1f984752.gif)

Default: 640 ( ~262k points )
Changed: 1280 ( ~1 million points )
Notes: slower by a factor of ~4

`depthmap_patchmatch_iterations`: virtually no change in output, just slower (increased `3` to `9`).

`depthmap_min_patch_sd`: 

Default: 5 ( ~262k points )
Changed: 2.5 ( ~310k points )
Notes: roads appear! same runtime

![depthmap_min_patch_sd](https://user-images.githubusercontent.com/1951843/36605720-8a605c54-188f-11e8-9195-cfcc4719dbbc.gif)

`depthmap_same_depth_threshold`: virtually no change in output (increased `0.005` to `0.015`)

`depthmap_num_matching_views`: virtually no change in output (increased `2` to `4`)

`depthmap_method`:

![depthmap_method_brute](https://user-images.githubusercontent.com/1951843/36607295-2c815f3e-1894-11e8-964d-94392fc29acc.gif)

Default: PATCH_MAP ( ~262k points )
Changed: BRUTE_FORCE( ~330k points )
Notes: Less noise, roads appear, runtime 3x slower

`depthmap_min_correlation_score`:

![depthmap_min_correlation_score](https://user-images.githubusercontent.com/1951843/36608506-10f31880-1898-11e8-89a1-5514cec5e269.gif)

Default: 0.7 ( ~262k points )
Changed: 0.4 ( ~282k points )
Notes: More noise

**Comment by pierotofy** [comment]
Overall I think we could expose:
 - depthmap_min_consistent_views
 - depthmap_method
 - depthmap_min_patch_sd

As they seem to impact the output the most.

**Comment by smathermather** [comment]
Love this! I've been playing with these parameters for specific projects, and would love to see them exposed. I would expose ```depthmap_resolution``` which defaults to a pretty conservative value.

**Comment by pierotofy** [comment]
I'll try to get this done during the code sprint this week.
