### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by cgdnorth** [OpenDroneMap/ODM#77]
Hello, I am getting the error `Segmentation fault (core dumped)` in running 4 images as a test. Can you give me a reason this is happening? The setup is Ubuntu 12.04 running in VirtualBox on a Mac.

```
Segmentation fault (core dumped)


quitting cause: 
    "/home/chris/process/corrected/../../OpenDroneMap/bin/bundler" "/home/chris/process/corrected/reconstruction-with-image-size-2400/list.txt" --options_file "/home/chris/process/corrected/reconstruction-with-image-size-2400/options.txt" > bundle/out
returned with code 35584
```

**Comment by smathermather** [comment]
Hi @cgdnorth -- can you post this to the user forum?

Thanks!
http://lists.osgeo.org/cgi-bin/mailman/listinfo/opendronemap-users

**Comment by ghost** [comment]
what was ever the resolution on this?

**Comment by dakotabenjamin** [comment]
Yes, check #171
