### ISSUE TITLE
Visibility-Consistent Thin Surface Reconstruction (TSR)

### ISSUE THREAD

**Issue by sberryman** [OpenDroneMap/ODM#775]
Have any project contributors looked at the TSR paper and source code? The results from the paper look pretty incredible. I know it is a far stretch from the current software used in the pipeline but I don't see why OpenSfM couldn't create linked point clouds to the sensors which captured them. The depth map linking looks a bit more difficult but that is due to the lack of experience with ODM.

Paper:
https://www.gcc.tu-darmstadt.de/media/gcc/papers/Aroudj-2017-TSR-Prepress.pdf

Source code:
https://github.com/SamirAroudj/TSR

Website:
https://www.gcc.tu-darmstadt.de/home/proj/tsr/tsr.en.jsp

**Comment by pierotofy** [comment]
Very cool research, thanks for posting the links.

Would be interesting to see how it renders a terrain scene, keeping in mind that most of the improvements this algorithm focuses on improving are thin objects. Maybe you'll get better looking vegetation.

Input requires points with "visibility information", so won't work straight out of OpenSfM.

**Comment by sberryman** [comment]
Sorry, thought I followed back up on your comment. Agree that the title alludes to thin objects but it seemed to do a pretty good job on Stephansdom reconstruction.

![image](https://user-images.githubusercontent.com/324437/37225584-f0803156-238b-11e8-8e43-2184de0e1b47.png)
![image](https://user-images.githubusercontent.com/324437/37225593-f55fc8da-238b-11e8-9c1a-3a34fc977cc0.png)
Image source: https://www.gcc.tu-darmstadt.de/home/proj/tsr/tsr.en.jsp

On a side note, I took a lot of your suggestions from #769. Specifically `depthmap_resolution=1280`, `depthmap_min_patch_sd=2.5` and `depthmap_method=BRUTE_FORCE`. I didn't pay a whole lot of attention to your time estimates and now waiting patiently for it to finish. It has been running since March 2nd and is only on `odm_25dmeshing`. The project contains ~1,443 images so I probably went a bit overboard.

**Comment by pierotofy** [comment]
Yeah I wouldn't recommend using the --use-25dmesh option for dense reconstructions, it will perform poorly.

**Comment by smathermather** [comment]
@sberryman -- why close this issue? I'm normally all for closing issues 😄, but this is an intriguing proposal and could stand to be explored.

**Comment by sberryman** [comment]
@smathermather simply to reduce your list of open issues, I figured it was more of an FYI and I didn't know about the gitter channel yet so this was my way of letting you guys know.

**Comment by smathermather** [comment]
Still an interesting proposal. @adamsteer -- do you want to look into this? :D

**Comment by adamsteer** [comment]
I already am, very slowly ;). I have to focus on things I can invoice for (or sell) :/

**Comment by smathermather** [comment]
Haha! Understood. :)

**Comment by smathermather** [comment]
Going to close this. TSR is interesting, and good meshing is important, but my experience with this implementation is that it is quite difficult to build.
