### ISSUE TITLE
Completion time estimates

### ISSUE THREAD

**Issue by arkadyark** [OpenDroneMap/ODM#776]
Is anything like this available, or would something like this be possible? Even a rough estimate, like "2-4 hours remaining" would be helpful.

**Comment by smathermather** [comment]
This is one of those features that is impossible to build well, but also desirable. I think @pierotofy was looking at the possibility of having a portion completed bar in WebODM, but I don't know if it's still just a wish list item, or something in progress.

**Comment by pierotofy** [comment]
We could create probable estimates based on a particular formula, but wouldn't be very accurate. Lots of factors at play and tweaking the parameters can change the estimates considerably.

**Comment by pierotofy** [comment]
Mandatory: https://xkcd.com/612/

**Comment by sberryman** [comment]
What about showing progress for each sub process? Even watching file counts in a directory can give a good idea of progress and duration for a lot of OpenSfM tasks.

So maybe starting out with a visual checklist? The fact OpenSfM has sub tasks of extract_metadata, detect_features, match_features, create_tracks, reconstruct, mesh, export_visualsfm, undistort, compute_depthmaps, export_bundler and export_geocoords was a surprise to me at first. (I know the pipeline is different based on settings but that is still a lot of sub tasks)

I don't recall seeing that in WebODM but I've moved along to manually executing all the steps to see what is going on.

Update: After re-reading @smathermather comment, my thoughts sound a lot like what @pierotofy was thinking?

**Comment by smathermather** [comment]
Closing. We now have https://github.com/OpenDroneMap/odm-benchmarks! Thanks @coreysnipes!
