### ISSUE TITLE
partial othrophoto creation

### ISSUE THREAD

**Issue by glw** [OpenDroneMap/ODM#779]
Im getting a similar output as issue #491 . Where my total AOI is not included in the final orthophoto.
Im using the docker version

`docker run -it --rm -v $(pwd):/code/images -v $(pwd)/odm_orthophoto:/code/odm_orthophoto -v $(pwd)/odm_texturing:/code/odm_texturing opendronemap/opendronemap --fast-orthophoto`

here are my results:
![image](https://user-images.githubusercontent.com/556205/37118112-bb44153a-2218-11e8-9c48-6b8a3ce227a1.png)

The points are the exif locations of my imagery. 

My overlap should have been somewhere around 80/80 or 85/85. Camera is Parrot Sequoia and Im only running the RGB images at the moment.

I saw in the previous issue, he had tweaked the `--min_num_features` , is this still the recommended route?

Thanks!

**Comment by smathermather** [comment]
@glw -- did you calibrate your parrot images? My hunch is barrel distortion is causing issues in the matching. @dakotabenjamin has a set of scripts for addressing this at https://github.com/OpenDroneMap/CameraCalibration

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/partial-othrophoto-creation/393

**Comment by glw** [comment]
Sorry for the delay in my reply, but thanks for pointing me in the right direction @smathermather and @dakotabenjamin . Ill take a look at those scripts and link.

**Comment by kikislater** [comment]
@glw Do you get decent result with this poor sensor readout on sequoia (Sony IMX206) ?
