### ISSUE TITLE
Check if proccess is running

### ISSUE THREAD

**Issue by muriloazevedo** [OpenDroneMap/ODM#789]
I started the process yesterday is running without errors like the image below
![screen shot 2018-03-22 at 10 41 34](https://user-images.githubusercontent.com/1427567/37774211-636cb28e-2dbe-11e8-9794-4a0149ca283c.png)

But I don't know if what step it's running and any estimative of the whole proccess. Is there any guide to explane what's ODM doing?

Thanks!

**Comment by yjmenezes** [comment]
@muriloazevedo 

you can run the pipeline step by step.
https://github.com/OpenDroneMap/OpenDroneMap/wiki/Run-Time-Parameters

--start-with
--end-with
and measure every step.
time  ./run.sh .....

your screenshot shows it is running first pipeline step:   bin/opensfm

**Comment by dakotabenjamin** [comment]
Yes, currently it's a "go get some coffee and wait" kind of deal. We have heard a lot of requests for better progress reporting so it's certainly on the backlog.

**Comment by dakotabenjamin** [comment]
This issue was moved to http://community.opendronemap.org/t/check-if-proccess-is-running/358
