### ISSUE TITLE
GCP does not seem to be used for georeference

### ISSUE THREAD

**Issue by tmizu23** [OpenDroneMap/ODM#795]
Evev if I run with "--gcp gcp_list.txt", gcp doesn't seem to be used for georeference.
It was written "Missing input in order to use GCP for georeferencing. Using EXIF data instead." in odm_georeferencing_log.txt. and the orthophoto result was also incorrect. 

gcpFileSpecified  at [Georef.cpp#L514](https://github.com/OpenDroneMap/OpenDroneMap/blob/master/modules/odm_georef/src/Georef.cpp#L514) is always false,cause of [odm_georeferencing.py#125](https://github.com/OpenDroneMap/OpenDroneMap/blob/master/scripts/odm_georeferencing.py#L125) is no "-gcpFile {gcp}" option

**Comment by dakotabenjamin** [comment]
What version are you running? Can you paste the content of your gcp file?

**Comment by tmizu23** [comment]
Sorry it was my misunderstanding.
I update docker image, then fix it.
thank you.

**Comment by tmizu23** [comment]
Today I update latest docker image, then this probrem ocuur again.
In some cases, the stable version is uploaded in docker hub, and in some cases, it seems that there are buggy version uploaded.
From 5 days ago until yesterday, it seems there is stable version in docker hub .
I check --help, then buggy version show "--proj" option and stable version don't show it.
In my guess, docker hub will be rebuild , if ODM or WebODM was updated in github.
then WebODM is stable and ODM is not.

Could you upload stable version  in docker hub? 

This is gcp file.
[gcp_list.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1865995/gcp_list.txt)

**Comment by yjmenezes** [comment]
@tmizu23 

I think your gcp_list.txt layout is ok for ODM 0.3.1.
try replace first line by this:
+proj=utm +zone=54 +north +datum=WGS84 +units=m +no_defs

map your directory:
 -v $(pwd)/gcp_list.txt:/code/gcp_list.txt 

and add
--gcp gcp_list.txt

**Comment by tmizu23** [comment]
@yjmenezes  thank you

I tried your option and chnage gcp line, but it was not fix.
my running command is this, and attached the log file

docker run -it --rm
-v ${odmdata}/images:/code/images
-v ${odmdata}/opensfm:/code/opensfm
-v ${odmdata}/odm_meshing:/code/odm_meshing
-v ${odmdata}/odm_texturing:/code/odm_texturing
-v ${odmdata}/odm_georeferencing:/code/odm_georeferencing
-v ${odmdata}/odm_dem:/code/odm_dem
-v ${odmdata}/odm_orthophoto:/code/odm_orthophoto
-v ${odmdata}/gcp_list.txt:/code/gcp_list.txt
opendronemap/opendronemap
--resize-to 2048
--min-num-features 8000
--opensfm-process 2
--mesh-size 100000
--gcp gcp_list.txt
--dsm
--dem-resolution 0.1
--dem-terrain-type FlatForest
--orthophoto-resolution 20


[odm_orthophoto_log.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1867024/odm_orthophoto_log.txt)
[odm_georeferencing_log.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1867025/odm_georeferencing_log.txt)

**Comment by yjmenezes** [comment]
@tmizu23 

you are right, we have a trouble with ODM 0.3.1, it is jumping gcp_list.txt.
Your log shows: Missing input in order to use GCP for georeferencing. Using EXIF data instead.

I will try to figure out the reason.

**Comment by 0x906** [comment]
is there any update on this issue?

**Comment by yjmenezes** [comment]
I run ODM 0.3.1 commit 7816d59  under docker and it is OK.
I run the supplied dataset 
cd  tests/testdata/
