### ISSUE TITLE
Using OpenDroneMap without geo data

### ISSUE THREAD

**Issue by Harvie** [OpenDroneMap/ODM#799]
Hello,
is there way to reconstruct point cloud / mesh from photos usinf ODM without having the gps coords? I don't need absolute position, just get 3D model for manual editing and aligning or 3d printing.

Right now i get this:

```
[WARNING] Could not generate coordinates file. Ignore if there is a GCP file. Error: Error in OdmExtractUtm:
Image is missing GPS Latitude data
For more detailed information, see log file.

[ERROR]   Could not find file /code/odm_georeferencing/coords.txt
```

I just want ODM to ignore this and give me output mesh with relative coords. I don't have gps in txt, gcp or exif. i just don't want to use them at all. I know this is possible with colmap. But i like ODM more.

Thanks for your time.

**Comment by pierotofy** [comment]
Could you copy/paste the full output of processing your task?

**Comment by Harvie** [comment]
I've used this command:

`docker run -it --rm -v $(pwd)/images:/code/images opendronemap/opendronemap --mesh-size 100000 --force-ccd 1  --help`

I don't have it set up right now. But i think there was nothing else unusual. Just info about loading the JPGs and then this.

**Comment by pierotofy** [comment]
Related: http://community.opendronemap.org/t/could-not-find-file-odm-georeferencing-coords-txt/487

**Comment by smathermather** [comment]
@Harvie -- this is fixed and tested on master. Give it a spin when you get a chance!
