### ISSUE TITLE
Can't locate Switch.pm in @INC

### ISSUE THREAD

**Issue by dbaldwin** [OpenDroneMap/ODM#8]
I received this error when executing run.pl:

Can't locate Switch.pm in @INC

I had to install the package:

sudo apt-get install libswitch-perl

and now it looks like run.pl works properly. This was with a base Ubuntu install from Amazon EC2:

ubuntu@ip-172-31-8-243:~/OpenDroneMap$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"

Just wanted to share this bit of info.

**Comment by smathermather** [comment]
Interesting. Thanks @dbaldwin . It looks like that is in the update list in install.sh -- have you been able to replicate this on another EC2 box? Did the `sudo apt-get install ...` fail?
