### ISSUE TITLE
Any way to generate a model with a single texture?

### ISSUE THREAD

**Issue by FarhadG** [OpenDroneMap/ODM#800]
### How did you install OpenDroneMap?
Docker

### What is the problem?
We have a unique case where we need to generate the 3D model with a single texture (e.g. similar to how Pix4D does it). I looked through the documentation but couldn't find anything about this sort of functionality. Any ideas?

**Comment by pierotofy** [comment]
There doesn't seem to be any particular advantage (aside from ease of portability?) to using a single texture; it's possible to add such feature, one would need to implement the changes of https://github.com/nmoehrle/mvs-texturing/compare/master...andre-schulz:single-texture-atlas into our mvs-texturing fork, expose a flag, and add the necessary config parameter. Note this seems to increase runtime and possibly memory usage, so it wouldn't be something that's turned on by default.

If this is still of interest, we'd welcome a pull request that implements it. :+1:
