### ISSUE TITLE
Global color adjustment problem on mosaic

### ISSUE THREAD

**Issue by giovannicimolin** [OpenDroneMap/ODM#801]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

### What's your browser and operating system? 

Ubuntu 14.04 - Running on AWS EC2 r3.4xlarge (16xCPU, 120GB-RAM, 320GB-SSD)

### What is the problem?

Recently, the generated orthophotos have a gradient of colors going from very white on one side of the mosaic to very dark on another side. This has been observed in many cases, shown below:

![screenshot from 2018-04-02 08-25-57](https://user-images.githubusercontent.com/27893385/38620600-379900e2-3d75-11e8-88c1-b3a7822a9ce8.png)
![screenshot from 2018-04-05 08-19-44](https://user-images.githubusercontent.com/27893385/38620603-3a5a9282-3d75-11e8-953d-94522729a039.png)
![screenshot from 2018-04-05 08-20-01](https://user-images.githubusercontent.com/27893385/38620657-6981e9de-3d75-11e8-8016-f8063c880825.png)

Processing these datasets using the following parameters:
```javascript
{
            "use-hybrid-bundle-adjustment": true,
            "min-num-features": 12000,
            "mesh-octree-depth": 6,
            "orthophoto-resolution": 20
}
```

Using `--texturing-skip-global-seam-leveling`, the problem doesn't happen, however, the result is not as normally expected:
![screenshot from 2018-04-02 13-30-42](https://user-images.githubusercontent.com/27893385/38620634-549b4d80-3d75-11e8-9193-0583a3de4c76.png)

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

An orthomosaic with good color balance.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)
I'm working on providing a dataset. The parameters used were:

```javascript
{
            "use-hybrid-bundle-adjustment": true,
            "min-num-features": 12000,
            "mesh-octree-depth": 6,
            "orthophoto-resolution": 20
}
```
I've also made tests without using `--mesh-octree-depth`.

EDIT: Switch links to images.

**Comment by giovannicimolin** [comment]
If you can point me to a possible parameter mistake or lines of code to look at I'd be happy to help. :smile:

**Comment by pierotofy** [comment]
Do you get better results if you turn on `--texturing-tone-mapping gamma`?

**Comment by pierotofy** [comment]
Also, screenshots are great, would it be possible to have access to the original images as well?

**Comment by smathermather** [comment]
@giovannicimolin -- FYI, you don't have to make the images open to share them. If you want to share them with @pierotofy, he can probably agree to not share them further.

**Comment by farmdude** [comment]
Thanks for pointing me here @pierotofy 

First image is --texturing-tone-mapping none
![screenshot from 2018-04-10 08-12-49](https://user-images.githubusercontent.com/37521795/38615421-34390682-3d56-11e8-8aa4-37c840ddc2b0.png)
Second image is --texturing-tone-mapping gamma
![screenshot from 2018-04-11 06-57-13](https://user-images.githubusercontent.com/37521795/38615396-2782e750-3d56-11e8-8579-90f45d160707.png)

However, the problem, in my opinion, becomes more pronounced when you turn gamma on.

**Comment by giovannicimolin** [comment]
Here is one of the mosaics with ` --texturing-tone-mapping gamma`:
![screenshot from 2018-04-11 09-12-21](https://user-images.githubusercontent.com/27893385/38616085-2c019584-3d69-11e8-8ef7-49fbb3a1b318.png)

I'm uploading a dataset and I'll send it privately to @pierotofy so he can reproduce the issue.

**Comment by pierotofy** [comment]
Possible fix should be available as soon as https://github.com/OpenDroneMap/mvs-texturing/pull/3 is merged.

**Comment by pierotofy** [comment]
@giovannicimolin could you try to update and see if this is fixed?

**Comment by foxsake** [comment]
I had the same issue. seen on the first pic
![asdaf](https://user-images.githubusercontent.com/5541760/39290108-18589e3e-4961-11e8-98d4-773002098d4c.PNG)
the update fixed the issue.
![asdf2](https://user-images.githubusercontent.com/5541760/39290109-189b2894-4961-11e8-956f-46a72b25848a.PNG)

-Thanks   @pierotofy!

**Comment by pierotofy** [comment]
Thanks for testing @foxsake !

**Comment by farmdude** [comment]
@pierotofy your fix worked for me! Thanks!

**Comment by giovannicimolin** [comment]
@pierotofy The solves all the problems! Thank you!
