### ISSUE TITLE
you can for aliyun create  mirrored warehouse

### ISSUE THREAD

**Issue by jmp12315** [OpenDroneMap/ODM#802]
![image](https://user-images.githubusercontent.com/21330513/38475155-7c78e6b2-3bd8-11e8-86fb-132b45190e8b.png)

**Comment by pierotofy** [comment]
Hi @jmp12315, please follow the [issue template](https://github.com/OpenDroneMap/OpenDroneMap/blob/master/docs/issue_template.md) to open an issue. I will close this one for now.
