### ISSUE TITLE
Error while generating orthophoto

### ISSUE THREAD

**Issue by bailingxiao** [OpenDroneMap/ODM#812]
This is my commands:"docker run -it --user root -v C:\Users\bailingxiao\odm_test_1/images:/code/images -v C:\Users\bailingxiao\odm_test_1/odm_orthophoto:/code/odm_orthophoto opendronemap/opendronemap"
An exception occurred during processing：
"Generating texture patches:
        Running... Killed
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/mvstex.py", line 133, in process
    '{keepUnseenFaces}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 137"

This is the log
[odm_dev_docker_log (2).txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1945882/odm_dev_docker_log.2.txt)

No result was generated. What should i do to solve this problem？

**Comment by pierotofy** [comment]
`Killed` means you ran out of memory. Either allocate more RAM to your docker environment, or reduce the resolution of your images (WebODM http://github.com/OpenDroneMap/WebODM has the ability to scale the images for you).
