### ISSUE TITLE
Error in windows

### ISSUE THREAD

**Issue by bailingxiao** [OpenDroneMap/ODM#817]
My commands: docker run -it --rm -v C:\Users/images:/code/images -v C:\Users/odm_texturing:/code/odm_texturing opendronemap/opendronemap
The error:
Generating texture views:
NVM: Loading file...
NVM: Number of views: 76
NVM: Number of features: 0
        Loading 0%...terminate called after throwing an instance of 'util::FileException'
  what():  No such file or directory
Aborted
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/mvstex.py", line 133, in process
    '{keepUnseenFaces}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 134

Use the image from: https://github.com/OpenDroneMap/odm_data

What should i do to solve this problem?

**Comment by pierotofy** [comment]
It probably has to do with the way you are mounting the `/code/odm_texturing` volume.

Check the README for possible suggestions on how to execute docker.
