### ISSUE TITLE
how to get the odm_mesh resuls? 

### ISSUE THREAD

**Issue by vgorte** [OpenDroneMap/ODM#818]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Installed via Docker

### What is the problem?
I have never used ODM before so I might be missing something obvious here.
How do I get the odm_mesh results? They are listed [here](https://github.com/OpenDroneMap/OpenDroneMap/wiki/Output-and-Results) but the created "odm_mesh" folder is empty. 
I used this terminal-command: 

```
docker run -it --rm \
    -v $(pwd)/images:/code/images \
    -v $(pwd)/opensfm:/code/opensfm \
    -v $(pwd)/odm_meshing:/code/odm_meshing \
    -v $(pwd)/odm_texturing:/code/odm_texturing \
    -v $(pwd)/odm_georeferencing:/code/odm_georeferencing \
    -v $(pwd)/odm_orthophoto:/code/odm_orthophoto \
    -v $(pwd)/odm_mesh:/code/odm_mesh \
    my_odm_image  
```
Any idea why I don't get anything? Everything else works fine.

**Comment by smathermather** [comment]
Have you tried ```odm_texturing``` as your directory? This would contain the final textured mesh, which is likely what you are looking for.

**Comment by vgorte** [comment]
You are correct. I don't really know why but I managed to first read 
https://github.com/OpenDroneMap/OpenDroneMap/wiki/Output-and-Results
and after posting this question I read the "View results" from the ReadMe.md ...
Is it safe to say that the above link is outdated ? 

Besides that, this issue can be closed. Thank you @smathermather ! 
Have a nice day!

**Comment by smathermather** [comment]
Hey @vgorte -- do you mind fixing it in the wiki?

**Comment by vgorte** [comment]
Hey @smathermather  
I fixed it in the wiki.

**Comment by smathermather** [comment]
Thanks!
