### ISSUE TITLE
OpenSfM does not handle EPSG codes

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#828]
https://github.com/mapillary/OpenSfM/blob/master/opensfm/io.py#L401

If you use any EPSG code definition (ex. "EPSG:4326") to specify a GCP projection, OpenDroneMap handles it OK, but is not valid in OpenSfM (see io.py).

Options:

1) We add support for EPSG codes in OpenSfM.
2) We remove support for EPSG codes in ODM.

Thoughts?

**Comment by smathermather** [comment]
Related, but GCPi doesn't support EPSG codes either, because it's built on a port of proj4 rather than gdal.

**Comment by pierotofy** [comment]
So... should we just remove EPSG codes and just use proj4 / UTM strings?

**Comment by smathermather** [comment]
Probably. I think otherwise we either need to deal with them ourselves, or introduce a dependency to OpenSfM.

**Comment by smathermather** [comment]
Since we have gdal as a dependency, we might be able to use gdal to convert EPSG codes to proj4 strings. I don't know enough about it to say for sure offhand.

**Comment by pierotofy** [comment]
That could work.

`gdalsrsinfo epsg:4326 -o proj4`
'+proj=longlat +datum=WGS84 +no_defs '

We would need to create a new GCP file to feed to OpenSfM.

**Comment by dakotabenjamin** [comment]
I'd like to advocate for epsg codes as a far more accessible block of text than proj4 strings

**Comment by pierotofy** [comment]
Seeing that calling gdalsrsinfo is straightforward, I'm for keeping EPSG codes also.

**Comment by smathermather** [comment]
Sounds like a plan.

**Comment by pierotofy** [comment]
Partecipants at FOSS4G have reported this as being an important issue for them. Just wanted to track the feedback.

**Comment by smathermather** [comment]
👍

**Comment by pierotofy** [comment]
This is done in the `speedimprov` branch.
