### ISSUE TITLE
Install Stops With No Status Messages

### ISSUE THREAD

**Issue by tpalshadow** [OpenDroneMap/ODM#83]
I am new to the Linux, so if I'm completely dumb in what I'm asking, just let me know.  You won't hurt my feelings. I'm running Ubuntu 14.04 LTS on an Oracle VirtualBox (setup just for this).

When I run the update I get this: 

---

todd@todd-VirtualBox:~/Documents/OpenDroneMap$ sudo ./install.sh

```
 created by Daniel Schwarz/daniel.schwarz@topoi.org
 released under Creative Commons/CC-BY
 Attribution

 if the script doesn't finish properly
 (i.e. it doesn't print "script finished" at the end)
 please email me the content of the logs folder
```
- script started - Wed Mar 18 16:18:44 CDT 2015
  
  > installing required packages

```
- updating
```

todd@todd-VirtualBox:~/Documents/OpenDroneMap$ 

---

And nothing seems to happen.  If I try and run a set of the sample images or the set that Dennis Baldwin has in his videos I get this:

---

sh: 1: jhead: not found
sh: 1: jhead: not found
sh: 1: jhead: not found
sh: 1: jhead: not found
sh: 1: jhead: not found

```
no CCD width or focal length found for img_4851.jpg - camera: " "sh: 1: jhead: not found
```

sh: 1: jhead: not found
sh: 1: jhead: not found
sh: 1: jhead: not found
sh: 1: jhead: not found

---

Any help would be appreciated!

-Todd

**Comment by smathermather** [comment]
Hi Todd, this should go to http://lists.osgeo.org/cgi-bin/mailman/listinfo/opendronemap-users

Short answer -- the install didn't complete or you would have a jhead executable. Go ahead and post to the users forum, and we can help you out.  Cheers

Steve
