### ISSUE TITLE
Question: edge coordinates for google earth 

### ISSUE THREAD

**Issue by wolkstein** [OpenDroneMap/ODM#84]
hi,
maybe a simple question.
i successfully run "~/Bilder/opendronemap-test/odm_data_caliterra-master$ perl /home/wolke/develop/git/OpenDroneMap/run.pl --resize-to 2400  --odm_georeferencing-useGcp "false" "
this ends with all steps done.

the result of odm-orthphoto.png is great. but where can i find the edge coordinates to create an google - earth overlay? i am looking around and can not find the simple edge coordinates for the ortho foto. did i miss something or must i generate the edge coords separately?

thx a lot for this great script!
/g
wolke

**Comment by smathermather** [comment]
Hi @wolkstein -- try the latest version and you'll get a geotiff as output. Cheers.
