### ISSUE TITLE
2.5D mesh generation via DSM samples and poisson

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#840]
* Generate DSM (via IDW) right after point cloud generation step (evaluate whether we can reuse odm_dem or if we need to compute a DSM twice)
 * Extract raster points (see #838)
 * Run PoissonRecon
 * Texture resulting 2.5D model, use for orthophoto generation

**Comment by smathermather** [comment]
One thing to look at with the potential for odm_dem reuse is the merging of the different search windows for the data. Currently we are introducing some artifacts into the DEM due (I suspect) to a naive merging approach. This can't be seen in the raw data, as we don't have the capacity to discern these kind of artifacts directly, but _can_ be seen in derivative products, e.g. a hillshade run on the data.

**Comment by pierotofy** [comment]
I think the artifacts you are referring to are due to the fact that our point clouds aren’t (yet) very dense; I think that smvs and perhaps adjusting the default values for the radius steps will yield much better results. 

Our DEM algorithm is the same as http://www.opentopography.org/otsoftware/points2grid for which recommendation is “The local gridding approach employed by Points2Grid is most effective in situations where lidar shot densities exceed the resolution of the grid to be produced from these data.” http://lidar.asu.edu/KnowledgeBase/WCptcount/

Using a nearest neighbor idw interpolation yields better results in sparse datasets, but cripples fast with larger datasets. Or at least the algorithm in VTK does.

**Comment by pierotofy** [comment]
You can try experimenting by using v.surf.idw within GRASS to see the performance problem. https://github.com/GRASS-GIS/grass-ci/blob/master/vector/v.surf.idw/main.c

Granted, GRASS's implementation is not multi-threaded and it could be improved/optimized.

Gridded with current defaults:

![image](https://user-images.githubusercontent.com/1951843/41134949-122c6736-6a9d-11e8-9010-5f77b7fe02f0.png)

Gridded with radius 0.56 and 1.68 (I changed the value manually in `odm_dem.py:93`):

![image](https://user-images.githubusercontent.com/1951843/41135134-293e7e90-6a9e-11e8-84bf-1e6667bfba38.png)

v.surf.idw (12 neighbors, power 2):

![image](https://user-images.githubusercontent.com/1951843/41135095-eb43dd60-6a9d-11e8-9019-4cc15cb68ad5.png)

v.surf.idw took 4 minutes for ~300.000 points, grid method took 14 seconds.

The circular artifacts, just like the recommendation says, are most evident in areas where point density is low. In those areas, nearest neighbor IDW creates a much better interpolation.

**Comment by smathermather** [comment]
Cool. Yes, I wouldn't recommend IDW for such large datasets. Thanks for the comparison of techniques. I will withhold judgment until the point clouds are better. :)

**Comment by pierotofy** [comment]
Another feature we should add to this for better outputs:
 - Mesh cleanup via island removals

![image](https://user-images.githubusercontent.com/1951843/41205366-f6865846-6cbf-11e8-8a34-007ae1878129.png)

**Comment by pierotofy** [comment]
After some analysis, the DSM will need to be computed twice.

 - odm_georeferencing requires a mesh (always).
 - our approach to meshing requires a DSM.

point cloud --> DSM --> mesh --> texturing --> georeferencing --> transformed point cloud --> georeferenced DSM.

Future work could revolve around changing how georeferencing works (removing its dependency on meshes, we could theoretically move it after the point cloud step):

point cloud --> georeferencing --> DSM --> mesh --> texturing --> ....

But I'm not sure what the implications would be and if it's feasible. More research will be needed.

**Comment by pierotofy** [comment]
Island removal!

![cleanup](https://user-images.githubusercontent.com/1951843/41267574-ee86cf26-6dc9-11e8-97a6-2ef1ccbd07e4.gif)

We'll add decimation in the mix as well for preserving the --mesh-size option which is missing in the new PoissonRecon.

**Comment by smathermather** [comment]
Yay island removal! I assume based on these mushroom shapes, this is not yet a 2.5D mesh.

**Comment by pierotofy** [comment]
Correct, skirts have been added as of https://github.com/OpenDroneMap/OpenDroneMap/pull/844/commits/b54c4808e1cfbeb9185f184c25d0cb336b7ccccd

**Comment by pierotofy** [comment]
Done!
