### ISSUE TITLE
app = ODMApp(args=args) fails

### ISSUE THREAD

**Issue by g33kyaditya** [OpenDroneMap/ODM#853]
### How did you install OpenDroneMap? (Docker, natively, ...)?

A modified ODM that runs in a conainer and gets input from the cloud. The base image is `opendronemap/opendronemap:latest`

### What is the problem?
My first step is to download images from the cloud. Those get saved in the container path `/code/output/images/`

Next step starts the ODM process. It gives the following traceback.

```
Traceback (most recent call last):
  File "run.py", line 93, in <module>
    app = ODMApp(args=args)
  File "/code/scripts/odm_app.py", line 27, in __init__
    ecto.BlackBox.__init__(self, *args, **kwargs)
  File "/code/SuperBuild/install/lib/python2.7/dist-packages/ecto/blackbox.py", line 259, in __init__
    self.__connect()
  File "/code/SuperBuild/install/lib/python2.7/dist-packages/ecto/blackbox.py", line 284, in __connect
    raise BlackBoxError('Got error "%s" when calling connections on "%s"' % (str(e), str(self)))
ecto.blackbox.BlackBoxError: Got error "           exception_type  EctoException
[diag_msg] = no inputs or outputs found

[cell_name] = ODMLoadDatasetCell

[tendril_key] = photos

" when calling connections on "<scripts.odm_app.ODMApp object at 0x7f6664b45810>"

```

**Comment by pierotofy** [comment]
This should now be fixed since ecto is gone. Also the new docker image is `opendronemap/odm`. If not, please open a new issue! :+1:
