### ISSUE TITLE
Generating texture patches terminates with bad_alloc (>350 images)

### ISSUE THREAD

**Issue by nj07** [OpenDroneMap/ODM#855]
I am running OpenDroneMap using Docker on GCP. My instance has 32GB RAM. Input size is 413 images.

docker run -it --rm -v "$(pwd)/images:/code/images" -v "$(pwd)/odm_prthophoto:/code/odm_orthophoto" -v "$(pwd)/odm_texturing:/code/odm_texturing" opendronemap/opendronemap

While generating texture patches, it terminates with bad_alloc. 

        Building BVH from 114082 faces... done. (Took: 240 ms)
        Calculating face qualities 100%... done. (Took 844.099s)                
        Postprocessing face infos 100%... done. (Took 0.999s)                   
        Maximum quality of a face within an image: 84027.3
        Clamping qualities to 6899.33 within normalization.
        Writing data cost file... done.
        Optimizing:
                Time[s] Energy
                0       88736
                1       87660
                1       85639
                2       84446
                2       83905
                2       83630
                3       83473
                4       83312
                4       83210
                4       83132
                5       83086
                5       83046
                5       83017
                6       82999
                6       82976
        13652 faces have not been seen
        Took: 853.919s
Generating texture patches:
        Running... terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/mvstex.py", line 139, in process
    '{keepUnseenFaces}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 134

Please help. Thanks

**Comment by pierotofy** [comment]
Not enough memory, same as #856
