### ISSUE TITLE
It keeps Installing OpenDroneMap

### ISSUE THREAD

**Issue by YasinYigit** [OpenDroneMap/ODM#86]
I am a student from Vives in Belgium (Oostende) and I want to install OpenDroneMap on my laptop (Windows 7). I followed the steps to install the program, but after step 11, it doesn't do anything. It just keeps installing. Normally after 20 minutes, the installation would be completed. I even waited 2 hours, but it keeps installing OpenDroneMap. I don't think that this is normal. 

Can someone tell me what the problem could be?
My laptop runs on Windows 7 Home Premium 64-bit and has 3GB RAM.

**Comment by smathermather** [comment]
Hi @YasinYigit -- can you post these questions to the mailing list? http://lists.osgeo.org/cgi-bin/mailman/listinfo/opendronemap-users  Thanks, best, Steve
