### ISSUE TITLE
Help: Install Gromacs

### ISSUE THREAD

**Issue by maxisebascastillo** [OpenDroneMap/ODM#866]
I have the next error:
maximiliano@maximiliano-VirtualBox:~/Proyecto Final/gromacs-2018/build$ make
[  0%] Performing configure step for 'fftwBuild'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... configure: error: unsafe srcdir value: '/home/maximiliano/Proyecto Final/gromacs-2018/build/src/contrib/fftw/fftwBuild-prefix/src/fftwBuild'
src/contrib/fftw/CMakeFiles/fftwBuild.dir/build.make:109: recipe for target 'src/contrib/fftw/fftwBuild-prefix/src/fftwBuild-stamp/fftwBuild-configure' failed
make[2]: *** [src/contrib/fftw/fftwBuild-prefix/src/fftwBuild-stamp/fftwBuild-configure] Error 1
CMakeFiles/Makefile2:1440: recipe for target 'src/contrib/fftw/CMakeFiles/fftwBuild.dir/all' failed
make[1]: *** [src/contrib/fftw/CMakeFiles/fftwBuild.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

I NEED HELP!! Please!

**Comment by pierotofy** [comment]
Hey @maxisebascastillo I think you posted this in the wrong place? This is the issue tracker for OpenDroneMap, not Gromacs.
