### ISSUE TITLE
TypeError during split-merge

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/ODM#868]
_what's the preference for something like this? forum post or GitHub issue?_

- AWS specs:
    - **ami:** ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180522 - ami-db710fa3
    - **instance type:** m4.2xlarge (ECUs: 26, vCPUs: 8, Memory: 32 GiB)
- OpenDroneMap native install at 58a19b7c4cb51cd62d6d68a2e4406d3eebe83302 (9-Jul-2018)
- dataset is 2,378 images, 4000 × 3000, taken with a DJI Mavic
- split-merge run with run_all.sh and only change to settings.yaml was setting the project_path.
- the [full log](https://github.com/OpenDroneMap/OpenDroneMap/files/2181746/log-type-error.txt) 

```
[94m[INFO]    Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt[0m
[94m[INFO]    Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt[0m
[92m[DEBUG]   Found GEOS DLL: <CDLL '/usr/local/lib/python2.7/dist-packages/shapely/.libs/libgeos_c-bd8d3f16.so.1.10.2', handle 2574610 at 7f616ef23dd0>, using it.[0m
[92m[DEBUG]   Trying `CDLL(libc.so.6)`[0m
[92m[DEBUG]   Library path: 'libc.so.6'[0m
[92m[DEBUG]   DLL: <CDLL 'libc.so.6', handle 7f6192ca44e8 at 7f616ef23e10>[0m
Traceback (most recent call last):
  File "/home/ubuntu/OpenDroneMap/scripts/metadataset/merge.py", line 78, in <module>
    if poly.contains(Point(point[[2, 3]])):
  File "/usr/local/lib/python2.7/dist-packages/shapely/geometry/point.py", line 49, in __init__
    self._set_coords(*args)
  File "/usr/local/lib/python2.7/dist-packages/shapely/geometry/point.py", line 130, in _set_coords
    self._geom, self._ndim = geos_point_from_py(args[0])
  File "/usr/local/lib/python2.7/dist-packages/shapely/geometry/point.py", line 209, in geos_point_from_py
    dx = c_double(coords[0])
TypeError: a float is required
```

**Comment by smathermather** [comment]
If your hunch is that it is a bug, then by all means post here, though in general terms it is better to start on community and then escalate if needed. This quacks like a bug, so happy to have it here.

We need @dakotabenjamin too look at shapely and the final merge step for split-merge anyway, e.g. : https://github.com/OpenDroneMap/OpenDroneMap/issues/815

I assume all your orthophotos output?

**Comment by danbjoseph** [comment]
I checked a few folders for the file via cyberduck (were there) and downloaded and looked at one.
![screen shot 2018-07-10 at 4 27 58 pm](https://user-images.githubusercontent.com/4806884/42535760-498b47b2-845e-11e8-81a0-58965d7b85e1.png)

**Comment by dakotabenjamin** [comment]
I'm not sure on this one. Can you tell me what version of `shapely` and `libgeos` you are running?

**Comment by dakotabenjamin** [comment]
@smathermather can you also recommend meshing parameters for Dan to improve the ortho there?

**Comment by danbjoseph** [comment]
```
$ pip show shapely
---
Metadata-Version: 2.0
Name: Shapely
Version: 1.6.4.post1
Summary: Geometric objects, predicates, and operations
Home-page: https://github.com/Toblerity/Shapely
Author: Sean Gillies
Author-email: sean.gillies@gmail.com
Installer: pip
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  Intended Audience :: Science/Research
  License :: OSI Approved :: BSD License
  Operating System :: OS Independent
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Topic :: Scientific/Engineering :: GIS
```
 how do i get the `libgeos` version?

**Comment by smathermather** [comment]
```ldconfig -v | grep libgeos```

**Comment by danbjoseph** [comment]
```
$ ldconfig -v | grep libgeos
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.23.so is the dynamic linker, ignoring

	libgeos-3.5.1.so -> libgeos-3.5.1.so
	libgeos_c.so.1 -> libgeos_c.so.1.9.1
/sbin/ldconfig.real: Cannot stat /usr/lib/libmca_common_sm.so: No such file or directory
/sbin/ldconfig.real: Cannot stat /usr/lib/liboshmem.so: No such file or directory
/sbin/ldconfig.real: Cannot stat /usr/lib/libopen-rte.so: No such file or directory
/sbin/ldconfig.real: Cannot stat /usr/lib/libopen-pal.so: No such file or directory
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
```

**Comment by danbjoseph** [comment]
@dakotabenjamin i can also give you access to the EC2 instance so you can poke around if that would help

**Comment by danbjoseph** [comment]
installing on AWS, is there a recommended ami that might have different default software versions? or something i should try to see if this a dependency issue (versions, compatibility, etc)? anything i could try and adjust before running this again?

**Comment by tamaradjerdj** [comment]
Is there any news on this bug?

**Comment by smathermather** [comment]
@gyorgytamara, we are working on a rebuild of split-merge, making it a core part of ODM. That work is set to kick off shortly and continue through January.

**Comment by pierotofy** [comment]
Brand new split-merge pipeline is now merged into `master` so this can probably be closed! If there are still errors, please open a new issue. :+1:
