### ISSUE TITLE
custom parameter --time -> file location

### ISSUE THREAD

**Issue by vgorte** [OpenDroneMap/ODM#869]
The ODM docs state that the custom parameter --time creates a benchmark file. 
Where can I find this file?
I would really appreciate if someone could help me.

**Comment by pierotofy** [comment]
Look for a `benchmark.txt` file.

**Comment by vgorte** [comment]
Hey @pierotofy. Thanks for your reply. There is no benchmark.txt.

I use docker and I ran something like:

```
docker run -it --rm \
    -v $(pwd)/images:/code/images \
    -v $(pwd)/opensfm:/code/opensfm \
    -v $(pwd)/odm_meshing:/code/odm_meshing \
    -v $(pwd)/odm_texturing:/code/odm_texturing \
    -v $(pwd)/odm_orthophoto:/code/odm_orthophoto \
    my_odm_image --time --min-num-features 2500
```
Is there an error in the command?

**Comment by pierotofy** [comment]
No, no error, but the file will be created inside the docker container and the file is not mapped to the host filesystem (so it won't show up).

Try with:

`docker run -ti --rm -v $(pwd):/datasets/code my_odm_image --time --min-num-features 2500 --project-path /datasets`

**Comment by vgorte** [comment]
Works like a charm. Thank you very much.
