### ISSUE TITLE
Incomplete output while processing the complete dataset

### ISSUE THREAD

**Issue by deepthipatric** [OpenDroneMap/ODM#870]
Hi,
I have been using ODM and WebODM for processing datasets from GoPro Hero 4 Black.
So when I process half of the dataset, the results seem impressive but when I try to process the complete dataset it gives me unusual results. (Even after retaining  high resolution)

The datasets were processed using ODM deployed natively,  docker and webODM.
 

![screenshot from 2018-07-26 12-54-42](https://user-images.githubusercontent.com/33624842/43250815-d7fc5aac-90db-11e8-881f-87c4f9e5d2ab.png)
![screenshot from 2018-07-26 13-03-42](https://user-images.githubusercontent.com/33624842/43250817-d8ad2de6-90db-11e8-8fcd-5e0148e71982.png)

**Comment by smathermather** [comment]
Hi Deepthi,

Are you calibrating the images first?

Cheers,
Best,
Steve

**Comment by deepthipatric** [comment]
Hey Steve,
The images were calibrated before processing in ODM.
Image resolution was  7 MP medium .

**Comment by smathermather** [comment]
Here's my hunch -- I think you are getting multiple models because you aren't getting good enough matches between the subsets of the dataset.

Unfortunately, I'm about to go on vacation, so it might be good to restart this thread on community.opendronemap.org so that someone else can help.

**Comment by deepthipatric** [comment]
The images were taken with an overlap and sidelap of 80%.
I'll start the discussion in the community webpage.
Have a great vacation :)
