### ISSUE TITLE
Issue while running ODM on Ubuntu 17.10 with docker - Nothing happen

### ISSUE THREAD

**Issue by mimoun973** [OpenDroneMap/ODM#875]
Hello,
I installed OpenDroneMap with docker (CE version). When I run  the classic 
`docker run -it --rm \
-v "$(pwd)/images:/code/images" \
-v "$(pwd)/odm_orthophoto:/code/odm_orthophoto"\
-v "$(pwd)/odm_texturing:/code/odm_texturing"\
opendronemap/opendronemap`

The two subdirectories are created (odm_orthophoto and odm_texturing) but then the command finished and nothing more happen. I looked into the differents issues, I have not seen it yet.

Installed on Ubuntu 17.10.

**Comment by dakotabenjamin** [comment]
Perhaps it couldn't find the images, but I wouldn't be able to know without seeing the command line output. Can you check that you were running the command from the project directory? `$(pwd)/images` shouyld already have your images in it.
