### ISSUE TITLE
found no usable images

### ISSUE THREAD

**Issue by YasinYigit** [OpenDroneMap/ODM#88]
i have installed odm correctly. At the end i get script finished.
When i want to "run the opendronemap app on the an odm_data test datatest",
it says that it founds no usable images.
please, can someone help me with this one. I need it for my project...
Thanks
![no usable images](https://cloud.githubusercontent.com/assets/11645333/6866411/428dd9a0-d478-11e4-846b-0f44ebdd3d1d.png)

**Comment by smathermather** [comment]
Hi @YasinYigit -- can you do an `ls -l` in the directory you are in?

**Comment by YasinYigit** [comment]
I solved the problem. I can run ODM now. Thanks for your help !!!

**Comment by smathermather** [comment]
Great!
