### ISSUE TITLE
libexiv2-dev needs to be updated

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#880]
Currently it will not read certain images' EXIF tags (such as ones we captured with a Mavic Pro). This in turns makes the `odm_extract_utm` program to fail. Using to the latest version from Github (not the Ubuntu package) fixes the problem (plus some minor modifications to odm_extract_utm to support the newer version).

**Comment by smathermather** [comment]
👍

**Comment by pierotofy** [comment]
Related: http://community.opendronemap.org/t/an-orthophoto-could-not-be-generated/1018/4

**Comment by pierotofy** [comment]
![image](https://user-images.githubusercontent.com/1951843/45227446-8027eb00-b28e-11e8-8dbf-1af709b1b2a7.png)

We should switch to GExiv2
