### ISSUE TITLE
Read initial photo angles from EXIF

### ISSUE THREAD

**Issue by Komzpa** [OpenDroneMap/ODM#886]
DJI Mavic Pro (at least) stores all the angles of photo in EXIF. 

Gwenview is able to show them:

![image](https://user-images.githubusercontent.com/810638/44999859-06131000-afc9-11e8-85be-791ad76c9fdc.png)

It would be great if this info can be reused.

**Comment by pierotofy** [comment]
Yes, the problem is that the GPS and compass information are far too inaccurate to skip the structure from motion process, so even if the gimbal information is fairly accurate, we would still need to compute everything else to compute a good reconstruction.

That's to my knowledge at least.

**Comment by Komzpa** [comment]
@pierotofy I see the following possibilities for using this data:
 - Get a rough view box of image projected on the ground. Look for pairs by matching overlapping boxes;
 - Remove photos with sky from reconstruction before even starting;
 - Mask sky on photos before finding matching points;
 - Remove photo from reconstruction if computed angles don't match the ones in EXIF.

Does this make sense?

**Comment by Komzpa** [comment]
Here's a way to quickly group photos into down-facing and not down facing:
```
exiftool -n -"Directory<GimbalPitchDegree" .
```

After that you get a bunch of directories named as pitch degree. Pull only the ones with <-60 into processing to get rid of the ones having horizon in them, or <-80 to get down-looking only.

**Comment by pierotofy** [comment]
This is now available in `2.7.0`! Choose `--sfm-algorithm triangulation` to use OPK angles. :clinking_glasses:
