### ISSUE TITLE
Ortophoto improvements

### ISSUE THREAD

**Issue by Komzpa** [OpenDroneMap/ODM#887]
OpenDroneMap Blog features a post on improvements, showing cool perpendicular buildings:
https://www.opendronemap.org/2018/07/repost-upcoming-improvements-to-opendronemap-better-everything/

However Docker latest version still produces this:
![image](https://user-images.githubusercontent.com/810638/45003979-bfd1a700-aff0-11e8-8353-edaac36cbbf4.png)

Where do I take the version featured in blog post?

**Comment by pierotofy** [comment]
The version featured on the blog hasn't been released as of yet. We don't have a timeline, but we're hoping to release it within a few weeks. :+1:

**Comment by Komzpa** [comment]
@pierotofy is there a branch to look at?

**Comment by pierotofy** [comment]
Some (not all) work is available on: https://github.com/OpenDroneMap/OpenDroneMap/commit/8e59b2f107f02b6b119f73885801d691dea99f19

I don't think it's in usable state however.

**Comment by hoffa111** [comment]
@pierotofy Hello,
Is it possible to use v0.4 RC1 to get better results for orthophoto? I built it from source on my ubuntu and it still produced results with warping and visual artifacts. Thanks in advance.

**Comment by pierotofy** [comment]
@hoffa111 make a clone from `master`. We just merged #889 :+1:

**Comment by hoffa111** [comment]
@pierotofy many thanks, I will try! Which parameters I need to use to get better quality? In previous version I used those parameters:
--resize-to: -1
--min-num-features: 25000
--mesh-octree-depth: 6
--mesh-solver-divide: 6
--orthophoto-resolution: 100
--dem-terrain-type: FlatNonForest
--force-ccd: 13.1
Also, I mainly use it for photos with buildings.

**Comment by pierotofy** [comment]
Change `--orthophoto-resolution` to 0.001 with the new version (we've changed the units), also remove --mesh-octree-depth and --mesh-solver-divide.

**Comment by hoffa111** [comment]
@pierotofy Hello,
I just tested it and roofs of buildings has strange wavy effects (see attachment). I used these parameters:
--min-num-features: 25000
--orthophoto-resolution: 0.001
--force-ccd: 13.1
How can I fix this? Thanks in advance.

![wavy](https://user-images.githubusercontent.com/8358617/45484047-0ce61380-b77d-11e8-859a-2a1b6c7acfac.png)

**Comment by pierotofy** [comment]
Let's move the conversation over to http://community.opendronemap.org since this is starting to look like a question thread and the GitHub repo should be used only for bug reports. Thank you!

**Comment by Komzpa** [comment]
The link won't work:
![image](https://user-images.githubusercontent.com/810638/45596172-8752a580-b9c0-11e8-9dff-b76ba7f4f758.png)

**Comment by pierotofy** [comment]
Ah, sorry, use this URL (non-https): http://community.opendronemap.org
