### ISSUE TITLE
Working with big datasets 

### ISSUE THREAD

**Issue by vgorte** [OpenDroneMap/ODM#894]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

Question:

What is the best way to work with big datasets? I mean really big, like 5000+ images.
I was thinking of running the following command:

`docker run -ti --rm -v $(pwd):/datasets/code opendronemap/opendronemap --project-path /datasets --time --verbose --min-num-features 2000`

Any advice for working with big datasets? Also, what if the process terminates in between? Is there a way to continue from the point before the termination? 
For example in the middle of the candidate matching, can I restart the process from before the termination?

Thanks in advance

**Comment by pierotofy** [comment]
Hi @vgorte, could we please move the conversation over to http://community.opendronemap.org? That's the best place to ask questions. Thank you!
