### ISSUE TITLE
Not possible to save the smvs results

### ISSUE THREAD

**Issue by plouj** [OpenDroneMap/ODM#902]
This line:
https://github.com/OpenDroneMap/OpenDroneMap/blob/9b4345681518fc668a2a051e032e3032ce9e747e/scripts/smvs.py#L63 makes it almost impossible to save the smvs step's work in order to be able to resume without having to redo it. Currently running with docker like:

```
docker run -it --rm \
    -v "$(pwd)/images:/code/images" \
    -v "$(pwd)/odm_georeferencing:/code/odm_georeferencing" \
    -v "$(pwd)/odm_meshing:/code/odm_meshing" \
    -v "$(pwd)/odm_orthophoto:/code/odm_orthophoto" \
    -v "$(pwd)/odm_texturing:/code/odm_texturing" \
    -v "$(pwd)/opensfm:/code/opensfm" \
    -v "$(pwd)/smvs:/code/smvs" \
    opendronemap/opendronemap
```

results in:

```
...
[INFO]    Running SMVS Cell
Traceback (most recent call last):  
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)  
  File "/code/scripts/smvs.py", line 63, in process
    shutil.rmtree(tree.smvs)  
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info()) 
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree 
    os.rmdir(path)  
OSError: [Errno 16] Device or resource busy: '/code/smvs'
```

**Comment by pierotofy** [comment]
Hey @plouj, that error means you probably have a container already mounting the smvs directory.

What if you run OpenDroneMap as follows?

Place your JPGs in a folder named “images” (for example /my/project/images) , then simply run

`docker run -ti --rm -v /my/project:/datasets/code opendronemap/opendronemap --project-path /datasets`

**Comment by plouj** [comment]
[Edit]

Ah, I see what you mean now. The command you've provided should work for me now. I just didn't realize that I could use ```--project-path``` since the ```README.md``` file recommended mounting individual directories separately.

**Comment by pierotofy** [comment]
Yes, I think we should change the command reference in the `README.md`.

Perhaps you could help us and change it if you have time? https://github.com/OpenDroneMap/OpenDroneMap/edit/master/README.md

**Comment by plouj** [comment]
I would love to, but I think it would be faster for someone else to do it instead of me at this time.
