### ISSUE TITLE
Update documentation for new run-time parameters introduced by v0.4

### ISSUE THREAD

**Issue by thomas-bamford** [OpenDroneMap/ODM#905]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker OpenDroneMap

### What's your browser and operating system?

Ubuntu 18.04 LTS, browser is NA

### What is the problem?

Documentation at http://docs.opendronemap.org/using.html is not up to date with the latest release detailed in https://www.opendronemap.org/2018/09/better-everything-announcing-opendronemap-0-4/.

### What should be the expected behavior?

Update documentation to include change to cm/px resolution, and new arguments (depthmap-resolution, texturing-nadir-weight).

### How can we reproduce this?

Using current documented default orthophoto resolution of 20 px/meter produces an orthophoto at 20 cm/px.

**Comment by smathermather** [comment]
Closed by https://github.com/OpenDroneMap/docs/pull/11
