### ISSUE TITLE
Georeferencing failing even with geotagged photos

### ISSUE THREAD

**Issue by thsant** [OpenDroneMap/ODM#907]
Using ODM 0.4, I got the following error:

```
Error in OdmOrthoPhoto:
Problem reading header in modelfile!
```

Investigating the issue, I saw that `odm_textured_model_geo.obj` was not generated. Previously, I got the following warning:
`
[WARNING] Georeferencing failed. Make sure your photos have geotags in the EXIF or you have provided a GCP file.`

The photos were produced by a DJI Phantom 4 Pro and, apparently, all of them are properly geottaged:

```
GPS Version ID                  : 2.3.0.0
GPS Latitude Ref                : South
GPS Longitude Ref               : West
GPS Altitude Ref                : Above Sea Level
GPS Map Datum                   : WGS-84
GPS Altitude                    : 917.3 m Above Sea Level
GPS Latitude                    : 21 deg 58' 36.09" S
GPS Longitude                   : 47 deg 51' 10.74" W
GPS Position                    : 21 deg 58' 36.09" S, 47 deg 51' 10.74" W
```
I have gotten this issue over and over again, with different sets of images, since 0.4 update.

Any tip of advice?

**Comment by pierotofy** [comment]
Hey @thsant , thanks for reporting the problem.

Could you upload a few of the images for us to take a look at?

**Comment by thsant** [comment]
Thanks, @pierotofy. [At Dropbox](https://www.dropbox.com/sh/q3zevsytxp6dtzl/AACQ6VgsCmI6mcIazW6ybcpGa?dl=0) you will a few images plus some files I guess could help :

```
img_list.txt
odm_25dmesh.ply
odm_mesh.ply
reconstruction.json
```
Such files show that structure from motion, multiple view stereo and meshing steps look fine.

The command employed:

`docker run -ti --rm -v /home/odm/tutorial:/datasets/code opendronemap/opendronemap --project-path /datasets --start-with odm_orthophoto --dsm --dtm --orthophoto-resolution 2.0 --build-overviews --proj '+proj=longlat +ellps=WGS84 +datum=WGS84'`

The output (last lines):

```
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_geocoords /datasets/code/opensfm --transformation --proj '+units=m +proj=longlat +ellps=WGS84 +datum=WGS84'
[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running SMVS Cell
[WARNING] Found a valid SMVS reconstruction file in: /datasets/code/smvs/smvs_dense_point_cloud.ply
[INFO]    Running ODM SMVS Cell - Finished
[INFO]    Running ODM Meshing Cell
[WARNING] Found a valid ODM Mesh file in: /datasets/code/odm_meshing/odm_mesh.ply
[WARNING] Found a valid ODM 2.5D Mesh file in: /datasets/code/odm_meshing/odm_25dmesh.ply
[INFO]    Running ODM Meshing Cell - Finished
[INFO]    Running MVS Texturing Cell
[WARNING] Found a valid ODM Texture file in: /datasets/code/odm_texturing/odm_textured_model.obj
[WARNING] Found a valid ODM Texture file in: /datasets/code/odm_texturing_25d/odm_textured_model.obj
[INFO]    Running ODM Texturing Cell - Finished
[INFO]    Running ODM Georeferencing Cell
[WARNING] Georeferencing failed. Make sure your photos have geotags in the EXIF or you have provided a GCP file. 
[WARNING] Georeferencing failed. Make sure your photos have geotags in the EXIF or you have provided a GCP file. 
[INFO]    Running ODM Georeferencing Cell - Finished
[INFO]    Running ODM DEM Cell
[INFO]    Classify: True
[INFO]    Create DSM: True
[INFO]    Create DTM: True
[INFO]    DEM input file /datasets/code/odm_georeferencing/odm_georeferenced_model.laz found: False
[WARNING] DEM will not be generated
[INFO]    Running ODM DEM Cell - Finished
[INFO]    Running ODM Orthophoto Cell
[WARNING] Found a valid orthophoto in: /datasets/code/odm_orthophoto/odm_orthophoto.png
[INFO]    Running ODM OrthoPhoto Cell - Finished
[INFO]    OpenDroneMap app finished - Mon Nov 05 16:16:15  2018

```

**Comment by pierotofy** [comment]
Ah, I think the problem is the `--proj` param. You typically don't want to pass that parameter if you want to use the EXIF coordinates. Could you try to reprocess without it?

**Comment by thsant** [comment]
Thanks, @pierotofy, it's working now (removing the `--proj` option).

I (wrongly) assumed `--proj` could be employed to transform data between spatial reference systems.

**Comment by smathermather** [comment]
Excellent!
