### ISSUE TITLE
gippy and psutil modules not found after configure.sh install

### ISSUE THREAD

**Issue by fredlllll** [OpenDroneMap/ODM#908]
hi i just needed to reinstall odm again and used the latest release (checked out the commit) and after it was done installing i still had to manually install gippy and psutil using pip. can someone confirm that a fresh install is missing these? or was this just a hickup on my side again? i used a freshly installed ubuntu 16.04

**Comment by pierotofy** [comment]
The two modules should be installed with the configure.sh script:

https://github.com/OpenDroneMap/OpenDroneMap/blob/master/configure.sh#L101

**Comment by fredlllll** [comment]
strange. guess it was just a hiccup then
