### ISSUE TITLE
odm_georef does not handle points clouds > 600 million points

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#928]
While it doesn't crash, the point cloud it generates is corrupted. This is likely due to some overflow in the PCL PLY parser.

Artifacts:

![image](https://user-images.githubusercontent.com/1951843/50386254-55cd3280-06b1-11e9-91c3-89d5f66a11fb.png)

How it should look instead:

![image](https://user-images.githubusercontent.com/1951843/50386261-65e51200-06b1-11e9-9268-f75f2bdd036e.png)

I will rewrite the PCL loading code and add the ability to do stream read/writes, so that the point cloud does not need to be loaded in memory all at once.

**Comment by pierotofy** [comment]
Or perhaps using the PDAL C++ API.

By using PDAL we could remove the unnecessary step of generating a PLY file and we could go directly to LAZ by passing the SRS as a param to odm_georef.

**Comment by smathermather** [comment]
Could speed that step up a bit too.

**Comment by garlac** [comment]
I came across same issue...Below are the screenshots. 1201 images and point cloud had 217.77 million points and size 9.2 Gb.

Georeferenced point cloud Vs normal dense point cloud:
![gcp_hosur](https://user-images.githubusercontent.com/40228026/50883340-c6908080-140d-11e9-9d8e-52d4315afbbe.png)

It also created some other point cloud below like this:
![gcp_hosur_1](https://user-images.githubusercontent.com/40228026/50883366-d6a86000-140d-11e9-8ba4-ffb9158b7d72.png)

Hope the pull request in - https://github.com/OpenDroneMap/ODM/pull/929/files
solves this problem. Will test it.

Thank you.

**Comment by garlac** [comment]
I have tested it and found that the geo-referenced point cloud came good. Thank you @pierotofy .

**Comment by pierotofy** [comment]
Thanks for testing @garlac!

Out of curiosity, what environment did you test this on? (Windows, Linux, Mac, and was it with docker or native?)

@dakotabenjamin do you need more time to test #929?

**Comment by garlac** [comment]
It was Linux env and native install. 64 Gb RAM 12 cores.
