### ISSUE TITLE
Mobius Cam

### ISSUE THREAD

**Issue by FLYBYME** [OpenDroneMap/ODM#93]
Do you think we can add support for the Mobius Cam?

**Comment by smathermather** [comment]
Might be tricky. Any thoughts @wildintellect?

**Comment by wildintellect** [comment]
I don't see any particular reason why not, just need a camera model for it. Cole was testing checkerboard calibration code, maybe give that a try. Not sure if it's posted yet.

**Comment by FLYBYME** [comment]
I have some information here that might be of use.

https://github.com/DroidPlanner/Tower/issues/1290

**Comment by smathermather** [comment]
Cool. Can you run `jhead` on an image from the Mobius Cam?

**Comment by FLYBYME** [comment]
```
Approximate quality factor for qtable 0: 90 (scale 19.88, var 1.14)
Approximate quality factor for qtable 1: 90 (scale 20.45, var -6.08)
JPEG image is 2304w * 1536h, 3 color components, 8 bits per sample
File name    : .\IMAG1102.JPG
File size    : 1334184 bytes
File date    : 2015:03:31 17:45:40
Resolution   : 2304 x 1536
```

All I got from jhead.

**Comment by smathermather** [comment]
Re: Cole, he posted code, but I don't think it's yet a full utility yet.

**Comment by smathermather** [comment]
@FLYBYME -- install exif
`sudo apt-get install exif`

and run EXIF on it. It should state the name of the camera in the header too.

**Comment by smathermather** [comment]
Hey @FLYBYME -- re-reading, you did provide everything needed, so I added it:

https://github.com/OpenDroneMap/OpenDroneMap/commit/c96b49c480defcc87d9622b772267acbd514794f

Cheers
