### ISSUE TITLE
Georeferencing point clouds before making meshes

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#932]
It's been suggested (https://community.opendronemap.org/t/what-would-you-like-to-see-next/1617/5) to add an option to skip meshing, but to still allow point cloud georeferencing.

**Comment by smathermather** [comment]
This mirrors something I have been thinking about -- we should provide as many georeferenced products as possible regardless of whether meshing and orthos complete (i.e. even if they fail or are opted not to be created).

**Comment by smathermather** [comment]
Did this ever happen?

**Comment by pierotofy** [comment]
Nop, also don't think it will get implemented anytime soon. Not enough interest.

**Comment by casbolwerk** [comment]
Would also appreciate this!
