### ISSUE TITLE
native install with splitmerge-ecto fails

### ISSUE THREAD

**Issue by danbjoseph** [OpenDroneMap/ODM#934]
### How did you install WebODM? (Docker, natively, ...)?

ran `bash configure.sh install` on AWS EC@ - Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-076e276d85f524150 (64-bit x86) with `splitmerge-ecto`  https://github.com/OpenDroneMap/ODM/commit/3eac0c7048940e815b3fa7a2d7d9f1434295f9ba

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

see above

### What is the problem?

ended with
```
...
-- Configuring incomplete, errors occurred!
```
- [install-output-log.txt](https://github.com/OpenDroneMap/WebODM/files/2753530/install-output-log.txt)
- [CMakeError.log](https://github.com/OpenDroneMap/WebODM/files/2753532/CMakeError.log)
- [CMakeOutput.log](https://github.com/OpenDroneMap/WebODM/files/2753533/CMakeOutput.log)

### What should be the expected behavior?

it should install. running `sudo bash configure.sh reinstall` on `master` completes without error.
```
...
[100%] Linking CXX executable ../../bin/odm_georef
[100%] Built target odm_georef
Configuration Finished
```

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

see above

**Comment by pierotofy** [comment]
Hey @danbjoseph, this should now be fixed since we did some large changes in the split-merge pipeline (now merged into `master`)! If not, please re-open this. :+1:
