### ISSUE TITLE
Automagical UTM south zone detection would be nice to have

### ISSUE THREAD

**Issue by adamsteer** [OpenDroneMap/ODM#935]
ODM always writes out UTM coordinates for northern hemisphere zones in the georeferencing step.

usage:
`time docker run -ti --rm -v $(pwd):/datasets/code opendronemap/opendronemap --project-path /datasets --end-with odm_georeferencing --rerun-all --force-ccd 5.97 --time`

sample image EXIF: 
```
exiftool image.jpg
....
GPS Altitude                    : 624.5 m Above Sea Level
GPS Latitude                    : 35 deg 18' 48.69" S
GPS Latitude Ref                : South
GPS Longitude                   : 149 deg 3' 13.25" E
GPS Longitude Ref               : East
GPS Position                    : 35 deg 18' 48.69" S, 149 deg 3' 13.25" E
...
```
ODM writes out the proj string:
`+units=m +no_defs=True +datum=WGS84 +proj=utm +zone=55 ` 

...to `odm_georeferencing`, which needs `+south`.

PDAL medatata output:
```
pdal info --metadata odm_georeferencing/odm_georeferenced_model.laz | jq .metadata.srs.wkt
"PROJCS[\"WGS 84 / UTM zone 55N\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",147],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],AUTHORITY[\"EPSG\",\"32655\"]]"
```

..should be `EPSG:32755` (UTM 55 South)

I should dive in and fix it myself, but lack time right now :/ sorry. Test image sets: 

https://drive.google.com/open?id=1iKaln4zzi7lnvn4Ced8Y7clr9gwe4u9w

Theres a .7z file which has 'overhead' imagery, the other data (backyard-test) is oblique. Either way, both get northified. I've also tested on third-party provided imagery and found the same issue (completely different collection platform).

(the ODM command above will have the correct ccd width for the imagery here)

Cheers

**Comment by adamsteer** [comment]
Ok this is a 'nice to have'  given the option:

```
--proj <PROJ4 string>
                      Projection used to transform the model into geographic
                      coordinates
```

**Comment by pierotofy** [comment]
Hey @adamsteer it's odd that this is happening. How does your `odm_georeferencing/coords.txt` file look like?

**Comment by pierotofy** [comment]
Ah, yep, here it is https://github.com/OpenDroneMap/ODM/blob/master/opendm/types.py#L166

utm_pole parsed but disregarded.

**Comment by adamsteer** [comment]
Thanks @pierotofy - I’ll be able to check/test on Monday. For anyone who wants to try, test images are linked in the issue post above (shout if you can’t get access to them)
