### ISSUE TITLE
Crash using depthmap-resolution parameter

### ISSUE THREAD

**Issue by zeb0x** [OpenDroneMap/ODM#937]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker ODM

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 64 on Ubuntu Linux.  12 cpu cores, 112 GB RAM

### What is the problem?

It crashes without finishing all the steps when I increase the depthmap-resolution.

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

I am following examples in [#769](https://github.com/OpenDroneMap/ODM/issues/769) to achieve denser point clouds.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I am processing 872 4800x3200 images taken with a drone.  

`docker run -ti --rm -v "/datadrive:/datasets/code" opendronemap/opendronemap 
   --project-path /datasets 
   --time 
   --depthmap-resolution 1200 
   --opensfm-depthmap-min-consistent-view 3 
   --opensfm-depthmap-method PATCH_MATCH 
   --resize-to 2048`

If I change the above to --depthmap-resolution 640 then it completes without issue

Here is a log file.
[log-Job_140-1200-3-PATCH_MATCH-2048.txt](https://github.com/OpenDroneMap/ODM/files/2774538/log-Job_140-1200-3-PATCH_MATCH-2048.txt)
Last part of log which shows some error messages:
` [92m[DEBUG]   Writing ODM Mesh file in: /datasets/code/odm_meshing/odm_mesh.ply[0m
[92m[DEBUG]   running /code/SuperBuild/src/PoissonRecon/Bin/Linux/PoissonRecon --in /datasets/code/smvs/smvs_dense_point_cloud.ply --out /datasets/code/odm_meshing/odm_mesh.dirty.ply --depth 9 --pointWeight 4 --samplesPerNode 1.0 --threads 12 --linearFit [0m
[92m[DEBUG]   running /code/build/bin/odm_cleanmesh -inputFile /datasets/code/odm_meshing/odm_mesh.dirty.ply -outputFile /datasets/code/odm_meshing/odm_mesh.ply -removeIslands -decimateMesh 100000  [0m
ERROR: In /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/IO/PLY/vtkPLYWriter.cxx, line 114
vtkPLYWriter (0x1012e60): No data to write!

[92m[DEBUG]   Writing ODM 2.5D Mesh file in: /datasets/code/odm_meshing/odm_25dmesh.ply[0m
[93m[WARNING] Cannot calculate GSD, using requested resolution of 5.0[0m
[92m[DEBUG]   ODM 2.5D DSM resolution: 0.2[0m
[94m[INFO]    Created temporary directory: /datasets/code/odm_meshing/tmp[0m
[94m[INFO]    Creating DSM for 2.5D mesh[0m
[94m[INFO]    Creating ../datasets/code/odm_meshing/tmp/mesh_dsm_r0.282842712475 [max] from 1 files[0m
[92m[DEBUG]   running pdal pipeline -i /tmp/tmpyuyzf0.json > /dev/null 2>&1[0m
[94m[INFO]    Completed ../datasets/code/odm_meshing/tmp/mesh_dsm_r0.282842712475 [max] in 0:08:51.881262[0m
[94m[INFO]    Starting gap-filling with nearest interpolation...[0m
[94m[INFO]    Completed gap-filling to create ../datasets/code/odm_meshing/tmp/mesh_dsm.tif in 0:00:12.538000[0m
[94m[INFO]    Creating mesh from DSM: /datasets/code/odm_meshing/tmp/mesh_dsm.tif[0m
[92m[DEBUG]   running /code/SuperBuild/src/dem2mesh/dem2mesh -inputFile /datasets/code/odm_meshing/tmp/mesh_dsm.tif -outputFile /datasets/code/odm_meshing/odm_25dmesh.ply -maxVertexCount 100000   [0m
[94m[INFO]    Running ODM Meshing Cell - Finished[0m
[94m[INFO]    Running MVS Texturing Cell[0m
[92m[DEBUG]   Writing MVS Textured file in: /datasets/code/odm_texturing/odm_textured_model.obj[0m
[92m[DEBUG]   running /code/SuperBuild/install/bin/texrecon /datasets/code/opensfm/reconstruction.nvm /datasets/code/odm_meshing/odm_mesh.ply /datasets/code/odm_texturing/odm_textured_model -d gmi -o gauss_clamping -t none       -n 65535[0m
/code/SuperBuild/install/bin/texrecon (built on Nov 29 2018, 13:56:13)
Load and prepare mesh: 
	Could not load mesh: No such file or directory
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/mvstex.py", line 126, in process
    '-n {nadirWeight}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1`

**Comment by smathermather** [comment]
Rather than using https://github.com/OpenDroneMap/ODM/issues/769, I suggest trying https://github.com/OpenDroneMap/ODM/pull/921, at least once it has been cleaned up a bit and merged into master. In extensive testing with these approaches, they are a bit of dead-end relative to using the smvs or mve libraries.

We're just a few weeks away from merging this in. I will close this issue for now.
