### ISSUE TITLE
Subprocess.Popen hangs infinitely if called application segfaults

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#944]
This is documented here http://code.activestate.com/lists/python-list/598080/

In short, if any program called via `system.run` seg faults, the program will hang infinitely. This is bad especially for NodeODM, because it has no way to know that the process failed and free up the queue.

**Comment by smathermather** [comment]
Has this been addressed?

**Comment by pierotofy** [comment]
I don't remember specifically fixing it, however, I haven't seen processes hanging up recently (and we have MVE still routinely crashing 10% of the time, but that doesn't stop the pipeline, so...). I'd say this can be closed and re-opened if hanging problems are identified in the future.
