### ISSUE TITLE
OdmExtractUtm Cannot read EXIFs for Mavic 2 Zoom

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#946]
Trying to process images from the Mavic 2 Zoom causes odm_extract_utm to fail with:

```
Error in OdmExtractUtm:
Failed parsing GPS position for DJI_0076.jpg
```

Related thread with images sample: https://community.opendronemap.org/t/i-can-not-create-an-orthophoto/1759

**Comment by juvinski** [comment]
Hi,

I faced the same problem and one of my images was without the GPS Altitude field filled.
Could you please send the exiftool of your image?

**Comment by pierotofy** [comment]
If you look at discussion in the forum there's a download link to the images.

**Comment by juvinski** [comment]
Sorry, I didn't realize that.
All the images are without the Altitude information - DJI_0073, DJI_0074, DJI_0076, DJI_0077 and DJI_0078.

GPS Altitude                    : 0 m Above Sea Level

**Comment by juvinski** [comment]
I was with same problem, but in my case just 1 image of 274 was with value 0 for Altitude - the 273 was right but the orthophoto wasn't generated. In this sample, 6 images of 6 was with without the Altitude information. Maybe a trigger to check the number of images with incorrect GPS data(altitude, latitude and longitude) could be implemented to ensure if you have values less than this threshold this errors could be ignored or not :)

**Comment by SebBub** [comment]
Dear all,

just managed to install WebODM on Mac and am super happy that it is all up and running now. :-) Just ran 109 pics that I took with my Mavic 2 Pro and Drone Harmony App. It took some time to process but finished successfully. The point cloud is there and looks great although seems to be flipped upside down (i.e. the treetops are pointing down in the 3D model. Will post in ODM Community on this issue.

Unfortunately I am having the same issue and cannot create an Orthophoto.

> An orthophoto could not be generated. To generate one, make sure GPS information is embedded in the EXIF tags of your images, or use a Ground Control Points (GCP) file.
> 
All images can be found here: [https://1drv.ms/f/s!Ak7jPKJPqpeBgYser3PvqY2esR1ODw](url)
GPS Coordinates extracted from images: [https://1drv.ms/t/s!Ak7jPKJPqpeBgYwPdAnFzlSGFOJSQg](url)

Full Task Output, also contains error message 
> Error in OdmExtractUtm:
> Failed parsing GPS position for DJI_0222.JPG
Text file can be found here: [https://1drv.ms/u/s!Ak7jPKJPqpeBgYwQdF3NoPv4z7MxJA](url)

@pierotofy so glad the project exists and I am really looking forward to a fix, as I trust many want to map with the consumer drones like the Mavic 2.

Thanks a million and best regards

**Comment by SebBub** [comment]
Herwith an update, I did manually correct the altitude data in Adobe Bridge from "0m below sea level" to 30m and now it seems to be all working just fine! Herwith link to Task Output: https://1drv.ms/t/s!Ak7jPKJPqpeBgakJ_TT-68SwVLTz4A

Not sure this is a bug in WebODM or rather an issue with the metadata written to the files from the Mavic 2.

**Comment by juvinski** [comment]
hi @pierotofy , can I change the default behavior of the utm extract to deal with altitude on the different way of today implementation? Any ideia how to deal with altitude ? what would be the impact of this change on the other modules of odm?

Best regards

**Comment by matonaka** [comment]
I responded to DJI support and received an answer.

Since e-mail is coming in Japanese, I will post the translated text in English on the translation site as it is.


We become indebted to.
It is DJI JAPAN Technical Support.

I sincerely apologize for taking time to answer.

We confirmed to head office department We are currently experiencing abnormality in altitude calculation recorded in EXIF ​​information due to product firmware bug.

※ This problem occurs only in calculation of the value entered in the EXIF ​​information, altitude on the application or altitude recognized by the barometer of the aircraft is normal.


According to the specifications of our products including Mavic 2, errors are always generated at the altitude in the Exif information
It will be relieved with future Mavic 2 firmware update.
At present, the release date etc. are undecided.

I apologize for any inconvenience,
We appreciate your understanding.

**Comment by pierotofy** [comment]
Images without an altitude field should now be much better supported. This includes the mavic 2 zoom dataset. Please update, test and re-open if this is not solved?

**Comment by leighghunt** [comment]
> Images without an altitude field should now be much better supported. This includes the mavic 2 zoom dataset. Please update, test and re-open if this is not solved?

Seems to work with my quick test just now with latest docker images. `adv 2...` and `adv 3...` projects using same datasets of small set of 4 images - only difference between them is latest docker images. 

<img width="1411" alt="Screen Shot 2019-04-10 at 4 30 14 PM" src="https://user-images.githubusercontent.com/349153/55851759-30a3f780-5bae-11e9-8ba6-892c3ccc3142.png">

I'll retest with larger dataset, but looks good. Thanks for your work @pierotofy :-)

[Update - larger dataset of 90 pictures worked fine]
