### ISSUE TITLE
how to compile opendronemap on vs2015

### ISSUE THREAD

**Issue by WF946773243** [OpenDroneMap/ODM#952]
how to compile opendronemap on vs2015?

**Comment by LightFieldVision** [comment]
I also encountered the same problem.

**Comment by LightFieldVision** [comment]
@smathermather

**Comment by WF946773243** [comment]
I'm Windows user, and I'm using VS2015 to compile my С++ projects for Windows.I have not found any documentation in Google.Can you tell me how to compile opendronemap on vs2015? @smathermather

**Comment by smathermather** [comment]
It cannot be done. OpenSfM cannot be compiled on Windows by any trivial means.  That said, @pierotofy is working on a windows port and would probably be open to help/collaboration.
