### ISSUE TITLE
Scale problem

### ISSUE THREAD

**Issue by mesaricardo** [OpenDroneMap/ODM#964]
Hello,

I am using webODM some months ago and I have good results (EEUU, Canada), but in a particular area (Uruguay, WGS84 UTM21S) the result wasn't well. I tried with a differents flights and all had the same result.

 I don't have GCP of this areas, but all was tested with other photogrametry sofwares and the resault was well.

Description
Installation: webODM natively
Browsers: Explorer, Edge, Mozilla, Chrome
OS: Ubuntu Server 16.04 LTS

Drone: eBee
Camera: Canon PowerShot ELPH 110 HS

The result testing diferents configuration of proccess was all similars.

This is a print screen of the results:

![Capture1](https://user-images.githubusercontent.com/49068799/55237833-cab08b00-5211-11e9-8f16-ff8f33eaea14.PNG)
![Capture2](https://user-images.githubusercontent.com/49068799/55237834-cb492180-5211-11e9-8d2e-49870d76852a.PNG)
![Capture3](https://user-images.githubusercontent.com/49068799/55237831-ca17f480-5211-11e9-8c4f-7caae52eda6c.PNG)
![Capture4](https://user-images.githubusercontent.com/49068799/55237832-cab08b00-5211-11e9-9865-0c7da00b9604.PNG)

How can fix this?

Best regards
Ricardo

**Comment by smathermather** [comment]
@pierotofy -- this isn't related to how we are handling Southern Hemisphere projection, it it?

**Comment by pierotofy** [comment]
Not related to that fix.

**Comment by pierotofy** [comment]
Wonder what happens if you pass `--use-fixed-camera-params` @mesaricardo ?

**Comment by mesaricardo** [comment]
Hi Piero,

all of Project haven't GCP that I run in webODM. But I runed them in other
software and the result was good.

Best regards.
Ricardo

**Comment by mesaricardo** [comment]
Dear Piero,

I tried with your suggestion but the result was identical to the others.

[image: Captura.JPG]

Kind regards.
Ricardo

**Comment by smathermather** [comment]
This is probably addressed by the use of Brown-Conrady camera by default.
