### ISSUE TITLE
Expose SMRF variables

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#972]
Would be useful to control the dsm generation parameters.

**Comment by smathermather** [comment]
Agreed. This might be a good place to discuss then the potential API surface for filtering. Direct manipulation of SMRF variables the most flexible, but keeping and refining the pre-sets may also be useful.

![](https://s3-eu-west-1.amazonaws.com/brussels-images/content/gallery/visit/place/Statue-Schtroumpfs_dfff70c5a19412d355dd216ed0dc7930cb786f5b_sq_640.jpg)
