### ISSUE TITLE
odm_cleanmesh

### ISSUE THREAD

**Issue by KeoChi** [OpenDroneMap/ODM#975]
Hello! In screened_poisson_reconstruction, after doing poisson_recon, it would do odm_cleanmesh. I don't understanding principle and purpose of odm_cleanmesh. Who can explain? Do you have relevant information or papers?

**Comment by pierotofy** [comment]
`odm_cleanmesh` serves two purposes:
 * Decimate the number of faces in a mesh (keep triangle count under control)
 * Remove "islands" (or isolated/floating components, e.g. components that are not connected to the main surface).

No papers, we kind of just did it on our own :)

p.s. next time let's open a question on the forum https://community.opendronemap.org instead.

**Comment by KeoChi** [comment]
OK. Thank you for your reply!
