### ISSUE TITLE
Can't signup/login to the community forum.

### ISSUE THREAD

**Issue by MatthiasSiewert** [OpenDroneMap/ODM#982]
I tried several methods including (email, github and twitter) to create an account or sign in to:
https://community.opendronemap.org/

The confirmation email never arrived on my email account (tried several email addresses) and the other methods returned an authentication issue:

' Sorry, there was an error authorizing your account. Perhaps you did not approve authorization? '

Also tried several browsers on two different computers with different ip adresses.

**Comment by ismailsunni** [comment]
I have the same problem

**Comment by smathermather** [comment]
Thanks. Looking into it.

**Comment by smathermather** [comment]
Try now @ismailsunni and @MatthiasSiewert.

**Comment by ismailsunni** [comment]
@smathermather I still got errors for Github, twitter, and Google.

**Comment by smathermather** [comment]
Can you log in via email? I will look into the others.

**Comment by MatthiasSiewert** [comment]
Thanks for looking into it. I cannot log in via email. I didn't have an account before and haven't recieved a confirmation email yet.

**Comment by luipir** [comment]
Hey... I've the same problem. can't login via basic auth or oauth too

**Comment by smathermather** [comment]
Thanks for the updates: I can't replicate this with basic auth. Can you give me more details? I signed up with a new email account a few minutes ago, it sent the activation link, and I am now logged in.

**Comment by MatthiasSiewert** [comment]
When I try with google, I get the following message, maybe that helps:

400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, https://community.opendronemap.org/auth/google_oauth2/callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/1081421517513-vjr8tsgnak98s12bv036fud0rrjnh9vc.apps.googleusercontent.com?project=1081421517513

**Comment by luipir** [comment]
I'm able to sign-in with mail link, and with basic auth after a password reset.
Not yet able to sign-in with oauth (tested with google and gtihub).
github error: "Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?" but in my github config I do not have any restriction to ODM
google error: as notifed by @MatthiasSiewert

**Comment by MatthiasSiewert** [comment]
Still none of the options works for me. Maybe I am a robot....?!?

**Comment by smathermather** [comment]
Probably not a robot. Give me a few days, I need a block of time to troubleshoot.

**Comment by smathermather** [comment]
Piero got this working again. I need to finish up with twitter login but the rest should be working as of a few days ago.

**Comment by pierotofy** [comment]
This should be fixed, please re-open if the problem persists.

**Comment by mj-saunders** [comment]
I am also not receiving the activation link email.
Not in a position to re-open this, but didn't want to start a new thread for what appears to be the same issue.

**Comment by pierotofy** [comment]
Did you check the spam folder? What's your username on the forum?

**Comment by mj-saunders** [comment]
@pierotofy Yes, nothing at all. Username 'berilac'

**Comment by pierotofy** [comment]
I've manually activated your account :+1:

**Comment by mj-saunders** [comment]
@pierotofy Thank you! :)

**Comment by camcarto** [comment]
hi, ive recently started using WebODM. I am new and would like to join the forum but I am unable to create an account. Ive tried two email accounts and google sign up each time "New registrations are not allowed from your IP address (maximum limit reached). Contact a staff member." Is it not possible to sign up from South Africa?

**Comment by Saijin-Naib** [comment]
Hey, please reach out to hello@uav4geo.com and I'll work with you to get your account sorted.

**Comment by camcarto** [comment]
> Hey, please reach out to [hello@uav4geo.com](mailto:hello@uav4geo.com) and I'll work with you to get your account sorted.

Thank you @Saijin-Naib! i have sent 👍
