### ISSUE TITLE
Code 1 always

### ISSUE THREAD

**Issue by arnaldoasneto** [OpenDroneMap/ODM#984]
### How did you install OpenDroneMap? (Docker, natively, ...)?
server installer

### What's your browser and operating system? 
ubuntu 16.04 64x 16ram 

### What is the problem?
I get always a 
Process exited with code 1
when start processing, tried with different datasets, all them worked with other software

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

I get this on the task:
File "/code/run.py", line 12, in <module>
from stages.odm_app import ODMApp
File "/code/stages/odm_app.py", line 4, in <module>
from opendm import types
File "/code/opendm/types.py", line 1, in <module>
import cv2
ImportError: No module named cv2

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

For sure is not a problem of the dataset.. i can give access to the cloud server

**Comment by pierotofy** [comment]
Hey @arnaldoasneto, this is not the right place to ask. If you purchased the installer get in touch with support at https://masseranolabs.com/contact/, they'll help you out.
