### ISSUE TITLE
[Windows] Docker: Getting invalid reference format error while trying to run SAG APIGateway.

### ISSUE THREAD

**Issue by shahin231** [OpenDroneMap/ODM#985]
****************************************
Hi,

I am trying to install SAG API Gateway and have pulled the image.
1. docker pull store/softwareag/apigateway-trial:10.4
2. docker images                                    (checked the images)
 REPOSITORY                          TAG               IMAGE ID      SIZE
ubuntu                                  latest         7698f282e524   69.9MB
nginx                                     latest         53f3fd8007f7   109MB
store/softwareag/apigateway-trial   10.4    cdc9c8b3f824   1.64GB
hello-world                           latest         fce289e99eb9   1.84kB
docker4w/nsenter-dockerd  latest         2f1c802f322f   187kB

3. I want to run it on the port 5550 and hence run the below command to install it.
docker run -d -p 5550:5550 -p 9072:9072 \ --DESKTOP-8R2H9BA \ --store/softwareag/apigateway-trial:10.4

but its throwing error as below mentioned.

Error Message: PS C:\Users\shahi> docker run -d -p 5550:5550 -p 9072:9072 \ --DESKTOP-8R2H9BA \ --store/softwareag/apigateway-trial:10.4
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: invalid reference format.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

Please help to fix it.

Thanks
Shahin
![Error Capture](https://user-images.githubusercontent.com/50538940/58369696-93154500-7f1b-11e9-82a4-ffd0d975ac98.JPG)

**Comment by smathermather** [comment]
Can you please post this at https://community.opendronemap.org? This isn't likely a bug but a configuration question. If it turns out to be a bug, we can reopen this issue.

Thanks!
