### ISSUE TITLE
GCP file should ignore images that are not available

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#986]
This can allow a user to process a subset of a dataset without having to create a new GCP file.

**Comment by smathermather** [comment]
Important for split-merge, I imagine... .

**Comment by pierotofy** [comment]
Split-merge already takes care of that, this would be for single workflows.

**Comment by smathermather** [comment]
Split-merge parses and splits the GCP file?

**Comment by pierotofy** [comment]
Yep. https://github.com/OpenDroneMap/ODM/blob/master/opendm/gcp.py#L50

**Comment by smathermather** [comment]
I missed that. That's great.

**Comment by pierotofy** [comment]
Done in `speedimprov` branch.
