### ISSUE TITLE
[Feature Request ] Parallelize odm_filterpoints

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#991]
Parallelize odm_filterpoints to reduce the bottleneck at this stage in the process.

**Comment by pierotofy** [comment]
This can be done when/if this gets done https://github.com/PDAL/PDAL/issues/2570

**Comment by kornyhiv** [comment]
Looks like it has been completed:
https://github.com/PDAL/PDAL/issues/2570

**Comment by pierotofy** [comment]
Some work has been started here https://github.com/pierotofy/OpenDroneMap/tree/parallel_filterpoints but it might be a while before I can finish it. @kornyhiv would you be interested in contributing to it?

**Comment by pierotofy** [comment]
We can now raise funds to get this done using quadratic funding! https://fund.webodm.org/#/fund/1

**Comment by pierotofy** [comment]
See #1132 for updates. This is now done! Please test and see if performance improves (it does from our tests). Thanks to everyone who contributed!
