### ISSUE TITLE
MicMac process fails to produce Orthophoto

### ISSUE THREAD

**Issue by ChipwizBen** [OpenDroneMap/ODM#993]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

N/A

### What is the problem?

After processing a known-good GPS dataset, the Orthophoto failed to complete. Appropriate log lines:
```
No orthophoto found at odm_orthophoto/odm_orthophoto.tif: will skip MBTiles generation Found suitable point cloud for PotreeConverter: odm_georeferencing/odm_georeferenced_model.ply
```

The 3D model completed successfully. 

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Orthophoto should build correctly. 

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

First dataset in here:
https://community.opendronemap.org/t/poets-park-upper-hutt-new-zealand-x2/2042

Options: max-concurrency: 12, image-footprint: true, camera-cloud: true

**Comment by pierotofy** [comment]
Hey @ChipwizBen, could we move this to the NodeMicMac repository? https://github.com/dronemapper-io/NodeMICMAC/issues

Thank you!
