### ISSUE TITLE
split process error unrecognized arguments: submodel_0000

### ISSUE THREAD

**Issue by sueng66** [OpenDroneMap/ODM#994]
I am using opendronemap/odm from master and process using split but always got an error unrecognized arguments: submodel_0000 when start processing submodel_0000 :
> [INFO]    ========================
> [INFO]    Processing submodel_0000
> [INFO]    ========================
> [DEBUG]   running /code/run.py code --project-path /datasets/code/submodels --orthophoto- cutline --dem-euclidean-map --skip-3dmodel submodel_0000
> usage: run.py [options] <project name>
> run.py: error: unrecognized arguments: submodel_0000
> Traceback (most recent call last):
>   File "/code/run.py", line 56, in <module>
>     app.execute()
>   File "/code/stages/odm_app.py", line 94, in execute
>     self.first_stage.run()
>   File "/code/opendm/types.py", line 375, in run
>     self.next_stage.run(outputs)
>   File "/code/opendm/types.py", line 356, in run
>     self.process(self.args, outputs)
>   File "/code/stages/splitmerge.py", line 146, in process
>     system.run(" ".join(map(quote, argv)), env_vars=os.environ.copy())
>   File "/code/opendm/system.py", line 76, in run
>     raise Exception("Child returned {}".format(retcode))
> Exception: Child returned 2

My command is 
```
docker run -ti --rm -v /mnt/public/INDO/Area_1-Test\ GCP/:/datasets/code jas_odm --project-path /datasets --split 250 --split-overlap 100
```

**Comment by pierotofy** [comment]
Hey @sueng66, thanks for reporting this :hand:

Looks like a bug. We'll look into it.
